### ISSUE TITLE
6.02问题

### ISSUE THREAD

**Issue by quxg** [lmk123/crx-selection-translate#100]
win10 64位，chrome64位最新版，在取词翻译框内切换翻译,朗读引擎无效，只能进入选项里切换。鼠标在翻译框内时会出现“朗读”当鼠标指向“翻译”时又会显出“朗读”的选项，个人觉得多余。

**Comment by lmk123** [comment]
> 切换翻译,朗读引擎无效

能给出重现的步骤吗？提供截图最好。

翻译按钮下面的朗读我会考虑要不要删除的。

**Comment by quxg** [comment]
不好意思，是我没搞懂切换引擎后要点一下翻译，现在可以切换翻译引擎了，但朗读依然是只有一种发音，而且也不是默认翻译引擎的读音，不知是否有意为之？很喜欢你的这个扩展，用了快两年了，祝越做越好。

在 2016年1月30日 上午11:02，Milk Lee <notifications@github.com>写道：

**Comment by lmk123** [comment]
从 v6.0 开始，我把朗读换成了系统自带的语音，不过我正着手改回原来的语音 #92
