### ISSUE TITLE
划词翻译增加一个快捷键

### ISSUE THREAD

**Issue by johncming** [lmk123/crx-selection-translate#1001]
## 功能简介

类似网页翻译, 可以给划词翻译增加一个快捷键. 该软件的划词翻译好用, 网页翻译用的不多, 但是有时候不需要划词. 

## 为什么你觉得需要（改进）这个功能？

而加前缀的划词翻译比较麻烦, 一段时间需要划词翻译, 一段时间不需要划词翻译, 从时间段上可以清晰的分开, 因此加入一个快捷键非常的帮

Thanks

**Comment by lmk123** [comment]
我猜你指的是通过快捷键来切换【禁用网页划词】的选项吧。

好的，我会在下个版本中加入。

**Comment by johncming** [comment]
> 我猜你指的是通过快捷键来切换【禁用网页划词】的选项吧。
> 
> 好的，我会在下个版本中加入。

是的. Thanks
