### ISSUE TITLE
阿里翻译报错10013

### ISSUE THREAD

**Issue by ciddiaz** [lmk123/crx-selection-translate#1003]
## 基本信息

划词翻译版本：v7.6.1
浏览器版本：Microsoft Edge 版本 90.0.818.42 (官方内部版本) (64 位)
操作系统：Windows10 专业版

## 重现问题的步骤

1. 新开通阿里云翻译服务
2. 在划词翻译设置中添加key，在翻译源中启用阿里翻译
3. 尝试在网页中选中一行英文进行翻译

### 预期行为
各翻译源正确显示翻译结果
阿里云是新开通服务，不可能瞬间用完免费额度
完全按照划词翻译的帮助文档操作

### 实际行为
阿里云报错“10013”，即“账号服务没有开通或者欠费”
其它翻译源均正常

**Comment by lmk123** [comment]
我这么操作下来是可以正常使用的，建议你找阿里翻译的客服问问是怎么回事。就像[也有人百度翻译报“IP 非法”的错误](#988)一样，我的百度也是正常的，我也不知道是什么原因。

**Comment by lmk123** [comment]
如果你问过之后知道是什么问题，可以反馈给我，我会标注在文档里。

**Comment by ciddiaz** [comment]
问题已解决，再次开通阿里翻译服务即可
说来也是很神奇。明明之前开通过，连Key都有了，都贴到“划词翻译”的设置里了，再去检查的时候还有“开通”的按钮，再次点击“开通”，直接就可以用了，“划词翻译”的设置不必做任何修改
