### ISSUE TITLE
对不起，实在没找到网页翻译按钮

### ISSUE THREAD

**Issue by kingone51** [lmk123/crx-selection-translate#1005]
我在手机yandex浏览器上使用这个拓展，我实在不知道怎么打开网页翻译。非常抱歉。希望可以自动翻译从前翻译过的域名。

**Comment by lmk123** [comment]
网页翻译按钮在这里：

![image](https://user-images.githubusercontent.com/5035625/115952057-a3bf0300-a516-11eb-825b-f59aa5d30a0a.png)

但是在手机上用划词翻译我是没有想到的……

**Comment by kingone51** [comment]
手机上只能在点击拓展图标后显示这个窗口。我本来是想找个能自动翻译曾经手动翻译过的域名的拓展。目前网络上有用谷歌翻译实现自动翻译的拓展，就是翻译的质量……能用国内翻译源自动翻译网站的不好找……[Image]



________________________________
发件人: mingkaili ***@***.***>
发送时间: 2021年4月24日星期六 16:04
收件人: lmk123/crx-selection-translate
抄送: kingone51; Author
主题: Re: [lmk123/crx-selection-translate] 对不起，实在没找到网页翻译按钮 (#1005)


网页翻译按钮在这里：

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5035625%2F115952057-a3bf0300-a516-11eb-825b-f59aa5d30a0a.png&data=04%7C01%7C%7Cae5e0f570e4540bcbe0c08d906f78fea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637548482617431013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2BJtJW9wwmnvBKoU7Ud54M83L1WnBfyhb0YZ8QSkM3o%3D&reserved=0>

但是在手机上用划词翻译我是没有想到的……

―

**Comment by lmk123** [comment]
> 手机上只能在点击拓展图标后显示这个窗口。

是的，网页翻译目前只支持两种触发方式：

- 第一种就是在页面上划词后，点击翻译按钮，然后在这个弹出来的窗口里点击按钮；
- 第二种就是用快捷键，但手机没有键盘，所以是用不了快捷键的

未来我可能会在右键菜单中新增网页翻译的选项，也许这样在手机上也行得通？

> 我本来是想找个能自动翻译曾经手动翻译过的域名的拓展。

没太明白你的意思……
