### ISSUE TITLE
独立窗口（初始打开/人为刷新）闪现：（浅色）`你隐藏了所有翻译源`

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#1007]
## 基本信息

划词翻译版本：7.6.2
浏览器版本：Chrome/90.0.4430.86
操作系统：Win7

### 实际行为
独立窗口（初始打开/人为刷新）闪现：（浅色）`你隐藏了所有翻译源`
深色模式时更明显。
好像是7.6.2才有的现象。

**Comment by lmk123** [comment]
这其实跟 #967 是同一个问题 :joy:

**Comment by GH01** [comment]
设置 慢点无所谓，
但是这个，照理不该先有这提示。

**Comment by lmk123** [comment]
出现这个的原因就是，在读取到用户开启过的翻译源这个设置项之前，“选中的翻译源”这一设置默认是空的（不然就会显示出来默认的翻译源的结果），而空的翻译源就会给出这个提示，提示用户至少勾选一个翻译源；等读取到设置之后，这个提示就会消失。

根本原因是我将“还没有读取到设置”和“读取到了设置但设置是空的”这两种情况做区分……也许我未来会做一个区分。

**Comment by lmk123** [comment]
v7.6.6 单独针对独立窗口的这个问题做了下改进，现在不会出现这种情况了
