### ISSUE TITLE
[字体大小]改为滑条（调整更细），放宽极值（适应更多分辨率）

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#1008]
## 功能简介
[字体大小]改为滑条，放宽极值。

## 为什么你觉得需要（改进）这个功能？
调整可以更细。
适应更多分辨率（对于较低分辨率，[最小]也许可以更小）。

**Comment by lmk123** [comment]
我感觉这属于可以做但没必要的事情……

从技术上讲，现有的大、中、小三个数值是我在代码里用的固定数值，也就是 12px、16px 和 22px，如果改成滑条可以自由设置，那工作量就大了，但是我觉得改成滑条没有必要，有什么场景是一定要用 14px 或 20px 的吗？

放宽极值——现在的“小”已经是浏览器支持的最小了，也就是 12px 的字体大小，浏览器最小只支持 12px；至于更大，现在的“大”我觉得对于家用台式电脑已经够大了，家用台式电脑一般再大也就 27 寸吧
