### ISSUE TITLE
在 Firefox 网页翻译使用DeepL有的网页会导致排版崩坏

### ISSUE THREAD

**Issue by Mosney** [lmk123/crx-selection-translate#1009]
## 基本信息

划词翻译版本：7.6.2
浏览器版本：Firefox 88.0 (64 位)
操作系统：Windows 10 1809

## 重现问题的步骤

1.最近很多网页都发现有这个问题
2.使用快捷键唤出网页翻译
3.如果使用DeepL翻译源轻则完全不翻译，重则排版炸掉，切换到Google翻译就没问题了，但是由于Google翻译结果不如DeepL，故一直优先DeepL

下方示例截图链接：https://urllib3.readthedocs.io/en/latest/reference/urllib3.exceptions.html#urllib3.exceptions.InsecureRequestWarning
### 预期行为
![图片](https://user-images.githubusercontent.com/22477230/116007236-5d19f780-a641-11eb-8b91-bda0623bb9cd.png)

### 实际行为
![图片](https://user-images.githubusercontent.com/22477230/116007232-568b8000-a641-11eb-8378-04380c940e87.png)

**Comment by lmk123** [comment]
DeepL 网页翻译不完整的问题会在下个版本中修复（#1006）

你说的“排版炸掉”应该也是由于翻译不完整引起的。我大概会在今天发布 v7.6.3 版本，你升级到 v7.6.3 版本之后再看看还有没有问题。

以下是我用未发布的 v7.6.3 网页翻译的截图：

![image](https://user-images.githubusercontent.com/5035625/116021132-2dd3ac80-a67a-11eb-8c36-10804db3f56a.png)

**Comment by lmk123** [comment]
我已经提交了 v7.6.3 的审核了，正式上架估计要到 2 天后，不过你可以现在就去下载离线安装包试试看 https://hcfy.limingkai.cn/install.html

期待你的反馈

**Comment by Mosney** [comment]
好的，我知道了，等等升级看看，谢谢回复！

**Comment by Mosney** [comment]
升级7.6.3之后，看起来问题依然存在
https://www.efficientip.com/glossary/dhcp-option/

> ![图片](https://user-images.githubusercontent.com/22477230/116105510-f994d600-a6e3-11eb-9ac4-02f196b18d5c.png)
> ![图片](https://user-images.githubusercontent.com/22477230/116105559-044f6b00-a6e4-11eb-931e-bffab5ba6728.png)
>

**Comment by lmk123** [comment]
确认了，在 Firefox 里排版错乱的情况确实存在，但是在 Chrome 里是没有的。这个问题我会在下个版本中修复，你可以临时用 Chrome 上的划词翻译

**Comment by lmk123** [comment]
排版错乱的根本原因是 DeepL 翻译多个段落的文本时，翻译结果没有换行。我单独开了一个 issue 来解决这个问题，后续进展可以看 #1011
