### ISSUE TITLE
划词翻译被 Chrome 网上应用店给删除了

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#101]
大家可以暂时使用 [v5.6.1 的安装包](https://github.com/lmk123/crx-selection-translate/releases/tag/v5.6.1)手动安装划词翻译。

## 2016年1月30日：

他们给我发来了一封邮件：

![default](https://cloud.githubusercontent.com/assets/5035625/12693745/087b6a3c-c74f-11e5-829d-13f9b4e72b40.png)

为了减小划词翻译安装包的大小，我使用了精简工具将源码都精简成一行了，这违反了 Chrome 网上应用店的政策。

## 2016年1月30日更新：

已提交 v6.0.3 版本，正等待 Chrome 网上应用店人工审核。

## 2016年1月31日更新：

审核没有通过，对方给我发了同样的一封邮件。我立刻回复了如下一封邮件：

![20160201004715](https://cloud.githubusercontent.com/assets/5035625/12703412/6f6f1e4e-c87d-11e5-85b6-660bb448d6ca.png)

但对方又回复了同样的邮件给我，只是有一部分加粗了：

![reply](https://cloud.githubusercontent.com/assets/5035625/12703421/88ee2b9e-c87d-11e5-8850-237c5c9f8dd7.png)

## 2016年2月1日更新：

我可能知道审核不通过的原因在哪了：网页翻译需要插入第三方脚本到网页里去，但是这些代码我没有包含在扩展里，为此我注释掉了所有跟网页翻译相关的代码并重新发布了 [v6.0.4 版](https://github.com/lmk123/crx-selection-translate/releases/tag/v6.0.4)，然后就审核通过了。

**Comment by lmk123** [comment]
在划词翻译重新上架之前我会一直打开这个 issue

**Comment by lmk123** [comment]
到现在还是待审核。。看来是有人举报我的扩展有恶意行为，所以谷歌才会突然要审查我扩展内的代码。开源了都还有人举报 :pensive:

**Comment by XhstormR** [comment]
现在有什么方法能够不通过 Chrome 商店安装的吗？

**Comment by lmk123** [comment]
@XhstormR 你可以试试使用 v5.6.1 的 .crx 安装包安装：https://github.com/lmk123/crx-selection-translate/releases/tag/v5.6.1

**Comment by XhstormR** [comment]
@lmk123 
用了下，感觉不错，还开源，就你了。
另外版本更新都能提供 CRX 下载就更好了，毕竟没有VPS，hosts也经常失效。

**Comment by lmk123** [comment]
@XhstormR v6.0 版本还处于小范围试用阶段，所以没有提供 .crx 安装包，不过等这次审核通过之后我每次都会上传 .crx 安装包的。觉得好用就推荐给你周围的朋友吧 :laughing:

**Comment by ldw4033** [comment]
my god !

**Comment by henices** [comment]
我直接用源码了，影响不大。

**Comment by lmk123** [comment]
审核通过了，只是网页翻译暂时用不了了。
