### ISSUE TITLE
将译文跟原文在视觉上做出一点区分

### ISSUE THREAD

**Issue by shikaiguo** [lmk123/crx-selection-translate#1010]
## 功能简介
网页翻译双语的时候，希望可以自定义译文的样式，包括不限于自定义css  自定义前后标识符如
asdf{正在翻译，请稍后...}
## 为什么你觉得需要（改进）这个功能？
原文和译文凑在一起，很容易混淆，如果能自定义样式如颜色 下划线等，可以区分原文和译文

**Comment by lmk123** [comment]
我明白了，你的主要诉求是希望原文和译文能有一定的区分度。我会做一些区分，但是不是用自定义 CSS 的形式，毕竟这种形式对不懂技术的普通用户来讲并不友好。

**Comment by xishian** [comment]
加个框就行，主要是方便阅读，thx

**Comment by lmk123** [comment]
@xishian 加个框的提议不错。

> 还有能不能不要显示"正在翻译，请稍后"，等翻译好了再渲染界面

如果不显示的话，那么点击之后页面没有任何反应（特别是 DeepL 这种要等十秒左右才出结果的），用户会觉得是功能挂掉了。

**Comment by xishian** [comment]
> @xishian 加个框的提议不错。
> 
> > 还有能不能不要显示"正在翻译，请稍后"，等翻译好了再渲染界面
> 
> 如果不显示的话，那么点击之后页面没有任何反应（特别是 DeepL 这种要等十秒左右才出结果的），用户会觉得是功能挂掉了。

那跟chrome原生翻译一样，分页翻译，逐步渲染行不

**Comment by lmk123** [comment]
@xishian 试了下 Chrome 原生的网页翻译，由于太快了所以没有感受到“分页翻译，逐步渲染”是啥体验 :joy:

我猜你的问题是在于 “正在翻译，请稍候……”这几个字太长了，在翻译过程中破坏了页面结构让页面不可读了吗？如果是的话，那要不我把这段提示改短一点，比如“翻译中…”，这样也许会好一些？

**Comment by lmk123** [comment]
@xishian 我计划对“正在翻译，请稍候……”这个问题做个改进，见 https://github.com/lmk123/crx-selection-translate/issues/1177
