### ISSUE TITLE
在 Firefox 里用 DeepL 翻译多个段落的文本时，翻译结果没有换行

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1011]
## 基本信息

划词翻译版本：v7.6.3
浏览器版本：Firefox 88
操作系统：win10

## 重现问题的步骤

1. 使用 Firefox 的 DeepL 翻译下面的文本

```
Supplying DHCP options is a smart way to configure network clients during the early phase of network access deployment.
        
DHCP is an evolution of the BOOTP protocol (see RFC951) designed at first to bootstrap a diskless client.
```

### 预期行为

翻译的文本有两个段落，所以翻译结果也应该有两个段落

### 实际行为

DeepL 的翻译结果没有段落，谷歌的是正常的（但谷歌也有点小问题，即它实际上有三个段落，其中第二个段落是空的，但按照预期，空行应该被去掉）（可能有 bug 的点：空行不应该在翻译结果中去掉，因为翻译源应该跟翻译结果的段落数量保持一致；空行应该在显示的时候去掉。）

![image](https://user-images.githubusercontent.com/5035625/116183772-2206e980-a751-11eb-8bed-aa477a3807c0.png)

**Comment by lmk123** [comment]
作为对比，下图是在 Chrome 上翻译的结果：

![image](https://user-images.githubusercontent.com/5035625/116184012-875ada80-a751-11eb-8d0c-8f8d26f14614.png)

**Comment by lmk123** [comment]
@Mosney 这个问题我调整到 v7.6.5 再修复，因为 v7.6.4 的一些改进是影响到所有浏览器版本的，所以我先发布 v7.6.4 了，抱歉

**Comment by Mosney** [comment]
> 
> 
> @Mosney 这个问题我调整到 v7.6.5 再修复，因为 v7.6.4 的一些改进是影响到所有浏览器版本的，所以我先发布 v7.6.4 了，抱歉

没关系啦，又不是不能用，你慢慢来

**Comment by lmk123** [comment]
@Mosney 我试了一下，划词翻译 v7.6.5 已经没有这个问题了，看起来似乎是我无意间修复了这个问题 :joy: 你可以试一下升级到划词翻译 v7.6.5 还有没有这个问题，如果有的话欢迎继续留言。
