### ISSUE TITLE
是否可以支持google doc, 腾讯文档等文档类划词/网页翻译

### ISSUE THREAD

**Issue by bartdong** [lmk123/crx-selection-translate#1012]
## 功能简介
支持google doc以及腾讯文档等文档类内容划词/网页翻译
## 为什么你觉得需要（改进）这个功能？
与外企合作时经常会交换共享文档，有翻译功能会方便很多

**Comment by lmk123** [comment]
我可以尝试添加支持，你可以提供一些示例链接供我测试用吗？

**Comment by bartdong** [comment]
非常感谢~
