### ISSUE TITLE
加显示中文拼音的功能吗

### ISSUE THREAD

**Issue by L170300102** [lmk123/crx-selection-translate#1013]
## 功能简介

如果翻译外语- > 中文，翻译好的结果（中文）旁边或下面添加拼音

## 为什么你觉得需要（改进）这个功能？

我是在中国念书的一个韩国学生。平时翻译插件带来很大的帮助，谢谢。无论看英文文献还是中文。但是，有时候看到生词，不知怎么读。只能听发音或者复制去别的词典找找。如果划词里面实现这种功能，太好了

![ggg](https://user-images.githubusercontent.com/48048507/116248272-adf73080-a7a6-11eb-97d4-f4074d0d9a8a.png)

**Comment by lmk123** [comment]
好的，下个版本 v7.6.4 会将谷歌翻译的中文拼音显示出来。v7.6.4 预计在这周五之前发布。

附带拼音的截图如下：

![image](https://user-images.githubusercontent.com/5035625/116262229-f1ec3480-a7aa-11eb-9cca-82588ec2d819.png)

**Comment by GH01** [comment]
那 韩文/日文的罗马注音 是不是也能在7.6.4见着了？

**Comment by L170300102** [comment]
我的版本是7.6.4 但是没显示拼音或者韩文的英文发音写等。是不是设置里有什么开关？

**Comment by lmk123** [comment]
> 那 韩文/日文的罗马注音 是不是也能在7.6.4见着了？

@GH01 目前只会显示英语音标和汉语拼音

> 我的版本是7.6.4 但是没显示拼音或者韩文的英文发音写等。是不是设置里有什么开关？

@L170300102 没有开关，v7.6.4 会自动显示汉语拼音。比如翻译“开关”的时候会显示拼音 `/Kāiguān/`。如果没有显示，大概率是出现了 bug，你可以告诉我你是在翻译什么汉字时没有出现拼音吗？

![image](https://user-images.githubusercontent.com/5035625/116383890-dc7a1780-a849-11eb-8192-d287ac6e014d.png)

**Comment by L170300102** [comment]
我知道原因了。target language设置成英文即可显示拼音。中文->韩文（日语、西班牙语等，除了英语，其他全部）就没有了。 
-----Original Message-----

**Comment by lmk123** [comment]
我在这个版本限制了只在翻译为英文时才显示拼音。这样吧，我在下个版本会放开这个限制，中文翻译为韩语的时候也把拼音显示出来。

**Comment by lmk123** [comment]
> 那 韩文/日文的罗马注音 是不是也能在7.6.4见着了？

@GH01 日文韩文的注音我也会显示出来，不过我只会在字符数小于 4 的时候才显示出来，不然如果翻译一段句子的话，注音太长了。
