### ISSUE TITLE
支持同步文本翻译服务里面的秘钥

### ISSUE THREAD

**Issue by suyar** [lmk123/crx-selection-translate#1014]
## 功能简介
在【同步设置】中，也把翻译服务的 `appid` 和 `秘钥` 进行同步。

## 为什么你觉得需要（改进）这个功能？
我在家里或者不同浏览器之间安装此插件，每次还要登录各种平台去复制相关的 `appid` 和 `秘钥`，步骤比较麻烦。

**Comment by lmk123** [comment]
如果我上传了用户的密钥，一旦未来有用户认为自己密钥里的免费额度或资金被盗用了，我是没法证明自己没有使用这些密钥的。

**Comment by suyar** [comment]
> 如果我上传了用户的密钥，一旦未来有用户认为自己密钥里的免费额度或资金被盗用了，我是没法证明自己没有使用这些密钥的。

可以给个开关，让用户自由选择要不要上传，提示上传风险。默认不同步秘钥，我觉得这个功能很受用。
又或者同步前需要对这些秘钥进行加密，秘钥由用户提供，同步的时候需要解密，让用户输入秘钥。加密解析都在客户端，服务端只存储和同步。
作为一个永久订阅用户，真诚的希望能够有办法同步这些配置。

**Comment by lmk123** [comment]
我再考虑看看吧。

**Comment by lmk123** [comment]
仔细想想风险还是挺大的，特别是腾讯云和阿里云的密钥。

阿里云不支持创建子用户，所以阿里云的密钥拥有用户整个账号的资源调用权限；腾讯云虽然支持子用户，但是我估计大部分用户会为了省事而不去创建，所以我估计大部分腾讯云的密钥也有整个账号的资源调用权限。如果密钥从我这泄露出去了（比如我的服务器被黑了），后果有点不堪设想。

虽然可以像你说的那样加密解析都在客户端，但是，划词翻译的用户群体中，程序员毕竟只是很少的一部分，如果我加上了这个功能，首先，我得向用户解释风险，其次，我得向用户解释提供加解密字符串的原因……整个流程对普通用户来说略显复杂并加深了他们觉得“麻烦”的想法。

而且，这些翻译源需要密钥才能用就已经让大部分用户觉得麻烦了，现在为了同步这些密钥，又得进一步做一些更复杂的事情，而实际上大部分用户都不喜欢复杂，所以总的来看，我觉得是得不偿失的。

相比之下，从各个官方网站复制一遍这些密钥只是一次性的工作，我觉得大部分人的常用设备是两台，每台的常用浏览器是两个，所以一般而言，每个人复制这些密钥不会超过 4 次。我觉得这是更便于用户理解、更简单的操作方法。

**Comment by suyar** [comment]
_(:з」∠)_ 表示理解

**Comment by lmk123** [comment]
感谢理解

**Comment by GH01** [comment]
用个密码管理扩展/软件来存储，复制起来更方便。

我倒是想要能 本地切换ID（同一服务 有多个ID）……
