### ISSUE TITLE
划词翻译显示音标

### ISSUE THREAD

**Issue by TurnerXi** [lmk123/crx-selection-translate#1015]
## 功能简介
划词翻译显示音标
## 为什么你觉得需要（改进）这个功能？
上班不方便戴耳机听读音，但希望知道某个单词应该怎么读

**Comment by skyemin** [comment]
哪个翻译源可以显示音标?之前百度有,现在也没了

**Comment by lmk123** [comment]
必应词典、有道翻译和搜狗翻译都可以显示音标。
