### ISSUE TITLE
网页翻译会出现额外的字符翻译

### ISSUE THREAD

**Issue by Mosney** [lmk123/crx-selection-translate#1016]
## 基本信息

划词翻译版本：7.6.4
浏览器版本：FIrefox 88.0 
操作系统：Windows10 1809

## 重现问题的步骤

https://www.howtogeek.com/174705/how-to-reduce-the-size-of-your-winsxs-folder-on-windows-7-or-8/
网页翻译上述网页时会出现额外的字符翻译

![图片](https://user-images.githubusercontent.com/22477230/116369108-94ec8f00-a83b-11eb-8502-7acb73c7be11.png)

原文：
![图片](https://user-images.githubusercontent.com/22477230/116369476-ff9dca80-a83b-11eb-8cab-0ccb2433f2f3.png)

**Comment by lmk123** [comment]
这段文本下面其实有一个广告，你没看到是因为被 ad block 隐藏了，但划词翻译在读取文本时读到了这个广告内的样式文本，所以导致出现了这段额外的字符。

我会在后面的版本中做个优化，避免读取到隐藏的或样式内的文本。

**Comment by lmk123** [comment]
v8.1.1 中已修复此问题。如果你更新到 v8.1.1 之后还有这个问题，欢迎继续反馈。
