### ISSUE TITLE
划词翻译内部发生了未知错误

### ISSUE THREAD

**Issue by startfan** [lmk123/crx-selection-translate#1017]
## 基本信息

划词翻译版本：8.6.4
浏览器版本：firefox 78.9.0esr (64 位)
操作系统：linux

## 重现问题的步骤

1.选定网页上的文字,点击出现的翻译器按钮进行翻译

### 实际行为
除了专业版,其它的翻译源都显示:划词翻译内部发生了未知错误，错误消息：(intermediate value).languages[0] is undefined

**Comment by lmk123** [comment]
已发布 v7.6.5 修复此问题。
