### ISSUE TITLE
给文本框添加一个确定按钮

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1020]
## 功能简介
目前，文本框停止输入后的 0.5 秒会自动触发翻译
## 为什么你觉得需要（改进）这个功能？
这导致用户手动输入完一个句子的时候触发了好几次翻译，会造成字符数的浪费

**Comment by GF-Huang** [comment]
怎么关掉这个功能？每次都要点按钮才翻译好麻烦。

**Comment by lmk123** [comment]
我在下个版本加个设置项吧

**Comment by lmk123** [comment]
@GF-Huang 翻译按钮是可以通过 Ctrl + Enter 触发的，我觉得这比以前的自动翻译应该没有麻烦多少。。

**Comment by GF-Huang** [comment]
> @GF-Huang 翻译按钮是可以通过 Ctrl + Enter 触发的，我觉得这比以前的自动翻译应该没有麻烦多少。。

好的，谢谢提醒。
