### ISSUE TITLE
加一个新的选项“自动读取剪切板内的截图”

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1021]
## 功能简介
目前，打开独立窗口或扩展窗口时只能读取到剪切板内的文本
## 为什么你觉得需要（改进）这个功能？
有了截图翻译功能之后，需要支持读取剪切板内的图片

**Comment by GH01** [comment]
加个 并列选项 可能更好。
而非 子选项。

**Comment by lmk123** [comment]
可
