### ISSUE TITLE
网页翻译部分文本缺失

### ISSUE THREAD

**Issue by li-xuanhong** [lmk123/crx-selection-translate#1022]
## 基本信息

划词翻译版本：7.6.5
浏览器版本：edge 90
操作系统：win10

## 重现问题的步骤

1.打开网页[https://www.aclweb.org/anthology/P19-1207/](https://www.aclweb.org/anthology/P19-1207/)，或是https://arxiv.org/abs/1912.03135
2.使用网页翻译快捷键进行网页翻译，两个页面的中间英文部分都没有被翻译

### 预期行为
正常翻译

### 实际行为
翻译缺失
![image](https://user-images.githubusercontent.com/44440077/117102304-a2a99380-adaa-11eb-9eca-07216f5cc669.png)

**Comment by hmrg-grmh** [comment]
我这个似乎更严重。。。

![image](https://user-images.githubusercontent.com/68635334/121110767-6b625280-c840-11eb-8660-388962e9a4a4.png)

https://www.metalevel.at/prolog/introduction

----

插件版本：
![image](https://user-images.githubusercontent.com/68635334/121110881-93ea4c80-c840-11eb-88a8-dae6cc708473.png)

浏览器：
![image](https://user-images.githubusercontent.com/68635334/121110951-a95f7680-c840-11eb-9a48-f71bc25d8d0a.png)

OS：
win10

**Comment by lmk123** [comment]
一个新的未完全翻译的网址：

https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c

**Comment by lmk123** [comment]
即将发布的 v8.5.0 使用了全新的网页全文翻译算法，已确认此 issue 里的所有链接都可以完整翻译。
