### ISSUE TITLE
给翻译按钮加一个显眼的提示：可以用 Ctrl + Enter 触发

### ISSUE THREAD

**Issue by JadeQi** [lmk123/crx-selection-translate#1024]
## 基本信息

划词翻译版本：v.7.6.6
浏览器版本：chrome  89.0.4389.90
操作系统：win10

## 重现问题的步骤

1.  手动输入需要翻译的文本时，需要点击对应按钮才能翻译，以前只需要【回车】即可翻译文本
2. 
![image](https://user-images.githubusercontent.com/35448093/117522488-4763e500-afe6-11eb-90c4-caed22f3ca6e.png)

### 预期行为
手动输入需要翻译的文本，点击【回车】键即可翻译

### 实际行为
手动输入需要翻译的文本，只能点击一个搜索图标才能翻译文本。不方便快捷的操作

**Comment by lmk123** [comment]
以前不是需要点击回车翻译，而是会在你停止输入 0.5 秒后自动翻译，这样会导致输入过程中浪费不必要的字符数量，所以我加了一个翻译按钮。另外，这个翻译按钮是能通过 Ctrl + Enter 触发的。这个提示似乎不太明显，我下个版本加个明显一点的提示。

**Comment by GH01** [comment]
可以用 清空则显示提示文 的形式。
不然空着也是浪费。

**Comment by JadeQi** [comment]
> 以前不是需要点击回车翻译，而是会在你停止输入 0.5 秒后自动翻译，这样会导致输入过程中浪费不必要的字符数量，所以我加了一个翻译按钮。另外，这个翻译按钮是能通过 Ctrl + Enter 触发的。这个提示似乎不太明显，我下个版本加个明显一点的提示。

好的，感谢。Ctrl + Enter 是可以触发，之前不清楚😂
