### ISSUE TITLE
给全文翻译工具栏添加一个选项：自动连续翻译

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1026]
## 功能简介
目前，网页翻译只会翻译浏览器可视区域内的文本，当用户滚动网页后，才会开始翻译新的进入可视区域的文本。
## 为什么你觉得需要（改进）这个功能？
虽然这样做能做到“按需加载”，最大限度的节约用户的字符数量，但同时也会导致滚动网页后，用户需要等待一段时间才能看到翻译结果。

所以，可以考虑加个选项，勾选之后就自动翻译整个网页的文本，即使文本不在可视范围内也翻译

**Comment by GH01** [comment]
做成“一次性”的 可能更好。
或者，分 当前页/全局 两个选项。

**Comment by hmrg-grmh** [comment]
> 做成“一次性”的 可能更好。
> 或者，分 当前页 / 全局 两个选项。

现有的网页翻译的功能是，你必须让那部分在可视范围内（其实我的体验是被触发范围会比我的人眼可视范围还大一点点），那部分自然段才会被提交翻译。所以我提了这个【不用非得看到也能开始翻译】的功能增加。

**Comment by GH01** [comment]
我是在你说的基础上，对主人的进一步需求。

**Comment by hmrg-grmh** [comment]
> 我是在你说的基础上，对主人的进一步需求。

从 #1025 明白你意思了 （捂头）

**Comment by lmk123** [comment]
在开发过程中，我不打算加入这个选项了。因为如果一个网页它非常的长，开启这个选项的话会导致整个网页的文本都被提交翻译，但用户可能会看不了多少就关闭网页，这样一来很容易造成字符的浪费。

但为了解决目前往下滚动网页需要等待一段时间才有翻译结果的情况，我将预取范围扩大了。

以前是：只有当某个段落进入了可视区域之后，才会开始翻译。

改进之后：如果这个段落进入了**可视区域加上周围 500px 的范围内**就会开始翻译。

也就是说，可视区域的范围扩大了。使用 DeepL 测试了一下，现在滚动网页的时候基本不会出现要等待翻译结果的情况了，滚动下去的网页都是翻译好的

**Comment by lmk123** [comment]
修正：把预取范围从 500px 改成了 1000px，差不多是一个屏幕的高度

**Comment by GH01** [comment]
各机分辨率不同，用绝对的像素值可能不够好，有没有更合适的相对值可用？

也许让用户自调更好？

**Comment by lmk123** [comment]
要么我改一下，通过代码读取屏幕高度作为预取范围好了
