### ISSUE TITLE
默认确认翻译功能

### ISSUE THREAD

**Issue by apades** [lmk123/crx-selection-translate#1029]
## 为什么你觉得需要（改进）这个功能？
旧版本是可以直接输入文字就提供翻译了，怎么新版就直接去了还c+enter才能用，设置也没有相关回到旧版功能，用着老别扭了

**Comment by lmk123** [comment]
原因是以前的“0.5秒后自动翻译”会导致输入长文本的过程中触发多次翻译，造成不必要的字符浪费。

我在下个版本中加回来吧。

**Comment by floxy** [comment]
我特意来写工单, 看到原来不止我一个人被这个功能给困扰了. 以前粘贴到框框就立马翻译, 现在还要按crtl+enter, 非常地恼人.
