### ISSUE TITLE
DeepL 不显示翻译结果

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1031]
## 基本信息

划词翻译版本：v7.6.8
浏览器版本：chrome 90
操作系统：win10

## 重现问题的步骤

1. 在任意页面划选任意文本

### 预期行为
deepl 显示翻译结果
### 实际行为
deepl 始终处于加载状态，而不显示翻译结果

**Comment by ice-lite** [comment]
同样的问题，DeepL一直卡在加载状态

**Comment by GH01** [comment]
还以为是网络问题……

我想做个快捷链接先，
有谁知道DeepL的URL中“自动检测”的参数（下面*处）怎么写？
`https://www.deepl.com/translator#*/zh/%s`
试了一堆，不成……

也请主人优先处理 https://github.com/lmk123/crx-selection-translate/issues/732 （`始终处于加载状态` 同理）。

**Comment by xinghai1949** [comment]
> 还以为是网络问题……
> 
> 我想做个快捷链接先，
> 有谁知道 DeepL 的 URL 中 “自动检测” 的参数（下面 * 处）怎么写？
> `https://www.deepl.com/translator#*/zh/%s`
> 试了一堆，不成……
> 
> 也请主人优先处理 #732 （`始终处于加载状态` 同理）。

https://www.deepl.com/translator#en/zh/%s

**Comment by GH01** [comment]
@xinghai1949 
en是英文，
我是要“自动检测”。

**Comment by lmk123** [comment]
@GH01 

DeepL 不支持自动检测了。这次出问题的原因就是因为这一点，以前是可以通过 https://www.deepl.com/translator#auto/zh/test 的形式自动检测源语种并翻译，但现在不行了。

**Comment by GH01** [comment]
那目前这个问题是怎么解决的？

我后来发现：DeepL的detected机制似乎是始终存在的，无论用户怎样预设参数：
（不仅[源语种]，连[目标语种]也会智能切换）
https://www.deepl.com/translator#ru/zh/Разработчики
https://www.deepl.com/translator#ru/en/Разработчики
https://www.deepl.com/translator#ru/ru/Разработчики

https://www.deepl.com/translator#en/zh/Разработчики
https://www.deepl.com/translator#en/en/Разработчики
https://www.deepl.com/translator#en/ru/Разработчики

https://www.deepl.com/translator#zh/zh/Разработчики
https://www.deepl.com/translator#zh/en/Разработчики
https://www.deepl.com/translator#zh/ru/Разработчики

地址栏URL也会随之更正。
如果是**文段**，则URL会省略参数：`https://www.deepl.com/translator`
这让我想到另一个问题：
【划词翻译】在翻译（比如俄文）**文段**时不会显示[源语种]。
▲这个问题能否再探索解决？
