### ISSUE TITLE
不能安装到谷歌浏览器

### ISSUE THREAD

**Issue by wzyww** [lmk123/crx-selection-translate#1032]
## 基本信息

划词翻译版本：7.6.8
浏览器版本：不是很清楚装的是易得客的5.0.1 版本
操作系统：win7

## 重现问题的步骤

1.无法加载背景脚本“vendors-background-content-script-content-script-all-frames-panel-pdfViewer-popup-settings.js”。
2.
3.

**Comment by lmk123** [comment]
我在易得客官网只看到 4.1.1  版本。我看了一下，易得客内置的浏览器不是谷歌浏览器，是火狐浏览器，所以你需要在易得客里打开 https://addons.mozilla.org/zh-CN/firefox/addon/hcfy/ 安装划词翻译

**Comment by lmk123** [comment]
如果易得客确实有 5.0.1 版本，你可以告诉我在哪里下载，我再试一下

**Comment by wzyww** [comment]
﻿cdn.selleros.cn/edecker/edecker5/eDecker5.0.1.exe

**Comment by lmk123** [comment]
我试了一下，是可以安装并正常使用的。

易得客 5.0.1 内置的确实是 chrome 浏览器，但它似乎不支持将离线安装包拖放到扩展管理页面的方式安装，但是可以直接从 Chrome 网上应用店安装。

打开 https://chrome.google.com/webstore/detail/ikhdkkncnoglghljlkmcimlnlhkeamad 然后点击【添加到 Chrome】就可以正常安装划词翻译了

**Comment by wzyww** [comment]
可为啥我还是不行。。。

**Comment by lmk123** [comment]
你能截个图或者录个 gif 让我看看具体是什么问题吗？录 gif 可以用 LICEcap https://www.cockos.com/licecap/

**Comment by wzyww** [comment]
Uploading QQ录屏20210513160640.mp4…

**Comment by wzyww** [comment]
https://user-images.githubusercontent.com/84112482/118097469-52af7a00-b405-11eb-8a13-08383c248caf.mp4

**Comment by wzyww** [comment]
https://user-images.githubusercontent.com/84112482/118097527-6529b380-b405-11eb-8903-0792fbf00007.mp4

**Comment by wzyww** [comment]
为啥qq的不行。。你这个太高级了 搞不来。。

**Comment by wzyww** [comment]
![1](https://user-images.githubusercontent.com/84112482/118098231-3a8c2a80-b406-11eb-844e-f86cf8ef34c2.gif)

**Comment by wzyww** [comment]
可能不是插件的问题 我找下易得客那边 谢谢

**Comment by lmk123** [comment]
还有另一种可能，就是文件名太长了，超过了 Win7 的长度限制。

我这边也在下个版本把这个文件名改短一点试试。如果你从易得客那里得到了一些反馈需要我修改也可以留言告诉我。

**Comment by lmk123** [comment]
我在 v7.6.9 中把这个文件的名字改为了 26 个字符了，等谷歌商店上架 v7.6.9 之后你可以再安装试试看。
