### ISSUE TITLE
划词翻译的面板无法上下调节高度，只能调节宽度

### ISSUE THREAD

**Issue by rainseason1** [lmk123/crx-selection-translate#1033]
希望支持调节高度功能，急切需要这个功能

**Comment by lmk123** [comment]
方便告诉我为什么你需要上下调节高度的功能吗？

**Comment by rainseason1** [comment]
这怎么回复啊，算了，我就在这里说好了。调节高度，我可以看到更多位于文本框中的原文，上下对照作用，直接看网页的原文特别不方便，不仅是字体的大小，更有页面宽度，图片阻挡各种障碍。最重要的是，我可以手动编辑文本框的原文，比如删去几个单词，去掉括号，引号或者自己替换其中几个单词。
特别希望支持自由调节文本框的高度，宽度，比例这样。
当前版本的文本框，对于大段文字，就是一个门缝的感觉。

**Comment by lmk123** [comment]
你是希望能调节文本框得高度是吧？文本框是可以调节高度的，鼠标移动到文本框的右下角，鼠标指针会变成双箭头，此时就可以调整文本框的高度了；宽度可以通过把翻译窗口的宽度拉长来调节。

不知道这是不是解决了你的问题？

**Comment by rainseason1** [comment]
作者大大，你找个英文网页试一试，真的可以调吗？我放到右下角，双箭头是出来了，那双箭头是水平方向的，此时鼠标只允许水平移动，不允许垂直移动。调节不了高度啊

**Comment by rainseason1** [comment]
还有快捷键有办法自定义吗，作者大大？

**Comment by lmk123** [comment]
我在 https://developer.mozilla.org/en-US/docs/Web/API/Event 试了下是可以正常调整文本框高度的，如下图：

![t](https://user-images.githubusercontent.com/5035625/118120051-de370400-b421-11eb-92f1-c0240f371307.gif)

如果你不能调，可能是你遇到了 bug，我需要你提供给我你的浏览器版本、划词翻译版本和操作系统，我重现一下。

文本框的快捷键暂时不能修改，但是我计划在下个版本中提供一个选项，可以将以前的自动翻译加回来。

**Comment by rainseason1** [comment]
![image](https://user-images.githubusercontent.com/63706673/118121266-cceef700-b423-11eb-9152-c429f668fcce.png)
为啥我这个没有你右下角的小白标，
chrome浏览器最新版，win10，划词翻译版本：v7.6.8。
实在不行等更新吧，说不定新版就能调了。

**Comment by rainseason1** [comment]
还有你这个双箭头是斜着的，我的双箭头只有水平方向一种状态，真是奇怪。

**Comment by lmk123** [comment]
那就奇怪了，我的环境跟你是一样的，win10、chrome 90、划词翻译 v7.6.8。

也有可能是其它插件覆盖了划词翻译的样式，你可以试试把所有插件都关闭之后能不能拖动。
