### ISSUE TITLE
将全文翻译工具栏变成竖直的

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1035]
## 为什么你觉得需要（改进）这个功能？
现在的横向工具栏偶尔会遮挡页面

**Comment by hmrg-grmh** [comment]
我觉得，更好的方案应该是，加一个按钮，然后横横竖竖来回切换。。。

**Comment by lmk123** [comment]
先改成竖向的看看用户反馈吧，我觉得设置项太多了也不好

**Comment by zerojade** [comment]
不会是我之前那个issue才改的吧，那我的反馈是竖向遮住更多内容了。不如给用户选择：可以让这个工具栏一开始就不要出现，直接翻译就可以了，翻译引擎在设置界面改。

**Comment by lmk123** [comment]
@zerojade 我决定使用你提的建议 https://github.com/lmk123/crx-selection-translate/issues/1070 里的第一点来改进全文翻译的面板：自动收起，鼠标移动上去再展开
