### ISSUE TITLE
全文翻译应当记住双语 / 译文 / 原文选项

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1037]
## 为什么你觉得需要（改进）这个功能？
现在每次启动全文翻译功能，默认就是显示双语的。应当记住这个选项，上次关闭时用户选择了哪个，那么下次打开全文翻译时就选择哪个。

**Comment by lewkoenl** [comment]
附议

**Comment by cxhttt233** [comment]
赞同，改了可能入个永久

**Comment by cxhttt233** [comment]
简单的改了下，默认只显示全文翻译的中文结果。
下载离线版crx，改成zip解压，在解压结果文件夹打开845.js，搜索Ee.both
把除了{name:"原文",value:Ee.both}之外的所有Ee.both改成Ee.result
chrome->扩展程序->加载解压的扩展->选择解压结果文件夹

**Comment by lmk123** [comment]
@cxhttt233 动手能力挺强的 :joy:

不过下个版本这个功能就会加入了

**Comment by cxhttt233** [comment]
> @cxhttt233 动手能力挺强的 😂
> 
> 不过下个版本这个功能就会加入了

好的好的
