### ISSUE TITLE
独立窗口关闭或隐藏，请增加esc快捷键来操作

### ISSUE THREAD

**Issue by snsnsjsn** [lmk123/crx-selection-translate#1039]
## 为什么你觉得需要（改进）这个功能？
独立窗口关闭或隐藏，请增加esca来操作，独立窗口经常 alt+F4 ，一不小心把所有chrome窗口关闭，又要重新打开，然后ctrl+shift+t慢慢恢复。
 esc是最优雅的退出键

**Comment by lmk123** [comment]
好的

**Comment by lmk123** [comment]
v8.1.1 中已添加了 esc 关闭独立窗口的功能。

**Comment by GH01** [comment]
`Ctrl+W` `Ctrl+F4` 也还算优雅，损失可以降至最小
