### ISSUE TITLE
提供 iciba 或 dictionary.com 的单词释义

### ISSUE THREAD

**Issue by asinitial** [lmk123/crx-selection-translate#104]
查询单个单词的时候，建议能将弹出窗口右下角的"via 有道翻译"改为其他提供更详细内容的网站，比如iciba或dictionary.com都可以。谢谢作者。
![screenshot from 2016-01-31 20 23 19](https://cloud.githubusercontent.com/assets/9674332/12702109/140adc4c-c859-11e5-9f77-cae1f63d75a0.png)

**Comment by lmk123** [comment]
或许我可以添加一个“更多信息”啥的，让我考虑下

**Comment by pluwen** [comment]
可以增加一个链接，跳转到对应翻译的网页版

**Comment by lmk123** [comment]
@pluwen 右下角的 `via 有道翻译` 就是指向对应网页翻译的链接

**Comment by pluwen** [comment]
很好，我刚才还没用
UI确实该改进了，功能不错，特别是有 Bing翻译

**Comment by lmk123** [comment]
新版本准备加入爱词霸的单词解义

**Comment by lmk123** [comment]
我单独开了一个工单用于收集新翻译源的反馈 #854 ，金山词霸和剑桥词典已经各计入  1 票了。
