### ISSUE TITLE
全文翻译没有正确识别到列表里的文本

### ISSUE THREAD

**Issue by hmrg-grmh** [lmk123/crx-selection-translate#1040]
## 基本信息

划词翻译版本：

![image](https://user-images.githubusercontent.com/68635334/118360267-73203580-b5b9-11eb-85cc-19aec1363473.png)

浏览器版本：

![image](https://user-images.githubusercontent.com/68635334/118360296-87fcc900-b5b9-11eb-9bc9-bef5e0a91a8a.png)

操作系统：

![image](https://user-images.githubusercontent.com/68635334/118360318-a5ca2e00-b5b9-11eb-8136-d13a7fc44dc8.png)

## 重现问题的步骤

1. 进入这个网址 ： https://www.thegeekstuff.com/2008/11/overview-of-ramfs-and-tmpfs-on-linux/
2. 执行翻译。
3. 在下图就能看到这里所说的现象

![image](https://user-images.githubusercontent.com/68635334/118360423-fc376c80-b5b9-11eb-9c61-c7c4202e11f0.png)

![image](https://user-images.githubusercontent.com/68635334/118360391-de6a0780-b5b9-11eb-9855-0d0b06e13998.png)

### 预期行为

像如图中圈圈部分应该也出现请稍后，然后翻译结果可以在这出现：

![image](https://user-images.githubusercontent.com/68635334/118360568-f1c9a280-b5ba-11eb-9782-89abef508886.png)

### 实际行为

实际就如重现步骤所示了。

另外，这个情况在 starkoverflow 里我记得也有，当时没空就没提。像这样：

![image](https://user-images.githubusercontent.com/68635334/118360503-82ec4980-b5ba-11eb-800b-63b237ed257a.png)

一开始看起来其实还正常

![image](https://user-images.githubusercontent.com/68635334/118360507-8c75b180-b5ba-11eb-9ec4-103982b0e875.png)

不过之后的结果却是只是翻译了人名。。。。

测试地址 ： https://stackoverflow.com/questions/6958689/running-multiple-commands-with-xargs

**Comment by hmrg-grmh** [comment]
很神奇，另一篇文章（https://www.thegeekstuff.com/sed-awk-101-hacks-ebook/）的列表就没有这个问题。

☝这个或许可以对排查原因有帮助吧。

**Comment by hmrg-grmh** [comment]
然后像这种，请稍后就完全出不来了：

https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt

猜测有可能是整片都被视为代码部分了。（如果是这样的话那我觉得这个不好改就算了吧）

**Comment by lmk123** [comment]
列表的那个问题确实是一个 bug。

> 猜测有可能是整片都被视为代码部分了。

是的，目前全文翻译只会翻译几种特定的内容，代码部分是不会被翻译的。

**Comment by hmrg-grmh** [comment]
> 列表的那个问题确实是一个 bug。
> 
> > 猜测有可能是整片都被视为代码部分了。
> 
> 是的，目前全文翻译只会翻译几种特定的内容，代码部分是不会被翻译的。

但是像下面 starkoverflow 应该是另一种原因了吧。。。**至少它看上去也不像列表，也不像代码块**。

更像是，比如这样一个故事：

- 小荣（=回复内容）和小明（=人名部分）一起乘着友谊的小船要完成航行（=被翻译），但是小荣紧挨着小明，小明根本看不到远处的风景，但是，小明跟划船的（=翻译工具的判定点之类的）挨得比较近。
- 这时候，划船的也看小荣不顺眼，就凑在小明边上，耳语到：「彼可取而代之」，小明也很开心：「捏黑~」，然后他们一起把小荣踹下水，小荣就没上岸。
- 后来，老师（=管页面排版的）看到问，小荣呢？船夫指着小明「这就是小荣」，老师说「这不是小荣这是小明」，船夫说「这就是小荣」，可能因为争执下去老师更费口舌（或者别的什么原因），总之，最后老师就把回来的小明，安排在了本来就相互挨着的小明小荣俩人的座位上了（=翻译结果的位置上只有人名）。

（。。。忍不住玩了玩梗。虽然故事有点血腥，可是没办法啊，零和一的世界是残酷的。。。。）

**Comment by lmk123** [comment]
哈哈哈你的回复好有意思。

StackOverflow 的问题其实跟划词翻译没有翻译代码块是一个道理——目前划词翻译的全文翻译只会翻译特定内容（例如文本段落 `<p>`  标签内的文本）而不会翻译其它标签内的内容（如代码块 `<pre>` 标签、普通的 `<div>` 标签）。StackOverflow 里的回复是在 `<div>` 标签内，所以没有翻译。

这一情况会在之后的版本中改进。

**Comment by hmrg-grmh** [comment]
> 哈哈哈你的回复好有意思。
> 
> StackOverflow 的问题其实跟划词翻译没有翻译代码块是一个道理——目前划词翻译的全文翻译只会翻译特定内容（例如文本段落 `<p>` 标签内的文本）而不会翻译其它标签内的内容（如代码块 `<pre>` 标签、普通的 `<div>` 标签）。StackOverflow 里的回复是在 `<div>` 标签内，所以没有翻译。
> 
> 这一情况会在之后的版本中改进，想知道进展的话可以关注 #1022

我发现了一个现象：

![image](https://user-images.githubusercontent.com/68635334/118395110-3e74b280-b67b-11eb-86c5-19d96aef446e.png)

这是否说明，不一定是代码块会影响呢？当然，这并不是没有被触发翻译，而是位置错了。
但我也在考虑，所谓的没有看见，有可能其实也只是位置错了而已。有的位置错了也仍然能被看见，有的，那个位置就刚好是不可见的被挡着的一个位置。

**Comment by hmrg-grmh** [comment]
这个的话可能和 StackOverflow 的情况类似：

![image](https://user-images.githubusercontent.com/68635334/118610351-4143e480-b7ee-11eb-85d9-3150c4e987e7.png)

(https://www.linuxquestions.org/questions/linux-software-2/rsync-and-acl-124564/)

**Comment by lmk123** [comment]
我用划词翻译 v8.4.0、Chrome 91 无法重现列表不翻译的问题了。https://www.thegeekstuff.com/2008/11/overview-of-ramfs-and-tmpfs-on-linux/ 这个链接里的列表现在会正常翻译出来。我没改过相关代码，所以我也不确定这是为什么。

你可以再试一下，如果你还能重现这个问题，可以继续留言。

关于其它问题：

- https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt 这个问题会在 #1022 中解决
- https://dreamsongs.com/WIB.html 这个问题其实跟 #1064 是同一种情况

**Comment by hmrg-grmh** [comment]
试了一下，似乎翻译结果是一块怼下面去了：

![image](https://user-images.githubusercontent.com/68635334/124114895-b833f480-da9f-11eb-9002-8341fe2e1877.png)

8.3.4
edge v91

**Comment by hmrg-grmh** [comment]
另外两个页面了解到了。

https://www.metalevel.at/prolog/introduction

这个网址的翻译跟 #1022 是一个问题吗？

另外还发现了一个新的地址也有缺失问题，但是是某个自然段缺失，跟无法复现的那个当初挺像的：https://www.righto.com/2009/03/y-combinator-in-arc-and-java.html

![image](https://user-images.githubusercontent.com/68635334/124116275-5c6a6b00-daa1-11eb-9d84-14d4e9e76be2.png)

**Comment by lmk123** [comment]
> 试了一下，似乎翻译结果是一块怼下面去了

这部分跟 #1064 是同一个情况

> https://www.metalevel.at/prolog/introduction
> https://www.righto.com/2009/03/y-combinator-in-arc-and-java.html

这俩网址跟 #1022 是同一个情况。网页全文翻译只会处理特定的 HTML 标签，如段落 `<p>`、链接 `<a>`、标题 `<h1>` 等，但这俩网址里的文本没有包含在任何标签里，所以没有被翻译。

准确点说 #1022 其实是很多种情况的合集，我把所有“网页全文翻译文本缺失”的情况都统一集中到 #1022 中，未来再逐个优化
