### ISSUE TITLE
自动翻译

### ISSUE THREAD

**Issue by maobuzheng** [lmk123/crx-selection-translate#1042]
## 为什么你觉得需要（改进）这个功能？
省去手动点击翻译的时间

**Comment by lmk123** [comment]
我猜你指的是在文本框内输入文本后自动翻译吧？设置里有选项的，你开启就行

**Comment by lmk123** [comment]
如果你是希望划词后不显示翻译按钮就直接翻译，那么你可以先将翻译窗口变成固定模式（点击图钉按钮即可），固定模式下，划词之后会直接翻译，不用点击按钮

**Comment by maobuzheng** [comment]
thanks













在 2021-05-17 20:06:27，"mingkaili" ***@***.***> 写道：

如果你是希望划词后不显示翻译按钮就直接翻译，那么你可以先将翻译窗口变成固定模式（点击图钉按钮即可），固定模式下，划词之后会直接翻译，不用点击按钮
