### ISSUE TITLE
单词"process"不会被翻译

### ISSUE THREAD

**Issue by TheCGDF** [lmk123/crx-selection-translate#1043]
## 基本信息

划词翻译版本：8.0.0
浏览器版本：Chrome/90.0.4430.95
操作系统：Win10 x64

## 重现问题的步骤

1. 划词翻译“process”

### 预期行为

翻译“process”

### 实际行为

检测到英语，但是未进行翻译

![vivaldi_zE0vE4oreg](https://user-images.githubusercontent.com/17256673/118836335-b69eda80-b8fe-11eb-9a35-687e307d88af.jpg)

PS: 如果在process后面加个字母，又会正常翻译，但是加数字不行

![vivaldi_MYmqVzghWe](https://user-images.githubusercontent.com/17256673/118836623-01b8ed80-b8ff-11eb-8e2a-0f434640bffd.jpg)
![vivaldi_M215eKHySr](https://user-images.githubusercontent.com/17256673/118836691-10070980-b8ff-11eb-8c9c-f7ea1ee94ac3.jpg)

**Comment by Xiaoxiong-Liu** [comment]
Vice也是。

**Comment by lmk123** [comment]
目前确实有这样的问题。原因是自动检测语种的方法有点小问题，如果字符数很短会识别出错，比如 process 这种比较短的英语单词会被识别为中文，由于目标语种也是中文，所以划词翻译会改为请求英语的翻译结果。

我看看怎么改善这一情况吧。

**Comment by TheCGDF** [comment]
那还挺神奇的，proc比process还短，却可以正常翻译

语种检测方法原来不是统一的么。。。

**Comment by lmk123** [comment]
是统一的，但是这个检测方法确实把 process 识别成了中文，但又把 proc 正确识别成了英文 😂

**Comment by GH01** [comment]
DeepL对俄文单词 считаю 表示无语，是否也是这个原因？

**Comment by lmk123** [comment]
> DeepL对俄文单词 считаю 表示无语，是否也是这个原因？

@GH01 DeepL 网页版在翻译这个俄文单词时也没有提供结果，初步判断跟划词翻译内置的语种检测没关系 https://www.deepl.com/translator#ru/zh/%D1%81%D1%87%D0%B8%D1%82%D0%B0%D1%8E

**Comment by lmk123** [comment]
即将发布的 v8.2.0 中已修复此问题
