### ISSUE TITLE
用浏览器打开本地一个.txt进行右键全文翻译后不变化

### ISSUE THREAD

**Issue by pendave** [lmk123/crx-selection-translate#1044]
![image](https://user-images.githubusercontent.com/1331881/118922041-db7d6700-b96b-11eb-89b4-c143cd57a536.png)

对本地路径里的文本，拖进 Chrome 浏览器可以做翻译的。

如图，上面的 Google 的全文翻译是可以出现变化的。

但划词翻译不行啊，只能框选后翻译。

对本地文件操作，需要在 chrome://extensions/?id=ikhdkkncnoglghljlkmcimlnlhkeamad 开启这个“允许访问文件网址”
![image](https://user-images.githubusercontent.com/1331881/118922278-52b2fb00-b96c-11eb-867b-9dde6ebdc979.png)

**Comment by LuckyHookin** [comment]
@pendave 划词翻译是一个浏览器插件，谷歌浏览器为了安全起见，不允许插件访问本地文件，需要用户自行开启“允许访问文件网址”选项才能访问本地文件；谷歌浏览器自带的翻译功能是谷歌浏览器的一部分，不受这个限制影响。

**Comment by lmk123** [comment]
@LuckyHookin 感谢你帮我回答问题，不过其实不是这个原因 😂 

@pendave 这个问题确实是存在的，原因是划词翻译现在的全文翻译算法还不太完善，只会对网页里的特定结构触发翻译，部分在特定结构之外的文本是不会被翻译的。 txt 文件在浏览器中渲染出来的结构是不包含划词翻译识别文本需要的特定结构的，所以导致了你的问题。

这个问题会在未来的版本中优化，后续进展可以关注 #1022

**Comment by lmk123** [comment]
v8.5.0 已经使用了全新的网页全文翻译算法，但是这个算法目前还不支持纯 txt 文件，所以我重新开启了这个 issue，会在后期支持纯 txt 文件

**Comment by lmk123** [comment]
下个版本将增加对 txt 文件的支持，截图如下：

![image](https://user-images.githubusercontent.com/5035625/132858095-edab23a2-13b3-4b68-b4f0-4143173c2212.png)
