### ISSUE TITLE
翻译界面字体模糊

### ISSUE THREAD

**Issue by yc-z** [lmk123/crx-selection-translate#105]
翻页界面字体没有旧版的清晰，甚至感觉有点模糊，难道是字体的原因，还是高分屏的原因？
![default](https://cloud.githubusercontent.com/assets/15177069/12701863/f8425450-c852-11e5-965a-d971c3258393.PNG)

**Comment by woniu369** [comment]
新版的的确感觉很模糊

**Comment by woniu369** [comment]
![image](https://cloud.githubusercontent.com/assets/9634079/12704827/8acfa89a-c89e-11e5-813d-5a010ce77cf5.png)

**Comment by wewoor** [comment]
请问这个问题如何解决的？

**Comment by yc-z** [comment]
上面的评论中有信息显示作者已经修复了，但实际上好像还是有这个问题，只是出现的频率小了，当然这是我的情况，我现在已经忽略这个问题了。
![1](https://cloud.githubusercontent.com/assets/15177069/13546665/79cafe44-e2ef-11e5-8d44-af8ccbe00339.png)

**Comment by lmk123** [comment]
修复后仍然会出现这个问题吗？

**Comment by yc-z** [comment]
有时会有这个问题，但频率很低，我也是偶尔遇到，不过在翻译窗口点击固定按钮的一瞬间肯定会变模糊，见图，另外没有点击固定按钮也模糊的情况一下子也找不出，等到遇到了再截张图。
![default](https://cloud.githubusercontent.com/assets/15177069/13547151/d2ddec92-e300-11e5-9891-bcd2405e4ae3.png)

**Comment by yc-z** [comment]
刚才又发现个问题，固定后的窗口无法取消固定，即使点击取消后，点击其他单词进行翻译依然显示的是固定状态，刷新网页也没用。

**Comment by lmk123** [comment]
新的问题重开一个 issue 吧

**Comment by lmk123** [comment]
我修改了一下，现在无论是“译”字或是翻译窗口应该都不会出现模糊的情况了。

我会在解决了其它一些问题之后一并发布的。
