### ISSUE TITLE
朗读原文能不能用 Edge 浏览器的Microsfot Xiaoxiao Online (Natral) - Chinese (Mainland)(zh-CN) 语音啊？

### ISSUE THREAD

**Issue by pendave** [lmk123/crx-selection-translate#1050]
朗读原文能不能用 Edge 浏览器的 Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland)(zh-CN) 语音啊？

或者开发个能调用 Edge 浏览器大声朗读功能的 Chrome 插件呢？

![image](https://user-images.githubusercontent.com/1331881/119252008-3b7a4480-bbdc-11eb-986b-b65e392b16b6.png)

在用 52pojie 上的这个工具感觉不错啊
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1362811

Win7上也能用，但是会默认去安装 Edge 浏览器。

**Comment by lmk123** [comment]
在【设置】-【系统语音】-【选择系统语音】里给“中文简体”设置为 xiaoxiao 即可，不过选择系统语音是一个会员功能。

**Comment by lmk123** [comment]
截图如下：

![image](https://user-images.githubusercontent.com/5035625/119252922-513e3880-bbe1-11eb-93c2-dc852e8793ca.png)
