### ISSUE TITLE
给源文本处理添加一个新选项 - 将换行符替换为空格

### ISSUE THREAD

**Issue by sheer-rey** [lmk123/crx-selection-translate#1052]
## 功能简介

希望能将 “去掉换行符” 选项改为（或新增）“将换行符替换为空格” 选项。

## 为什么你觉得需要（改进）这个功能？

在现有的 ”源文本出处理-去掉换行符“ 功能中，插件仅仅是将源文本中的换行符去掉。
但是在大多数情况下，将源文本中换行符去掉之后会使得前一行的最后一个单词和后一行的第一个单词连在一起，这会对翻译准确度产生相当大的影响，尤其是英文论文普遍都分为两栏，每一行其实就只有几个单词，如果仅仅是去掉换行符，其实也就使得这个功能显得有些鸡肋了。
下图是以上问题描述的示例。

![Snipaste_2021-05-24_13-10-34](https://user-images.githubusercontent.com/80184424/119300856-08938780-bc94-11eb-90ad-54c82f843e2a.png)

**Comment by lmk123** [comment]
我猜你是在 SCI-Hub 里用划词翻译的内置 PDF 阅读器在看 PDF。如果是的话，那么这里没有空格的原因其实是内置 PDF 阅读器的一个 bug，见 https://github.com/lmk123/crx-selection-translate/issues/786 

也就是说，虽然我们在视觉上看到 `a` 和 `Single-Winding` 有换行，但是由于这个 bug 的存在，划词之后它们之间是既没有换行也没有空格的，并不是把换行换成空格就能解决的。

如果不是在 PDF 里，你可以继续留言，并提供给我出现这个问题的链接，我确认一下换行处是否是真的没有空格。

**Comment by lmk123** [comment]
内置 PDF 的这个 bug 似乎就要修复了 https://github.com/mozilla/pdf.js/pull/13257

等 PDF.js 发布新版本后我会立刻更新。

**Comment by sheer-rey** [comment]
> 我猜你是在 SCI-Hub 里用划词翻译的内置 PDF 阅读器在看 PDF。如果是的话，那么这里没有空格的原因其实是内置 PDF 阅读器的一个 bug，见 #786
> 
> 也就是说，虽然我们在视觉上看到 `a` 和 `Single-Winding` 有换行，但是由于这个 bug 的存在，划词之后它们之间是既没有换行也没有空格的，并不是把换行换成空格就能解决的。
> 
> 如果不是在 PDF 里，你可以继续留言，并提供给我出现这个问题的链接，我确认一下换行处是否是真的没有空格。


我是用的 Edge Chromium 阅读的本地PDF文件，没有用内置PDF阅读器。同时我阅读了您回复中的 [#786](https://github.com/lmk123/crx-selection-translate/issues/786) 问题，然后去自行测试了一下，发现了如下问题：
- 按照问题中的的操作方式：选中文本 -> 右键 -> 划词翻译 -> 翻译这段文本 -> 得到的结果是没有错误的，如下图。
![image](https://user-images.githubusercontent.com/80184424/119309157-85c4f980-bca0-11eb-880e-26b4be5e91d6.png)
- 有问题的操作方式：选中文本 -> CTRL+C -> 快捷键打开独立翻译窗口 -> 插件自动粘贴+源文本处理 -> 然后就是有问题的结果，如下图。
![image](https://user-images.githubusercontent.com/80184424/119309796-5f538e00-bca1-11eb-8392-9c5d276624c6.png)
- 我将图中的源文件上传至附件，您可以自行测试一下。

最后，我还有另外一个疑问：
Edge Chromium 阅读本地PDF文件是否无法使用默认快捷键 Alt+S ?（在独立翻译窗口中显示当前网页中选中文本的翻译结果）。
也就是说，我目前遇到的第二个问题是Edge Chromium 阅读本地PDF文件时无法直接使用快捷建翻译选中的文本（右键选项卡的方式可行），这个问题是否有办法解决呢？

**Comment by lmk123** [comment]
我也试了下，确实是那样，通过右键菜单翻译没有问题，但是复制到剪切板再粘贴到文本框翻译就是有问题的。我会加一个选项“将换行符替换为空格”来避免这个问题。

> Edge Chromium 阅读本地PDF文件是否无法使用默认快捷键 Alt+S ?

是的，因为浏览器自带的 PDF 阅读器，扩展程序是没有权限注入代码的，只能通过右键菜单的方式拿到你划选的文本。这也是为什么划词翻译内置了一个 PDF 阅读器的原因。

**Comment by lmk123** [comment]
在下个版本 v8.5.7 中，我没有增加新的选项，而是把目前的“去除换行符”直接改为了“将换行符替换为空格”，因为我估计文本中多几个空格应该不会影响翻译结果的质量。
