### ISSUE TITLE
开发开一个桌面客户端。

### ISSUE THREAD

**Issue by xxxxha** [lmk123/crx-selection-translate#1055]
## 为什么你觉得需要（改进）这个功能？
目前，我使用DeepL的桌面版本，两次“Ctrl+C”就能呼出翻译界面，相当好用。但国内用户使用DeepL并不是很稳定，大部分时间还是要开启vpn，但有时任然不稳定的（网络的因素）。google翻译还是比较稳定的。
所以，希望能开发一个客户端，功能基本就和目前的插件一致就行，可以多一个选择，比如多一个google翻译。

**Comment by lmk123** [comment]
开发桌面客户端正在考虑，目前会先优先保证新功能的开发和已有功能的改进，之后可能会开始开发桌面端。

后续进展可以关注 #992

**Comment by lmk123** [comment]
不过划词翻译是支持在浏览器外用 Ctrl + Shift + 1 （可以修改成短一点的）来呼出独立翻译窗口的，所以我觉得使用体验上跟桌面端没有区别，你是不是不知道划词翻译的这个功能？

**Comment by clark-cui** [comment]
> 不过划词翻译是支持在浏览器外用 Ctrl + Shift + 1 （可以修改）来呼出独立翻译窗口的，所以我觉得使用体验上跟桌面端没有区别，你是不是不知道划词翻译的这个功能？

### 大佬你好，关于这一点，我也有一些使用体会
1. 我开启了独立翻译窗口，在别的软件需要翻译的时候，先要选中,然后**ctrl+c**复制到剪贴板，这时独立翻译窗口并不会自动读取我的剪贴板内容，我需要手动触发他才会更新翻译，也就是**ctrl+shift+1**。其实是需要3步操作的。
而加入用客户端实现，就只需要两步操作了，比如鼠标选中，然后快捷键。我注意到一些软件的实现，也更加巧妙一些，比如鼠标选中后按鼠标滚轮，这样一只手就能实现。
2. 我也注意到独立窗口只有一个图片翻译的选项，可以选择图片和读取剪贴板的图片。如果使用的话，其实也是需要多加操作步骤的，比如借助微信的截图工具，然后在粘贴到剪贴板。我猜测是因为划词翻译的截图翻译用的是chrome的api?所以在浏览器外无法截图，要实现的话只能自己写？

我个人觉得从使用体验的角度来说，客户端的实现，还是很有必要的，我觉得也能拉动一波新用户，毕竟文字工作者是翻译软件的重度用户，而他们大都是在一些第三方软件输入输出文字的。前面有老哥也说了electron相关的技术，是否可以做一个参考呢？不知道大佬怎么看。

**Comment by lmk123** [comment]
@clark-cui 

1. 是的，受限于浏览器的限制，划词翻译无法持续监听你的剪切板，所以只有当你按下快捷键后才能用独立窗口翻译
2. 是的，也是受限于浏览器的限制，无法截取浏览器外的屏幕。

由于浏览器有以上限制，所以我确实有开发桌面版的打算，但这不是目前的最高优先级。在功能比较稳定之后，我会尝试开发一个桌面端。
