### ISSUE TITLE
阿里翻译异常

### ISSUE THREAD

**Issue by SWAT-hongyi** [lmk123/crx-selection-translate#1056]
## 基本信息

划词翻译版本：7.6.9
浏览器版本：Microsoft Edge 90.0.818.66 
操作系统：Win10

## 重现问题的步骤

1.正常进行划词翻译

### 预期行为
阿里翻译给出结果
### 实际行为
阿里翻译提示：服务器返回了错误的 HTTP 响应码：404

**Comment by lmk123** [comment]
阿里翻译报 404 错误说明你的 AccessKey ID 不存在，请确认你的  AccessKey ID 是否填写正确。
