### ISSUE TITLE
PDF翻译功能文字选定异常

### ISSUE THREAD

**Issue by Justin-Young** [lmk123/crx-selection-translate#1058]
您好，非常感谢您开发这么好用的插件！最近我在使用插件的PDF翻译功能时遇到了一些困扰，非常希望可以改善，谢谢！
## 基本信息

划词翻译版本：v7.6.9
浏览器版本：Microsoft Edge 90.0.818.66 Chrome
操作系统：Win10 20H2 19042.985

## 重现问题的步骤

1.在划词翻译中打开英文文档 如[deep learning](https://s3.us-east-2.amazonaws.com/hkg-website-assets/static/pages/files/DeepLearning.pdf) [MeDNN](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8203852)
2.最好是能够用MeDNN这篇文档（但是下载有限制，如果您需要可以邮件发给您），选定文本进行翻译或者复制
3.不能很好的根据原文本选定文本，即选定区域和实际文本有差异，因此也造成了选定区域不易控制，选定区域老是跳。对于arxiv上的文档（单栏）表现较好，但对于IEEE Xplore等**双栏文档**表现不好，尤其左侧的选定常常不太好用

### 预期行为
选定文本和原文文本能够一一对应，达到浏览器内置PDF阅读器的选定效果，选定更加方便
### 实际行为
显示的选定文本和原本文本不对应，因此也导致选定区域不易控制(下面两张图只是选定文本时**多选了1个字母**后的选定区域的效果对比），如下图
![image](https://user-images.githubusercontent.com/53030626/119758781-ae840380-bed9-11eb-8883-b3a12726e1e9.png)
![image](https://user-images.githubusercontent.com/53030626/119758829-c9567800-bed9-11eb-87fd-87013b6f584e.png)

![image](https://user-images.githubusercontent.com/53030626/119760434-9366c300-bedc-11eb-86d7-ebbc984187c5.png)
![image](https://user-images.githubusercontent.com/53030626/119762419-4389fb00-bee0-11eb-906e-c1b6d8b73a67.png)

![image](https://user-images.githubusercontent.com/53030626/119762341-13daf300-bee0-11eb-96e6-cc7774f61689.png)
![image](https://user-images.githubusercontent.com/53030626/119762347-19383d80-bee0-11eb-8942-a842b3544d6e.png)

**内置浏览器的选定效果**
![image](https://user-images.githubusercontent.com/53030626/119759070-281bf180-beda-11eb-8f36-1da4d3311fa3.png)
**复制效果**
选定区域
![image](https://user-images.githubusercontent.com/53030626/119764027-3a4e5d80-bee3-11eb-8ee2-9816d490e627.png)
复制的文本 `mobile devices. In this work, we design`

**Comment by lmk123** [comment]
你好，非常感谢你提供了如此详细的问题重现步骤！但是很抱歉，这些问题可能一时半会儿得不到很好的解决。

建议你使用浏览器自带的 PDF 来阅读 PDF，并使用划词翻译的独立窗口获取翻译结果。浏览器自带的 PDF 阅读器能提供更好的使用体验，但是划词翻译无法直接在它内部显示翻译结果，不过划词翻译支持使用独立窗口显示翻译结果。

具体做法如下：不要开启“自动打开 PDF”，将 PDF 拖放到浏览器中后，浏览器会用它自带的 PDF 阅读器打开。你划词后：

- 右键选择“翻译这段文本”
- 或者，用 Ctrl + C 复制文本后，使用全局翻译快捷键（默认为 Ctrl + Shift + 1）打开独立翻译窗口进行翻译

### 为什么这些问题一时半会儿不能解决？

内置 PDF 阅读器是我基于 Firefox 浏览器开源的 [PDF.js](https://github.com/mozilla/pdf.js) （也就是 Firefox 浏览器里的 PDF 阅读器）二次开发的，你提的这些问题都属于 PDF.js 的问题，但是，这些问题需要等待 Firefox 修复，我能做的只有在 PDF.js 发布新版本时尽快更新到划词翻译当中。

**Comment by Justin-Young** [comment]
谢谢您的回复，我还想反映另外一个问题，在使用内置PDF进行阅读，并通过Ctrl+C、Ctrl+Q翻译时，**会有很多换行符，导致翻译的效果变差，可读性也变差**，请问这个问题能否解决呢？

**Comment by lmk123** [comment]
有两种解决方案：

- 第一种，在【设置】-【源文本处理】中开启“去掉换行符”；未来还会加一个新选项“将换行符替换为空格”，可以关注 #1052 查看进展
- 第二种，按照 #1052 中用户的反馈，使用**浏览器**的 PDF 阅读器时，划词后用右键菜单的“翻译这段文本”是没有多余的换行符的，你可以试试看是不是这样的。

如果对以上两种方法有疑问，欢迎继续留言。

**Comment by Justin-Young** [comment]
可以解决了，谢谢
