### ISSUE TITLE
全都要钱了？

### ISSUE THREAD

**Issue by micenote** [lmk123/crx-selection-translate#1059]
全都要钱了？

**Comment by lmk123** [comment]
如果你指的是普通的功能，那么并没有，v6.x 存在的功能包括网页划词、内置 PDF 阅读器、自动朗读等功能，在 v7.x 里仍然是免费的。v7.x 只对新添加的功能，例如截图翻译、全文翻译、语音翻译加了每天使用限制。

如果你指的是百度、有道等翻译源，这些翻译源一直都是支持自行申请密钥使用免费额度、或者购买翻译积分使用的，并没有要求一定要购买翻译积分才能用。
