### ISSUE TITLE
划词翻译--百度 旧服务已下线，请迁移至 http://api.fanyi.baidu.com

### ISSUE THREAD

**Issue by woniu369** [lmk123/crx-selection-translate#106]
旧服务已下线，请迁移至
 http://api.fanyi.baidu.com

**Comment by lmk123** [comment]
谢谢提醒 :)

**Comment by kslr** [comment]
正想趁机发个PR呢

**Comment by lmk123** [comment]
@kslr 实际上我代码已经写好了，只是百度翻译现在要收费了，所以我一直在考虑还要不要继续接入百度翻译

**Comment by greatapp** [comment]
百度死要钱

**Comment by kslr** [comment]
@lmk123 有没有考虑过模拟发送POST数据

curl 'http://fanyi.baidu.com/v2transapi'  -H 'Origin: http://fanyi.baidu.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.8' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: */*' -H 'Referer: http://fanyi.baidu.com/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'DNT: 1' --data 'from=zh&to=en&query=%E4%BA%8B%E5%AE%9E%E4%B8%8A&transtype=realtime&simple_means_flag=3' --compressed

**Comment by lmk123** [comment]
@kslr 这是个好办法

**Comment by 178620086** [comment]
http://fanyi.baidu.com/v2transapi?query=
可以使试试这个接口

**Comment by gggccc44** [comment]
收费就算了吧，本来你就是免费的，反正不用百度还有其他

**Comment by lmk123** [comment]
已恢复百度翻译 lmk123/translation.js#1
