### ISSUE TITLE
发现了一个偶发性的网页翻译错误：翻译结果会被放到错误的位置

### ISSUE THREAD

**Issue by hmrg-grmh** [lmk123/crx-selection-translate#1062]
## 基本信息

划词翻译版本：
![image](https://user-images.githubusercontent.com/68635334/119835175-2d595a80-bf33-11eb-9aa2-f3b205cc9020.png)

浏览器版本：
![image](https://user-images.githubusercontent.com/68635334/119835230-3b0ee000-bf33-11eb-8431-e275426d843a.png)

操作系统：win10

## 重现问题的步骤

问题是偶发性的，而且是之后重新检查离线的网页才发现的，所以不能提供复现步骤。

猜测可能是我上下滑页面太快了导致的？这只是猜测。

链接：https://learnyousomeerlang.com/the-hitchhikers-guide-to-concurrency

### 对比1

错误的效果：
![image](https://user-images.githubusercontent.com/68635334/119835590-8d500100-bf33-11eb-9e8f-5dcedd850876.png)

正确的效果：
![image](https://user-images.githubusercontent.com/68635334/119835690-a35dc180-bf33-11eb-9b3c-4ae0d5d13fbe.png)

### 对比2

错误的效果：
![image](https://user-images.githubusercontent.com/68635334/119836209-1ff0a000-bf34-11eb-9656-813159a2cc61.png)

正确的效果：
![image](https://user-images.githubusercontent.com/68635334/119836009-f33c8880-bf33-11eb-9d70-0dd2e67cd277.png)

**Comment by lmk123** [comment]
理论上讲不应该出现这个问题，所以如果不能稳定重现的话，我也无从解决 :joy:

**Comment by hmrg-grmh** [comment]
> 理论上讲不应该出现这个问题，所以如果不能稳定重现的话，我也无从解决 😂

...嗯... 不过也可以自己尝试以下，打开页面开启翻译，然后比较暴力地快速往下滑，再往上滑回去，用鼠标（我是用的触摸板双指），没事儿用工具的时候可以这样试试，兴许就把情况复现了呢。。。。🐒

**Comment by hmrg-grmh** [comment]
又重现了一次。
是在翻译github的时候我展开了提交的详细描述，然后它就卡住了。
等了会儿还是卡着。

然后我就快捷键收起翻译，快捷键再开翻译，
它就把下面卡住没出来的翻译内容，在上面错误的位置整出来了。

卡住本身并不能稳定重现，不过前面见到过一次“虽然引擎已经返回了内容但是页面还是请稍后”的情况。所以说可能有网络不稳定（或者有特殊字符）的影响，不一定是翻译结果没有得到。

**Comment by lmk123** [comment]
> 翻译结果会被放到错误的位置

这个问题没能重现。我开启网页全文翻译并快速上下滚动，尝试了 3 次之后还是没能重现。如果能稳定重现的话，可以继续留言。

> 在翻译github的时候我展开了提交的详细描述，然后它就卡住了

我在 https://github.com/lmk123/crx-selection-translate/commits/7.x-master 找了一个有详细描述的 commit “fix: 修复火狐不能拖动窗口的问题”，并展开了它的详细描述，但没有出现卡住的情况。事实上，由于 commit 的详细描述是包含在代码块  `<pre>` 标签里的，所以全文翻译不会翻译它，不过里面的链接 `<a>` 是可以正常翻译出来的，没有出现卡住的情况。

如果你还有这个问题，可以再开一个 issue（因为看起来它跟“翻译结果会被放到错误的位置”不是同一个问题），并附上具体的重现步骤，例如提供出现这个问题的链接、具体是哪个 commit 有这个问题等。
