### ISSUE TITLE
无法把繁体中文翻译为简体中文

### ISSUE THREAD

**Issue by aoxu** [lmk123/crx-selection-translate#1063]
选中一段繁体中文时，翻译结果应该是简体中文，实际结果是英文。

此时采用了默认设置：源文本的语言为简体中文时，翻译为英文；否则翻译为简体中文。
启用的翻译接口按顺序为：DeepL、Google 翻译、必应词典
我在 Chrome/Edge 浏览器+ Windows 10/macOS Catalina 下可以稳定重现这个问题，浏览器和系统都是最新的稳定版。

我猜测有可能是划词翻译（或采用的翻译接口）错误地把繁体中文的源文本识别为了简体中文。

**Comment by lmk123** [comment]
你的猜测很准确 😂 

划词翻译使用的判断语种的方法不能区分繁体中文和简体中文，所以导致了这个情况发生。我会想办法看看能不能优化这一情况

**Comment by aoxu** [comment]
谢谢
我使用的另一款浏览器扩展 Mate Translate 没有这个问题，相信你也可以解决
2021年5月31日 +0800 06:09 mingkaili ***@***.***>，写道：

**Comment by lmk123** [comment]
划词翻译内置语种检测确实无法区分繁体中文和简体中文，所以源语种设置为“自动检测”时，这个问题无法避免。但在下一个版本 v8.4.2 中，我将源语种改为跨页面固定了（以前是修改源语种后只对当前页面生效，刷新页面或跳转到另一个页面就会重置为“自动检测”），当你需要经常将繁体中文翻译为简体中文时，可以将源语种设置为“繁体中文”，就不会有这个问题了。

**Comment by aoxu** [comment]
没想到还能这样解决，我试试，谢谢
