### ISSUE TITLE
全文翻译优化对<br>的处理

### ISSUE THREAD

**Issue by CCXXXI** [lmk123/crx-selection-translate#1064]
## 功能简介
示例网页：https://www.penguinrandomhouse.ca/books/58774/i-cannot-tell-a-lie-exactly-by-mary-ladd-gavell/9780375758225/excerpt

其中正文部分整个位于`<p></p>`中，段落之间用`<br><br>`分隔。

如果尝试全文翻译，翻译结果会被添加到整个`<p></p>`之后，并且会卡在`正在翻译，请稍候……`。（因为内容太多了？）

希望翻译被添加到每段之后，就像正常使用`<p></p>`标记段落的网页那样。

**Comment by lmk123** [comment]
好的，我会在未来的版本中优化。

> 因为内容太多了？

是的，一次只能翻译 4000 个字符以下的文本

**Comment by lmk123** [comment]
即将发布的 v8.5.0 使用了全新的网页文本识别算法，已针对这种情况做了适配。
