### ISSUE TITLE
某些网站比如论坛在全文翻译时除了帖文其余都能翻译😹

### ISSUE THREAD

**Issue by tortoo** [lmk123/crx-selection-translate#1065]
划词翻译版本：8.1.2
浏览器版本：Chrome 90.0.4430.212
操作系统：Mac OS 11.2.3

## 重现问题的步骤

1. 比如[macrumors论坛某一篇帖子](https://forums.macrumors.com/threads/ios-app-on-m1-mac-is-confused.2294524/)，用划词翻译的全文翻译，帖文正文无法翻译，其余都能
2.用Chrome自带的全文翻译，帖文和其余都能正常翻译

### 预期行为
全文翻译时，论坛的帖文应该像浏览器自带的翻译那样都能正常翻译
### 实际行为
帖子正文无法翻译

**Comment by lmk123** [comment]
确实是有这个问题的，未来的版本会修复这个问题，后续进展会更新到 #1022
