### ISSUE TITLE
作者大大，您好，我想问一下github和官网的发布问题。

### ISSUE THREAD

**Issue by rainseason1** [lmk123/crx-selection-translate#1067]
我注意到github上面版本的发布已经落后好几个版本了，应该是和官网不同步了。我想问一下，以后是都在官网上面更新了吗？
彻底抛弃github了？
那如果官网发布了更新，我在浏览器上面装的扩展如何更新呢？

**Comment by lmk123** [comment]
如果你是从商店安装的划词翻译，那么我发布到商店之后，浏览器会自动更新；如果你由于某种原因不能自动更新，可以在官网下载离线安装包：https://hcfy.limingkai.cn/docs/install#offline
