### ISSUE TITLE
您好，8.3.2版本选完词后不能换行了

### ISSUE THREAD

**Issue by gkm0120** [lmk123/crx-selection-translate#1069]
## 基本信息

划词翻译版本：8.3.2
浏览器版本： Chrome 91.0.4472.77
操作系统：win10

## 重现问题的步骤

1.打开pdf，如 https://arxiv.org/pdf/2104.13030
2.使用内置的 PDF 阅读器复制两行文字以上，谷歌/百度翻译的结果不能自动换行
3.如图所示![image.png](https://i.loli.net/2021/06/07/CcF9KmwAuaDMkR6.png)

### 预期行为
昨天翻译一切正常，今天不能实现换行，麻烦看一下，谢谢。

**Comment by lmk123** [comment]
已确认此 bug，原因是 v8.3.2 升级了内置 PDF 阅读器的版本，而这个版本有这个问题。我会尽快修复

**Comment by lmk123** [comment]
已发布 v8.3.3 修复了这个问题，审核需要一段时间，不过可以去官网下载离线安装包安装。
