### ISSUE TITLE
v6.0.2、v6.0.1用浏览器打包失败，希望提供插件，谢谢！

### ISSUE THREAD

**Issue by greatapp** [lmk123/crx-selection-translate#107]
提示：清单文件缺失或不可读。

**Comment by greatapp** [comment]
v6.0.3也不行，求助。
另外，旧版的，百度翻译失效

**Comment by lmk123** [comment]
我推荐你暂时先使用 [v5.6.1](https://github.com/lmk123/crx-selection-translate/releases/tag/v5.6.1) 的安装包。

每次在 Chrome 网上应用店里发布之后，我才能下载它提供的安装包，这次划词翻译被删除了也就没有提供安装包给我下载了。

如果我自己打包一个，那 Chrome 浏览器可能会阻止你安装（因为来源不是 Chrome 网上应用店），并且你无法自动更新。

**Comment by greatapp** [comment]
那别人怎么用的？
还有，百度翻译，旧服务已下线，请迁移至 http://api.fanyi.baidu.com

**Comment by lmk123** [comment]
那是因为在 Chrome 网上应用店删除划词翻译之前，他们的 Chrome 就已经自动升级至 v6.0.2 版本了。

百度翻译的事情我已经知道了 #106

**Comment by greatapp** [comment]
哦，我的也自动升级了，不过我发现百度不能用，又被我删了，哭……

**Comment by lmk123** [comment]
百度翻译现在要收费啦，所以我一直在考虑还要不要接入百度翻译，于是就迟迟没有动手改。:grin:
