### ISSUE TITLE
优先翻译为中文(简体)功能有问题

### ISSUE THREAD

**Issue by iseeyo** [lmk123/crx-selection-translate#1071]
划词翻译版本：v8.3.3
浏览器版本：360极速浏览器v13.0.2250.0，Chromium内核是v86.0.4240.198
操作系统：Windows10

## 重现问题的步骤
任意繁体中文网页，选中不会翻译成简体中文，而是直接翻译成英文了，建议修正，让繁体中文也能翻译成简体中文。如图：
![image](https://user-images.githubusercontent.com/7778828/121380359-605e0e00-c977-11eb-94f2-225022295f9d.png)

### 预期行为
翻译成简体中文

### 实际行为
翻译成英文

**Comment by lmk123** [comment]
已知问题（#1063），会在未来的版本中修复

**Comment by lmk123** [comment]
划词翻译内置语种检测确实无法区分繁体中文和简体中文，所以源语种设置为“自动检测”时，这个问题无法避免。但在下一个版本 v8.4.2 中，我将源语种改为跨页面固定了（以前是修改源语种后只对当前页面生效，刷新页面或跳转到另一个页面就会重置为“自动检测”），当你需要经常将繁体中文翻译为简体中文时，可以将源语种设置为“繁体中文”，就不会有这个问题了。
