### ISSUE TITLE
有些网页用网页全文翻译不能翻译正文

### ISSUE THREAD

**Issue by zerojade** [lmk123/crx-selection-translate#1072]
## 基本信息

划词翻译版本：8.3.3
浏览器版本：chrome 91.0.4472.77
操作系统：win10

## 重现问题的步骤

1.打开https://chinesesites.library.ingentaconnect.com/content/ben/cnanom/2018/00000008/00000001/art00006
2.正常使用网页全文翻译

### 预期行为
网页全文翻译
### 实际行为
最主要的正文部分没有翻译，只翻译了网页按钮
![屏幕截图 2021-06-10 012619](https://user-images.githubusercontent.com/21169074/121401104-ec2d6580-c98a-11eb-8135-7e79d618895b.png)

**Comment by lmk123** [comment]
看了一下，跟 #1022 是同一个问题，后续进展会更新到 #1022
