### ISSUE TITLE
全文翻译复制翻译结果，中英没有换行。

### ISSUE THREAD

**Issue by ronnywr** [lmk123/crx-selection-translate#1074]
![image](https://user-images.githubusercontent.com/38126770/121650592-48e46980-cacc-11eb-95f5-57532c18dfde.png)
复制的翻译结果是跟原文连在一起的。希望可以像网页上的展示一样中英文分开

**Comment by lmk123** [comment]
感谢反馈，这算是一个 bug，我会在未来的版本中修复

**Comment by lmk123** [comment]
即将发布的 v8.5.0 将修复这个问题。
