### ISSUE TITLE
建议：直接显示有道词典的查询结果

### ISSUE THREAD

**Issue by microka** [lmk123/crx-selection-translate#1077]
## 功能简介
在翻译面板上直接显示有道词典的查询结果
## 为什么你觉得需要（改进）这个功能？
参考[穆译 (Smooth Translator)](https://github.com/greatghoul/smooth-translator) #346 
本人认为有道词典的查询结果挺不错的（比如 HomePod 一词，谷歌翻译和必应词典都没有可用的查询结果，而有道词典至少解释了「n. 由 Apple 公司推出的智能音箱」），希望作者能予以适配，感谢。

**Comment by lmk123** [comment]
由于[这个原因](https://hcfy.limingkai.cn/blog/2021/01/14/use-official-api#why)，我不打算使用你提到的方式接入有道词典，抱歉。

另外，目前划词翻译里的【有道翻译】其实就自带有道词典的内容，如图：

![image](https://user-images.githubusercontent.com/5035625/122684349-7ef5bc00-d237-11eb-8af2-a53810330290.png)
