### ISSUE TITLE
在 Genius 站点中全文翻译后仅有解析的歌词会被翻译

### ISSUE THREAD

**Issue by ZeaKyX** [lmk123/crx-selection-translate#1078]
## 基本信息

划词翻译版本：8.1.2
浏览器版本：Microsoft Edge 版本 91.0.864.54 
操作系统：Windows 10

## 重现问题的步骤

1.进入 Genius，选择一首歌曲，如[这首](https://genius.com/Bo-burnham-welcome-to-the-internet-lyrics)
2.开启全文翻译

### 预期行为

可以每一句都翻译

### 实际行为

能够进入详细解析（有控件）的句子才会被翻译，如图：
![image](https://user-images.githubusercontent.com/43315078/122639503-ca6f7380-d12c-11eb-9c14-74235e24fc37.png)

**Comment by lmk123** [comment]
我看了一下，跟 #1064 属于同一种情况，将会在未来的版本中进行优化

**Comment by ZeaKyX** [comment]
@lmk123 我查证了一下，实际上 Genius 站点貌似在搞新界面灰度测试

**使用 Edge 浏览器会有特别的界面布局**，截图上方就可以看出来。旧版的界面确实以`<p></p>`包含整个正文，与您提供的参考连接相同。但是新界面不同，Chrome 应该是复原了另一个bug😂

附上新布局下段落的代码，正文有若干段落,：
```
<div data-scrolltrigger-pin="true" class="Lyrics__Container-sc-1ynbvzw-7 jjqBBp">
...
</div>
```
所以往下滑也没看到翻译

**Comment by lmk123** [comment]
这个网站现在在 Chrome 和 Edge 的表现一致了，即将发布的 v8.5.0 使用了全新的网页文本检测算法，已确认在你提供的网站里可以正常翻译。
