### ISSUE TITLE
“不在文本框划词”的适用范围还不够宽啊，在有些网站的输入框内不起效

### ISSUE THREAD

**Issue by sherlocknieh** [lmk123/crx-selection-translate#1079]
## 基本信息

划词翻译版本：v8.3.4
浏览器版本：Firefox
操作系统：Win10

## 重现问题的步骤

1.设置中勾选了“不在文本框划词”
2.在 [GitMind ](https://gitmind.cn)、[Wolai](https://www.wolai.com)、[腾讯文档](https://docs.qq.com)等网站编辑在线文本
3.在编辑区域划词

### 预期行为

不弹出翻译面板

### 实际行为

不弹出翻译面板

**Comment by lmk123** [comment]
确实有这个问题，会在未来的版本中改进。

**Comment by lmk123** [comment]
感谢反馈，已在 v8.6.7 中修复此问题。v8.6.7 将在近期发布。
