### ISSUE TITLE
给“读取剪切板内的图片并翻译”添加一个快捷键

### ISSUE THREAD

**Issue by JamesW99** [lmk123/crx-selection-translate#1082]
## 功能简介
使用快捷键呼出一个截图工具，并对截图进行ocr和翻译。而不是截图-保存-打开翻译窗口-找到保存的图片。

## 为什么你觉得需要（改进）这个功能？
某些网站或者弹出提示没法复制

**Comment by lmk123** [comment]
> 某些网站或者弹出提示没法复制

这个是浏览器的安全限制，划词翻译没法突破这个限制。具体点讲，如果你用划词翻译截图的话，只能在 https 里复制截图

我猜你的痛点估计是，你用了其它截图软件（例如微信的截图工具）截了图之后，想在划词翻译里翻译这个截图，但路径太长了。

针对这一点，我打算加入一个新的选项“打开窗口时自动读取剪切板里的图片”（见 #1021），不知道是否能解决你的问题？

**Comment by JamesW99** [comment]
shift+win+s 的截图应该就在剪贴板里吧？

但我不希望所有截图都被ocr和翻译，这样会浪费大量的接口额度。只需要用某个特定快捷键呼出的截图工具才进行ocr和翻译（像 bob一样，有个功能叫截图翻译）。

**Comment by lmk123** [comment]
> shift+win+s 的截图应该就在剪贴板里吧？

是的

> 只需要用某个特定快捷键呼出的截图工具才进行ocr和翻译（像 bob一样，有个功能叫截图翻译）

bob 是运行在操作系统之上的软件，但划词翻译是运行在浏览器之上的，这也是为什么 bob 的截图翻译可以截整个桌面、但划词翻译的截图只能截网页的原因。

> 但我不希望所有截图都被ocr和翻译，这样会浪费大量的接口额度。

或者，我不做成自动翻译截图的形式，而是每次打开翻译窗口时，如果检测到剪切板里有图片，就在翻译窗口上给出一个提示，点了确定再翻译，你觉得怎么样？

**Comment by lmk123** [comment]
又或者我加个快捷键“翻译剪切板内的截图”，只要按下这个快捷键就读取剪切板里的截图并翻译，所以如果你要用外部工具截图然后在划词翻译里翻译，只需要按下两个快捷键：

1. 第一个快捷键为外部截图工具（例如微信的 Alt + A）
2. 第二个快捷键为划词翻译的快捷键

**Comment by JamesW99** [comment]
如果在图片翻译的按钮边上再加一个读取剪贴板并翻译的按钮呢？我只是不想把要翻译的东西都已图片的形式保存在硬盘里。

**Comment by JamesW99** [comment]
> 又或者我加个快捷键“翻译剪切板内的截图”，只要按下这个快捷键就读取剪切板里的截图并翻译，所以如果你要用外部工具截图然后在划词翻译里翻译，只需要按下两个快捷键：
> 
> 1. 第一个快捷键为外部截图工具（例如微信的 Alt + A）
> 2. 第二个快捷键为划词翻译的快捷键

这是个很好的主意！

**Comment by lmk123** [comment]
我将这个用法改了一下，没有单独给“读取剪切板内的图片并翻译”加快捷键，而是给“自动读取剪切板”加了一个新的选项“自动读取剪切板内的图片”，并默认开启，也就是 https://github.com/lmk123/crx-selection-translate/issues/1021

这样一来，当你打开独立翻译窗口 & 扩展按钮弹窗的时候，就会自动读取剪切版内的图片并翻译，而独立翻译窗口和扩展按钮弹窗都有各自的快捷键。

特别是独立翻译窗口支持全局快捷键 Ctrl + Shfit +1，所以使用方式最终变成了：

1. 使用外部截图工具（例如微信的 Alt + A 或 Windows 系统自带的 Win + Shift + S）
2. 按下 Ctrl + Shfit +1 打开独立翻译窗口

下个版本 v8.4.2 就会上线这个功能，到时候欢迎反馈给我你的使用体验。
