### ISSUE TITLE
全文翻译StackOverflow的回答页面时，回答下的回复内容未翻译

### ISSUE THREAD

**Issue by Orienser** [lmk123/crx-selection-translate#1084]
## 基本信息

划词翻译版本：v8.3.4
浏览器版本：Google Chrome 91.0.4472.114 (64位)
操作系统：Windows10

## 重现问题的步骤
1. 随便打开一个StackOverflow问题，例如[这个](https://stackoverflow.com/questions/67988828/why-is-python-recursion-so-expensive-and-what-can-we-do-about-it)。
2. 开启插件的网页全文翻译。

### 预期行为
每个回答下的回复内容应该能被翻译。

### 实际行为
回答内容已翻译，但回答下的回复未翻译，仍显示英文。只有回复中带链接的短语以及回复人名称被翻译了。

**Comment by lmk123** [comment]
其实这个问题跟 #1022 是同一个，后续请关注 #1022
