### ISSUE TITLE
一级右键菜单下开启全文翻译

### ISSUE THREAD

**Issue by Orienser** [lmk123/crx-selection-translate#1085]
## 功能简介
希望能添加一个设置项，可以将浏览器右键菜单中的网页全文翻译单独拎出来，放到右键菜单的一级目录下。

## 为什么你觉得需要（改进）这个功能？
可以减少开启全文翻译功能的操作时间。
类似我一样比较常浏览英文文档的，但英文又没那么好可以快速浏览大片内容的人，全文翻译的使用频率就会很高。
目前开启全文翻译的流程是这样的：右键菜单->滑到“划词翻译”菜单组->等待子菜单内容显示->点击网页全文翻译。
而谷歌浏览器内置的谷歌翻译只需：右键菜单->点击“翻成中文(简体)”。
咋看只少了一个步骤，但从谷歌翻译换过来就感觉明显繁琐，因此希望能新增可以直接在一级菜单目录下开启全文翻译的功能。

**Comment by lmk123** [comment]
由于划词翻译有多个右键菜单项（至少三个：截图翻译、网页全文翻译、音视频翻译），而 Chrome 会强制将同一个扩展的多个菜单项整合到一个父菜单项（也就是名为“划词翻译”的菜单组），这是无法改变的强制行为。

有以下两种方法可以解决你的痛点：

1. 在设置中给网页全文翻译设置一个快捷键。这是我比较推荐的做法
2. 又或者，我开发一个可以编辑右键菜单项的功能，这样你就可以把截图翻译和音视频翻译从右键菜单中删除掉，只保留一个网页全文翻译，当只有一项时，这个右键菜单项就会直接显示在一级菜单目录下。但是，这需要我花费一定的时间来开发。

你是否更希望我开发一个编辑右键菜单项的功能？

**Comment by TheCGDF** [comment]
1.使用快捷键快多了

2.可以直接右击插件图标然后选择“网页全文翻译”

3.一堆插件已经把我的右键菜单塞得满满的了，不能再加了，甚至划词翻译根本就不应该往右键菜单里加东西，明明只要划词就会弹出按钮，不划词还可以右击划词插件图标，实在不想点鼠标还有快捷键，右键菜单里一格“划词翻译”属实占地方

**Comment by Orienser** [comment]
> 由于划词翻译有多个右键菜单项（至少三个：截图翻译、网页全文翻译、音视频翻译），而 Chrome 会强制将同一个扩展的多个菜单项整合到一个父菜单项（也就是名为“划词翻译”的菜单组），这是无法改变的强制行为。
> 
> 有以下两种方法可以解决你的痛点：
> 
> 1. 在设置中给网页全文翻译设置一个快捷键。这是我比较推荐的做法
> 2. 又或者，我开发一个可以编辑右键菜单项的功能，这样你就可以把截图翻译和音视频翻译从右键菜单中删除掉，只保留一个网页全文翻译，当只有一项时，这个右键菜单项就会直接显示在一级菜单目录下。但是，这需要我花费一定的时间来开发。
> 
> 你是否更希望我开发一个编辑右键菜单项的功能？

快捷键的确是更快捷的方法，刚开始用没想到这点。
新增一个编辑右键菜单项的功能对我来说是不太重要了，稍后会关掉这个问题。

还是希望Chrome能开放个管理插件右键菜单的界面，像键盘快捷键那样，就没这么多事了。
