### ISSUE TITLE
能在面板上显示必应翻译的 web 释义吗？

### ISSUE THREAD

**Issue by Ansen** [lmk123/crx-selection-translate#1087]
## 功能简介

能在面板上显示必应翻译的 web 释义吗？

面板显示如下图：

![面板](https://user-images.githubusercontent.com/676412/124090185-2b7d3c80-da87-11eb-81db-f92a43201a84.png)

[网页翻译](https://cn.bing.com/dict/search?q=Persistent&qs=n&form=Z9LH5&sp=-1&pq=persistent&sc=8-10&sk=&cvid=160D304DD97D482598177E24478FAC42)如下图，面板缺少了框里面的web结果：
![网页翻译](https://user-images.githubusercontent.com/676412/124090340-54053680-da87-11eb-838f-ac9e188677d7.png)

## 为什么你觉得需要（改进）这个功能？

一些时候web的结果比书面释义更准确

**Comment by lmk123** [comment]
好的，我会在近期加入
