### ISSUE TITLE
图标优化

### ISSUE THREAD

**Issue by TheCGDF** [lmk123/crx-selection-translate#1088]
## 功能简介

如果有空可以考虑一下给图标加个白色描边，不然在浏览器Night Theme下就是这样的：

![image](https://user-images.githubusercontent.com/17256673/124303698-b18ba700-db9d-11eb-874b-36bfb0e083b5.png)

## 为什么你觉得需要（改进）这个功能？

浏览器Night Theme下看不见图标

**Comment by lmk123** [comment]
感谢反馈，后续进展会同步在 #1002
