### ISSUE TITLE
谷歌翻译识别源语言老是出错

### ISSUE THREAD

**Issue by htqx** [lmk123/crx-selection-translate#1089]
## 功能简介
比如英语识别成西班牙还是葡萄牙语，我只能无语。
看了贵软件的设置，没有发现可以设置源语言优先为英语的选项，只有设置目标语言优先为英语。
我请求你们可以开发这个选项。
谢谢正在996的你们！

## 为什么你觉得需要（改进）这个功能？
因为我觉得92%的人都是优先翻译英语的。

**Comment by htqx** [comment]
例子：resolveDynamicComponent

**Comment by lmk123** [comment]
> 没有发现可以设置源语言优先为英语的选项

有的，在这里：

![image](https://user-images.githubusercontent.com/5035625/124357711-95484280-dc4f-11eb-874a-55fe92399c1d.png)

不过这个地方的源语种选项只对当前页面有效，换了一个页面之后又会还原为“自动检测”

> 例子：resolveDynamicComponent

对于这种驼峰式的文本，建议你开启源文本处理功能，开启后，划词翻译会自动识别成如下的文本再翻译：

![image](https://user-images.githubusercontent.com/5035625/124357764-ca549500-dc4f-11eb-9889-b2987b1859fc.png)

> 谢谢正在996的你们！

没有“们”，就我一个 :joy:
