### ISSUE TITLE
新增自动开启全文翻译的功能

### ISSUE THREAD

**Issue by cxhttt233** [lmk123/crx-selection-translate#1090]
## 功能简介
选项：在全文翻译的标签页点击链接跳转之后可以继续自动全文翻译

## 为什么你觉得需要（改进）这个功能？
全文翻译多半是为了阅读当前网站的文章
假如我为了阅读没有人去翻译的原著小说，那么我看完这一章，点击下一章还要重新全文翻译，每次都要重复进行，尽管有快捷键但是还是很麻烦，也会影响阅读体验
如果增加了当前标签页继续自动翻译的选项，那么我就可以沉浸式的一直阅读，这样阅读体验就会变好

**Comment by lmk123** [comment]
不错的提议，已加入优先开发计划

**Comment by cxhttt233** [comment]
> 不错的提议，已加入优先开发计划

非常感谢😄

**Comment by lmk123** [comment]
最近也有用户建议添加这个功能，但是不是针对单个标签页，而是无论打开什么页面都自动开启网页全文翻译。

你觉得改成“无论打开什么页面都自动开启网页全文翻译”对你的使用上会有什么影响吗？

**Comment by cxhttt233** [comment]
> 最近也有用户建议添加这个功能，但是不是针对单个标签页，而是无论打开什么页面都自动开启网页全文翻译。
> 
> 你觉得改成“无论打开什么页面都自动开启网页全文翻译”对你的使用上会有什么影响吗？

就个人而言，我觉得这样是会影响到的。可以折衷一下，从全文标签页打开的所有新标签页也自动全文，全文标签页跳转之后也自动保持全文。

这个功能的目的是为了省去多余的点击操作，但是如果无论什么页面都全文的话，反而可能会带来多余的关闭全局的操作。
这样的话我可能会专门开edge用翻译，然后开chrome用于普通的浏览和搜索

因此从我个人的角度来看，还是保留对页面的细粒度控制权对用户更加方便点

**Comment by cxhttt233** [comment]
不过做个总开关实现感觉也挺简单的，如果有人真的有需要的场景，感觉也可以

**Comment by lmk123** [comment]
这样吧，这个版本我先做一个总开关，开启的话就对所有页面自动打开网页全文。你可以先用一下，如果觉得有问题，那在未来的版本我再考虑更细粒度的控制

**Comment by cxhttt233** [comment]
好的好的

**Comment by zerojade** [comment]
> 最近也有用户建议添加这个功能，但是不是针对单个标签页，而是无论打开什么页面都自动开启网页全文翻译。
> 
> 你觉得改成“无论打开什么页面都自动开启网页全文翻译”对你的使用上会有什么影响吗？

影响很大，我想在一些网页自动开，如果能自定义网址规则决定哪些网页自动开/关（就是总开关加个例外名单？v2ray分应用代理那种逻辑）就完美了。比如说有时候我要摸鱼看个视频，这个功能就很碍事，等我回归工作就要重新开上。（因为我喜欢双语对照，不管中英文都会翻译的）
或者有时候我看文献希望它开着，但是找资料的时候用到中文网页就不需要开，如果开着会令我很困惑，假如找资料和看文献的状态切换得频繁点，就要不断开开关关。如果总开关不开，那我每篇文献都要手动开（因为不是每篇文献都看全文，所以短时间内会过目挺多文献的）

**Comment by lmk123** [comment]
我新开了一个工单 #1112 专门用于讨论这个功能的改进
