### ISSUE TITLE
将 deepl 的其他翻译结果分行显示

### ISSUE THREAD

**Issue by diaolizhi** [lmk123/crx-selection-translate#1091]
如图：
![image](https://user-images.githubusercontent.com/24501682/124499586-dd529b00-ddf0-11eb-8721-97c643cea97e.png)
![image](https://user-images.githubusercontent.com/24501682/124499635-ef343e00-ddf0-11eb-9005-4fd36e53e5b4.png)

结果是正确的，但是看起来像会以为是错的。

**Comment by lmk123** [comment]
我改进一下吧，将“其他翻译结果”分行显示
