### ISSUE TITLE
v6.4.8 有道翻译一直返回异常

### ISSUE THREAD

**Issue by zrlh2803** [lmk123/crx-selection-translate#1092]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.翻译引擎选择有道翻译时，一直返回“接口返回了错误的数据，请稍候重试。”。版本是V6.4.8。切换百度翻译可用。
2.
3.

**Comment by lmk123** [comment]
v6 版本已不再维护，请使用最新版本划词翻译 v8.4.0
