### ISSUE TITLE
切换窗口后翻译文本与结果自动被清除掉

### ISSUE THREAD

**Issue by devinlee24** [lmk123/crx-selection-translate#1094]
## 功能简介
保留翻译文本与结果
## 为什么你觉得需要（改进）这个功能？
作者你好，使用这个插件已经有一年多了，最近总发现有一个比较不顺的地方，就是每次翻译了结果 如果切换了窗口或者选项卡后，回来翻译窗口结果已经没清掉了。我想很多人都会有这个不便的感受吧。 希望采纳谢谢。

**Comment by lmk123** [comment]
你好，我用 Chrome 91、划词翻译 v8.4.0 试了一下，没有出现你所说的情况，见下面的 gif

![t](https://user-images.githubusercontent.com/5035625/126829093-27bb2ada-8b68-4672-b3d2-63c806b90320.gif)

由于我无法重现，所以我没法帮你解决这个问题。如果你能稳定重现这个问题，你可以继续留言，并告诉我一些基本信息：

- 你的浏览器版本、划词翻译版本
- 能重现这个问题的简单步骤，或者你也可以像我一样录个 gif
- 这个问题是在所有网站里都有还是只在部分网站里有？如果是部分网站里有，写一下出现这个问题的网址

期待你的回复。
