### ISSUE TITLE
希望英语单词可以显示音标

### ISSUE THREAD

**Issue by cloudwww** [lmk123/crx-selection-translate#1097]
## 功能简介
希望单个英语单词下可以显示英语音标，长句子可以酌情考虑
## 为什么你觉得需要（改进）这个功能？
对于学生党很好用，查单词顺便可以学习下读音，也许还可以帮助听力障碍人群？

**Comment by lmk123** [comment]
谷歌翻译、有道翻译、搜狗翻译和必应词典都是会显示单词的音标的。其它翻译服务没有提供音标，所以划词翻译也没法显示出来。
