### ISSUE TITLE
DeepL 翻译源一直处于加载

### ISSUE THREAD

**Issue by AkaiNoCat** [lmk123/crx-selection-translate#1099]
## 基本信息

划词翻译版本：划词翻译 v8.4.0
浏览器版本：版本 91.0.4472.114（正式版本） (x86_64)
操作系统：ubuntu 20.04

## 重现问题的步骤

1. 翻译“hello”

### 预期行为
deepl：  你好

### 实际行为
DeepL 翻译源一直处于加载，用 deepl 客户端可以正常得到结果，感觉可以排除网络问题

**Comment by lmk123** [comment]
我手上没有 ubuntu 环境，但理论上讲应该跟操作系统没有关系。我用 wins 10、Chrome 91、划词翻译 v8.4.0 是可以正常使用 deepl 的（虽然加载了 15 秒才显示结果），所以我还是觉得可能是网络因素造成的。

划词翻译里用到的 deepl 翻译地址是 https://deepl.com/translator ，跟 deepl 客户端里使用的地址应该是不一样的，所以如果你下次出现了 deepl 一直加载的问题，可以试一下能不能正常打开 https://deepl.com/translator

**Comment by AkaiNoCat** [comment]
@lmk123 谢啦，恢复了，因为在 deepl 注册之后，浏览器记录了 cookie，一直会以登录身份去查翻译结果，但是国内还没有支持个人订阅，所以会被弹窗拦住，应该一直处于加载是这个问题，清理掉 cookie 就恢复啦
![image](https://user-images.githubusercontent.com/46026384/126259586-f23c2df7-de1f-4f62-a723-7f5b48eb3b9e.png)

**Comment by lmk123** [comment]
原来还有这种情况，我会把这个情况写进常见问题当中
