### ISSUE TITLE
chrome.google.com/webstore 里的页面被禁止使用划词翻译

### ISSUE THREAD

**Issue by pendave** [lmk123/crx-selection-translate#1100]
在 https://chrome.google.com/webstore/detail/niftysplit/bkmjnlfillpnkgmjnhgklpjjlpjnfeil 我无法直接快捷使用划词翻译，点击浏览器右上的划词翻译图标，会显示

> 此页面已禁用网页划词
在浏览器的内置页面中，只能使用划词后在右键菜单中选择“翻译这段文本”的翻译方式。

估计这个 BUG 是你们把这种地址算进内置页面了！这明明是网址啊！

**Comment by lmk123** [comment]
见常见问题 https://hcfy.limingkai.cn/docs/faq/#why-can-not-use-in-store
