### ISSUE TITLE
希望能自动从win剪切板取截图

### ISSUE THREAD

**Issue by SimpleIcomputer** [lmk123/crx-selection-translate#1101]
在独立翻译窗口中，希望能自动从win剪切板取截图
因为我在翻译一些OCR不太准确，或是耗时较长的PDF时使用截图工具截下来的图需要先从剪切板转换到本地磁盘里，在从本地磁盘里传到翻译插件中，十分不方便。我又希望能在特定外部PDF软件打开需要翻译的PDF文件。
达成这个功能后就可以方便的从第三方截图软件翻译，例如某一需要翻译的截图就可以先转到翻译插件里翻译，然后再复制翻译后的图片传到图床里。

**Comment by lmk123** [comment]
好的，会在后续的版本中优先处理
