### ISSUE TITLE
Firefox DeepL 翻译错误

### ISSUE THREAD

**Issue by nebula93** [lmk123/crx-selection-translate#1103]
## 基本信息

划词翻译版本：8.4
浏览器版本：Firefox  90.01 
操作系统：Windows 10

## 重现问题的步骤

1. 选中文本
2. 划词翻译
3. 

### 预期行为

等待一段时间后翻译成功

### 实际行为
DeepL 显示
翻译时出错了，错误消息：找不到source的语种下拉框。

Chrome 和 edge 没有这个问题

**Comment by lmk123** [comment]
我用 firefox 90 、 划词翻译 v8.4.0 试了一下，是可以正常使用的。你可以试一下在 firefox 里打开 https://deepl.com/translator 看看网页有没有遮挡之类的东西，如果有就关掉，如果没有就试一下重新安装划词翻译试试。

**Comment by lmk123** [comment]
@sbwtw 我没有安装 95 Nightly，但我用正式版 93 试了一下，没有问题。

偶尔确实是会出现这个问题，不过重试几次之后应该就会恢复了。如果你是 100% 出现了这个问题，我再去安装 Nightly 试一下

**Comment by sbwtw** [comment]
@lmk123 NoScript 扩展导致的
