### ISSUE TITLE
邮件当中全文翻译有时翻译不完整

### ISSUE THREAD

**Issue by sysuyep** [lmk123/crx-selection-translate#1106]
## 基本信息

划词翻译版本：v8.4.0
浏览器版本：chrome  91.0.4472.114（正式版本） (x86_64)
操作系统：macOS Big Sur 11.4

## 重现问题的步骤

订阅的一些英文Newsletter，在gmail网页版打开，正文某段内容如果后面跟有超链接，那么“全文翻译”只能翻译超链接部分的文字，超链接之前的文字无法显示翻译结果。情况如下图片所示：

<img width="533" alt="WX20210721-184517@2x" src="https://user-images.githubusercontent.com/25950101/126477619-5de6c2c7-beea-45ca-b3f5-2b4bc0a6d4a2.png">

**Comment by lmk123** [comment]
确实有这个问题，后续进展会同步到 #1022
