### ISSUE TITLE
使用代理时腾讯翻译无法翻译

### ISSUE THREAD

**Issue by brighterjiang** [lmk123/crx-selection-translate#1107]
## 基本信息

划词翻译版本：８．４
浏览器版本：chrome 92
操作系统：ubuntu20.04

## 重现问题的步骤

1.使用qv2ray代理软件时
2. 腾讯翻译显示网络错误
3.

**Comment by brighterjiang** [comment]
keyile

**Comment by lmk123** [comment]
如果以后还遇到这个问题，可以把腾讯翻译的服务地址加入直连名单 https://hcfy.limingkai.cn/docs/faq/#why-services-always-loading
