### ISSUE TITLE
优化源文本处理实现, 可以去除自定义字符

### ISSUE THREAD

**Issue by ruantu** [lmk123/crx-selection-translate#1110]
## 功能简介
可以自定义源文本处理去除的字符或字符串

## 为什么你觉得需要（改进）这个功能？
有很多编程语言的注释并不是以//开头的

**Comment by lmk123** [comment]
挺好的想法，我会在未来的版本中给源文本处理新增这一功能

**Comment by lmk123** [comment]
v8.5.7 已添加自定义正则来添加替换逻辑的功能。
