### ISSUE TITLE
推特（twitter）个人主页关注的用户推文不能够完全翻译

### ISSUE THREAD

**Issue by ECHOMINO** [lmk123/crx-selection-translate#1111]
划词翻译版本：v8.4.2
浏览器版本：Google Chrome  92.0.4515.107（64 位）
操作系统：windows10

## 重现问题的步骤

1.打开推特（twitter）个人主页
2.开启划词翻译（v8.4.2）网页翻译功能

### 预期行为

推特相关用户的推文能够被翻译显示（双语）；

### 实际行为
并没有直接提供推文的翻译（只是翻译的推特用户的名字和某些功能按钮的名字）；但是类似的翻译软件彩云小译可以比较好的翻译推文内容。
推特原文：
![image](https://user-images.githubusercontent.com/88179061/127606487-932bb30d-50f2-4eac-9a78-f33c27968b70.png)

划词翻译的效果：
![image](https://user-images.githubusercontent.com/88179061/127606444-622afe83-9cbc-42cd-a119-b1ac286a6e27.png)

彩云小译的效果：
![image](https://user-images.githubusercontent.com/88179061/127606338-af497d99-0d95-4ac1-905b-ce8a2abf03c9.png)
![image](https://user-images.githubusercontent.com/88179061/127606361-9bebe98a-8870-4341-b77b-3302dafb213e.png)

**Comment by ECHOMINO** [comment]
其他的新闻网站没有出现类似的问题，但是推特这里翻译的效果不好

**Comment by lmk123** [comment]
感谢反馈。目前划词翻译的网页全文翻译功能确实不够完善，会导致在 twitter、youtube 等网站里出现部分文本没有翻译的情况。我已经着手修复这些问题，预计会在最近的版本中发布。后续进展可以关注 #1022
