### ISSUE TITLE
css 嵌入效率优化

### ISSUE THREAD

**Issue by fjqingyou** [lmk123/crx-selection-translate#1113]
## 功能简介
页面加载优化

## 为什么你觉得需要（改进）这个功能？
当前每一个页面都将植入 css ，然鹅，明明是本机加载，嵌入的耗时未免太高了
blueprint.css                          ->  707ms
blueprint-select.css              ->  468ms
cropper.css                            ->  468ms

``` 
# blueprint.css
Queued at 985.41 ms
--
Started at 985.41 ms
Connection Start |   | DURATION
Stalled | ​ | 706.64 ms
Request/Response |   | DURATION
Content Download | ​ | 0
Explanation |   | 706.64 ms

```

**Comment by lmk123** [comment]
我在当前页面刷新多次查看了一下 css 加载时间，但是每次都没有你这么长的 stalled。你是不是在某些特定页面才有这么长的时间？另外，stalled 时间过长有对实际使用产生影响吗？（例如是否会造成页面加载完成后很久才能划词？）

截图如下：

blueprint.css  82.53ms

![image](https://user-images.githubusercontent.com/5035625/127865757-c7c7af24-871c-45fc-8488-952715fd432d.png)

blueprint-selectcss  75.33ms

![image](https://user-images.githubusercontent.com/5035625/127865856-d2892e12-9add-4b30-bfa4-cc73821ed96a.png)

cropper.css 75.18

![image](https://user-images.githubusercontent.com/5035625/127865961-b1ebaf45-6bdf-47a2-8033-f6eaba92f243.png)

**Comment by fjqingyou** [comment]
不确定是否跟系统有关。我得到这个高延迟的是在mac系统下的。
是否有影响之前没注意到，那是公司电脑才有的系统，现在无法测试！

**Comment by fjqingyou** [comment]
mac 系统的环境下，
我这边测试腾讯首页，一样是很高的延迟，各个网页都普遍很高。
不过偶尔确实会降到计时毫秒的程度，不过规律不明，因为在相同页面在此刷新后又飙升到好几百毫秒了。
至于是否会影响，这个插件貌似是网页加载完毕后才激活的。不确定这个延迟是否在原有网页加载延迟基础上叠加。还是并行加载。如果是并行应该的话就没影响。

![20210803103322](https://user-images.githubusercontent.com/31087168/127951464-358dcf7a-6f3c-44ca-a3b9-fd62f9b377c0.jpg)
![20210803103631](https://user-images.githubusercontent.com/31087168/127951471-30ad9914-de50-49cb-844b-97043d4292c8.jpg)
![20210803103643](https://user-images.githubusercontent.com/31087168/127951473-76b3ed77-c090-4b0e-bdcf-a131fc10df05.jpg)
![20210803103701](https://user-images.githubusercontent.com/31087168/127951475-e95f14a8-19f2-490e-971e-99b30df26d23.jpg)

**Comment by lmk123** [comment]
感谢反馈。

我目前不会去改善这个情况，因为：

- 划词翻译确实是在网页加载完成后才激活的，但是由于这三个 css 文件是并行加载（都 `Started at 3.61s`），所以在 500ms 内就全部加载完了，几乎不会造成影响
- 由于在我和你的浏览器上表现不一致，所以看起来跟操作系统、甚至硬件状况有关，我无法确定改进手段是否有效。

如果可以确定由于这个原因影响到了划词翻译的激活速度，可以继续留言。
