### ISSUE TITLE
针对有偿翻译服务的 全文翻译 开关

### ISSUE THREAD

**Issue by qinhanlei** [lmk123/crx-selection-translate#1114]
## 功能简介
可对具体的某个翻译服务进行 全文翻译（也可以考虑句子/段落 ） 开关

## 为什么你觉得需要（改进）这个功能？
不希望付费服务进行 段落/全文 翻译，因为比较消耗积分或 API 次数，尤其是网页全文翻译。
但希望保留其 选词 翻译，因为，比如“有道翻译”在单词翻译上，表现力更好一些，词性和一词多意展示更全面。

**Comment by lmk123** [comment]
> 对具体的某个翻译服务进行 全文翻译 开关

这个似乎没有必要，因为只要选择全文翻译的时候不去选择有偿的服务，就不会消耗积分。而且，全文翻译默认使用的是免费的服务。

> 不希望付费服务进行 段落/全文 翻译，但希望保留其 选词 翻译

这个需求其实可以“变通实现”。翻译面板内的各个翻译服务是可以折叠起来的，你平时可以把有道翻译折叠起来，只在划选单词后才展开。这个方法你觉得你能接受吗？

**Comment by qinhanlei** [comment]
@lmk123 
1.  总想对比看看不同的全文翻译，尤其新手会误点，建议默认关闭，用户手动开启
2. 折叠起来如果不消耗积分/API次数，倒是算个折衷；还是希望能自动化一下😄

**Comment by lmk123** [comment]
> 总想对比看看不同的全文翻译，尤其新手会误点

事实上也确实有用户反馈这个问题，我会提高一下这项改进的优先级。我已经将这一需求记录在了 #1109

> 还是希望能自动化一下

我觉得可以。我打算给每个翻译服务加一些通用的选项，比如你提到的有道翻译的使用场景，可以加一个“字符数少于 10 个才显示有道翻译结果”之类的。我开了一个新的 issue 用来追踪这项改进 #1117

你所希望的几项改进应该都已经有结论了，所以这个 issue 我就关闭了，后续有新的提议欢迎再开 issue。
