### ISSUE TITLE
chrome全文翻译没有反应

### ISSUE THREAD

**Issue by sysuyep** [lmk123/crx-selection-translate#1115]
## 基本信息

划词翻译版本：v8.4.2
浏览器版本：92.0.4515.107
操作系统：Mac Big Sur 11.4

## 重现问题的步骤

1. Gmail邮箱里的邮件或者medium之类的英文网页，右键选择划词翻译里面的全文翻译，右下角会弹出选项窗口，但是网页并没有进行翻译。
2. 不管是deepL还是谷歌翻译都无法正常响应。
3. 选项窗口比如默认的是deepL的翻译源，如果选择谷歌等其他翻译，无法正常切换，会自动弹回默认选项。
4. 划词翻译选中文本翻译是正常的

**Comment by sysuyep** [comment]
已经重新安装过一遍

**Comment by lmk123** [comment]
已确认是 v8.4.2 版本的 bug，我会尽快更新版本进行修复，在这之前你可以去官网先临时安装 v8.4.1 版本的离线安装包
