### ISSUE TITLE
淡蓝色的放大镜翻译按钮故障

### ISSUE THREAD

**Issue by yuanhepeng** [lmk123/crx-selection-translate#1116]
## 基本信息

划词翻译版本：8.4.1
浏览器版本：92.0.902.62 
操作系统：win10

## 重现问题的步骤

![image](https://user-images.githubusercontent.com/39111057/128145162-7ad9bd1d-feef-404f-bca5-7aa244161291.png)

### 预期行为
应当出现组装的英文
### 实际行为
没有出现

----------------
希望可以回车即可翻译，输入单词后还需要鼠标去点击下翻译按钮才可以翻译很繁琐

**Comment by Kumiko-git** [comment]
我也出现了 一样的情况
8.4.2 
92.0.4515.107

**Comment by justinqee** [comment]
一样的问题，我这里表现为独立翻译窗口的翻译按钮点击失效，网页中的翻译按钮点击有效。
仍然可以通过快捷键ctrl+enter进行翻译。
划词翻译版本：8.4.1
浏览器版本：Microsoft Edge 92.0.902.62
Windows 11  22000.100

**Comment by yuanhepeng** [comment]
嗯嗯，谢谢，这次记住快捷键了。原来是ctrl+enter



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 晚上8:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lmk123/crx-selection-translate] 淡蓝色的放大镜翻译按钮故障 (#1116)




 
一样的问题，我这里表现为独立翻译窗口的翻译按钮点击失效，网页中的翻译按钮点击有效。
 仍然可以通过快捷键ctrl+enter进行翻译。
 划词翻译版本：8.4.1
 浏览器版本：Microsoft Edge 92.0.902.62
 Windows 11  22000.100
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmk123** [comment]
感谢反馈，会在下个版本中修复
