### ISSUE TITLE
对于不开启划词翻译的网站，不检测剪贴板

### ISSUE THREAD

**Issue by wzyjobs** [lmk123/crx-selection-translate#1118]
## 基本信息

划词翻译版本： v8.4.3
浏览器版本：版本 92.0.4515.131（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

1.leetcode中文站
2.划词插件已经屏蔽了leetcode，复制代码，会直接弹出翻译

### 预期行为
对于不开启划词翻译的网站，不检测剪贴板
### 实际行为
对于不开启划词翻译的网站，检测剪贴板并弹出

**Comment by lmk123** [comment]
划词翻译不会在你复制代码之后自动弹出翻译。你是不是设置了 `Ctrl` 键作为辅助键且勾选了“松开辅助键后翻译选中的文本”？

**Comment by wzyjobs** [comment]
确实是辅助键的问题，谢谢~ :yum:

**Comment by lmk123** [comment]
不用谢，有问题欢迎反馈
