### ISSUE TITLE
新版的网页全文翻译排版在阅读舒适度上略差与旧版

### ISSUE THREAD

**Issue by Mjhhh** [lmk123/crx-selection-translate#1121]
## 当前环境配置
系统：win11
划词翻译：v8.5.0
浏览器：Microsoft Edge 版本 92.0.902.67 & Google Chrome 版本 92.0.4515.131
## 功能简介
在reddit上使用网页全文翻译，在排版的阅读舒适度上略差与旧版
以下是原文与开启全文翻译后的对比图
原文：
![网页捕获_8-8-2021_143959_www reddit com](https://user-images.githubusercontent.com/32394379/128623428-6a7506fb-a8be-45f5-b996-91b1c8a46143.jpeg)

![网页捕获_8-8-2021_145113_www reddit com](https://user-images.githubusercontent.com/32394379/128623614-bbb8e10d-90e1-4c52-9610-135e56c86c30.jpeg)
网页全文翻译：
![网页捕获_8-8-2021_144139_www reddit com](https://user-images.githubusercontent.com/32394379/128623441-290ada22-98d4-40cc-a334-85729151e09a.jpeg)

![网页捕获_8-8-2021_145143_www reddit com](https://user-images.githubusercontent.com/32394379/128623620-8849e020-d32a-4b8d-8edc-dd99f98f1cd8.jpeg)

## 为什么你觉得需要（改进）这个功能？
旧版在排版的舒适度上高于新版

**Comment by lmk123** [comment]
确实如此。我会在后面的版本中慢慢改进，让新版本的网页全文翻译也能有旧版本的显示方式。

**Comment by lmk123** [comment]
已经在下个版本对排版进行了优化，将部分情况下（例如按钮内）的原文和翻译结果在同一行显示了。后面会继续优化，不过现阶段就先优化到这吧 :joy:

截图如下（网址为 https://www.reddit.com/r/osx/comments/f97x87/macos_version_of_deskpins/）：

![image](https://user-images.githubusercontent.com/5035625/129777395-229411cb-7244-43c8-a331-5c7424518138.png)

![image](https://user-images.githubusercontent.com/5035625/129777234-1f233f9d-b975-4714-90f9-ac04d515f809.png)
