### ISSUE TITLE
8月11日凌晨4点左右更新后程序无法使用

### ISSUE THREAD

**Issue by LingFeng1226** [lmk123/crx-selection-translate#1125]
## 基本信息

划词翻译版本：8.5.1
浏览器版本：google游览器 92.0.4515.131（正式版本） （64 位）
操作系统：windows10 21H1

## 重现问题的步骤

1.扩展程序中，直接点选项，打开空白页面，无法设置。
2.右键菜单无选项
3.使用离线版8.5.1同样问题。
4.改用离线版本8.5.0正常
5.在进行离线8.5.1前已经重置google游览器。。。

**Comment by LingFeng1226** [comment]
在mac下同样问题。

**Comment by teng-eb** [comment]
补充信息 (打开 选项 后, 在控制台下报错):
![image](https://user-images.githubusercontent.com/54974306/128954422-5b684b26-8545-4544-ab45-c1a9765334f5.png)

**Comment by icepole-jon** [comment]
出现同样问题

**Comment by xiaoyuhao0716** [comment]
同样问题

**Comment by lmk123** [comment]
我已经提交了 v8.5.2 的版本修复了这个问题，在通过审核之前，可以通过离线安装包的方式立刻升级到 v8.5.2 https://hcfy.limingkai.cn/docs/install/#offline

**Comment by haroldxing** [comment]
> 我已经提交了 v8.5.2 的版本修复了这个问题，在通过审核之前，可以通过离线安装包的方式立刻升级到 v8.5.2 https://hcfy.limingkai.cn/docs/install/#offline

新版本通过商店审核一般是多久？

**Comment by lmk123** [comment]
@haroldxing 不好说，快的话 3 个小时，慢的话 2 个工作日

**Comment by haroldxing** [comment]
> @haroldxing 不好说，快的话 3 个小时，慢的话 2 个工作日

好吧，感谢。现在稍微有点不适应，我等一下吧

**Comment by lmk123** [comment]
@haroldxing 下载离线安装包跟等待 Chrome 自动更新的其实是一样的，因为离线安装包就是从 Chrome 扩展商店里下载下来的，所以也会自动更新

**Comment by haroldxing** [comment]
> @haroldxing 下载离线安装包跟等待 Chrome 自动更新的其实是一样的，因为离线安装包就是从 Chrome 扩展商店里下载下来的，所以也会自动更新

哦？我以为离线包会固定到那个版本，我去试试看😄

**Comment by LingFeng1226** [comment]
> > @haroldxing 下载离线安装包跟等待 Chrome 自动更新的其实是一样的，因为离线安装包就是从 Chrome 扩展商店里下载下来的，所以也会自动更新
> 
> 哦？我以为离线包会固定到那个版本，我去试试看😄

离线安装一样可以自动更新。不用担心。
