### ISSUE TITLE
browser is not defined

### ISSUE THREAD

**Issue by Spencer17x** [lmk123/crx-selection-translate#1126]
## 基本信息

划词翻译版本：8.5.1
浏览器版本： 92.0.4515.131（正式版本） (arm64)
操作系统：macOS Big Sur，11.5.1

## 重现问题的步骤

1. 控制台报错 browser is not defined

### 预期行为

无任何插件引起的报错

**Comment by lmk123** [comment]
请查看  https://github.com/lmk123/crx-selection-translate/issues/1125#issuecomment-896441252
