### ISSUE TITLE
新的界面好难看

### ISSUE THREAD

**Issue by dedoyle** [lmk123/crx-selection-translate#113]
v6.0.5好难看，能恢复原来的界面吗
![qq 20160202134825](https://cloud.githubusercontent.com/assets/12028922/12740992/8856e310-c9b3-11e5-86b3-e22f93d29a12.png)

**Comment by lmk123** [comment]
我知道，所以我正在向有经验的人求助，你可以在这里发表你对新界面的意见：#93

**Comment by dedoyle** [comment]
原来的样子挺好的

**Comment by lmk123** [comment]
一千个人心里有一千个哈姆雷特 :joy:

**Comment by dedoyle** [comment]
咱可不能受新年吉祥物影响
