### ISSUE TITLE
网页全文翻译右下角的弹出窗口太大且不可调

### ISSUE THREAD

**Issue by wuhongyewhy** [lmk123/crx-selection-translate#1131]

**Comment by lmk123** [comment]
感谢支持。我准备把右下角弹窗改为自动隐藏在侧边的形式，只露出一个小按钮，鼠标移动到按钮上就显示完整的弹窗，这样就能解决遮挡问题了，见 #1070

我觉得这样比“最小化”+“可以拖动”要简单一点。如果你有更好的建议，欢迎继续留言。
