### ISSUE TITLE
购买翻译积分，有道翻译用不了，显示401错误码

### ISSUE THREAD

**Issue by pdk0826** [lmk123/crx-selection-translate#1132]
## 基本信息

划词翻译版本：v8.5.2
浏览器版本：92.0.4515.131
操作系统：Windows 10 21H1

## 重现问题的步骤

1. 购买翻译积分
2. 使用有道翻译进行划译

### 预期行为
显示翻译结果

### 实际行为
显示错误信息：有道翻译报错了，错误码：“401”

![image](https://user-images.githubusercontent.com/49113861/129050854-1a1842c9-b856-48b1-a5e5-185465b149f4.png)

**Comment by lmk123** [comment]
我的有道翻译账号欠费了，但是我给它充值的时候总是报错，我联系一下看看

**Comment by lmk123** [comment]
补了个公告说明  https://hcfy.limingkai.cn/blog/2021/08/12/yd

**Comment by lmk123** [comment]
有道翻译平台的充值问题解决了，我已经给划词翻译的有道翻译账号充值了，现在划词翻译内的有道翻译已经恢复正常使用了，感谢反馈。
