### ISSUE TITLE
查询结果时发生了网络错误

### ISSUE THREAD

**Issue by sxzq46** [lmk123/crx-selection-translate#1135]
## 基本信息

划词翻译版本：8.5.2
浏览器版本：版本 92.0.4515.131（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

1.查询结果时发生了网络错误，错误消息：服务器没有响应，请检查您的网络是否畅通。。请确认您能否正常打开 腾讯翻译君。
我配置了有道和腾讯，都提示以上错误信息。
![image](https://user-images.githubusercontent.com/2561843/129179674-498836d9-4377-49b4-b05c-844a0585c6c8.png)

**Comment by lmk123** [comment]
请先查看这篇文档看看是否是代理的原因 https://hcfy.limingkai.cn/docs/faq/#proxy

**Comment by sxzq46** [comment]
看过了，我虽然有开过SS，但是关掉后还是不行，开着也不行

**Comment by lmk123** [comment]
那就不好办了。我自己填写了有道和腾讯的密钥试过了，是可以正常使用的。我这边没法重现你的问题，所以只能提供可能可以解决这个问题的一些方法：

- 重装试试。阿里翻译在报 400 错误的时候，重装就没问题了，虽然我也不知道是怎么回事。
- 你的系统的时区是北京时间吗？如果不是的话调整成北京时区试试。

如果以上方法还是不行，那么我也无能为力了。填写密钥的时候，划词翻译是直接从你的电脑访问的翻译服务（也就是上面那篇文档里写的服务地址），中间没有经过划词翻译服务器的中转，所以如果出现网络问题，大概率是你的网路把它们屏蔽了，要么就是它们把你屏蔽了

**Comment by lmk123** [comment]
哦对了还有一种可能，你是不是安装了自定义 ssl 证书之类的东西？这个好像会导致其它网站的 https 证书失效，被浏览器认定为不安全的网站。

**Comment by lmk123** [comment]
今天一个用户的反馈让我又发现了一种可能性：你是不是在划词翻译的管理页面（`chrome://extensions/?id=ikhdkkncnoglghljlkmcimlnlhkeamad`）调整了权限，把【有权访问的网站】从【所有网站】改成了别的？

如果是的话，你需要改回【所有网站】

**Comment by sxzq46** [comment]
非常感谢，我的问题解决了，确实是权限问题，估计是被我无意中点到的。
