### ISSUE TITLE
在chrome上将网页保存为`单页面`(mhtml)时,右下角出现面板

### ISSUE THREAD

**Issue by AirBashX** [lmk123/crx-selection-translate#1141]
## 基本信息

划词翻译版本：v8-5-3-1
浏览器版本：chrome 92.0.4515.159
操作系统：windows10

## 重现问题的步骤

1. 打开一个网页,按ctrl+s保存为单网页(mhtmll);
2. 打开保存后的文件,发现左下角多了一个面板图案
3. 关闭该工具再次保存时,面板消失

**Comment by lmk123** [comment]
确实有这个问题，将优先处理。后续进展请跟进 #1030

**Comment by lmk123** [comment]
昨天我把 Chrome 升级到 93 了，今天当我准备修复这个问题的时候，发现我无法重现了。我看了一下保存下来的代码，现在里面已经没有划词翻译的代码了，也就是说，你只要将 Chrome 升级到 93 就不会有这个问题了。

由于这个问题升级 Chrome 即可解决，所以我就不另外做代码上的修复了。
