### ISSUE TITLE
百度截图翻译BUG

### ISSUE THREAD

**Issue by hsichien** [lmk123/crx-selection-translate#1143]
## 基本信息

划词翻译版本：v8.5.3.1
浏览器版本：Microsoft Edge 版本 92.0.902.73 (官方内部版本) (64 位)
操作系统：windows10 1909

## 重现问题的步骤

1.网页点击右键，选择划词翻译->截图翻译然后选择截图，会出现该提示“从图片中提取文字时发生了一个错误：Cannot read property 'reduce' of undefined”
2.先用截图工具截图后在通过拓展读取剪切板内的图片也会出现同样的提示

### 预期行为
出现翻译结果
### 实际行为
提示“从图片中提取文字时发生了一个错误：Cannot read property 'reduce' of undefined”

**Comment by lmk123** [comment]
之前也有几个用户反馈这个问题，但最后发现都是因为他们填错了密钥，你可以重新填一下密钥试试

**Comment by hsichien** [comment]
> 之前也有几个用户反馈这个问题，但最后发现都是因为他们填错了密钥，你可以重新填一下密钥试试

找到原因了，是没有在百度云智能里领取免费额度，领取后功能正常，麻烦了

**Comment by lmk123** [comment]
还是感谢你的反馈，这样我就能把这个错误写进文档并告诉其他人问题出在哪了。
