### ISSUE TITLE
页面划词翻译   英文 -> 中文 自动弹出独立页面   中文 -> 英文 还是页面弹窗

### ISSUE THREAD

**Issue by vast0906** [lmk123/crx-selection-translate#1144]
## 基本信息

划词翻译版本：8.5.3.1
浏览器版本：chrome 92.0.4515.131
操作系统：mac 11.4 

## 重现问题的步骤
在 chrome 浏览器全屏模式下 
![image](https://user-images.githubusercontent.com/18095287/130174369-b5ae6cd1-a546-49b2-833f-1a0e76c5e5f4.png)

![image](https://user-images.githubusercontent.com/18095287/130174213-f8a98657-1e2b-41bd-928d-24d7975a7ae6.png)

### 预期行为
英文 <-> 中文  都是页面弹窗  而不是独立模式
### 实际行为
   英文 -> 中文 翻译会弹出独立页面   中文 -> 英文 还是页面弹窗

chrome 下使用默认配置

**Comment by lmk123** [comment]
我试了下，在普通网页的全屏模式下，划词后也是直接在页面中显示页面弹窗的。你似乎把独立翻译窗口给全屏了，但这不会影响到页面弹窗的显示。

划词翻译在网页划词后会且只会出现页面弹窗，跟选择什么语种没有关系。只有以下两种情况会在独立窗口中显示结果：

- 当你在[扩展程序无权控制的页面](https://hcfy.limingkai.cn/docs/faq/#why-can-not-use-in-store)且在右键菜单选择了“翻译这段文本”的时候
- 当你配置了“在独立窗口中翻译网页中选中的文本”快捷键且按下了快捷键的时候

能确认一下你出现的“英文 -> 中文 翻译会弹出独立页面 中文 -> 英文 还是页面弹窗”情况是以上情况之一吗？如果不是，那你得提供一下详细的复现问题的步骤给我，我才能帮你解决这个问题。

**Comment by vast0906** [comment]
> 我试了下，在普通网页的全屏模式下，划词后也是直接在页面中显示页面弹窗的。你似乎把独立翻译窗口给全屏了，但这不会影响到页面弹窗的显示。
> 
> 划词翻译在网页划词后会且只会出现页面弹窗，跟选择什么语种没有关系。只有以下两种情况会在独立窗口中显示结果：
> 
> * 当你在[扩展程序无权控制的页面](https://hcfy.limingkai.cn/docs/faq/#why-can-not-use-in-store)且在右键菜单选择了“翻译这段文本”的时候
> * 当你配置了“在独立窗口中翻译网页中选中的文本”快捷键且按下了快捷键的时候
> 
> 能确认一下你出现的“英文 -> 中文 翻译会弹出独立页面 中文 -> 英文 还是页面弹窗”情况是以上情况之一吗？如果不是，那你得提供一下详细的复现问题的步骤给我，我才能帮你解决这个问题。

我是在 Google 翻译页面 使用右键菜单的"选择翻译这段文本"    没有配置快捷键

**Comment by lmk123** [comment]
我在 https://translate.google.cn/ 试了一下，是正能常弹出页面翻译窗口的，如图：

![t](https://user-images.githubusercontent.com/5035625/130287303-0c35ec5b-18d3-475c-a563-4a1dbdd5fdba.gif)

你是不是修改过划词翻译的权限？见 https://hcfy.limingkai.cn/docs/guides/options#per

**Comment by vast0906** [comment]
![image](https://user-images.githubusercontent.com/18095287/130343907-f6c2c677-ec5f-4b7b-ab62-daf25cf29848.png)
权限没改过

**Comment by lmk123** [comment]
还有一种情况，你的步骤是否是：

1. 先打开了谷歌翻译网页
2. 安装了划词翻译
3. 回到第一步中打开的谷歌翻译网页，划词后用右键菜单选择“翻译选中的文本”

如果是以上步骤，那么确实会用独立窗口弹出翻译结果，这是因为在安装划词翻译前的标签页里，划词翻译是没有权限控制的，所以会改为用独立窗口显示结果。你需要在安装划词翻译后刷新一下安装前的页面，这样才会正常通过页面弹窗打开。

**Comment by lmk123** [comment]
无反馈且无法重现，这个 issue 我先关闭了，不过你还是可以继续留言。
