### ISSUE TITLE
Ctrl+Shift+1 快捷键与写Markdown冲突，想修改划词翻译该快捷键

### ISSUE THREAD

**Issue by terence1023** [lmk123/crx-selection-translate#1149]
## 基本信息

划词翻译版本：8.5.3.1
浏览器版本：Google Chrome  92.0.4515.159
操作系统：Windows 10 20H2

## 重现问题的步骤

1.根据提示找到划词翻译设置面板
2.在快捷键一项中：请前往键盘快捷键页面修改这些快捷键。修改后没有生效？但是这里的链接跳转到扩展程序，这里没有发现又可以更改快捷键的地方

### 预期行为
修改Ctrl+Shift+1 快捷键操作
### 实际行为
暂时还没找到修改的地方

**Comment by lmk123** [comment]
我猜你关闭 issue 是因为你知道怎么改了，不过我还是说一下吧 :joy:

在 `chrome://extensions/shortcuts` 找到划词翻译，修改“打开独立窗口”这个快捷键。如果修改不了，查看 https://hcfy.limingkai.cn/docs/faq/#edit-shortcut-key
