### ISSUE TITLE
朗读功能失效

### ISSUE THREAD

**Issue by chenjuntong** [lmk123/crx-selection-translate#115]
chrome 48.0.2564.97 m 朗读（自动或手动）失效

**Comment by chenjuntong** [comment]
找到问题所在了，需要手动把默认设置的｛“自动选择”<>“自动选择”｝ 改成｛“英语”<>“中文”｝才能正常使用

**Comment by chenjuntong** [comment]
在每一个新页面都需要这样重新设置，使用不便，烦请修复

**Comment by lmk123** [comment]
能提供你一下你朗读的是什么文本、使用了哪个翻译引擎吗？

**Comment by chenjuntong** [comment]
英语文本，有道引擎，默认设置下不能自动朗读，需要手动把设置下的｛“自动选择”<>“自动选择”｝ 改成｛“英语”<>“中文”｝才能自动朗读；另外网页缩放的情况下，翻译框里的文字分辨率不能自动适应，会模糊（偶尔会自动适应）

**Comment by lmk123** [comment]
你所有的英文都没法朗读？

**Comment by chenjuntong** [comment]
对，即使我手动点了“朗读”的选项也没有反应（“复制”选项正常），手动修改设置后“朗读”选项可正常使用

**Comment by chenjuntong** [comment]
已经是6.0.5（或者说升级后才有这个bug），win10，难道只有我有这个问题 T_T

**Comment by lmk123** [comment]
划词翻译会尝试用国外的谷歌翻译判断语种，你的电脑是不是没 FQ？

**Comment by chenjuntong** [comment]
试了下，翻墙后自动朗读功能正常，但翻译成功率以及速度明显下降了……

**Comment by lmk123** [comment]
国内和国外的谷歌翻译对翻墙工具而言是有冲突的，所以你没翻墙的时候就用国内谷歌，翻墙了就用国外谷歌。

翻了墙之后的翻译速度取决于你的翻墙工具。我不太懂你说的“翻译成功率”，只是这些翻译引擎都是使用第三方提供的翻译服务，所以我也爱莫能助啊 :joy:

**Comment by chenjuntong** [comment]
就是说翻墙后由于速度大大下降所以有时会出现“（连接不成功）稍后再试”…所以说墙内不能解决（默认设置下）自动朗读的问题了吗？或者说加入一个全局设置（就不用单个页面手动设置了），因为我（应该也有很多人）只使用 英文->中文

**Comment by chenjuntong** [comment]
在网页放大（按住ctrl+滚轮）的情况下，翻译框里的文字分辨率不能自动适应，会模糊，这个bug呢？以前的版本没有这个问题

**Comment by lmk123** [comment]
我觉得翻墙之后不会降低翻译速度，你是不是使用了全局代理？你应该使用 pac 设置一下哪些网址走代理，哪些网址不走代理，这样百度、有道这些翻译接口的速度就不会受到是否翻墙的影响。

新的问题单独开一个 issue，一个 issue 里只应该有一个主题，不然我不好管理。
