### ISSUE TITLE
划词翻译会导致有 iframe 的网页运行异常

### ISSUE THREAD

**Issue by aikin-vip** [lmk123/crx-selection-translate#1150]
## 基本信息

划词翻译版本：8.5.2
浏览器版本：edge:
操作系统：mac 

## 重现问题的步骤
公司的一个登录页 点击登录按钮以后，会在一个post请求中设置图中所属的请求头？这是咋发生的？导致公司登录态失效。。原本的登录Token被覆盖了。。关掉划词翻译后恢复正常

![image](https://user-images.githubusercontent.com/64122272/130738826-faeae747-fe82-4509-a030-a511b7a9fcd8.png)

**Comment by watertreestar** [comment]
在confluence的编辑页面上也有相同的问题，导致很多error打印。异常的地方在下图中的JSON.parse中
![image](https://user-images.githubusercontent.com/29186031/131951425-88b06432-a33a-4443-9262-3d0cec04489a.png)

**Comment by lmk123** [comment]
是的，正是因为怕被网页自己的代码用 JSON.parse 通过，才会故意将划词翻译发送的 json 消息前加入了 `greetings from hcfy` :joy:

**Comment by watertreestar** [comment]
> 是的，正是因为怕被网页自己的代码用 JSON.parse 通过，才会故意将划词翻译发送的 json 消息前加入了 `greetings from hcfy` 😂

这种有没有什么好的解决方案呢，虽然这个错误也不会影响使用，但是一连串的错误让人心烦意乱呀。~~~~~

**Comment by lmk123** [comment]
暂时没有，只能等我修复了

**Comment by Lichun0529** [comment]
遇到了类似的问题，我的情况是拖动iframe内滚动条或使用鼠标滚轮时会频繁发送postMessage

**Comment by lmk123** [comment]
@Lichun0529 是的，因为滚动之后需要重新计算页面上被选中文本的位置。你只需要给 JSON.parse 加个 try / catch 过滤掉划词翻译发送的消息就可以了

**Comment by lmk123** [comment]
将在下个版本 v8.6.3 中修复
