### ISSUE TITLE
Logo兼容或可自定义

### ISSUE THREAD

**Issue by RollBack2010** [lmk123/crx-selection-translate#1151]
使用Edge或暗色主题时Logo就看不到了，希望可以提供暗色和亮色的logo
![image](https://user-images.githubusercontent.com/15976246/131775382-de1f5072-9720-4963-9e99-f2af1e44d083.png)

**Comment by lmk123** [comment]
确实如此，很早就有人反馈了我一直没改 :joy: 我会提高这个问题的优先级，后续进展可关注 #1002
