### ISSUE TITLE
能否在android上支持划词或全文翻译

### ISSUE THREAD

**Issue by wisecrick** [lmk123/crx-selection-translate#1152]
## 功能简介
android上有些浏览器是支持扩展的，比如kiwi browser（ 这个好像安装划词翻译会崩溃），yandex browser等，但是安装上似乎很难使用，希望增加这方面的支持。

## 为什么你觉得需要（改进）这个功能？
这样就可以在android手机和平板上用了

**Comment by lmk123** [comment]
目前我手头没有安卓手机，所以没法测试，以后有机会了我会尝试适配的，后续进展可以关注 #1102
