### ISSUE TITLE
希望deepl也可以自定义api key

### ISSUE THREAD

**Issue by wisecrick** [lmk123/crx-selection-translate#1153]
## 功能简介
刚刚得到一个api key，我想把它用上去
希望能同时支持free和pro的（两个api的域名有一点区别）

## 为什么你觉得需要（改进）这个功能？
或许翻译速度会更快更稳定？

**Comment by lmk123** [comment]
hi，我最近在着手添加对 DeepL API key 的支持，不过我有一点疑问，就是你的 api key 是怎么申请到的？我看了网上的说明，似乎需要用 DeepL 支持的地区的信用卡才能开通。

**Comment by wisecrick** [comment]
美国的虚拟信用卡

**Comment by lmk123** [comment]
了解一下虚拟信用卡，感觉选择太多了，你方便透露一下你是在哪里开的虚拟信用卡吗 :joy:

**Comment by wisecrick** [comment]
淘宝就可以，然后找一个真实地址填进去。
不如我直接送你一个free api key好了，好像闲鱼上也有卖这个api的

**Comment by lmk123** [comment]
free api key 我已经在淘宝买了，不过我是想自己注册一个正式的 api key 用来提供用翻译积分使用 deepl 的能力。

我上淘宝去咨询一下

**Comment by lmk123** [comment]
DeepL API 确实更快更稳定，实测只需要 2 秒就能出结果 :joy:

v8.7.0 已经支持通过密钥使用 DeepL 了，应该会在下周发布
