### ISSUE TITLE
希望能在扩展自身的弹出对话框加入全文翻译按钮

### ISSUE THREAD

**Issue by wisecrick** [lmk123/crx-selection-translate#1154]
## 为什么你觉得需要（改进）这个功能？
似乎android上，除了设置页面，就只能弹出这个对话框了
![Screenshot_20210906_121724](https://user-images.githubusercontent.com/1472179/132160148-d8981165-29eb-4ca2-8702-3ad41f80356d.png)

**Comment by lmk123** [comment]
好的，我会在这里把功能按钮全都加上，包括网页全文、截图翻译等

**Comment by wisecrick** [comment]
不知道是不是因为嵌入了tesseract，使安装包比较大，在Kiwi Browser上一安装就崩溃，只在yandex browser上才能安装。或许可以搞个lite版的出来？

**Comment by lmk123** [comment]
目前我手头没有安卓手机，所以我也无法测试把 tesseract 删了是不是就可以正常安装了。安卓手机的兼容还是等我有安卓手机了再说吧 :joy: 后续进展可以关注 #1102

**Comment by lmk123** [comment]
v8.5.7 已将截图翻译和网页全文翻译的按钮加入到扩展弹出页中。
