### ISSUE TITLE
修改密码的时候服务器返回 418 

### ISSUE THREAD

**Issue by nerdneilsfield** [lmk123/crx-selection-translate#1155]
## 基本信息

划词翻译版本：v8.5.6
浏览器版本：Microsoft Edge Insider 版本 93.0.961.38
操作系统： Windows 11

## 重现问题的步骤

1. 在插件设置页面选择登录账号
2.  选择忘记密码选项
3. 输入邮件，发送验证码
4. 收到验证码，填入。填入新密码，确认填入新密码
5. 返回： 

![image](https://user-images.githubusercontent.com/8458783/132344703-295d4c31-33d8-4456-927c-a9c06859c451.png)

### 预期行为

修改密码成功

### 实际行为

![image](https://user-images.githubusercontent.com/8458783/132344739-5f50bf23-ab8e-4037-bc75-66fe10f6e0e0.png)

```
Failed to load resource: the server responded with a status of 418 (I'm a teapot)
```

**Comment by lmk123** [comment]
已确认此 bug，我会立刻修复。

**Comment by lmk123** [comment]
已修复，感谢反馈，如果仍然有问题可以继续留言。

**Comment by nerdneilsfield** [comment]
已确认修复，谢谢！
