### ISSUE TITLE
希望勾选“鼠标悬浮取词”后全局生效

### ISSUE THREAD

**Issue by Boundless666** [lmk123/crx-selection-translate#1156]
## 基本信息

划词翻译版本：
8.5.5
浏览器版本：
Version 93.0.961.38 (Official build) (64-bit)
操作系统：
win10 Education
version:2004
OS build:19041.1165

## 重现问题的步骤
预先设置好的鼠标悬浮取词 新进入一个页面或者刷新  原先勾选过的鼠标悬浮取词就需要重新勾选
1.
2.
3.

### 预期行为
不需要重新设置
### 实际行为
鼠标悬浮取词被重置了，此设置并没有保存到相应配置中去。
应该是保存操作那里没有带这个参数

**Comment by lmk123** [comment]
这实际上是有意为之的，因为悬浮取词操作比较影响正常阅读，所以我默认没有让它全局生效，只对当前标签页生效，而其它标签页需要另外开启。

我会考虑一下要不要改为全局生效。

@GH01 你怎么看？

**Comment by lmk123** [comment]
还是改成全局生效吧，快捷选项里就差这一个选项没有全局生效了。
