### ISSUE TITLE
无法关闭双击显示划词翻译 即便禁用了还是会出现

### ISSUE THREAD

**Issue by Vi-jay** [lmk123/crx-selection-translate#1159]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
我试了一下，勾选“在所有网站中禁用划词翻译”后，划词后就不会弹出按钮了。由于我无法重现你的问题，所以麻烦你补充更多信息，也就是填完上面得内容，否则我也没法帮到你。

当你填好之后，你可以继续在此 issue 下留言。
