### ISSUE TITLE
网页放大情况下翻译框文字模糊

### ISSUE THREAD

**Issue by chenjuntong** [lmk123/crx-selection-translate#116]
网页无缩放的翻译框文字效果：
![](http://ww3.sinaimg.cn/large/6ccda21fgw1f0ta453zpcj208v077dgk.jpg)

网页放大到125%的时候：
![](http://ww2.sinaimg.cn/large/6ccda21fgw1f0ta4sd8w0j20az09o752.jpg)
可以看到文字已经模糊失调了

**Comment by gggccc44** [comment]
我的怎么没有。和浏览器或者系统字体有关吧？

**Comment by chenjuntong** [comment]
有可能，我用Stylish自定义了字体，不过旧版本没这个问题

**Comment by gggccc44** [comment]
确实以前翻译框和译那个字不会随页面放大。我还因此给作者说字太小，因为咱4张了，喜欢大字。不过我用uc和360浏览器都没这问题。win7 64。不用谷歌原版是因为原版太蛋疼了

**Comment by lmk123** [comment]
重复 #105
