### ISSUE TITLE
qq浏览器快捷键

### ISSUE THREAD

**Issue by wenwen100** [lmk123/crx-selection-translate#1162]
谢谢大佬开发的插件!!!
谢谢大佬开发的插件!!!
谢谢大佬开发的插件!!!
我的问题是: chrome应用(账号)要梯子. 所以. 用的是qq浏览器方便.  但是qq浏览器没法设置扩展的快捷键.  现在是默认的可以用. 没法修改. 我想问问大佬们. 我该怎么做才能修改快捷键?

**Comment by lmk123** [comment]
没用过 QQ 浏览器，查了下好像 QQ 浏览器就是不支持设置扩展的键盘快捷键，这种情况下我也没办法，要么你可以用 edge，也是不用梯子的
