### ISSUE TITLE
让网页全文翻译支持 Shadow DOM

### ISSUE THREAD

**Issue by msghost** [lmk123/crx-selection-translate#1163]
## 基本信息

划词翻译版本：8.5.7
浏览器版本：Firefox 92.0
操作系统：Win10 21H1 19043.1165

## 重现问题的步骤

1.浏览器正常加载划词翻译工具，测试在其他页面使用全文翻译没有问题
2.打开https://developer.salesforce.com/docs/atlas.en-us.bot_cookbook.meta/bot_cookbook/bot_cookbook_greet_customer_lex.htm ， 使用全文翻译功能，工具浮窗可以出现，但是内容没有变化
![图片](https://user-images.githubusercontent.com/16555025/133880849-d2ee0658-8f95-4e5a-b557-4e478ce46b95.png)

3.打开该网站的其他子站点对比测试https://help.salesforce.com/s/articleView?id=sf.bots_service_setup_dialog_message.htm&type=5，全文翻译成功
![图片](https://user-images.githubusercontent.com/16555025/133880880-c04cf20e-d503-4865-aabf-ee688fa4b446.png)

### 预期行为
全文翻译成功

### 实际行为
全文翻译有窗口但是没有实际翻译

**Comment by lmk123** [comment]
感谢反馈，已成功重现这个问题。

出现此问题的原因是这个网页使用了 [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) 封装了具体的页面结构，而全文翻译目前还不支持使用了 Shadow DOM 的页面，我会尝试添加支持。

**Comment by lmk123** [comment]
下个版本已支持 Shadow DOM，截图如下：

![image](https://user-images.githubusercontent.com/5035625/134328741-a82e0258-ec29-485c-89b1-0a2a8f24a6ec.png)

**Comment by msghost** [comment]
牛逼，这改进速度。已购入永久会员支持。

**Comment by lmk123** [comment]
感谢支持~
