### ISSUE TITLE
【网页全文翻译】启用【在当前窗口自动开启】后，点击新链接会导致网页中的代码块部分被翻译

### ISSUE THREAD

**Issue by Unintendedz** [lmk123/crx-selection-translate#1167]
## 基本信息

划词翻译版本：  v8.5.7
浏览器版本：Microsoft Edge 版本 93.0.961.52 (官方内部版本) (64 位)
操作系统：Windows 10 20H1

## 重现问题的步骤

1. 打开 https://www.codecademy.com/learn/learn-c-sharp/modules/learn-csharp-interfaces-inheritance/cheatsheet
2. 右键，划词翻译，网页全文翻译
3. 选择“在当前窗口自动开启”
4. 在网页左边的Topic随便点击另一个新的链接

### 预期行为
不要翻译代码内容
![1111](https://user-images.githubusercontent.com/64687143/134095660-1c853f2a-4fc0-4703-9bc9-5229346665ba.jpg)

### 实际行为
把代码给翻译了
![2222](https://user-images.githubusercontent.com/64687143/134095675-fd62ce06-b97a-4b67-97d7-cea818140054.jpg)

**Comment by lmk123** [comment]
感谢反馈，重现了，将在之后的版本中修复

**Comment by lmk123** [comment]
在划词翻译 v8.6.5 版本中已经没有这个问题了，我猜你的问题跟 https://github.com/lmk123/crx-selection-translate/issues/1203 应该属于同一种情况。

如果你升级到 v8.6.5 之后还有这个问题，欢迎继续留言。
