### ISSUE TITLE
谷歌翻译的备用接口现在要挂梯子才能用了

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1168]
## 功能简介
translate.google.cn 现在被谷歌301跳转到.com了，而.com是需要挂梯子才能用的
## 为什么你觉得需要（改进）这个功能？
当用户使用谷歌翻译一直显示加载中的时候需要给用户一个提示，不然用户不知道为什么谷歌不能用了

**Comment by liugonglu** [comment]
什么是梯子，如何打开

**Comment by lmk123** [comment]
@liugonglu 即代理软件，需要你自己去下载的
