### ISSUE TITLE
无法注册划词翻译新账号,报错418

### ISSUE THREAD

**Issue by moeosu** [lmk123/crx-selection-translate#1173]
## 基本信息

划词翻译版本：8.5.7
浏览器版本：Chrome 93.0.4577.8
操作系统：Windows 10 教育版 21H1 19043.1237

## 重现问题的步骤

1.点击开通会员按钮
2.输入邮箱和密码（邮箱是foxmail）
3.报错

### 预期行为
注册成功

### 实际行为
报错418
![1](https://user-images.githubusercontent.com/61959166/134469789-b4ee9601-ef48-479e-aa45-b9aa5ce4d6df.PNG)

**Comment by lmk123** [comment]
我用我自己的一个 foxmail邮箱注册试了一下是正常的。你是在发送验证码的时候报的错，还是在输入验证码后点击注册时报的错？另外，方便提供一下你的完整邮箱吗，我看看是不是没有正确识别到你的邮箱格式

**Comment by lmk123** [comment]
如果不方便发到这里，你可以在公众号里发给我

**Comment by moeosu** [comment]
问题已解决，之前打开了AdGuard的隐形模式，关闭就可以正常发送验证码了
