### ISSUE TITLE
百度翻译 52001 超时

### ISSUE THREAD

**Issue by GF-Huang** [lmk123/crx-selection-translate#1175]
## 基本信息

划词翻译版本：v8.5.6
浏览器版本：MSEDGE 93.0.961.52 
操作系统：Win10 20H2

## 重现问题的步骤

1.
![image](https://user-images.githubusercontent.com/4510984/134809043-21a0a7ab-d130-4fb2-9582-48611afaf0c3.png)

2.
![image](https://user-images.githubusercontent.com/4510984/134809128-ae618ec0-217e-4f69-8b28-15ee886f56c6.png)

3.
![image](https://user-images.githubusercontent.com/4510984/134809144-04d6492c-92d5-4e05-9eb0-c829e030394e.png)

4.
![image](https://user-images.githubusercontent.com/4510984/134809149-7f5576bb-5372-4b0d-8824-a901baf43c63.png)

### 预期行为
不超时

### 实际行为
超时

**Comment by lmk123** [comment]
我试了我自己的密钥，是能正常使用的。百度为什么出现这个问题我也不太清楚，看它的解决方案是重试，我估计是百度自己的系统偶尔繁忙的时候会报这个错误，过会儿就会恢复。你现在还会报这个错误吗？

**Comment by GF-Huang** [comment]
问题依旧存在。

**Comment by lmk123** [comment]
由于我不知道问题的原因且无法重现，所以我只能提供一些可能可以解决问题的方法：

1. 卸载划词翻译后重新安装。有用户反馈阿里翻译有问题时，通过重装划词翻译就能解决，你可以试一下百度翻译是否也可以。
2. 联系一下百度翻译客服。填写密钥的时候，划词翻译是直接请求的百度翻译的接口，所以最好是问一下客服，看看是不是他们那边有什么特殊的规则。比如有道翻译如果时区设置的不对会报错、阿里翻译似乎将国外的一些  IP 列为了黑名单不让用，百度翻译倒是没有其它用户反馈有问题，你是第一个反馈百度翻译问题的 :joy:

**Comment by lmk123** [comment]
最近百度翻译恢复了吗？如果恢复了的话，希望你可以把出现问题的原因或者可能的解决方案分享给我，我会写在文档里，避免其它用户也出现相同的问题。

**Comment by GF-Huang** [comment]
> 最近百度翻译恢复了吗？如果恢复了的话，希望你可以把出现问题的原因或者可能的解决方案分享给我，我会写在文档里，避免其它用户也出现相同的问题。

通过邮件 translate_api@baidu.com 联系技术支持，告知他们我申请的 AppID 之后，过了几个小时就恢复了。

**Comment by lmk123** [comment]
感谢分享，我会将这个案例写进文档中。

**Comment by chenfengshijie** [comment]
我出现了52003的错误

**Comment by KKBIRD23** [comment]
> 我出现了52003的错误

我也是

**Comment by lmk123** [comment]
@chenfengshijie @KKBIRD23 从百度翻译的文档上看，52003 的错误含义是“未授权用户：请检查appid是否正确或者服务是否开通 ”，我猜测可能是你们没有正确的按照文档介绍的步骤开通服务、或者 APP id 和 key 没有填写正确。

如果你们确认你们有按照文档里的步骤开通了服务但仍然出现了这个错误，请新开一个工单，我会跟进。

**Comment by Howie7793** [comment]
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"58003","error_msg":"service invalid"}

**Comment by Howie7793** [comment]
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"58003","error_msg":"service invalid"} 大家有遇到这个问题嘛 我这里确认id和密钥没有错  前两天还能用的  换了台电脑

**Comment by suchacutesnake** [comment]
> baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"58003","error_msg":"service invalid"} 大家有遇到这个问题嘛 我这里确认id和密钥没有错 前两天还能用的 换了台电脑

以下是百度客服那边的自动回复

[错误代码58003]
请不要将您的APPID及密钥泄露出去，也不要填写到任何第三方软件中，包括“SCITranslate”、“微信学英语”、“Potplayer”等软件以及各类计算机辅助翻译工具插件。如因此造成密钥泄露形成经济损失，或因此被封禁，百度翻译将有权拒绝解封。

因黑产采用不正当手段收集用户APPID及密钥，由此产生的盗刷字符量现象日益猖獗，系统风控增加了IP校验规则，如同一IP当日使用多个APPID发送翻译请求，则该IP将被封禁当日请求权限，次日解封。
但由于IP多变，应用场景复杂，难免出现误伤正常使用的情况。如您属正常使用，但出现58003的提示，请发送邮件至 translate_api@baidu.com，同时提供如下信息。我方在收到邮件后将与您取得联系，核实后将解除封禁。
公司名称：
产品名称：
联系人：
联系方式：
服务器IP：
APPID：
注：如提供信息不全，将影响审核通过率。

**Comment by suchacutesnake** [comment]
> 我出现了52003的错误

我也遇到这种情况，排除appid输错的情况后，发现是没有开通百度翻译api的服务。这一疏漏来源于先查看的文字识别的教程： https://hcfy.app/docs/services/baidu-ocr  ，而文字识别里面也有一组api key和secret key，这两组key是不通用的。解决方法是按下面教程来一遍就好https://hcfy.app/docs/services/baidu-api
