### ISSUE TITLE
无法注册账号

### ISSUE THREAD

**Issue by DDL095** [lmk123/crx-selection-translate#1179]
## 基本信息

划词翻译版本：8.6
浏览器版本：EDGE
操作系统：WIN10

## 重现问题的步骤

1.
2.
3.

### 预期行为
注册账号，购买会员
### 实际行为
提示服务器无响应

**Comment by lmk123** [comment]
我试了一下，是可以正常注册账号的。你可以按照常见问题里的说明排查一下 https://hcfy.app/docs/faq/#server-no-response

**Comment by lmk123** [comment]
今天可以正常注册帐号了吗？

**Comment by lmk123** [comment]
无反馈且无法重现，所以这个 issue 我先关闭了，有问题可以继续留言。
