### ISSUE TITLE
In the Ubuntu14.04

### ISSUE THREAD

**Issue by Creativecole** [lmk123/crx-selection-translate#118]
无法自动朗读和朗读

**Comment by lmk123** [comment]
朗读功能基本上是跟系统无关的，我猜想你的问题可能跟这个有关：#115

朗读的时候，如果你没有选择源语种，我需要使用墙外的谷歌翻译检测语种，所以如果你的电脑没有翻墙，那么不会朗读。

你试试看选择一下源语种再朗读？

**Comment by lmk123** [comment]
我觉得问题的根源就在于我默认使用墙外的谷歌翻译来检测语种——如果没有反馈，我就这么认为并着手改进了。

**Comment by lmk123** [comment]
Done. c84bf61b9390699e05e380b4d3254a13935c1ba0

升级划词翻译至 v6.0.9 后看看还有没有这个问题。
