### ISSUE TITLE
增加小牛翻译的接口

### ISSUE THREAD

**Issue by DDL095** [lmk123/crx-selection-translate#1180]
## 功能简介
小牛翻译生物相关的还是可以，希望能增加这个功能。
## 为什么你觉得需要（改进）这个功能？
我自己有小牛的API跟词库，如果能网页翻译也带上就更方便了

**Comment by lmk123** [comment]
已在开发计划当中，等我把手头的一些优化项做完了就加，后续进展更新到 https://github.com/lmk123/crx-selection-translate/issues/1019
