### ISSUE TITLE
希望添加收藏夹的一级入口

### ISSUE THREAD

**Issue by ChangJin0520** [lmk123/crx-selection-translate#1182]
## 功能简介
准备把收藏夹当做单词本用，但是目前进入收藏夹，需要打开完整设置才能进入。
希望添加一级入口方便进入。

## 为什么你觉得需要（改进）这个功能？
需要划词翻译的一般都是不会的单词，收藏夹可以当做单词本使用，以供复习使用。希望把收藏夹功能打造的更强大点。

ps：我是前端，如果需要，可以 call 我，哈哈

**Comment by lmk123** [comment]
给你安排上，下个版本在翻译面板上加个按钮可以直接打开收藏夹

**Comment by lmk123** [comment]
在下个版本就可以在设置里将收藏夹和历史记录按钮显示在面板上了
