### ISSUE TITLE
网页全文翻译时，可以利用快捷键在双语和译文、原文之间跳转

### ISSUE THREAD

**Issue by adxrgh** [lmk123/crx-selection-translate#1184]
## 功能简介
网页全文翻译时，可以利用快捷键在双语和译文、原文之间跳转

## 为什么你觉得需要（改进）这个功能？
翻译经常需要比照对比，通常会先看机器的译文，再比对原文对照，再看原文，有一个快捷键会方便很多，特别是看一些细数据或者是细节翻译是不是到位的时候，需要经常来回跳转。

有一个可以设置快捷键设置真的方便很多

**Comment by lmk123** [comment]
可，会在最近的版本中加入

**Comment by lmk123** [comment]
v8.6.3 版本已添加了快捷键。v8.6.3 将在今天（10 月 31 日）提交审核。
