### ISSUE TITLE
阿里翻译标点符号是英文符号。

### ISSUE THREAD

**Issue by Daidaiduo** [lmk123/crx-selection-translate#1188]
## 基本信息
阿里翻译标点符号是英文符号。

划词翻译版本：v8.6.0
浏览器版本：
操作系统：

## 重现问题的步骤

1. 随便翻译都是

### 预期行为
应该是中文标点符号。

### 实际行为
是英文标点符号。

![image](https://user-images.githubusercontent.com/23332018/135973403-ee44a446-3863-4cb2-8ca1-ff100c5ee26f.png)

**Comment by lmk123** [comment]
翻译结果是由阿里翻译提供的，所以这属于阿里翻译的问题，划词翻译无能为力。如果你觉得这对你造成了困扰，你可以直接在阿里云里咨询客服，看看这个问题要怎么解决。

另外我翻译了一段英语，阿里翻译是可以正常显示为中文标点的，如下图，所以似乎并不是“随便翻译都是”，估计是阿里翻译有什么 bug，但具体是什么我也不清楚。

![image](https://user-images.githubusercontent.com/5035625/135975482-86d0ce49-0ce6-4105-8bf7-8fed403dba7c.png)
