### ISSUE TITLE
DeepL加载慢

### ISSUE THREAD

**Issue by Iambihua** [lmk123/crx-selection-translate#1193]
## 功能改进
DeepL加载显示翻译结果总是比其他翻译接口慢几秒，希望改善加载速度
## 为什么你觉得需要（改进）这个功能？
主要是考虑到如果改善DeepL的加载速度，会有一个比较好的使用体验，而相对于我来说，DeepL的加载速度令急性子的我很抓狂，特别是使用网页全文翻译的时候。

**Comment by lmk123** [comment]
DeepL 慢的问题无解，因为这是 DeepL 自己的问题。未来我会考虑通过 api key 的方式接入 DeepL（见 #1153）也许会快一些
