### ISSUE TITLE
疑似更新到8.6.2后用不了了

### ISSUE THREAD

**Issue by cotagxrdhy** [lmk123/crx-selection-translate#1197]
## 基本信息

划词翻译版本：8.6.2
浏览器版本：chrome、edge
操作系统：WIN10

## 重现问题的步骤

登录两个不同浏览器之后，划词就不能使用了，没有弹窗

**Comment by lmk123** [comment]
奇怪了，我刚才在 chrome 94 也删了重装，但是没有问题。。你是在哪个网址出现的问题，还是在所有网站都有问题？

**Comment by cotagxrdhy** [comment]
奇了怪。事情是这样的，我今天不知咋的突然谷歌浏览器更新8.6.2上之后，没过多久的划词截图啥的就用不了，只有网页翻译能用。然后我又下了个edge浏览器安装了8.6.2版本，刚开始一切正常，但我一登录我的账号后又出现这个问题。随后我又发现谷歌上的划词又正常能使用了，edge浏览器还是不能用，所有的网页都一样。

浏览器版本都是最新的

**Comment by lmk123** [comment]
自动更新后，在更新前打开的页面里确实是用不了的，需要刷新一下网页。不过这没法解释为什么edge里用了一会儿就用不了了……

我刚才尝试把chrome和edge的划词翻译都删了，然后按照你说的步骤，先在chrome上安装并登录，然后去edge安装并登录，然而我两边都是正常的。似乎“没过多久”是出现这个问题的一个必要条件？我多用一段时间看看

**Comment by cotagxrdhy** [comment]
问题是我现在用edge装回8.6.1版本也还是用不了...

**Comment by cotagxrdhy** [comment]
我电脑都重启了还是一样

**Comment by cotagxrdhy** [comment]
诶，关了扩展之后，正常了！！！

**Comment by cotagxrdhy** [comment]
https://pic.rmb.bdstatic.com/bjh/3b36f6054ee57986889d2c5531a91514.jpeg
是这个!!→  uBlock Origin ← 罪魁祸首就是它！！！

**Comment by lmk123** [comment]
问题又来了，我在 Chrome 94 上安装了 uBlock Origin，还顺手更新了一下最新的规则，但是我的划词翻译没有受到影响。把划词翻译卸载了之后再安装也没有影响。

你可以检查一下你的 uBlock 设置的自定义静态 / 动态规则，看看是不是误将划词翻译的相关元素给加入元素屏蔽规则里了

**Comment by cotagxrdhy** [comment]
好吧，我的问题我把网页翻译右下角的弹窗给屏蔽了...

**Comment by lmk123** [comment]
破案了 :joy:
