### ISSUE TITLE
查询结果时发生了网络错误，错误消息：服务器没有响应。查看帮助文档

### ISSUE THREAD

**Issue by TobySanm** [lmk123/crx-selection-translate#1198]
## 基本信息

划词翻译版本：8.6.0
浏览器版本：Edge
操作系统：Win 10

## 重现问题的步骤

1.谷歌翻译窗口出现“查询结果时发生了网络错误，错误消息：服务器没有响应。查看帮助文档”。
![Screenshot 2021-10-14 150727](https://user-images.githubusercontent.com/92509038/137268501-3d66f55d-8e3d-4a55-b02a-fef08c466118.png)

2.
3.

**Comment by lmk123** [comment]
你点一下“查看帮助文档”（也就是 [https://hcfy.app/docs/faq/#why-services-always-loading](https://hcfy.app/docs/faq/#why-services-always-loading)）就能看到原因了。大概率是因为触发了谷歌翻译的频率限制，需要挂梯子才能用了，具体原因见上方的链接。

如果挂了梯子还是不能用，你可以继续留言。
