### ISSUE TITLE
Cannot translate one certain pdf #1204

### ISSUE THREAD

**Issue by georgehandrew** [lmk123/crx-selection-translate#1207]
Hi lmk123,

I'd like give you some feedback.
pdf.js developer gave me feedback to try their most updated version of pdf.js rather than the the pdf viewer in chrom web store.
I tried to load the same pdf file at https://mozilla.github.io/pdf.js/web/viewer.html.
It looks the spaces are kept corretly.
So probably this issue could be solved when you use their updated pdf.js.

BTW, it looks that the OCR text layer has a return character for every line in one paragraph. From translation point of view, I think it might be better to remove the return character than to keep it. Can you think about this?

Thanks!

ps. it seems I cannot reopen the closed issue, so you can close this one as long as you have  seen this one. Thanks!

_Originally posted by @georgehandrew in https://github.com/lmk123/crx-selection-translate/issues/1204#issuecomment-950995905_

**Comment by lmk123** [comment]
I upgraded PDF.js to v2.10.377 in the next version (which is the latest stable version of PDF.js), and now it works great!

![Kapture 2021-11-01 at 22 22 44](https://user-images.githubusercontent.com/5035625/139687126-d5ffe19e-7dc7-4bae-8040-fea604a28082.gif)

**Comment by georgehandrew** [comment]
thank you very much!
