### ISSUE TITLE
希望为鼠标悬浮取词功能添加开关的快捷键

### ISSUE THREAD

**Issue by nlfiasel** [lmk123/crx-selection-translate#1209]
## 功能简介
使用快捷键打开或关闭鼠标悬浮取词功能
## 为什么你觉得需要（改进）这个功能？
现有的鼠标悬浮取词功能需要在快捷设置中勾选或反勾选鼠标悬浮取词实现打开或关闭，如果可以设置快捷键来控制这一功能的开关的话，可能会更方便一点

**Comment by lmk123** [comment]
v8.6.3 版本已给鼠标悬浮取词添加快捷键。v8.6.3 版本预计在今天（10 月 31 日）提交审核
