### ISSUE TITLE
希望网页翻译右下角弹窗动作取消掉

### ISSUE THREAD

**Issue by cotagxrdhy** [lmk123/crx-selection-translate#1214]
## 为什么你觉得需要（改进）这个功能？
每次使用网页翻译的时候右下角的弹窗动作会吸引注意力(有点强迫症...),感觉没必要,直接一直吸附在边缘就行了,需要更改的时候在去调整就好.

**Comment by lmk123** [comment]
我将在下个版本加一个选项，可以取消开启后自动弹出的动作

**Comment by lmk123** [comment]
我改主意了，我决定统一改成不自动弹出，也不打算加选项来控制它要不要弹出了

**Comment by wuhongyewhy** [comment]
> 

反对这点. 有时候翻译进度挺慢的, 有这个窗口起码知道确实开始翻译了.

**Comment by lmk123** [comment]
@wuhongyewhy 窗口没有消失，只是不会自动弹出了。开启之后，右下角的控制面板仍然会在。
