### ISSUE TITLE
動態載入頁面中，翻譯語言會變

### ISSUE THREAD

**Issue by ggg5269** [lmk123/crx-selection-translate#1217]
## 基本信息

划词翻译版本：v8.6.2
浏览器版本：edge 91.0.864.70 
操作系统：win10

## 重现问题的步骤

1. 網址：https://www.agriculture.com/markets/newswire
2. 該新聞頁面會在下滑到底時動態載入
3.

### 预期行为
載入新的新聞標題後，自動翻譯成中文

### 实际行为
當滑動到底並載入新標題數次後，翻譯內容會變成英翻英，如附圖

![image](https://user-images.githubusercontent.com/37011770/139966388-ea1a8f97-7ff4-490b-af5b-0db27d9c5368.png)

**Comment by lmk123** [comment]
感谢反馈。我使用 DeepL 和谷歌翻译在这个网址上试了一下，没有出现你这个问题——动态加载的新闻仍然是正常翻译为中文的。

你这个问题出现的原因很有可能是因为 DeepL 误将这部分英文识别为了中文导致的。就我个人的使用体验来看，DeepL 的语种判断偶尔是有问题的，比如它会把英文单词“test”识别成中文：

![image](https://user-images.githubusercontent.com/5035625/140015869-e858f82c-c76c-4ca0-b4a0-a48f21913cce.png)

如果这确实是 DeepL 的问题，那么我也无能为力；如果你能确认在 DeepL 上是正常的但在划词翻译里是不正常的，那么可能得麻烦你再多提供一些步骤让我能稳定重现这个问题，不然的话我很难确定问题出在哪里。

希望我的回复能帮到你，如果你仍有疑问，非常欢迎你继续留言。

**Comment by ggg5269** [comment]
![image](https://user-images.githubusercontent.com/37011770/140022292-9b20628c-9375-424b-b795-7723962b825e.png)

我後來重新使用 google翻譯也會有相同狀況，
我的操作是往下滑，往下滑，最後會顯示 **show more** 的按鈕
點擊之後再次載入更多頁面就會變成英文。

**Comment by lmk123** [comment]
感谢反馈，已重现，我会在最近的版本中修复此问题。

顺便贴个重现的图（Edge 95）：

![Kapture 2021-11-03 at 15 40 23](https://user-images.githubusercontent.com/5035625/140024305-11cbb1a5-3f0d-4c73-a027-2b5269dbf6b0.gif)


另外，在 Chrome 95 没有此问题。

**Comment by lmk123** [comment]
此问题已在下个版本中修复。下个版本预计在 11 月 15 日之后提交审核
