### ISSUE TITLE
希望本地网页翻译后能直接保存

### ISSUE THREAD

**Issue by wuhongyewhy** [lmk123/crx-selection-translate#1218]
我把英文电子书导出成多页的**本机html文件**, 然后全文翻译看书.  
## 如果能把翻译后的结果直接保存在原来的html文件里就好了.
注意这个和导出服务器上的网页翻译结果有点不同.

## 为什么你觉得需要（改进）这个功能？
很多英文电子书就可以翻译成中文, 再制作成电子书了. 
这比当前很多出版的中文版只有扫描版不知道好到哪里去了.

**Comment by lmk123** [comment]
浏览器本身就是有将当前网页存储为 html 的功能的，你可以在开启了网页全文翻译后将它再次导出为 html：

**Comment by lmk123** [comment]
浏览器本身就是有将当前网页存储为 html 的功能的，你可以在开启了网页全文翻译后将它再次导出为 html：

<img width="187" alt="截屏2021-11-03 下午2 28 18" src="https://user-images.githubusercontent.com/5035625/140017584-9a0f6cca-01cb-4264-a6c9-ee1aade14d8b.png">

我猜这应该就能满足你的需求了，如果这样还是不能的话，非常欢迎你继续留言。
