### ISSUE TITLE
deepl错误：错误消息：找不到source的语种下拉框。

### ISSUE THREAD

**Issue by rio-kiomi** [lmk123/crx-selection-translate#1220]
## 基本信息

划词翻译版本：v8.6.3
浏览器版本：edge 版本 95.0.1020.40
操作系统：win10

## 重现问题的步骤

1.滑词翻译无deepl的结果
2.
3.

**Comment by lmk123** [comment]
DeepL 出现这个错误有很多种原因。

首先，请按照 https://hcfy.app/docs/faq/#deepl-only 这里的说明排查一下。

然后，试着在扩展程序管理页面（chrome://extensions）关闭再开启划词翻译、然后重启下浏览器试试。

如果这两种办法都没生效，请继续留言，我会协助你解决问题。

**Comment by lmk123** [comment]
由于长时间没有反馈，所以这个 issue 我先关闭了，但是你仍然可以继续留言，我会持续跟进。
