### ISSUE TITLE
在一些页面上出错

### ISSUE THREAD

**Issue by wisecrick** [lmk123/crx-selection-translate#1221]
## 基本信息

划词翻译版本：8.6.3
浏览器版本：Chrome/95.0.4638.69
操作系统：Linux

## 重现问题的步骤

1.打开页面
https://www.thetimes.co.uk/article/voters-give-beleaguered-biden-warning-of-midterm-misery-2dlwtk978
![Screenshot_20211104_113133](https://user-images.githubusercontent.com/1472179/140253498-b67a0317-7d7f-4804-a301-0ec117457c86.png)

2.网页全文翻译，上下多滚动几下
![Screenshot_20211104_112840](https://user-images.githubusercontent.com/1472179/140253396-f4e03f5b-2480-4cbf-b617-99239019a965.png)

3.

### 预期行为
不要弹出这么多Save as之类

**Comment by wisecrick** [comment]
https://www.washingtonpost.com/ebooks/

![Screenshot_20211104_113820](https://user-images.githubusercontent.com/1472179/140254085-16e2152b-0272-469c-941b-4795e7f9d19b.png)
![Screenshot_20211104_113800](https://user-images.githubusercontent.com/1472179/140254096-bdcfb378-294c-4d2a-a8aa-ee8538761fa6.png)

**Comment by wisecrick** [comment]
https://www.washingtonpost.com/ebooks/

![Screenshot_20211104_113820](https://user-images.githubusercontent.com/1472179/140254293-94947565-311a-4b21-b52a-29608d99d037.png)
![Screenshot_20211104_113800](https://user-images.githubusercontent.com/1472179/140254305-e3b46692-914a-4333-aa02-2a39b5a5c57b.png)

**Comment by lmk123** [comment]
第一个问题在 macOS Chrome 95 上我没有重现，可能是因为我没有订阅，没法看到完整的文章。

第二个问题，你这个弹窗是怎么弹出来的？是不是也是需要订阅或者购买之后才能看到这个弹窗。。

如果这俩问题都需要订阅或者购买后才能重现，那我这边重现不了了 :joy:

**Comment by wisecrick** [comment]
这个订阅可以用ios app的试用白嫖
第一个是the times
第二个是Washington post

**Comment by lmk123** [comment]
从截图上看跟我遇到的另一个问题 #1217 很像。#1217 的根本原因就是划词翻译会把译文又翻译一遍，你的截图里好像也是这种情况。

#1217 已经解决了，你可以升级到 v8.6.5 试试你的问题还有没有

**Comment by wisecrick** [comment]
解决了，非常感谢！
希望能尽快把Deepl API开发出来，现有的在翻译一些特别长的HTML文档（通常是其它文档转化而来），就会出错

**Comment by lmk123** [comment]
解决了就好。

目前我正在着手改进设置页，然后就会添加 DeepL 和 Google API
