### ISSUE TITLE
PDF 的盖章没有显示

### ISSUE THREAD

**Issue by DIYer22** [lmk123/crx-selection-translate#1222]
这个 [带盖章.pdf](https://github.com/lmk123/crx-selection-translate/files/7482077/qRGK0Dl-QXTc40-4RoV2YH1dUDnCmpvCilgLoSsTjYbg3Wvt0BNE_Lm7k60YJprIE78R1bq2TEwz0IpuT4KDdA.pdf)

插件内置pdf阅读器:
![image](https://user-images.githubusercontent.com/10448025/140490578-d83e2c7b-b224-47af-a560-20928736abaa.png)

chrome 内置pdf阅读器:
![image](https://user-images.githubusercontent.com/10448025/140490534-87f60130-3908-4d52-b8fe-6449278bde15.png)

**Comment by lmk123** [comment]
这是 PDF.js 的问题，我无法解决，只能等 PDF.js 解决之后我再更新 PDF.js 的版本来解决。

看起来跟 https://github.com/mozilla/pdf.js/issues/14200 是同一个问题。

**Comment by lmk123** [comment]
已在 v8.6.4 中解决了此问题。v8.6.4 已提交审核，你可以去官网下载安装包立刻升级到 v8.6.4

**Comment by cksgh1224** [comment]
I know the latest version of pdf.js is 2.11.338, but what is v8.6.4?

我知道 pdf.js 的最新版本是 2.11.338，但什么是 v8.6.4？

**Comment by lmk123** [comment]
@cksgh1224 v8.6.4 is the version of "划词翻译". "划词翻译" is a [browser extension](https://chrome.google.com/webstore/detail/ikhdkkncnoglghljlkmcimlnlhkeamad) with a built-in PDF.js for displaying the translation results after select text on PDF files.

**Comment by cksgh1224** [comment]
I tracked an issue in PDF.js and mistook that issue (#1222) for a pdf.js story too. ^&^
