### ISSUE TITLE
能自定义添加网站自动网翻译吗

### ISSUE THREAD

**Issue by cotagxrdhy** [lmk123/crx-selection-translate#1223]
## 为什么你觉得需要（改进）这个功能？

比如经常逛的论坛要经常翻页,能自动翻译的话就能方便.

当前窗口翻译是没有限制网站,每次用了还得关闭才行

**Comment by lmk123** [comment]
你可以把你浏览的标签页分为两个浏览器窗口，比如你经常逛的论坛放在一个开启了“当前窗口自动翻译”的窗口，然后把普通的不需要自动翻译的放在另一个窗口。

我个人觉得这种办法可以避免掉需要自定义网站的情况且更灵活，你可以先这么用着试试，如果你觉得这种做法还是不好用的话，可以再继续留言分享你的感受给我，我再看看要不要给网页全文翻译加上通过网址来自动翻译的功能。

**Comment by cotagxrdhy** [comment]
好的,感谢!
