### ISSUE TITLE
同步设置提示建议改进

### ISSUE THREAD

**Issue by FetchTheMoon** [lmk123/crx-selection-translate#1224]
## 功能简介

这是原本同步设置的提示
![image](https://user-images.githubusercontent.com/79921141/140583985-99670515-52bb-48cf-8629-33f4c9b82d21.png)

## 为什么你觉得需要（改进）这个功能？

[是]和[否] 需要阅读上方文本经过一番理解才能知道含义, 而且按钮太小, 需要小心翼翼的点击, 一个点错后悔莫及

这是我的想法, 个人觉得这样只需要扫一眼就知道该如何选择
![image](https://user-images.githubusercontent.com/79921141/140584372-a03a8ad1-9302-44a1-be0b-f8fbc111bc49.png)

**Comment by FetchTheMoon** [comment]
不过老实说, 我不敢点否, 所以不知道点了否以后是否会弹出新的提示, 如果会弹的话当然会好很多

**Comment by lmk123** [comment]
很好的建议，将在下个版本中改进

**Comment by lmk123** [comment]
v8.6.5 已包含这项改进，感谢建议！
