### ISSUE TITLE
中英文混合网页全文翻译不正确

### ISSUE THREAD

**Issue by zhbslds** [lmk123/crx-selection-translate#1225]
## 基本信息

划词翻译版本：8.6.2
浏览器版本：
操作系统：win10 2019 LTSC

## 重现问题的步骤
网址:https://scholar.google.com/scholar?hl=zh-TW&as_sdt=0%2C5&q=test&btnG=
google本身被设置为中文
原始网页
![image](https://user-images.githubusercontent.com/31299780/140595761-b1848da8-746a-4a6d-96c3-8f6a946017f4.png)

翻译结果
![image](https://user-images.githubusercontent.com/31299780/140595717-5027be43-a936-41d7-8f7c-69fa84f6529d.png)
![image](https://user-images.githubusercontent.com/31299780/140595794-66b1aa33-68a5-4160-8fc9-8df171252eb3.png)

**Comment by lmk123** [comment]
这是已知问题，原因见[网页全文翻译常见问题](https://hcfy.app/docs/guides/page#faq)中的“多语言混合页面翻译结果有误”。

后面我会加一个选项“不翻译页面中的中文”（进展可以关注 #1183），这样就能确保网页全文翻译时只会收集到英语这一个语种。
