### ISSUE TITLE
启用扩展后在部分论坛进行回帖，点评等操作后不会自动返回

### ISSUE THREAD

**Issue by fiender1** [lmk123/crx-selection-translate#1228]
## 基本信息

划词翻译版本：8.6.3
浏览器版本：Chromium 86.0.4240.198)
操作系统：win7 64 sp1

## 重现问题的步骤

Cent Browser 版本 4.3.9.248（正式版本）
最近两天发现在 部分discuz论坛，例如hostloc 恩山 3dm 吾爱破解等，进行回帖，点评，评分等操作后，点击按钮后不会返回结果页面，但刷新页面后结果已生成，经过排查后发现禁用该扩展后就正常。希望排查后解决修复。

**Comment by lmk123** [comment]
已重现，将会优先解决此问题。

以下是具体重现步骤：

1. 打开 3DM 的任意帖子如 https://bbs.3dmgame.com/thread-5639256-1-1.html
2. 将页面滚动到最底部，会出现一个输入框。在输入框输入内容后，点击【发表回复】按钮

预期行为：网页应该会被刷新，然后 3DM 会显示“发表回复成功，金币 +10”的提示
实际行为：网页没有任何变化。手动刷新网页后 3DM 才会显示“发表回复成功，金币 +10”的提示，且回复内容确实出现在了最后一页

**Comment by lmk123** [comment]
Hi，我己经在下个版本中修复了此问题并在 3DM 测试通过，能否请你帮忙测试一下 hostloc 恩山 吾爱破解等其它网站？

如果你愿意帮忙的话，麻烦邮件联系我 hi@hcfy.app，我会将下个版本的安装包发送给你

**Comment by lmk123** [comment]
我已经将离线安装包上传到了网盘，希望你能安装一下并测试在其它网站是否能正常回帖，先谢谢了！

**Comment by fiender1** [comment]
安装8.6.4后问题修复，在多个论坛上以测试。谢谢，辛苦了！

**Comment by Ansen** [comment]
最近也遇到这个问题，今天终于闲下来查找到原因，结果已经解决了，firefox商店 还停留在863版本

**Comment by lmk123** [comment]
@Ansen  目前正在逐步发布 Chrome 商店，如果观察几天没有大的问题的话我就会发布 Firefox 商店
