### ISSUE TITLE
奇怪了，uc下设置窗口出不来，只有一条

### ISSUE THREAD

**Issue by gggccc44** [lmk123/crx-selection-translate#123]
难道是我打开的方式不对？6.0.8，6.0.5都这样。其他版没试，以前5.x正常

**Comment by lmk123** [comment]
uc 是指什么？

**Comment by lmk123** [comment]
“只有一条”又是什么意思？

**Comment by gggccc44** [comment]
uc浏览器pc版啊，只有一条意思是设置那个页面，你程序是做的想弹出一个条状然后再弹出设置窗口，现在只有开始那个弹出跳，具体的设置窗口没出来，以前5.x单独的设置窗口没这问题

**Comment by gggccc44** [comment]
我用Extensions Manager扩展间接解决了，在Extensions Manager里面可以点出单独的设置窗口

**Comment by lmk123** [comment]
找到解决方法就好 :smile: 

我仅仅在 Chrome 浏览器里做了测试。国内的“套壳”浏览器实在太多，并且内置的 Chrome 版本普遍偏低，所以可能会出现各种奇怪的问题，但我没有精力去一个个安装这些套壳浏览器并解决仅仅会出现在这些浏览器里的问题。
