### ISSUE TITLE
增加一个选项：将复制出来的文本的首字符改为小写

### ISSUE THREAD

**Issue by huanhl** [lmk123/crx-selection-translate#1231]
## 功能简介

增加设置，快捷翻译后，首字母非大写选项

## 为什么你觉得需要（改进）这个功能？

当前使用快捷方式翻译后，默认翻译出的文本为首字母大写，在复制到其他内容时，常常需要手动修改，
希望增加设置功能，可以自行选择翻译出文本是否为首字母大写，谢谢。

**Comment by lmk123** [comment]
可

**Comment by lmk123** [comment]
保险起见我再确认一下，你是希望将复制出来的文本的首字母变成小写是吧？

我比较好奇，什么样的情况下你希望将首字母变成小写？一般情况下首字母就是要大写的吧

**Comment by huanhl** [comment]
连续段落翻译时，默认首字符大写需要手动去修正，增加选项人为控制比较便捷。
