### ISSUE TITLE
关于DeepL

### ISSUE THREAD

**Issue by GiftLiwu** [lmk123/crx-selection-translate#1232]
目前得情况是，网页版DeepL都无法翻译，请问也有遇到的吗？

**Comment by ruantu** [comment]
你的ips屏蔽了DeepL?, 我这里(墙内)还是可以访问的

**Comment by lmk123** [comment]
我试了一下， https://www.deepl.com/translator 无论是否开梯子都是能直接打开的。我猜你那边也是被屏蔽了？

多个地点 ping 了一下也是能正常访问的

http://ping.chinaz.com/www.deepl.com/

**Comment by GiftLiwu** [comment]
在推特上搜了一圈，也有人遇到这种情况，不过目前已经可以访问，谢谢
