### ISSUE TITLE
收藏夹无法正确显示单词

### ISSUE THREAD

**Issue by XDXD233** [lmk123/crx-selection-translate#1233]
## 基本信息

划词翻译版本：v8.6.3
浏览器版本：Chrome 版本 95.0.4638.69（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

查看收藏夹中的单词时发现很多单词都无法正确显示，
具体如下图：
![image](https://user-images.githubusercontent.com/94083126/141203703-a0909aee-1aed-4039-b1c8-c0ab9b90dd8f.png)

**Comment by lmk123** [comment]
我试了一下，将 mediated 加入收藏夹后，看到的翻译结果是正常的。

你是不是登陆了另一个浏览器，然后同步下来的单词会显示成这个样子？

**Comment by lmk123** [comment]
由于我无法重现你的问题，所以我不知道该怎么解决 :joy: 如果你能提供一下可以 100% 重现这个问题的步骤，我也会第一时间解决这个问题。

一个解决方案：如果你开通了会员的话，你可以尝试卸载划词翻译后再重新安装，然后登录你的账号，之后划词翻译会重新查询收藏夹里的翻译结果。如果这种方式还是不行，你可以继续留言反馈给我。

**Comment by lmk123** [comment]
由于我无法重现，所以我没法处理这个问题，这个 issue 我先关闭了。如果你能提供一下可以稳定重现这个问题的步骤、或者你尝试了我提供的解决方案之后成功或失败了，欢迎你继续留言，我会继续跟进。
