### ISSUE TITLE
PDF选中文字颜色bug

### ISSUE THREAD

**Issue by zjw1111** [lmk123/crx-selection-translate#1234]
## 基本信息

划词翻译版本：8.6.3
浏览器版本：Chrome 95.0.4638.69
操作系统：Win10  10.0.18363.1256

## 重现问题的步骤

打开PDF选中文本后，会出现不符预期的选中状态，如图，会出现深蓝色或过于浅的浅蓝色

#### 图1
![image](https://user-images.githubusercontent.com/30893610/141274121-58c0df66-fbd2-4c1c-9371-c85a425511c4.png)
#### 图2
![image](https://user-images.githubusercontent.com/30893610/141274697-ceaed43a-24e3-4818-ae1b-1daa6c00f66b.png)

**Comment by lmk123** [comment]
感谢反馈！浅蓝色是符合预期的，但深蓝色应该是 bug，方便提供一下出现这个问题的 pdf 给我重现一下吗？

**Comment by zjw1111** [comment]
截图中出现深蓝色的PDF是这个 [test pdf.pdf](https://github.com/lmk123/crx-selection-translate/files/7524633/test.pdf.pdf)，第7页右边那栏。

BTW，为什么浅蓝色是符合预期的呢？浅蓝色是指图2中`In order to solve the centralization problem, some`这行，以及下图中红框部分

![image](https://user-images.githubusercontent.com/30893610/141403679-c023467d-ab58-4771-b24f-bd660b16a454.png)

**Comment by lmk123** [comment]
原来你指的是这个几乎看不见的蓝色 :joy: 我在图 2 里没注意到。这个几乎看不见的蓝色确实也是有问题的。

但是我用你提供的文件没有重现深 / 浅蓝色的问题，如图：

<img width="443" alt="截屏2021-11-12 上午11 39 59" src="https://user-images.githubusercontent.com/5035625/141405141-852c0c6e-f2fb-40ea-bd90-9f631f4f6780.png">

我的划词翻译也是 v8.6.3、浏览器也是 Chrome 95.0.4638.69（正式版本） (arm64) ，虽然我的操作系统是 macOS 但理论上这个问题跟操作系统没有关系。

由于无法重现，所以我可能没法帮到你，你可以卸载划词翻译后重新安装试试。

如果还是不行，那只能麻烦你再多尝试一下如何能让我重现这个问题。

**Comment by lmk123** [comment]
由于我无法重现且长期没有反馈，所以这个 issue 我先关闭了，但是你仍然可以继续留言，届时我会重新打开。
