### ISSUE TITLE
翻译面板添加音标/拼音

### ISSUE THREAD

**Issue by hsichien** [lmk123/crx-selection-translate#1237]
## 功能简介
翻译中文或者英语时在划词翻译面板显示该字/词的拼音或音标

## 为什么你觉得需要（改进）这个功能？
在遇到某些生僻字词时或者某些发音困难的英语单词时可以通过拼音或者音标来发音

**Comment by lmk123** [comment]
谷歌翻译是提供拼音 / 音标的。其它翻译服务如有道、必应也是有的。

如果翻译服务不提供音标，那么我也无法“变”出来 😂
