### ISSUE TITLE
使用浏览器自带的PDF查看器时，正则替换无效。

### ISSUE THREAD

**Issue by yuan-ge** [lmk123/crx-selection-translate#1238]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

在浏览器的内置PDF查看器中打开一个PDF文件，然后选择换行的文本，发现正则替换没有作用。

**Comment by lmk123** [comment]
v8.6.3 会提前将换行符 `\n` 替换成空格，这是为了让没有使用过【源文本处理】的用户也能正常翻译文本。

如果你的问题不是我说的这种情况，麻烦提供一下具体的信息，例如划词翻译和浏览器的版本、你的正则的具体配置、具体是在哪个 PDF 文件划选哪段文本时没有起作用等。

如果你觉得我不应该提前处理 PDF 里的换行符也可以继续留言探讨。

**Comment by yuan-ge** [comment]
![image](https://user-images.githubusercontent.com/61228924/141604243-9e642c4a-468b-41d9-a517-a92434a1c0f0.png)
我的版本是8.6.3，设置是将换行符替换成空格，图中是翻译的结果

**Comment by lmk123** [comment]
方便提供一下你这个 pdf 文件吗

**Comment by yuan-ge** [comment]
[autoware on board.pdf](https://github.com/lmk123/crx-selection-translate/files/7531341/autoware.on.board.pdf)

**Comment by lmk123** [comment]
重现问题了。你可以在划选之后通过右键菜单的【翻译这段文本】来使用，这种方式是能正常翻译的。

----------

具体问题描述：

这段文本复制出来的时候是带有换行符的：

```
Using
sensor data, autonomous vehicles perform localization, detection, prediction, planning, and control, which are core
modules of computing intelligence. Classical algorithms are
in favor of rule-based systems and pattern recognition, while
recent data-driven approaches to new algorithms leverage
machine learning and deep neural networks.
```

但即使勾选了【源文本处理】里的【将换行符替换成空格】，划词翻译在打开独立翻译窗口时也没有做替换。

**Comment by lmk123** [comment]
将在下个版本 v8.6.5 修复。如果升级到下个版本还是有问题麻烦留言告知我。

**Comment by yuan-ge** [comment]
吆西，看到这个功能要被修复，我觉得很高兴。毕竟是大家一起努力的结果，可惜不能与作者一起写代码hh。

**Comment by lmk123** [comment]
帮我找 bug 也是参与开发的一种重要形式！我很重视并感谢大家反馈的问题，因为这让划词翻译越来越完善了
