### ISSUE TITLE
唤出独立窗口后没有自动聚焦输入框

### ISSUE THREAD

**Issue by Czlun** [lmk123/crx-selection-translate#1241]
划词翻译版本：v8.6.5
浏览器版本：Chrome 95
操作系统：macOS 12

重现步骤：点击扩展按钮，然后点击“独立翻译窗口”；或者通过全局快捷键打开“独立翻译窗口”
按照预期：独立窗口打开后应该自动聚焦到文本框
实际行为：没有聚焦到文本框
其它信息：

- 已经试过，无论剪切板是否有文本都没有聚焦到文本框
- 尝试多次，偶尔有一两次会聚焦
- 扩展弹出页面倒是正常的

以下是原文：

---------------------

## 功能简介
在唤出独立翻译窗口后希望光标默认聚焦在输入框中，这样可以省去一个按快捷键后再使用鼠标或触控板点击的流程。

## 为什么你觉得需要（改进）这个功能？
在唤出独立翻译窗口后能做的事情就只有输入内容，默认聚焦在输入框中符合使用流程。

**Comment by lmk123** [comment]
这是一个 bug 😂  之前都是会自动聚焦输入框的
