### ISSUE TITLE
单词翻译的释义不全，与官网翻译结果不同

### ISSUE THREAD

**Issue by Chorer** [lmk123/crx-selection-translate#1242]
## 基本信息

划词翻译版本：8.6.3
浏览器版本：Chrome 95
操作系统： win10

## 重现问题的步骤

1. 进入[网址](https://www.typescriptlang.org/docs/handbook/2/functions.html)
2. 选中任意一个单词
3. 点击进行划词翻译

### 预期行为
和百度翻译官网一样，可以展示单词的所有释义（clause 这个单词本身有多个意思）
![image](https://user-images.githubusercontent.com/43442630/141942670-b9b9fe6a-9cc4-44ee-b3cd-9150da3946b8.png)

### 实际行为
只出现单词的一种释义
![image](https://user-images.githubusercontent.com/43442630/141942634-80091d73-cb8f-40bf-b993-7c35d226131d.png)

**Comment by lmk123** [comment]
划词翻译使用的是[百度翻译的官方接口](https://fanyi-api.baidu.com/)，而官方接口要求必须是**企业认证**用户才会返回词典数据，见[百度翻译通用翻译API产品介绍](https://fanyi-api.baidu.com/product/111)

如果你希望有词典数据，你可以用必应词典。
