### ISSUE TITLE
开启划词翻译会导致用iframe嵌入的代码编辑器无法使用

### ISSUE THREAD

**Issue by gaojunming** [lmk123/crx-selection-translate#1246]
我使用的是 Windows 10 Chrome 95 和划词翻译 8.6.6，今天我发现网页翻译功能会导致iframe内容无法正常展示。重现问题的步骤如下：

打开 https://flutter.cn/docs/codelabs/layout-basics#flexible-widget
找到页面嵌入的代码编辑器

预期行为：代码编辑器应该可以正常使用。
![image](https://user-images.githubusercontent.com/18290101/142214123-f4f25a3c-59e6-4328-825c-631075bcdeb0.png)

实际行为：代码编辑器无法编辑且编辑器内示例代码消失
![image](https://user-images.githubusercontent.com/18290101/142214074-3d9c678a-5055-4070-94c6-2c8ceb1685aa.png)

**Comment by lmk123** [comment]
已重现此问题，将会优先解决

**Comment by lmk123** [comment]
顺便纠正一下，你用的应该是 v8.6.5（现在的最新版本就是 v8.6.5）

我将立刻发布一个新版本 v8.6.6 解决这个问题

**Comment by lmk123** [comment]
我已经在 v8.6.6 中解决了这个问题，你能帮我测试一下在你这边是否正常吗？如果能的话，麻烦把你的邮箱给我，我将 v8.6.6 的代码包发给你

**Comment by gaojunming** [comment]
好的，给你发了邮件，你看下收到没

**Comment by gaojunming** [comment]
> 我已经在 v8.6.6 中解决了这个问题，你能帮我测试一下在你这边是否正常吗？如果能的话，麻烦把你的邮箱给我，我将 v8.6.6 的代码包发给你
942062942@qq.com  这个

**Comment by lmk123** [comment]
收到了，稍等我正在打包代码

**Comment by lmk123** [comment]
代码包已经发给你了，麻烦查收一下

**Comment by gaojunming** [comment]
可以了，网页现在打开正常了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmk123/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lmk123/crx-selection-translate] 开启划词翻译会导致用iframe嵌入的代码编辑器无法使用 (Issue #1246)





 
代码包已经发给你了，麻烦查收一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmk123** [comment]
感谢测试，我一会儿就提交审核，之后你可以去官网的网盘里下载 v8.6.6 的正式安装包

**Comment by gaojunming** [comment]
收到，等下去下载这么快解决了我的问题，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmk123/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lmk123/crx-selection-translate] 开启划词翻译会导致用iframe嵌入的代码编辑器无法使用 (Issue #1246)





 
感谢测试，我一会儿就提交审核，之后你可以去官网的网盘里下载 v8.6.6 的正式安装包
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmk123** [comment]
我刚刚把 v8.6.6 的正式安装包上传到网盘了。

改 bug 的途中又出现了另一个bug，导致我到现在才提交审核 :joy:

**Comment by gaojunming** [comment]
好的👌🏻，大佬辛苦了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日(周四) 凌晨2:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lmk123/crx-selection-translate] 开启划词翻译会导致用iframe嵌入的代码编辑器无法使用 (Issue #1246)




 
我刚刚把 v8.6.6 的正式安装包上传到网盘了。
 
改 bug 的途中又出现了另一个bug，导致我到现在才提交审核 😂
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
