### ISSUE TITLE
google play 全文翻译不支持

### ISSUE THREAD

**Issue by asasas234** [lmk123/crx-selection-translate#1247]
google play 上随便找一本书，全文翻译不支持，鼠标选词去翻译是可以的

**Comment by asasas234** [comment]
https://play.google.com/store/books/details?id=fhhPEAAAQBAJ&rdid=book-fhhPEAAAQBAJ&rdot=1 我看的是这本

**Comment by lmk123** [comment]
感谢反馈，目前来看这跟 #1219 是同一个问题。图书的内容被放在了子框架（[<iframe>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/iframe)）里，而全文翻译目前不支持翻译子框架里的文本。

此问题将在未来修复，你可以关注 #1219 来跟踪具体进展。
