### ISSUE TITLE
翻译面板在中文输入法异常卡住

### ISSUE THREAD

**Issue by dousybox** [lmk123/crx-selection-translate#1248]
## 基本信息

划词翻译版本：划词翻译 v8.6.6 划词翻译 v8.6.2
浏览器版本：Microsoft Edge 版本 96.0.1054.29 (官方内部版本) (64 位)
操作系统：win10

## 重现问题的步骤

1.任意页面打开翻译面板
2.切换输入法为搜狗中文
3.输入任意内容

### 预期行为
正常输入文本内容

### 实际行为
浏览器冻结,只能从任务管理器杀进程

**Comment by lmk123** [comment]
感谢反馈，确实一直有用户反馈翻译面板会卡死，看来跟搜狗输入法有关。我果断时间会在 win 电脑上试一下。

附注：在 macOS 上用搜狗拼音输入法没有重现。

**Comment by dousybox** [comment]
这个问题好像很诡异, 出问题的是公司的电脑, 我回家后这个问题就不能复现了，然后远程回公司电脑,居然也好了。

**Comment by lmk123** [comment]
我最近没有遇到这个问题了，所以这个问题似乎没法重现……如果你之后还遇到了这个问题，欢迎继续留言补充
