### ISSUE TITLE
希望独立翻译窗口能固定

### ISSUE THREAD

**Issue by GRELEEN** [lmk123/crx-selection-translate#1249]
在浏览器外或者浏览器自带PDF中，你需要选中、复制、点出独立翻译窗口（因为窗口外点击会最小化）、黏贴四步才能得到翻译

如果新增独立窗口固定

那么我不需要反复调出翻译窗口，而且在固定情况下可以随时查看翻译结果

**Comment by lmk123** [comment]
我猜你说的“固定”是指让独立翻译窗口始终显示在最顶部。扩展程序是做不到这一点的，只能靠第三方软件实现，比如 windows 系统上有一个软件叫 deskpins  https://efotinis.neocities.org/deskpins/index.html

另外，独立翻译窗口的使用步骤可以进一步简化：

> 在窗口外点击会最小化

独立窗口没有最小化，只是被其它窗口遮住了。你不需要去任务栏用鼠标点击独立翻译窗口，你可以用快捷键（默认是 Ctrl + Shift + 1）把它呼出来。你可以把这个快捷键设置短一点。

> 黏贴

你可以把“自动翻译剪切板内的文本”设置为“翻译”，这样的话你就不需要自己把文本粘贴进独立翻译窗口了，独立窗口在被快捷键呼出来的时候会自动读取剪切板并翻译

**Comment by GRELEEN** [comment]
非常谢谢，
deskpins使用效果很不错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmk123/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lmk123/crx-selection-translate] 希望独立翻译窗口能固定 (Issue #1249)





 
我猜你说的“固定”是指让独立翻译窗口始终显示在最顶部。扩展程序是做不到这一点的，只能靠第三方软件实现，比如 windows 系统上有一个软件叫 deskpins  https://efotinis.neocities.org/deskpins/index.html
 
另外，独立翻译窗口的使用步骤可以进一步简化：
  
在窗口外点击会最小化
  
独立窗口没有最小化，只是被其它窗口遮住了。你不需要去任务栏用鼠标点击独立翻译窗口，你可以用快捷键（默认是 Ctrl + Shift + 1）把它呼出来。你可以把这个快捷键设置短一点。
  
黏贴
  
你可以把“自动翻译剪切板内的文本”设置为“翻译”，这样的话你就不需要自己把文本粘贴进独立翻译窗口了，独立窗口在被快捷键呼出来的时候会自动读取剪切板并翻译
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmk123** [comment]
不用谢，有问题欢迎反馈！
