### ISSUE TITLE
希望能提供选项：隐藏右下角选择翻译源的窗口，把选项移入扩展弹出菜单

### ISSUE THREAD

**Issue by wisecrick** [lmk123/crx-selection-translate#1250]
## 为什么你觉得需要（改进）这个功能？
与一些扩展冲突，比如Super Dark Mode
https://chrome.google.com/webstore/detail/super-dark-mode/nlgphodeccebbcnkgmokeegopgpnjfkc
![Screenshot_20211124_181630](https://user-images.githubusercontent.com/1472179/143220637-d3012517-8419-4c80-9877-8c55710b2ae2.png)

在从右向左书写语言的页面上出错，比如希泊来语，阿拉泊语，波斯语
https://www.globes.co.il/news/article.aspx?did=1001391564
![Screenshot_20211124_181925](https://user-images.githubusercontent.com/1472179/143220802-d92b831b-25c3-4f03-a760-aa10de1ea75d.png)
![Screenshot_20211124_181850](https://user-images.githubusercontent.com/1472179/143220818-984d4bcc-7efa-4722-b91c-e99f9a5d4cbd.png)

**Comment by lmk123** [comment]
这项改进其实可以拆分成两个问题：

- 解决跟 super dark mode 的冲突 #714 
- 确保划词翻译在从右到左的网页里也是保持左到右显示的

如果这两个问题没法解决，我会再考虑改变右下角控制面板的显示位置

**Comment by wisecrick** [comment]
不是深色模式无效，划词翻译会在下面带来一个巨大的黑条

**Comment by lmk123** [comment]
标题是用户起的，我没改，你点进去看，这个用户说的就是跟 super dark mode 冲突的问题

**Comment by lmk123** [comment]
在阿拉伯网页中的排版问题我已经在 v8.6.7 中修复了。跟 super dark mode 冲突的问题我会更新到 #714
