### ISSUE TITLE
百度大脑通用文字识别不可用，无论是翻译积分还是自申请的API

### ISSUE THREAD

**Issue by FetchTheMoon** [lmk123/crx-selection-translate#1251]
## 基本信息

划词翻译版本：8.6.6
浏览器版本：版本 96.0.1054.29 (官方内部版本) (64 位)
操作系统：Windows 10

## 重现问题的步骤

尝试过切换到Tesseract OCR 再切换回来，都不管用
 
![1](https://user-images.githubusercontent.com/79921141/143447783-41982b38-9ebc-4064-b916-bc4a0f9aed88.jpg)
![2](https://user-images.githubusercontent.com/79921141/143447809-257cfd78-e1fb-4408-ae3d-086cbf2983b6.jpg)

**Comment by FetchTheMoon** [comment]
更新浏览器重启了一次可用了 ……

**Comment by lmk123** [comment]
😂 有时候重启浏览器确实可以解决一些疑难杂症
