### ISSUE TITLE
网页全文翻译的译文可编辑不是只读

### ISSUE THREAD

**Issue by HHPLow** [lmk123/crx-selection-translate#1253]
## 基本信息

划词翻译版本：8.6.6
浏览器版本：Firefox 94.0.2
操作系统：Windows

## 重现问题的步骤

1. 打开网页
2. 网页全文翻译
3. 双击并编辑

### 预期行为
应该为只读

### 实际行为
可编辑

**Comment by lmk123** [comment]
这是一个功能，因为有用户反馈跟我说希望译文可编辑，他们需要编辑一些机器翻译的不准确之处再导出。

为了避免影响用户复制译文，所以我做了一个限制，就是只有单击或双击的时候才会变成可编辑的输入框。

这一点对你造成了困扰吗？因为我觉得大部分人可能只需要复制译文，而不会在译文上单击或双击。

**Comment by HHPLow** [comment]
ok了解了。
暂时没有什么特别的困扰，只是碰巧发现点击之后浏览器的语法检查有提示， 然后发现了是可编辑。

**Comment by lmk123** [comment]
嗯嗯，如果这个功能对你造成了困扰，欢迎继续反馈，我会考虑加一个选项来确定译文是否可被编辑。
