### ISSUE TITLE
最新版本卡的要死，每次点都要等半天

### ISSUE THREAD

**Issue by ChrisPei** [lmk123/crx-selection-translate#126]
为何？原来反应很快，现在非常慢，多台电脑都是这样。

**Comment by lmk123** [comment]
你看看你是不是开启了**全局代理**？

**Comment by ChrisPei** [comment]
SwitchyOmega自动代理，Google会翻墙。但以前也这样，点图标弹出并没有受到影响。

**Comment by lmk123** [comment]
你所说的”点开等半天“是指划词的时候要等翻译结果等待很长时间，还是指点击浏览器地址栏右边的扩展图标时，弹出页要很长时间才打开？

**Comment by ChrisPei** [comment]
点击浏览器地址栏右边的扩展图标时，弹出页要很长时间才打开。

**Comment by lmk123** [comment]
”很长时间“大概是多长？我这边点击之后 1.5s 左右能打开。

**Comment by ChrisPei** [comment]
有时会到5秒

**Comment by lmk123** [comment]
是每一次点开都很慢吗？偶尔会不会能正常的很快就点开？

**Comment by ChrisPei** [comment]
刚刚仔细测试了下，停掉代理直连模式下，确实没感觉到什么延迟。而开启代理时，在完全关闭Chrome的时候，再打开，遇到最长大概8秒。不关闭Chrome再多次测试下，大部分时间小于0.5秒。

**Comment by ChrisPei** [comment]
多次完全关闭Chrome，开启自动代理时，大部分时间也小于0.5秒，但约10次中有2次，延迟严重。

**Comment by lmk123** [comment]
一开始我理解错了，其实右上角的弹出页打开的时间跟 FQ 与否无关的 :smile: 

新版本确实使用了一些新技术，但我认为，打开慢的原因更多的在于你的系统环境：你点开弹出页的时候，电脑正在执行计算量较大的任务，也就是我们俗称的“电脑卡” :joy:

例如：

 - 开启了多个 Chrome 标签页。你知道 Chrome 挺占内存的。
 - 系统正在运行其他需要很大计算量的任务，比如大型的游戏。某些后台任务也可能会导致你的电脑计算量变大。

就我而言，右上角的弹出页的打开时间从没超过 2s。

**Comment by ChrisPei** [comment]
i7-4770 32G 内存 开发机表示。。很少能喂饱它，还让他打个8秒的嗝。。。

旧版本从来没出现过这样的情况，新版本一更新的时候就有。刚刚撸代码时候想查东西，就卡住了，受不了了才是来吐槽下。

**Comment by ChrisPei** [comment]
// Handle Array
    if (obj instanceof Array) {
        copy = [];
        var len = obj.length;
        for (var i = 0; i < len; ++i) {
            copy[i] = self.clone(obj[i]);
        }
        return copy;
    }

刚刚我剪贴板里是这个，点击又卡半天。CPU并未出现明显峰值。

**Comment by lmk123** [comment]
我复制了你这段代码并点击扩展按钮，打开仍然很快。:grin:

**Comment by lmk123** [comment]
在我的电脑上没法重现你的问题，所以我就关闭这个 issue 了。

如果你以后找到了能重现此问题的确切步骤（比如开启了什么软件之类的），你可以继续留言 :smile:

**Comment by ChrisPei** [comment]
ok
