### ISSUE TITLE
油管直播聊天区能加入翻译吗

### ISSUE THREAD

**Issue by cotagxrdhy** [lmk123/crx-selection-translate#1260]
## 为什么你觉得需要（改进）这个功能？
目前是无法翻译的.

**Comment by lmk123** [comment]
我上油管上的比较少，能麻烦你描述一下“油管直播聊天区”具体是在哪个网址的哪个区域吗？

**Comment by cotagxrdhy** [comment]
就是直播视频右边这一块区域

地址:https://www.youtube.com/watch?v=Xct9rDWXGns

你可以上去看看先
![image](https://user-images.githubusercontent.com/80959178/144710811-8a9a648d-61fa-4f69-aabc-4bce413072f1.png)

**Comment by lmk123** [comment]
我的梯子估计有问题，这一块我没有显示出任何文字出来 :joy: 我明天再看看

**Comment by lmk123** [comment]
看到文字了。这跟 #1219 应该是同一个问题

**Comment by cotagxrdhy** [comment]
好的辛苦了!

**Comment by lmk123** [comment]
后续进展会更新到 #1219，这个 issue 就先关闭了
