### ISSUE TITLE
清除【激活扩展】的快捷键会显示为CTRL+Q，实际不起任何作用

### ISSUE THREAD

**Issue by FetchTheMoon** [lmk123/crx-selection-translate#1263]
## 基本信息

划词翻译版本：划词翻译 v8.6.6
浏览器版本：Microsoft Edge 版本 96.0.1054.43 (官方内部版本) (64 位)
操作系统：Windows 10

## 重现问题的步骤

1.  管理扩展 - 键盘快捷方式
2.  找到划词翻译，点击【激活扩展】快捷键输入框右边的X

### 预期行为
清除快捷键后，应当显示为空

### 实际行为
清除后显示了CTRL+Q，然而去别的网页里使用（已刷新页面）不起任何作用

**Comment by lmk123** [comment]
在 macos edge 96 上重现了。但是，【键盘快捷键】这个页面是浏览器自己的页面，也就是说，这是 edge 浏览器的 bug，不是划词翻译的，所以我解决不了 :joy:
