### ISSUE TITLE
内置PDF阅读器，划词翻译未能去除换行符的问题

### ISSUE THREAD

**Issue by null0728** [lmk123/crx-selection-translate#1264]
## 基本信息

划词翻译版本：v8.6.6
浏览器版本：Firefox 95.0
操作系统：Windows 10 教育版 21H1

## 重现问题的步骤

1.使用内置PDF阅读器打开PDF文件，PDF排版为有中缝的双列
2.使用划词翻译角标，翻译文本（使用原网页在线阅读时换行功能正常）

例如以下论文：
  原链接：https://www.sciencedirect.com/sdfe/reader/pii/S0021979703000651/pdf
  PDF文件：[1-s2.0-S0021979703000651-main.pdf](https://github.com/lmk123/crx-selection-translate/files/7660133/1-s2.0-S0021979703000651-main.pdf)
使用上面的网页打开的翻译是正常的，但是内置PDF阅读器不行。

### 预期行为
正常运行时为自动去除PDF中的换行符号，将上下两段话拼成一整句交给翻译器
### 实际行为
交给翻译器的文本如使用复制操作一样，是带有换行符号的

能不能让划词翻译内置PDF阅读器里复制文本时也去掉换行符？

**Comment by lmk123** [comment]
我明白你的意思了，你是先在划词翻译的内置 PDF 阅读器里复制了文本，然后粘贴进了划词翻译的文本框里进行翻译的是吗？如果是这样的话，那确实会出现这个问题。

我会做个改进，当从内置 PDF 阅读器里复制文本时，自动将换行符去掉。

P.S. 你可以直接在内置 PDF 阅读器里划词后点击翻译按钮，这种情况下，划词翻译会先把换行符去掉再翻译。

**Comment by lmk123** [comment]
不对，好像有问题 :joy:

看你的重现步骤，你是用划词翻译角标翻译的，但是这种方式，划词翻译是会自动去掉换行符的。我用你提供的 pdf 文件在 macos firefox 94.0.2 试过了，在内置 pdf 阅读器里翻译第一段话的时候是不会有换行符的。

只有当你从内置 pdf 阅读器里复制出来文本的时候，这段文本才是有换行符的。

**Comment by lmk123** [comment]
示例如下图：我划选了你提供的 pdf 文件里的第一段话，然后从文本框里把这段话复制了出来，你可以看到这段话粘贴进输入框之后是没有换行符的，因为当你用角标翻译的时候，划词翻译会自动把这段话里的换行符去掉。

![Kapture 2021-12-06 at 19 38 18](https://user-images.githubusercontent.com/5035625/144839703-195c6e82-7480-42c5-b9a6-c976262e08f4.gif)

**Comment by null0728** [comment]
可能是我的东西哪里没设置对？
我这边如下

![11111](https://user-images.githubusercontent.com/95615352/144847711-6036f942-12cb-416b-9ab4-35cad99eff7f.gif)

**Comment by null0728** [comment]
除了百度比较实诚把换行符放到了翻译出来的文本里之外，谷歌和腾讯都是各凭本事。可以看到谷歌翻译出的文本在换行的地方是一个空格，并且前后语义不连贯。
![22222](https://user-images.githubusercontent.com/95615352/144849750-64ce0976-df95-4ed0-a022-75a8d08cec35.gif)

有一种下个版本从改进了内置 PDF 阅读器里复制文本时，自动将换行符去掉的功能之后这个问题会自己消失的预感。

**Comment by lmk123** [comment]
嗯……这真的很神奇了，难道这真的跟操作系统有关系？:joy: 我有空了再试试看，如果我还是没法重现，那只能等我的 Windows 电脑到了之后看看是不是跟操作系统有关了。

**Comment by lmk123** [comment]
我把我的 firefox 更新到 95 了，又试了下是正常的：

<img width="508" alt="截屏" src="https://user-images.githubusercontent.com/5035625/145234629-286af7fd-34eb-486c-89e8-2a5095f8ee10.png">

**Comment by lmk123** [comment]
等等，我注意到了一个细节……

你划选的文本，单词和单词之间是没有空隙的。请仔细看我下面这张在 macOS Firefox 95、划词翻译 v8.6.5 的内置 PDF 阅读器里划的句子，`When`、`AIN`、`powder` 以及后面的单词之间很明显是看得见空隙的：

<img width="555" alt="截屏2021-12-08 下午11 30 51" src="https://user-images.githubusercontent.com/5035625/145236262-c5557849-ffc7-4087-8bb2-04005a9d3443.png">

但是你贴的图里是没有空隙的。理论上讲不应该出现这种不一致的现象，有以下几种可能：

- 你能再确认一下你用的划词翻译确实是 v8.6.6 吗？
- 也有可能真的是跟操作系统有关系？但不应该才对

**Comment by lmk123** [comment]
那我唯一能想到的情况就是也许真的跟操作系统有关了。。等我的 windows 电脑到了之后我再试试看

**Comment by lmk123** [comment]
我在测试版中修复了这个问题，能麻烦你测试一下有没有解决你的问题吗？如果你愿意的话，麻烦发邮件到 hi@hcfy.app ，我会把 v8.6.7.4 的测试包发给你
