### ISSUE TITLE
火狐浏览器右键菜单缺失全文翻译

### ISSUE THREAD

**Issue by HHPLow** [lmk123/crx-selection-translate#1266]
## 基本信息

划词翻译版本：8.6.6
浏览器版本：Firefox 95.0 (64 位)
操作系统：Windows 10 x64

## 重现问题的步骤

1. 打开特定网站，链接：https://docs.nvidia.com/drive/drive-os-5.2.0.0L/drive-os/index.html#page/DRIVE_OS_Linux_SDK_Development_Guide/intro_sdk.html
2. 在右侧正文页面点击鼠标右键
3. 选择划词翻译显示菜单

### 预期行为
菜单中应有全文翻译

### 实际行为
菜单中无全文翻译

**Comment by lmk123** [comment]
感谢，已在下个版本中修复，大约会在一个星期内发布
