### ISSUE TITLE
全文翻译范围不全

### ISSUE THREAD

**Issue by HHPLow** [lmk123/crx-selection-translate#1267]
## 基本信息

划词翻译版本：8.6.6
浏览器版本：Microsoft Edge 版本 96.0.1054.43 (官方内部版本) (64 位) && Firefox 95.0 (64 位)
操作系统：Windows 10 x64

## 重现问题的步骤

1. 打开特定网站，链接：https://docs.nvidia.com/drive/drive-os-5.2.0.0L/drive-os/index.html#page/DRIVE_OS_Linux_SDK_Development_Guide/intro_sdk.html
2. 使用快捷键或右键或扩展弹出窗口进行全文翻译

### 预期行为
网站所有内容均可以翻译

### 实际行为
仅有左侧目录及标题翻译，右侧正文没有翻译

**Comment by lmk123** [comment]
感谢反馈，这个问题跟 #1219 是同一个问题，会在未来的版本中修复
