### ISSUE TITLE
DeepL全文翻译不再是整段翻译而是逐词翻译

### ISSUE THREAD

**Issue by Louie-in-yr-AREA** [lmk123/crx-selection-translate#1269]
## 基本信息 在https://encyclopedia2.thefreedictionary.com/ 百科上全文翻译选项不再是整段翻译，而是逐词翻译

划词翻译版本：版本8.6.6
浏览器版本：版本 96.0.1054.43 (官方内部版本) (64 位)
操作系统：Windows 10

## 重现问题的步骤

1.在基本信息中的百科网站的点击全文翻译
2.出现的是逐词对应翻译（使用DeepL）

### 预期行为
![image](https://user-images.githubusercontent.com/95855674/145383513-41d8cd3e-835c-460e-a5b7-149e317e10b9.png)
逐段翻译

### 实际行为
![image](https://user-images.githubusercontent.com/95855674/145383453-a076a594-3071-4f16-82f5-d5c0f2f1f6bd.png)
逐词翻译影响体验

感谢运营和开发，如果有任何使用方法错误，请修正

**Comment by lmk123** [comment]
我手头暂时没有 windows 电脑，不过我在 macOS Edge 96 上用划词翻译 v8.6.6 试了一下你发给我的网址，是正常的整段翻译

但是你提供的这个网址好像跟你贴的截图的内容不一样，你能把你出现这个问题的网址发给我吗？

**Comment by Louie-in-yr-AREA** [comment]
Hi！
出现问题的网址：Wave-shaping circuits | Article about Wave-shaping circuits by The
Free Dictionary
<https://encyclopedia2.thefreedictionary.com/Wave-shaping+circuits>
[image: image.png]

mingkaili ***@***.***> 于2021年12月9日周四 11:08写道：

**Comment by lmk123** [comment]
我重现你的问题了，但这其实不算是一个“问题”……

全文翻译功能的文本分析算法最近一直没动过，做了改动的应该是这个网站。你应该注意到了，这篇文章里每个单词都是一个可以点击的链接——由于在大部分网站中，连续的多个链接一般用于导航栏、或者是多个并排显示的按钮，这种情况下，它们其实不是同一个段落的，所以我会把每个链接里的内容单独翻译。

如果我把多个连续的链接当成了一整个段落来翻译，那么在别的网站就不合适了。

目前想了想没有特别好的解决方案……

**Comment by lmk123** [comment]
已在下个版本 v8.6.7.6 当中做了改进，在此网站中将不会再逐词翻译。预计下周发布。
