### ISSUE TITLE
增加一个关闭独立翻译窗口的快捷键，或是改进esc键

### ISSUE THREAD

**Issue by Beyrea** [lmk123/crx-selection-translate#1270]
## 功能简介
增加一个关闭独立翻译窗口的快捷键，或是改进esc键
## 为什么你觉得需要（改进）这个功能？
当快捷键唤醒独立窗口后，光标默认已经在输入框，而目前的关闭键 esc 需要光标不在输入框而在窗口才能生效，所以关闭窗口时还需要鼠标去点击下窗口那边才能关闭。

因此，希望增加一个可以直接关闭独立翻译窗口的快捷键，无论他在窗口还是在输入框里，或是改进esc键。

另外，截图翻译似乎不能跨应用翻译？

**Comment by lmk123** [comment]
在文本框中按下 esc 不关闭的原因是用户可能只是为了关闭输入法。我可以尝试做一下改进，检测到没有输入法按下 esc 就关闭，但我不确定能否检测到。

如果不能检测到，那就改为在输入框中连续按下两次 esc 关闭。

> 另外，截图翻译似乎不能跨应用翻译？

是的，但是你可以用第三方工具（例如微信的截图快捷键 Alt + A）截图后，打开划词翻译的独立翻译窗口翻译。最好已经勾选了“自动翻译剪切板内的图片”，这样当打开独立翻译窗口时会自动翻译剪切板里的截图

**Comment by lmk123** [comment]
已在下个版本中做了改进，当文本框内没有输入法时也能用 esc 关闭独立窗口

**Comment by GH01** [comment]
所有输入法都能检测到？（我的老`极点`就没被检测到……）
还是`2次Esc`更好。

#1076 你还没整呢……

**Comment by lmk123** [comment]
@GH01  极点五笔输入法吗……我做改进的时候在 macOS 下测试了系统自带输入法和搜狗输入法，这么老的输入法我估计确实够呛。。

> #1076 你还没整呢……

是的还没有 :joy:
