### ISSUE TITLE
[重要bug]劫持window.addEventListener的重写导致的无法注册事件

### ISSUE THREAD

**Issue by zimengle** [lmk123/crx-selection-translate#1272]
hi,我们的页面使用了window.addEventListener('message',()=>{}) ,最近突然有很多用户反馈功能不正常,经过追查,发现划词拓展升级劫持了该api导致无法派发,还望尽快修复..半个月前应该是好的,升级导致的

这里是追查发现的劫持代码
![image](https://user-images.githubusercontent.com/5935585/145749453-1ea97f86-aa4e-4fc3-9dcd-635a1e516158.png)

## 基本信息

划词翻译版本：8.6.6
浏览器版本：chrome95
操作系统：macos

## 重现问题的步骤

1. 页面注册一个window.addEventListener('message',()=>{}) 无法触发

### 预期行为
1. 页面注册一个window.addEventListener('message',()=>{}) 无法触发
### 实际行为
1. 页面注册一个window.addEventListener('message',()=>{}) 能触发

**Comment by zimengle** [comment]
@lmk123 麻烦帮看下

**Comment by lmk123** [comment]
已经在 v8.6.7.3 中修复了此 bug，你可以去官网下载离线安装包试一下，希望你能反馈给我是否修复了这个问题！

**Comment by lmk123** [comment]
你也可以跟你们的用户说去官网下载 v8.6.7.3 的离线安装包

**Comment by lmk123** [comment]
此问题已在 v8.6.7.3 中修复，如果仍有问题，欢迎继续留言
