### ISSUE TITLE
内置谷歌翻译和直接在谷歌翻译网站上翻译出来的结果不一样

### ISSUE THREAD

**Issue by shenminghaikea** [lmk123/crx-selection-translate#1273]
## 基本信息

划词翻译版本：8.6.7.2
浏览器版本：chrome 96.0.4664.93
操作系统：win11

## 重现问题的步骤
原文：The sizeof operator gives the amount of storage, in bytes, required to store an object of the type of the operand
划词翻译(谷歌显示翻译)结果：尺寸操作员提供存储操作数类型所需的存储量，以字节为单位
谷歌翻译网页端翻译结果：sizeof 运算符给出存储操作数类型的对象所需的存储量（以字节为单位）

**Comment by lmk123** [comment]
已知问题：https://hcfy.app/docs/faq/#why-result-different

我目前正在着手改进这个问题，预计下个版本就能上线了。

**Comment by lmk123** [comment]
我已经发布 v8.6.8 改进了这个问题，你可以在设置中选择【速度慢、准确率高】的谷歌翻译来确保谷歌翻译的结果跟网站上是一致的。
