### ISSUE TITLE
在 Medium 文章情页选中文本后无法显示翻译弹窗

### ISSUE THREAD

**Issue by oodzchen** [lmk123/crx-selection-translate#1274]
## 基本信息

划词翻译版本：v8.6.7.3
浏览器版本：Firefox 94.0.2 
操作系统：Windows 10

## 重现问题的步骤

1.随便打开一篇 [medium.com](https://medium.com) 上的文章
2.选中文字，点击翻译按钮

### 预期行为
弹窗并显示翻译结果

### 实际行为
翻译按钮消失，翻译结果未出现

**Comment by lmk123** [comment]
感谢反馈，已在 火狐中重现此问题，将在近期修复

补充信息：

- 网址：https://engineering.udacity.com/why-you-should-be-doing-schema-validation-in-react-projects-ce3c4b1df02f
- Chrome 无此问题

**Comment by lmk123** [comment]
我确认了一下，发现这并不是划词翻译的问题，而是 medium 网站的问题：在划词之后，这个网站把拖蓝（也就是你划选的文本）给取消掉了。

请注意看下面的图片：

![Kapture 2021-12-15 at 18 03 03](https://user-images.githubusercontent.com/5035625/146166177-fda0008d-0cc1-465f-a2d4-2574447d919e.gif)

当点击翻译按钮时，划词翻译会去查找这个拖蓝里包含的文本，但由于它被 medium 网站给去掉了，所以查不到文本，也就没有显示翻译结果了。

在 Chrome 里，medium 是没有去掉拖蓝的，所以翻译按钮是正常的。我认为这是 medium 网站的一个 bug，也许他们会在以后修复。
