### ISSUE TITLE
允许划词翻译在后台持续运行

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#1276]
## 功能简介
关闭chrome之后，就没法通过全局快捷键呼出独立翻译窗口了

**Comment by lmk123** [comment]
相关文档：

- background 权限介绍 https://developer.chrome.com/docs/extensions/mv2/declare_permissions/
- background 权限可以被设为可选权限，见文档 https://developer.chrome.com/docs/extensions/reference/permissions/

**Comment by cesaryuan** [comment]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/35998162/588a794a-eb80-4489-86a6-d3538ab2b178)

![image](https://github.com/hcfyapp/crx-selection-translate/assets/35998162/2f2c0b94-d37a-495a-b544-9b1249f99b16)


只需要开启Chrome的这个选项就可以了吗，我这里开启这个选项并设置全局快捷键后Chrome还是不能后台运行诶。
