### ISSUE TITLE
声音不可用

### ISSUE THREAD

**Issue by epluguo** [lmk123/crx-selection-translate#128]
忽然发现声音不能用了。本来一直设置为自动朗读的，发现不行了，手动点一下朗读，也不行，没声音。
页面的其他元素是有声音的，比如说如果网页上面有歌曲的话，是会播放的，还是插件的翻译不能播放声音。
拓展里面设置，试过有道的、必应的都是没有声音
版本：
划词翻译 6.0.6
chrome  48.0.2564.109 m (64-bit)

**Comment by epluguo** [comment]
忽然发现百度的竟然有声音，是不是有道的api变更了或者地址错误了呢

**Comment by lmk123** [comment]
先尝试一下：

 1. 升级到最新版
 2. 确保你的电脑已翻墙

然后刚才我用有道翻译“ago”之后，英文是可以朗读的，但“前”这个汉字朗读不出来。

有时间我会深入调查一下的。

**Comment by lmk123** [comment]
这个问题跟 #131 应该有关联，因为谷歌朗读的接口地址改了。

划词翻译的朗读策略是，先尝试使用你使用的翻译接口来朗读，如果无法朗读就使用谷歌朗读。

现在谷歌朗读接口失效了，也就导致了你这个问题。
