### ISSUE TITLE
开启此插件会导致群晖web页面下的各种异常

### ISSUE THREAD

**Issue by windy0220** [lmk123/crx-selection-translate#1280]
划词翻译 v8.6.7.1
群晖系统版本  DSM 6.2.1-23824 Update 6
异常包含但不限于
- 系统状况，磁盘信息小组件无法正常显示
- docker 一直loading 无法加载成功
- 虚拟机界面一直loading

**Comment by lmk123** [comment]
此问题已在 v8.6.7.3 中修复，更新版本即可

**Comment by lmk123** [comment]
Chrome 和 Firefox 商店里已是最新版本 v8.6.7.4，你可以通过手动更新或者下载离线安装包的方式立刻更新到最新版本，详见文档：https://hcfy.app/docs/install/#offline

**Comment by windy0220** [comment]
v8.6.7.4 可以正常使用了。

**Comment by lmk123** [comment]
感谢反馈给我结果！如果之后还遇到问题欢迎反馈。
