### ISSUE TITLE
使用支付宝支付之后，依然不能使用会员功能

### ISSUE THREAD

**Issue by zhichucode** [lmk123/crx-selection-translate#1281]
## 基本信息

划词翻译版本：v8.6.7.4
浏览器版本：chrome
操作系统：windows 10

## 重现问题的步骤

1.我使用支付宝购买一个月会员3元的，扫码之后，（我发现旁边有个paypal的支付方式，于是点了一下），支付之后，我发现会员功能不能使用。而且想要再次支付也不行。
![image](https://user-images.githubusercontent.com/43780800/146898914-ab753a1a-9645-4f29-ba9b-3f9ed979879c.png)
![image](https://user-images.githubusercontent.com/43780800/146899001-bef69c3a-e7cf-4627-9468-67c4f9ab9aa2.png)

**Comment by zhichucode** [comment]
重启浏览器之后生效了，抱歉打扰。

**Comment by lmk123** [comment]
没关系，有任何问题请随时联系，不要客气
