### ISSUE TITLE
激活该扩展程序这个快捷键， 我已经这个快捷键取消了，也是生效的，但是我第二次再进去看的时候，那个快捷键还在

### ISSUE THREAD

**Issue by W-ChenAMG** [lmk123/crx-selection-translate#1284]
## 基本信息

划词翻译版本：v8.6.7.4
浏览器版本： 98.0.4758.9（正式版本）dev (x86_64)
操作系统：mac

## 重现问题的步骤

1.打开快捷键设置页面，将激活该扩展程序置为空，可以看到确实是空，快捷键也不生效了，然后关闭页面
2.再次打开快捷键设置页面，激活该扩展程序这个上面默认的 快捷键指令依然还在
3.

### 预期行为
我取消了快捷键，应该不管什么时候进去，都是取消的状态
### 实际行为
取消了快捷键，第二次进去设置页面，快捷键指令还在

**Comment by W-ChenAMG** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/37658262/147077244-4fb421c4-19a4-4131-9f0d-7c614cdf9265.png">

**Comment by lmk123** [comment]
Chrome 确实有这个问题，但这是 Chrome 自身的 bug，我没法解决。

我这边删除这个快捷键后，虽然快捷键仍然显示在那里，但实际上已经不生效了。

**Comment by W-ChenAMG** [comment]
确实是不影响，另外我看其他插件，设置不会出现这个问题。

**Comment by lmk123** [comment]
我猜你说的“其它插件”是不是没有像划词翻译这样设置了一个默认的快捷键？

这应该是 Chrome 浏览器在界面显示上的一个 bug，也就是清除了快捷键之后会把扩展程序预设的默认快捷键显示出来

**Comment by W-ChenAMG** [comment]
是的，了解了 ，谢谢

**Comment by lmk123** [comment]
不用谢，有任何问题欢迎反馈！

**Comment by MonicaQvQ** [comment]
这个问题我用Edge也有，我删别的原有的快捷键，删掉之后就不显示了，目前我用的扩展中，只有划词翻译和Proxy SwitchyOmega的“激活扩展”快捷键是删掉之后还显示的。

**Comment by lmk123** [comment]
edge 内核是 chrome，所以跟 chrome 有同样的 bug 我倒觉得不奇怪。关于 chrome 全局快捷键 bug 的详细描述见 https://hcfy.app/docs/faq/#edit-shortcut-key

**Comment by MonicaQvQ** [comment]
> Edge 内核是 chrome，所以跟 chrome 有同样的 bug 我倒觉得不奇怪。关于 chrome 全局快捷键 bug 的详细描述见 https://hcfy.app/docs/faq/#edit-shortcut-key

全局快捷键的问题我刚看过，我奇怪的是为什么有的扩展有这个问题，有的没有，出问题的快捷键还都是“激活扩展”快捷键，这个不是全局快捷键。

**Comment by lmk123** [comment]
这个帖子前面有提到过

>我猜你说的“其它插件”是不是没有像划词翻译这样设置了一个默认的快捷键？
>
>这应该是 Chrome 浏览器在界面显示上的一个 bug，也就是清除了快捷键之后会把扩展程序预设的默认快捷键显示出来

**Comment by MonicaQvQ** [comment]
> 这个帖子前面有提到过
> 
> > 我猜你说的“其它插件”是不是没有像划词翻译这样设置了一个默认的快捷键？
> > 这应该是 Chrome 浏览器在界面显示上的一个 bug，也就是清除了快捷键之后会把扩展程序预设的默认快捷键显示出来

其实不是的，因为我强迫症，所以所有扩展的预设快捷键我都是在安装的时候就会删掉的，我自己没有设置过，我删掉的其他扩展的也是在安装的时候默认自带的。

**Comment by MonicaQvQ** [comment]
> 这个帖子前面有提到过
> 
> > 我猜你说的“其它插件”是不是没有像划词翻译这样设置了一个默认的快捷键？
> > 这应该是 Chrome 浏览器在界面显示上的一个 bug，也就是清除了快捷键之后会把扩展程序预设的默认快捷键显示出来

我刚刚随便装了几个扩展试了一下，发现这个bug只发生在“激活扩展”快捷键上，别的预设快捷键删掉之后就不显示了，这个“激活扩展”快捷键删掉之后就一直在，不管它了。

**Comment by lmk123** [comment]
那就要综合多个案例来判断到底是什么条件组合才会触发 chrome 的这个 bug 了。

首先，我确认了下这个问题（清空划词翻译的“激活扩展”快捷键后，刷新一下页面快捷键仍然存在，但已失效）仍然存在。

然后，根据你的描述，这个 bug 有以下两个必要条件：

1. 必须是“激活扩展”这个快捷键
2. 必须给”激活扩展”预设了默认快捷键

然后你说目前只有划词翻译和 SwitchyOmega 有此问题，那就需要提供一下满足这两个必要条件但没有出现此问题的对照组来做对比，找出来其它必要条件了。

如果你想一探究竟，你可以提供几个没有此问题的扩展程序给我，我可以从代码层面来尝试分析一下它们跟划词翻译有没有什么不同点，能解决这个问题自然是最好的。

**Comment by MonicaQvQ** [comment]
我的意思是说，正如你所说，这个可能是chrome的bug，不是扩展的问题，所以解决不了。因为其他功能的快捷键都可以删除，只有这个功能的删掉之后还会显示，刚刚装了个GoFullPage - Full Page Screen Capture扩展，它也预设了”激活扩展”快捷键，我也是删不掉的。我目前装了20多个扩展，没有遇到满足这两个条件但是没出问题的扩展。
