### ISSUE TITLE
内置pdf窗口选择文本后，选中状态下拖动文本会报错

### ISSUE THREAD

**Issue by linkghm** [lmk123/crx-selection-translate#1286]
## 基本信息

划词翻译版本：8.6.7.4
浏览器版本：chrome 96.0.4664.110（正式版本） （64 位）
操作系统：arch linux

## 重现问题的步骤

1. 使用内置pdf窗口打开一个pdf文件（在线或者离线）
2. 选中部分文字，选中状态下，鼠标拖动向外拖动选中的文本，发生报错
![image](https://user-images.githubusercontent.com/25582521/147623743-d9e70063-0e9d-4bdc-ab83-bc3a347f8203.png)
![image](https://user-images.githubusercontent.com/25582521/147623805-90bdfe0b-1048-4784-9b81-f9bdfaa166f9.png)

3. 刷新页面会重新加载pdf

### 预期行为
选中状态下，拖动文字不会产生行为

### 实际行为
内置窗口报错

**Comment by linkghm** [comment]
firefox下测试没有问题

**Comment by linkghm** [comment]
windows下测试没有问题，可能是arch linux下的chrome出什么毛病了

**Comment by lmk123** [comment]
macos chrome 下测试也没问题，所以我也觉得跟操作系统有关系 😂

**Comment by linkghm** [comment]
> macos chrome 下测试也没问题，所以我也觉得跟操作系统有关系 joy

嗯嗯，辛苦了
