### ISSUE TITLE
翻译分割太碎了，没有识别为一个段落

### ISSUE THREAD

**Issue by wan230114** [lmk123/crx-selection-translate#1288]
对于部分网页的翻译不正常，表现为分割太碎了，没有识别为一个段落

如： <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5495127/> 的 Figure 5. 处

左图为本划词翻译插件，右图为沙拉查词的彩云小译网页翻译：   
![image](https://user-images.githubusercontent.com/33801625/147629696-1806c0df-68a4-4e34-bec4-dbd57e8013a0.png)

**Comment by lmk123** [comment]
感谢反馈，已重现此问题，将在最近的版本中修复。

补充信息：

划词翻译版本 v8.6.8
macos chrome 96

**Comment by lmk123** [comment]
已在下个版本 v8.6.9 中修复此问题，预计下周发布上线。

**Comment by wan230114** [comment]
感谢作者的积极回应与开发，这里还有一些网站也有类似情况，希望能更好的帮助您作为调试参考：  
- <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7213019/>
- <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5705222/>

**Comment by lmk123** [comment]
感谢提供新的案例，已确认 v8.6.9 版本在这些网址中不会出现分割段落的情况！
