### ISSUE TITLE
油管网页翻译存在滞留问题

### ISSUE THREAD

**Issue by cotagxrdhy** [lmk123/crx-selection-translate#1289]
划词翻译版本：划词翻译 v8.6.8
浏览器版本： Chrome 96.0.4664.110
操作系统：Win10

翻译一个页面后你打开油管其他页面也会存在之前翻译的内容.

**Comment by lmk123** [comment]
我猜测你说的“滞留”是指这种情况：在 youtube 开启了全文翻译之后，点了一下其它视频的链接，然后发现网页全文翻译没有关闭、之前翻译的内容仍然留在网页上。

这是符合预期的，因为 youtube 对网站做了“无刷新”处理，也就是你点了其它视频的时候，整个网页并没有刷新，仅仅只是将网页内容替换掉了。如果你手动刷新一下网页，你就会发现不会有“滞留”了。

如果不是我猜测的这种情况，那么需要你按照重现步骤详细阐述一下你指的“滞留”具体是什么问题。

**Comment by cotagxrdhy** [comment]
原来是这样啊,明白了
