### ISSUE TITLE
从外部编辑器拖放文字过来，应该是 复制，而不是 移动

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#1292]
## 功能简介
从外部编辑器拖放文字过来，应该是 复制（鼠标指针有+号），而不是 移动。

## 为什么你觉得需要（改进）这个功能？
拖放不应改变外部编辑器中的内容。
目前，即便用 Ctrl+拖放 也导致 移动。

**Comment by lmk123** [comment]
将在下个版本中修复
