### ISSUE TITLE
迪迦

### ISSUE THREAD

**Issue by glkappe** [lmk123/crx-selection-translate#1299]
![image](https://user-images.githubusercontent.com/21033020/148629783-5fbadcc4-93b5-419d-a4ec-f7b87fa189ea.png)

**Comment by glkappe** [comment]
google.com 翻译

**Comment by lmk123** [comment]
我用谷歌翻译将“迪迦”从中文翻译成英文，得到的结果都是“Diga”。

如果你指的是“翟加”，那是因为谷歌翻译自己就将它翻译成了“Zhai Jia”：https://translate.google.cn/?sl=zh-CN&tl=en&text=%E7%BF%9F%E5%8A%A0&op=translate
