### ISSUE TITLE
建议添加关闭悬浮窗快捷键

### ISSUE THREAD

**Issue by angela0** [lmk123/crx-selection-translate#130]
当使用Alt+A来打开翻译悬浮窗之后，只能使用鼠标点击其他区域进行关闭，这对键盘依赖重症患者来说不太方便。建议添加一个关闭悬浮窗的快捷键

**Comment by lmk123** [comment]
这个想法不错，你觉得 Esc 键怎么样？

**Comment by angela0** [comment]
嗯，可以，虽然比较远，但是蛮符合很多人的习惯

**Comment by lynnjadecn** [comment]
How about再次按下`Alt+A`键，则取消悬浮？

**Comment by lmk123** [comment]
@lynnjadecn 我不太喜欢这种方式，一个快捷键不应该有两种行为
