### ISSUE TITLE
在中英双语网页中全文翻译目标语言手动切换

### ISSUE THREAD

**Issue by jdjxk** [lmk123/crx-selection-translate#1301]
## 功能简介
网页全文翻译的目标语言手动切换功能
## 为什么你觉得需要（改进）这个功能？
在中英双语混杂的网页中，网页全文翻译倾向于将中文翻译成英文，是否能增加手动切换目标语言的选项？

**Comment by lmk123** [comment]
感谢反馈，此项改进已在开发计划当中 #943
