### ISSUE TITLE
页面无法翻译

### ISSUE THREAD

**Issue by wisecrick** [lmk123/crx-selection-translate#1303]
## 基本信息
https://telegra.ph/Tech-That-Will-Change-Your-Life-in-2022-01-16

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
不知道是不是我网络的问题，这个网址我无论挂不挂梯子都打不开……我过一会儿再试试看

**Comment by wisecrick** [comment]
现在能看到吗？

**Comment by lmk123** [comment]
看到了，页面确实没有翻译，只有网页标题被翻译了。

**Comment by lmk123** [comment]
这个网站对它的文章内容做了保护，导致划词翻译无法进行翻译。继续研究如何绕过这种保护有点花时间，所以我先放着了。

或者，你可以在 Chrome 的网站设置禁止 telegra.ph 运行 JavaScript，再开启网页全文翻译就能正常显示翻译结果了，如图：

<img width="981" alt="截屏2022-02-19 下午6 05 00" src="https://user-images.githubusercontent.com/5035625/154796515-74c5b194-5348-4bc5-ba78-a6c4c13e8d69.png">

**Comment by wisecrick** [comment]
关闭了以后，划词翻译右下角的弹出窗口就不会自动缩回去了

**Comment by lmk123** [comment]
确实会这样，我试试看能不能改进一下

**Comment by lmk123** [comment]
你好 @wisecrick ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
