### ISSUE TITLE
Arm设备上的兼容性报告与支援请求

### ISSUE THREAD

**Issue by NexusKMT** [lmk123/crx-selection-translate#1304]
## 基本信息

划词翻译版本：V8.6.10
浏览器版本：Kiwi Browser Chromium 98.0.4758.51
操作系统：Android 7.1.2

## 重现问题的步骤

1.于谷歌扩展商店中安装本插件
2.可正常弹出安全确认窗口
3.等待安装中闪退，重复多次情况仍一致

### 预期行为
于Arm设备上使用本插件（在Nexus 9与Pixel 3Xl上均是无法正常安装，但在同是Arm架构的Samsung Chromebook Plus上运行完美）
### 实际行为
安装中闪退

**Comment by lmk123** [comment]
我手头没有安卓设备，再加上有别的优先级更高的事情，所以我只能先放着 :joy:

后续进展会更新到 #1102
