### ISSUE TITLE
翻译后无法朗读

### ISSUE THREAD

**Issue by 302743375** [lmk123/crx-selection-translate#1305]
## 基本信息

划词翻译版本：8.6.10
浏览器版本：chrome 96.0.4664.110
操作系统：win10

## 重现问题的步骤

1.划词翻译后点击朗读
2.提示 朗读时出错：系统语音朗读超时。Chrome 浏览器提供的网络语音需要连接外网才能使用。你也可以前往设置中选择本地语音朗读英语。
3.设置中选择始终适用系统语音后仍然提示出错

**Comment by lmk123** [comment]
在win10里，由于操作系统没有提供本地语音，所以 chrome 是用它自带的网络语音来朗读的，也就是说，你需要在挂梯子之后才能朗读。

或者，你可以用 edge 浏览器，它自带的网络语音是不用挂梯子的。
