### ISSUE TITLE
疑似更换IP就会自动登出？

### ISSUE THREAD

**Issue by octigha** [lmk123/crx-selection-translate#1306]
## 基本信息

划词翻译版本：最新
浏览器版本：Chrome最新
操作系统：Mac最新

## 重现问题的步骤

1.更换IP
2.
3.

### 预期行为

没有登出

### 实际行为

需要重新登录

网络不稳，换个位置就登出一次重新登录，太麻烦了，一天可能换好几次，要不断的重新登录。能不能改一下这个机制？

**Comment by lmk123** [comment]
划词翻译没有对 IP 做过限制，我刚才也试过了，换 IP 不会登出。

划词翻译对账号的唯一限制是最多只能同时登录 4 个浏览器，当你登录第 5 个浏览器的时候，第一次登录的浏览器会被登出。

我猜测是不是你有什么扩展会删掉浏览器里的 cookie？

**Comment by octigha** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete

装了这个，Mac Chrome在启用扩展的情况下，同步设置就会自动登出。**但是已经加了白名单**

Chrome启用扩展，添加白名单
打开火狐，随便改个设置，同步设置
切回Chrome同步设置，自动登出
火狐启用扩展没有出现这个情况

之前的划词版本没有这个情况

**Comment by lmk123** [comment]
划词翻译的登录机制从来没有变过。

登录的 cookie 是放在 `hs-api.limingkai.cn` 下的，你可以把这个域名加入你这个扩展的白名单。

**Comment by octigha** [comment]
👌解决了
