### ISSUE TITLE
触发划词翻译导致网页文档大小变化

### ISSUE THREAD

**Issue by Elio-zhy** [lmk123/crx-selection-translate#1307]
## 基本信息

划词翻译版本：v8.6.8
浏览器版本：Version 97.0.1072.62 (Official build) (64-bit)
操作系统：Windows 10 Pro 21H2

## 重现问题的步骤

1. 打开划词翻译插件
2. 打开带有输入框的网页，如[google](https://www.google.com)
3. 在输入框中输入大量文本
4. 选中输入框中的部分文本触发划词翻译插件

### 预期行为
出现划词翻译浮窗

### 实际行为
出现划词翻译浮窗，同时整个网页文档的大小发生变化，疑似输入框中的文本内容总体大小被计入body大小，导致超出窗口边界，表现为显示了滚动条

### 补充
经过测试，仅在开启该插件时会触发上述问题。

![Animation](https://user-images.githubusercontent.com/30508272/150107464-8f3f36cf-300d-48e0-86ab-d7583e33b2cf.gif)

**Comment by lmk123** [comment]
我使用划词翻译 v8.6.10、macOS Chrome 97.0.4692.71（正式版本） (arm64) 无法在谷歌搜索中重现此问题。

你可以把所有其它扩展都关闭了之后再试试看

**Comment by Elio-zhy** [comment]
关闭其他扩展仍然有这个问题
调试发现选中文本后，插件在document底部添加了一个div，内容是input的value，长度超过了页面宽度
![image](https://user-images.githubusercontent.com/30508272/150117836-60bf1180-214a-4f6e-904d-0e91568e8168.png)

**Comment by lmk123** [comment]
划词翻译确实会插入一个 div，但同时划词翻译会读取文本框的 [getBoundingClientRect()](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/getBoundingClientRect) 确保了这个 div 的大小是跟被划词的文本框的大小是一样的（见最下面的图）。

理论上讲，在文本框没有被 `display: none` 的情况下，这个方法都是能正常读出文本框的位置和大小的，但是从你的截图来看似乎没有读取出宽度和高度。

目前来看我也不知道是什么原因造成的 :joy:

附图：

<img width="871" alt="截屏2022-01-19 下午9 10 55" src="https://user-images.githubusercontent.com/5035625/150137666-914e097a-c667-4c00-bef5-222d463df601.png">

**Comment by lmk123** [comment]
我明白你截图里为什么这么长了，你把鼠标放到文本（也就是 `#text`）上那 Devtools 确实会在网页上显示很长的一条蓝色框，但如果你把鼠标移动到 `div` 上就会只显示跟文本框差不多宽度的蓝色框了，见下图：

<img width="288" alt="截屏2022-01-19 下午9 20 46" src="https://user-images.githubusercontent.com/5035625/150138990-6a222d5f-25cb-424f-86b1-1c05b314b429.png">

**Comment by lmk123** [comment]
总之还是无法重现 :joy:

**Comment by Elio-zhy** [comment]
1. 我在windows下的edge和chrome均复现了该问题
2. 在这个新增的div中添加样式overflow: hidden，滚动条就消失了，所以应该是这个div导致的。
![Animation](https://user-images.githubusercontent.com/30508272/150278642-05020b6e-a0f0-4681-8c95-1ccbbf2e6c03.gif)

**Comment by lmk123** [comment]
你的这个问题确实是这个 div 引起的，但是在我 macOS 的 Chrome 上没法重现。虽然不大可能，但目前看来只能是跟操作系统有关系了，等我找个 Windows 系统试一下吧

**Comment by lmk123** [comment]
补充信息：

我在 macOS Chrome 谷歌搜索的 input div 有 `width: 438px` 的宽度限制，不会导致整个网页被撑开出横向滚动条，见下图。

用户在 Windows Chrome 谷歌搜索的 input div 也有 `width: 438px` 的宽度限制，但是却会导致整个网页宽度被撑开，加上 `overflow: hidden` 后恢复正常；

<img width="1326" alt="截屏2022-01-20 下午1 47 38" src="https://user-images.githubusercontent.com/5035625/150281041-e59a5d5f-79fc-47aa-84a6-3213cf37a27c.png">

**Comment by lmk123** [comment]
这个问题我在 #1319 中重现了，预计下个版本会修复。后续进展可以关注 #1319
