### ISSUE TITLE
无法使用自定义翻译源进行网页全文翻译

### ISSUE THREAD

**Issue by lrjia** [lmk123/crx-selection-translate#1311]
## 基本信息

划词翻译版本：v8.6.10
浏览器版本：chrome版本 97.0.4692.99（正式版本） (arm64)
操作系统：macOS 12.0.1 m1

## 重现问题的步骤

1. 添加自定义翻译源
2. 网页全文翻译中找不到自定义翻译源

### 预期行为
使用自定义翻译源进行网页全文翻译

### 实际行为
网页全文翻译中找不到自定义翻译源选项

## 其他
可以正常使用自定义翻译源进行划词翻译

**Comment by lmk123** [comment]
已确认，这是一个 bug :joy: 在某次版本更新之后忘记加进去了
