### ISSUE TITLE
能否自动监听粘贴板，并翻译？

### ISSUE THREAD

**Issue by DogeFlow** [lmk123/crx-selection-translate#1312]
如题，希望自动监听粘贴板，当粘贴板中的内容变化时，自动翻译

**Comment by lmk123** [comment]
不能，Chrome 浏览器不允许扩展程序持续监听剪切板，我尝试过。

未来我打算给划词翻译开发一个桌面客户端，应该是可以做到持续监听剪切板。 

https://github.com/lmk123/crx-selection-translate/issues/992

**Comment by lmk123** [comment]
下个版本 v10.3.0 给独立翻译窗口添加了一个新的选项“持续监听剪切板”，开启后，一旦剪切板内容变化，独立窗口就会自动翻译
