### ISSUE TITLE
请教一下st-span st-div st-footer组件在哪里定义的

### ISSUE THREAD

**Issue by jiangxiaoqiang** [lmk123/crx-selection-translate#1313]
你好，我写了一个翻译的接口想加入到划词翻译里，但是我阅读了源码在template里发现有st-span st-div st-footer标签，但是在代码里没有找到相关组件的定义。请教一下st-span st-div st-footer组件的定义在哪里啊？

**Comment by lmk123** [comment]
这些不是组件，就只是自定义元素，所以没有定义。
