### ISSUE TITLE
仅仅是一个小疑惑……为什么划词翻译扩展会和edge的“启动增强”冲突？

### ISSUE THREAD

**Issue by Genius-Lv** [lmk123/crx-selection-translate#1314]
![启动增强](https://cdn.jsdelivr.net/gh/Genius-Lv/image/garage1/2022-01-29_193543.png)

如图所示。
我在划词翻译扩展选项中好像相关的设置可以关闭这个提示的🤣
希望作者大大解答一下，谢谢😘

**Comment by lmk123** [comment]
你的图挂了，但是我搜了一下启动增强，其实它跟划词翻译的“让划词翻译在后台运行”是同一个功能，也就是打开电脑或者关闭所有edge浏览器窗口后，edge实际上还是在后台运行

所以我猜你应该是开启了划词翻译的“让划词翻译在后台运行”之后会被edge提示冲突？你可以关了试试。你开了启动增强后就不需要开启这个了。

如果不是因为这个，欢迎继续留言

新年快乐！
