### ISSUE TITLE
Edge浏览器密码问题

### ISSUE THREAD

**Issue by hsichien** [lmk123/crx-selection-translate#1318]
## 基本信息

划词翻译版本： v8.6.10
浏览器版本：版本 98.0.1108.43 (官方内部版本) (64 位)
操作系统：Windows11 企业版

## 重现问题的步骤

在选择edge已保存密码的情况下,在密码框中选中密码会显示出密码的翻译或原文,如图
![image](https://user-images.githubusercontent.com/78013146/153234902-641156a2-50f2-4613-9601-49a4b8598c98.png)
而手动输入密码的情况下一切正常,没有行为
![image](https://user-images.githubusercontent.com/78013146/153234536-39724748-a778-4227-9efa-38c90d5ddf96.png)
  **Edge中所有网址都复现,暂未测试过其他浏览器**
### 预期行为
无任何反应
### 实际行为
弹出翻译框

**Comment by lmk123** [comment]
~~我在 edge 98 中无法重现这个问题。~~

**Comment by lmk123** [comment]
抱歉，我重现这个问题了。

我看看要怎么修复

**Comment by lmk123** [comment]
补充详细步骤：

1. 找一个有密码输入框的网站，例如 https://music.migu.cn/v3/music/player/audio 点登录并切换到到密码登录
2. 随便输入一个邮箱和密码，然后点击浏览器地址栏右侧的钥匙图标，将刚才随便输入的邮箱和密码保存到浏览器的密码管理器中
3. 刷新网页，然后点击一下密码输入框，浏览器就会弹出刚才保存的密码的提示。点击这个提示，浏览器会将邮箱和密码自动填进去
4. 划选密码框里圆点

按照预期，密码是由圆点组成的，不会触发划词，但实际情况是，翻译按钮弹了出来且点击后翻译的原文是密码内容。

手动输入的密码在划词时是不会触发划词的，这就是符合预期的。
