### ISSUE TITLE
翻译速度有点慢，用的是有道，能否提高速度呢？

### ISSUE THREAD

**Issue by scoful** [lmk123/crx-selection-translate#132]
翻译速度有点慢，用的是有道，能否提高速度呢？

**Comment by lmk123** [comment]
我使用的是有道的翻译接口，所以速度不是由划词翻译来决定、而是由你自身的网络情况、有道翻译服务器的响应时间来决定的。

一般情况下，翻译慢都是因为你开启了全局翻墙导致国内翻译接口也走了一圈国外的代理。

**Comment by lmk123** [comment]
没有响应，假设已解决。

**Comment by scoful** [comment]
sorry，估摸找到原因了，你这个插件太火了，太多人用，有道提供的api有响应的限制，导致有时候不返回结果。

**Comment by lmk123** [comment]
是有这个问题，我正想办法解决中。#138

**Comment by gecece** [comment]
Chrome设置了全局代理之后，有道就不能用了（网络错误，请检查网络设置，然后重试）。你上面说 

> 导致国内翻译接口也走了一圈国外的代理

同样是全局代理，为什么其他的翻译（包括百度）都能返回结果，而有道不能呢？ 是代码中等待时间设的太短了吗？
而且需要代理翻墙的一般也是英文网站，我也很喜欢有道的音标，没办法完善一下吗？
