### ISSUE TITLE
口音设置（如自动）同系统语音设置不是同一个语言时，系统语音不生效

### ISSUE THREAD

**Issue by Hinlavic** [lmk123/crx-selection-translate#1327]
## 基本信息

划词翻译版本： v8.6.10
浏览器版本：EDGE 98.0.1108.56 (官方内部版本) (64 位)
操作系统：WIN11

## 重现问题的步骤

1. “何时选择系统语音”设为“始终使用系统语音朗读”；
2. 默认“选择口音”设置为“自动”，“选择系统语音”设为现有任意值；
3. 选择任意英文段落，朗读。

### 预期行为
英语发音同所选择的系统语音一致。

### 实际行为
英语发音始终不变，为澳大利亚英语的NATASHA发音；将“选择口音”英语改为“英语（美国）”后恢复正常。

**Comment by lmk123** [comment]
这不是 bug。

## TL;DR

当将口音设置为“自动”时，操作系统会自行决定用什么口音来朗读英文，在你这里也就是操作系统用了“英语（澳大利亚）”来朗读英文。

## 详细解释

举个例子，对于英文，我的电脑支持用“英语（美国）”和“英语（澳大利亚）”朗读，这俩也就是划词翻译所说的**口音**。

当播放“英语（美国）”时，macOS 既支持用男声播放，也支持用女声播放，这俩在 macOS 里分别叫“Alex - 本地语音” 和 "Fred - 本地语音"，也就是划词翻译所说的**系统语音**；

那么，当划词翻译让 macOS 朗读一段英文时，划词翻译首先会根据你的口音设置来决定是用“英语（美国）”和“英语（澳大利亚）”来朗读这段英文。这里假设你给“英语”设置的口音是“英语（美国）”，那么接下来，划词翻译会再根据你给“英语（美国）”设置的系统语音来决定是用男声 Alex 还是女声 Fred 来朗读。

当你将“英语”的口音设置为“自动”时，操作系统会自行决定是用“英语（美国）”还是“英语（澳大利亚）”来朗读这段英文。从你的描述来看，你的操作系统选择了用“英语（澳大利亚）”来朗读英文，这个决定是由操作系统自行作出的，可能跟你的操作系统的时区或者语言有关。

只有当你明确的将英语的口音设置为了“英语（美国）”时，你的操作系统才会始终用“英语（美国）”来朗读英文，而不会自行决定用什么口音来朗读英文。

**Comment by lmk123** [comment]
解释一下口音和系统语音的关系：口音是针对文字的语种的，例如英文可以选择用“英语（美国）”和“英语（澳大利亚）”来朗读，而系统语音是针对口音的，例如“英语（美国）”可以用“张三”和“李四”来朗读，“英语（澳大利亚）”可以用“王五”和“赵六”来朗读。

当然，也会出现“张三”既能朗读“英语（美国）”也能朗读“英语（澳大利亚）”的情况。

这个递进关系是：先确定文字的语种（比如英文）、然后确定要用哪个口音（比如英语（美国））、最后确定要用哪个系统语音（比如张三）；如果你给英文的口音设置的是英语（澳大利亚），那么划词翻译就会去读取英语（澳大利亚）的系统语音设置。

在你这里，虽然你给英语（美国）设置了系统语音，但是你的操作系统是用英语（澳大利亚）来朗读英文的，所以划词翻译不会去读英语（美国）的系统语音设置，而是去读了英语（澳大利亚）的系统语音设置

**Comment by lmk123** [comment]
写了一大段可能看着很绕，有问题可以继续留言

**Comment by lmk123** [comment]
我决定把这段说明整理一下放到设置页里，帮助其它用户理解 :joy:
