### ISSUE TITLE
Deel翻译不可用

### ISSUE THREAD

**Issue by maple5233** [lmk123/crx-selection-translate#1332]
## 基本信息

划词翻译版本：8.6.10
浏览器版本：Chrome 版本 98.0.4758.102（正式版本） (x86_64)
操作系统：MacOS

## 重现问题的步骤

1. 点击呼出背景页
2. 键入任意内容等待翻译

### 预期行为
Deepl翻译结果正常展示

### 实际行为
百度、谷歌翻译结果正常展示，但是Deepl翻译结果持续loading态

**Comment by lmk123** [comment]
已确认有此问题，我会尽快解决。

**Comment by lmk123** [comment]
这不是一个 bug，是因为 DeepL 出现了访问次数过多的情况（也就是文档 https://hcfy.app/docs/faq/#deepl-only 里所说的第二种情况）

我试了下切换了下 ip 就没问题了，如果仍有问题，欢迎继续留言。
