### ISSUE TITLE
购买了月会员，视频翻译还是提示要我开会员买积分之类的

### ISSUE THREAD

**Issue by mwanlyc** [lmk123/crx-selection-translate#1337]
## 基本信息

划词翻译版本：8.6.9
浏览器版本：火狐 97.0.2 (64 位)
操作系统：window 10

## 重现问题的步骤

1. 购买月会员
2. 关闭浏览器重新打开，打开视频页面，点击视频翻译，提示：
腾讯云实时语音识别需要消耗翻译积分才能使用，请前往【服务申请】购买翻译积分。<a href="https://hcfy.app/docs/faq/#why-apply" target="_blank" rel="noopener noreferrer">为什么腾讯云实时语音识别需要自行申请或购买翻译积分使用？</a>

**Comment by lmk123** [comment]
音视频功能需要用到腾讯云的实时语音识别接口将音频转为文字，这是一项第三方服务，并不包含在划词翻译的会员之中。划词翻译会员描述中的“音视频翻译   5 次 / 天”指的是如果不是会员，那么即使你有翻译积分，一天也只能开启五次音视频功能。

购买会员的时候也有明显提示，会员与第三方服务是不相关的，且无论是否是会员，都可以购买翻译积分。

如果有其他疑问，欢迎继续留言。

<img width="634" alt="截屏2022-03-06 下午10 01 48" src="https://user-images.githubusercontent.com/5035625/156926569-b5ffb0f2-fc7a-4b39-be33-2fe982b0aefa.png">

**Comment by lmk123** [comment]
也许是我没说明清楚让你产生了误会，我可以为你退款。
