### ISSUE TITLE
deepl一栏显示：翻译时出错了，错误消息：找不到清空文本的按钮

### ISSUE THREAD

**Issue by Passerby1011** [lmk123/crx-selection-translate#1338]
## 基本信息

划词翻译版本：划词翻译 v8.6.10
浏览器版本：Yandex 22.1.5.741 beta
操作系统：WIN 11 22000.493

## 重现问题的步骤

1.划词翻译
2.deepl一栏显示：翻译时出错了，错误消息：找不到清空文本的按钮。
![image](https://user-images.githubusercontent.com/63802758/157060611-72e59532-9a84-4e1e-b35d-39134202bb1d.png)

3.我确定没有修改[划词翻译的权限范围，是今天突然不能用了
4.可以正常打开 https://deepl.com/translator网页并且使用
![image](https://user-images.githubusercontent.com/63802758/157060875-270f4d18-5eb4-4a98-af66-0592afdb25cc.png)
![image](https://user-images.githubusercontent.com/63802758/157061115-b8d8a18a-2c40-4805-9a24-cb5c3030a8ca.png)

### 预期行为
deepl正常翻译
### 实际行为
显示：翻译时出错了，错误消息：找不到清空文本的按钮。

**Comment by SouthWindLoki** [comment]
今天用的时候也是这个情况

**Comment by qxt063** [comment]
同，昨天9点左右是正常的，现在不行了

**Comment by lmk123** [comment]
正在修复中，完成后会立刻发布一个新版本

**Comment by lmk123** [comment]
已修复，解决方案见公告

https://hcfy.app/blog/2022/03/08/deepl-error
