### ISSUE TITLE
面板翻译服务收起后可后台翻译

### ISSUE THREAD

**Issue by cotagxrdhy** [lmk123/crx-selection-translate#1340]
## 功能简介
面板翻译服务收起后可实现后台翻译
## 为什么你觉得需要（改进）这个功能？
比如我使用了多个翻译服务，正常的时候只看一个就行了，其他翻译会收起来。
当我觉得翻译的不太明白的时候才会展开其他翻译进行对比，这样基本上也能够理解。
但现在收起来的翻译展开之后才会开始翻译（尤其是DeepL的翻译会很慢），如果能实现收起能后台翻译的话会节约一些时间。
![image](https://user-images.githubusercontent.com/80959178/157252560-439e9ee1-c4d7-4406-8fc8-87e46ad9bc79.png)

**Comment by lmk123** [comment]
这是刻意为之，因为大部分翻译服务都是需要消耗字符数或翻译积分使用的，如果在收起的情况下也在消耗的话太不划算了。

建议你申请一个 DeepL 密钥来使用 DeepL，只需要 2 秒就能查到结果。
