### ISSUE TITLE
复制翻译后的网页内容在飞书文档无法粘贴

### ISSUE THREAD

**Issue by zhilincom** [lmk123/crx-selection-translate#1341]
## 基本信息
排查是自定义标签`hcfy-result`的问题，飞书文档无法处理自定义标签，希望能把自定义标签换成`<span></span>`标签的方式。

划词翻译版本：v8.6.10
浏览器版本：Chrome 99.0.4844.51
操作系统：win10

## 重现问题的步骤

1.打开一个英文网页，如 https://docs.mongodb.com/drivers/java/sync/current/quick-start/
2.使用划词翻译的网页全文翻译
3.复制翻译后的中文内容
4.粘贴进[飞书文档](https://docs.bytedance.net/)

### 预期行为
成功粘贴翻译后的网页富文本内容到飞书文档。
### 实际行为
飞书文档里一片空白。

**Comment by lmk123** [comment]
不能把自定义标签换成 span，因为大部分网站会给这些标签添加样式。

建议在粘贴时不要带格式，一般是 `Ctrl + Shift + V`，这种粘贴只会把文本内容粘贴进去，不会带有 html 标签。
