### ISSUE TITLE
必应词典的接口配置有问题

### ISSUE THREAD

**Issue by oodzchen** [lmk123/crx-selection-translate#1344]
## 基本信息

划词翻译版本：v8.7.1
浏览器版本：Firefox 98.0 (64-bit)
操作系统：Ubuntu 20.04 

## 重现问题的步骤

1. 用 Firefox 随便打开一个英文页面
2. 划词翻译插件勾选【必应词典】
3. 随便翻译一个英文单词，查看必应词典的翻译结果

### 预期行为
正确显示翻译结果

### 实际行为
提示“无翻译结果。如果你使用了代理软件，请关闭代理或将必应词典加入直连名单后重试..”

我已经在代理软件里面配置过白名单了，结果还是出现以上提示。

### 调试
我自己尝试打开了插件调试工具，结果看到必应的翻译接口响应数据有问题，Respnse 栏显示如下：
![Screenshot from 2022-03-12 22-16-37](https://user-images.githubusercontent.com/9650699/158021901-46974b8b-d7b1-432e-9494-ede4277dfb7e.png)

我看到请求接口地址是 `https://cn.bing.com/dict/search?q=discussion`，目测这个接口现在失效了。

**Comment by lmk123** [comment]
麻烦再检查一下你的白名单配置。

<img width="303" alt="截屏2022-03-12 下午10 29 34" src="https://user-images.githubusercontent.com/5035625/158022025-82199e57-600b-447f-81db-b47e50bec668.png">
