### ISSUE TITLE
希望能增加代理功能

### ISSUE THREAD

**Issue by MomentDerek** [lmk123/crx-selection-translate#1345]
## 为什么你觉得需要（改进）这个功能？
访问deepL时必须要挂tuntap驱动级代理才能让插件走代理进行翻译，但是那样太繁重，希望只有这个插件走代理，或者能和网页一起走SwitchyOmega插件的代理
能否加入类似其他软件的代理设置的选项？类似这种
![image](https://user-images.githubusercontent.com/40252940/158113889-f8fd1ac4-e588-4013-814a-4420193fd015.png)

**Comment by MomentDerek** [comment]
哪怕是能和浏览器的系统代理走一起也行

**Comment by lmk123** [comment]
我这边用 clash for windows 是能让划词翻译里的 deepl 通过代理访问的，浏览器的代理设置或者 switchyOmega 我不太熟。

如果要让划词翻译访问代理设置的话需要加个权限，但大部分用户都会觉得不能接受，因为这不应该是由划词翻译来做的事情。

**Comment by MomentDerek** [comment]
clash for windows 要开tun模式吧，不可以在网络请求的时候加入代理么，就是指不修改系统的代理，纯粹是插件内部走代理

**Comment by MomentDerek** [comment]
就是指让插件内部在进行http的请求走sock5代理或者http代理，不是修改或者访问本地的代理设置，而是在插件里面设置插件自己的代理

**Comment by MomentDerek** [comment]
好像又好了，可能刚刚是系统的问题，我重启了一次就正常代理了（但还是有点想要插件内设置代理）

**Comment by MomentDerek** [comment]
翻了一下v6的代码，是通过translation库来实现翻译的么 :joy: 那确实是没办法，这个库好像没有代理请求的选项

**Comment by lmk123** [comment]
这个库就是我写的 :joy: 扩展程序的代理跟这个库没关系，需要单独的扩展程序  api 来完成 https://developer.chrome.com/docs/extensions/reference/proxy/

但是用了这个 api 需要新增权限，加了权限就会导致所有用户的划词翻译被 chrome 禁用，然后提示用户划词翻译新增了权限，是否要继续使用。

我感觉有点太麻烦了。。

**Comment by MomentDerek** [comment]
我翻看了一下这个扩展程序代理api ，不知道是不是我理解错了😢，感觉上这个api指的是修改chrome的代理设置的，但能否使用nodejs的库来实现😁不过不可以就算了……还没写过chrome扩展确实不大清楚，打扰大佬了

目前来看，浏览器上的switchyOmega已经可以接管整个浏览器的代理设置，确实不需要系统级的代理，上次不行应该是属于某个环节的bug，目前使用正常（在我的理解里switchyOmega这种插件才是使用了proxy api接口的😂，直接接手整个浏览器的代理）

摸了一下下，打扰大佬了

**Comment by lmk123** [comment]
没事，我很乐意分享我知道的事情。

这个 api 确实是用来修改 Chrome 浏览器的代理设置的，SwitchyOmega 就是用这个 api 来实现的，这一点你理解的是正确的。

但是，扩展程序的运行环境其实是网页 js + Chrome 扩展 api，而网页里的 js 是没法通过一个代理来发起网络请求的（见 [stackoverflow - Making an XMLHttpRequest through a proxy?](https://stackoverflow.com/questions/43895039/making-an-xmlhttprequest-through-a-proxy)），也就是说，Chrome 浏览器里的所有网络请求都会经过 Chrome 浏览器的代理设置。

基于这一点，扩展程序是没法做到“让插件内部在进行http的请求走sock5代理或者http代理，不是修改或者访问本地的代理设置，而是在插件里面设置插件自己的代理”的，毕竟扩展程序不是一个独立的软件，它属于 Chrome 浏览器的一部分。

**Comment by lmk123** [comment]
如果要达到你的目的，就需要以下两项之一：

-  Chrome 浏览器自己加一个新功能，允许每个扩展程序自行管理代理而不是统一经过 Chrome 浏览器的代理设置
- 让 tc39 标准委员会给浏览器的 js 定制一个新的标准，允许 `XMLHTTPRequest` 或 `fetch` 提供代理设置，让特定的请求通过代理发起
- 写一个 [wasm 模块](https://developer.mozilla.org/zh-CN/docs/WebAssembly/Concepts)，让划词翻译的网络请求经过这个模块来发起，然后在 wasm 模块内部让这些网络请求通过单独的代理设置。这个方式只是我猜想的可能能实现的方式，未经过实际验证。

我个人猜测这俩在我有生之年前两个都不会实现 :joy: 而第三个就需要调研、还需要写 wasm 模块等，相比于这个需求来说，太麻烦了 :joy:
