### ISSUE TITLE
划词翻译没有权限操作当前网页

### ISSUE THREAD

**Issue by jkingben** [lmk123/crx-selection-translate#135]
surface 4的猎豹浏览器上没法用，一直是off的状态，点击划词图标弹出的窗口上出现没有权限提示，这是什么原因。
PC上是正常的。

**Comment by lmk123** [comment]
我猜问题的原因在于猎豹浏览器。我手头没有 surface 设备，你能帮忙测试一下 surface 4 上的 Chrome 浏览器能正常使用吗？

**Comment by jkingben** [comment]
chrome一样是没权限

**Comment by lmk123** [comment]
嗯……这就奇怪了。一般情况下这跟设备是没有关系的。

没有权限的提示在某些情况下是正常的，比如 Chrome 的设置页、空白的标签页等。

你在 https://github.com/lmk123/crx-selection-translate/issues/135 里点开划词翻译图标的窗口也是“没有权限”的提示吗？

**Comment by jkingben** [comment]
![image](https://cloud.githubusercontent.com/assets/5220242/13554983/4f95fc94-e3f0-11e5-9ce5-0272f7d49a85.png)

**Comment by jkingben** [comment]
![image](https://cloud.githubusercontent.com/assets/5220242/13554984/73f7b460-e3f0-11e5-8fca-de33b306b3c8.png)
猎豹上的扩展里设置是这样的，出不来

**Comment by jkingben** [comment]
PC猎豹上的设置也这样，不过使用正常的。

**Comment by lmk123** [comment]
我知道为什么你刚才回提示“没有权限”了，因为你打开的是以 file:/// 协议开头的本地文件，这个确实是要勾选“允许访问文件网址”后划词翻译才有权限访问。

**Comment by jkingben** [comment]
跟PC上比起来好像没啥关系，PC上是没勾的，我surface上勾不勾都无权限。访问的都是http的地址

**Comment by lmk123** [comment]
设置页打不开你可以尝试一下[这个解决方案](https://github.com/lmk123/crx-selection-translate/issues/123#issuecomment-185048451)

**Comment by jkingben** [comment]
设置页可以在地址栏扩展图标的右键点设置，能单独出来一个页面，这倒没啥大的影响。

**Comment by lmk123** [comment]
回到在 surface 上 Chrome 出现“无权限”提示的问题。

我没法保证划词翻译在套壳浏览器（例如猎豹）上的正常使用，因为这些浏览器可能缺少 Chrome 的某些功能，但如果在 Chrome 上也出现了问题，我会尽最大努力尝试修复。

你测试一下在 surface 里用 Chrome 在 https://github.com/ 这个网页里点开也是提示“无权限”吗？

**Comment by jkingben** [comment]
chrome 后来是正常的。现在就是PC的猎豹和surface的猎豹不一样。

**Comment by lmk123** [comment]
那也就是说，这个问题只会出现在猎豹浏览器里而不是 Chrome 里，对吗？

**Comment by jkingben** [comment]
在surface的猎豹浏览器里，目前就划词翻译在surface上出现了问题。

**Comment by lmk123** [comment]
我注意到猎豹浏览器是一个**双核**浏览器，出现这个问题的时候你是不是使用的 IE 内核？如果是，那切换到 Chrome 内核再试试看呢？

**Comment by jkingben** [comment]
是chrome内核。

**Comment by lmk123** [comment]
谢谢你的反馈，我会尝试修复这个问题的

**Comment by DangoYoung** [comment]
我也碰到了这个问题，很多网页都没有权限，比如我现在在看的mysql、django等等。Chrome浏览器。

**Comment by AiminHe** [comment]
![20200329181349](https://user-images.githubusercontent.com/48062850/77846533-5f651480-71e9-11ea-8a99-0a7dc9faa981.jpg)
这个网页为什么显示没有权限操作呢？划词翻译我选的是所有网站啊？这出什么问题了吗？

**Comment by SemiLavender** [comment]
有一些网站不知道怎么设置的，很多技术官网都没有权限，如k8s

**Comment by lmk123** [comment]
v7.0 已开发完成，并且尝试解决了这个问题，将在近期发布。如果新版本还有这个问题，欢迎反馈。

**Comment by UnLeon** [comment]
我也遇到了这个问题，但原因是我没有开启浏览器的弹窗权限，打开就好了~
