### ISSUE TITLE
翻译窗口固定问题

### ISSUE THREAD

**Issue by yc-z** [lmk123/crx-selection-translate#136]
翻译窗口固定后，无法取消固定状态，但点击空白地方窗口会消失，而点击取消固定状态，再点击空白地方，窗口不会消失，这两种情况是不是反了？
![gif](https://cloud.githubusercontent.com/assets/15177069/13547273/a7de099a-e306-11e5-9372-a908bbd5c7b8.gif)

**Comment by lmk123** [comment]
我没有重现你的问题，在我这边固定功能是正常的。你试试看删除之后重新安装？

**Comment by yc-z** [comment]
删除后重装还是这样，不过没关系，不影响正常使用。
上次发的操作可能不清楚，有录了一张，不能解决也没关系。
![gif](https://cloud.githubusercontent.com/assets/15177069/13554651/751349de-e3e8-11e5-9056-c66e56409483.gif)

**Comment by lmk123** [comment]
图钉竖着时是非固定状态，图钉45度倾斜了是已固定状态

**Comment by yc-z** [comment]
原来是这样，不好意思，可能是受以前的习惯影响，那应该没问题了。

**Comment by lmk123** [comment]
不过我在图示里发现“译”字有点模糊，你是不是把网页放大了的？

**Comment by yc-z** [comment]
应该是的，chrome在高分屏下会默认放大网页，不然字会非常小。
