### ISSUE TITLE
有道翻译也收费了

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#138]
由于划词翻译的有道翻译请求次数过多，有道翻译将划词翻译的接口给封禁了。我联系了有道翻译，对方给我如下回复：

>您好！
>
>  您现在使用的是免费版API，单次请求200字符，每小时1000次限制，为了不影响其他用户的正常访问，不能再给您提高限制了；您可以接入我们的收费版API，收费版与免费版接口基本一致，但是：
>
> - 按字符数而不是请求次数统计 
> - 现在接入每自然日有10万免费流量，超过部分按使用量计费，每百万字符收费为人民币50元，一个汉字一个英文一个标点都会计为一个字符。
> - 单次请求的上限字符数默认为4000，还可以根据需要再相应开大；
> - 服务更稳定，提供更多参数可选，例如语言方向全部开 
> - 根据您的使用场景需求，提供定制机器翻译引擎（根据实际需求情况可能需要另付费） 

百度翻译收费后，有道翻译也要收费了，我需要引导用户自行申请有道翻译 API Key。

**Comment by lmk123** [comment]
因为有道翻译使用量巨大，所以会导致偶尔被封禁，但是封禁一小时后会自动解封。

我现在会在用户选择有道翻译时给出提示（ 8aab511ec62b1a60614782894d8d144e9b3a5e17 ），但是我要考虑像百度那样使用网页版有道翻译的接口了。

**Comment by yanxu4780** [comment]
so sad

**Comment by wellhu** [comment]
难怪这几天用不了了

**Comment by 6769** [comment]
1. 能不能加一个自定义api的选项，让用户自己设置翻译接口；
2. 或者，把api接口的密钥开放出来让大家自己申请个密钥填写喽。
这样就不用担心什么使用过量的问题了

**Comment by lmk123** [comment]
@6769 我考虑的是使用网页在线翻译的接口，这样就没有限制了，百度翻译收费后我就是这么做的。如果这样做不行，那就只能让用户自行申请密匙了。

**Comment by andyhu** [comment]
或者能不能先支持输入api，再逐步转到网页接口？

**Comment by lmk123** [comment]
@andyhu 我是个懒人，比较喜欢一劳永逸的办法 :smile:

**Comment by wcx** [comment]
给用户自定义有道APIKEY的选项，想用的自己去申请

**Comment by lmk123** [comment]
Hi all，现在起可以在划词翻译中自行添加 API Key 了。
