### ISSUE TITLE
划词翻译里的有道翻译用不了了

### ISSUE THREAD

**Issue by YaniYang** [lmk123/crx-selection-translate#140]
每次用有道那个翻译引擎的时候就一直翻译不出来，划词显示的都是“正在查询，请稍后”，然后等好久都没有结果，而且这个框框还关不掉。点chrome右上角的图标去查词也查不到，一直都是“正在查询，请稍后”。

**Comment by mikicomo** [comment]
我也遇到这个问题，现在已经切换到bing，望修复。 @lmk123

**Comment by YaniYang** [comment]
是的，好像只有bing可以用的起来

**Comment by mikicomo** [comment]
@YaniYang 我这里百度，谷歌都正常的，就有道挂了

**Comment by mikicomo** [comment]
另外网页翻译上bing的好像坏了

**Comment by YaniYang** [comment]
哦对，我这里百度也用的起来，谷歌好像不大稳定吧有时候。网页翻译没试过。我划词翻译都重装好几遍了还是不行。。。

**Comment by lmk123** [comment]
有道翻译也要收费了，见 #138 

有道翻译免费额度每小时只有 1000 次，超出频率后有道翻译服务器就会封禁接口一个小时，之后自动解封。

我正在想办法。
