### ISSUE TITLE
弹窗在查询未结束时，点击外部无法关闭。

### ISSUE THREAD

**Issue by johnwatsondev** [lmk123/crx-selection-translate#141]
Mac OS X 10.11.3
crx-selection-translate Version: 6.0.10
Chrome Version 48.0.2564.116 (64-bit)

![2016-03-09 21 49 09](https://cloud.githubusercontent.com/assets/12760754/13637184/e7be56e0-e640-11e5-8674-d96c29aa1292.jpg)

例如：网络不佳时，正在等待返回翻译结果，点击弹窗外部无法关闭。
网络请求应该异步实现，用户可以随时关闭弹窗。
用户可能有更重要的事情要做。例如在写英文 email 时，查某个词语，结果好几秒没有结束查询，弹窗会一直遮挡在输入 Editor 中，从而影响用户体验。

**Comment by lmk123** [comment]
查询状态是不会超过 3 秒的，之所以会出现图中这种总是正在查询的状态，是因为有道翻译不能用了，见 #138

**Comment by johnwatsondev** [comment]
OK. Thanks.
