### ISSUE TITLE
能否自定义网络连接？

### ISSUE THREAD

**Issue by EasyChris** [lmk123/crx-selection-translate#144]
我本地开着shadowsock 能否自定义网络到本地127.0.0.1 这样我就可以直接使用google的翻译了，而不是要切换全局翻墙。

**Comment by lmk123** [comment]
我用的也是 Shadowsocks，开启 PAC 模式的时候是可以同时使用谷歌翻译和国内的其它翻译的，你检查一下你的 PAC 列表里有没有 `||googleapis.com` 这一条？没有就添加进去再试试。

**Comment by EasyChris** [comment]
Hi 李名凯，
    感谢您的回复！
    我这边查过是有 ||googleapis.com
  不过我是用Proxy SwitchyOmega插件+本地shadowsock翻墙 利用proxy将流量代理到本地的shadowsock，这样就可以自定义所有的网站翻墙
  然后PAC是更新在 https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt 的列表
  本地启用PAC 可以使用。自定义搭配插件还是不能使用。
  不过感谢您的回复。我再看看有没有办法。



isevenfox@gmail.com
 
发件人： 李名凯
发送时间： 2016-03-17 09:38
收件人： lmk123/crx-selection-translate
抄送： Chris
主题： Re: [crx-selection-translate] 能否自定义网络连接？ (#144)
我用的也是 Shadowsocks，开启 PAC 模式的时候是可以同时使用谷歌翻译和国内的其它翻译的，你检查一下你的 PAC 列表里有没有 ||googleapis.com 这一条？没有就添加进去再试试。

**Comment by lmk123** [comment]
你将 `*.googleapis.com` 添加进 SwitchyOmega 的切换规则试试？

**Comment by EasyChris** [comment]
Hi
您好，我已经解决了。加进去就可以了。
之前是我配置有点问题


这样配置之后就可以了，感谢！



isevenfox@gmail.com
 
发件人： 李名凯
发送时间： 2016-03-17 11:04
收件人： lmk123/crx-selection-translate
抄送： Chris
主题： Re: [crx-selection-translate] 能否自定义网络连接？ (#144)
你将 *.googleapis.com 添加进 SwitchyOmega 的切换规则试试？
