### ISSUE TITLE
本地网页无法翻译

### ISSUE THREAD

**Issue by lengmianshi** [lmk123/crx-selection-translate#150]
下载的英文网页文档翻译不了？

**Comment by lmk123** [comment]
请在[常见问题](https://github.com/lmk123/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)里寻找答案

**Comment by lengmianshi** [comment]
非常感谢，这个翻译扩展真心好用






在2016年04月10 21时37分, "李名凯"<notifications@github.com>写道:



请在常见问题里寻找答案
