### ISSUE TITLE
无法更改翻译平台

### ISSUE THREAD

**Issue by Helen-Guo** [lmk123/crx-selection-translate#152]
怎么老是默认百度翻译，百度翻译太不准了，而且有时只有一个结果，切换到其他翻译后有好几个结果，结果关闭后，再翻译又变成百度翻译了，怎么无法保存设置啊

**Comment by lmk123** [comment]
是的，关闭之后翻译引擎会被重设，你需要在设置里设置一下默认的翻译引擎

**Comment by Helen-Guo** [comment]
我的设置选项是空的，无法设置啊，我用的是UC浏览器

**Comment by lmk123** [comment]
意思是你打不开设置页吗？

**Comment by Helen-Guo** [comment]
![uc 20160413112050](https://cloud.githubusercontent.com/assets/8447414/14481914/e8b04cf4-0169-11e6-8418-4050b5cda20c.png)
你看一下，打开设置 选项是这样的

**Comment by lmk123** [comment]
chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/options/index.html

打开这个试试

**Comment by Helen-Guo** [comment]
好了，终于可以了，非常感谢！为什么同样是谷歌内核的UC浏览器无法出现这个选项呢

**Comment by lmk123** [comment]
这你就要问问 UC 浏览器了 :joy:

**Comment by Helen-Guo** [comment]
哦，那好的！
