### ISSUE TITLE
网页翻译多窗口存在识别问题

### ISSUE THREAD

**Issue by quericy** [lmk123/crx-selection-translate#153]
开启多个窗口时,在其中一个窗口选择翻译当前网页(这里我用的谷歌翻译),又是会翻译另一个窗口的最后一个标签页

开启普通窗口和隐身窗口时,网页翻译总是翻译普通窗口的网页

**Comment by lmk123** [comment]
可能跟 #147 重复了

**Comment by quericy** [comment]
是的,一样的问题.我close了吧.
