### ISSUE TITLE
建议增加选择主题色功能

### ISSUE THREAD

**Issue by JasonSi** [lmk123/crx-selection-translate#156]
应该不难实现的吧。。虽然说这话都站着说话腰不疼...

觉得自己选择颜色会舒服些

**Comment by Anveena** [comment]
言之有道理!

**Comment by JasonSi** [comment]
啊哈，算是个小提议;
自定义主题配色，按钮大小（太小了 鼠标灵敏度略高每次都点不到 [译]） 
很感谢这个扩展！
