### ISSUE TITLE
打不开设置页面~

### ISSUE THREAD

**Issue by gqbre** [lmk123/crx-selection-translate#157]
如题，卸载重装插件问题依旧

**Comment by lmk123** [comment]
尝试过[常见问题](https://github.com/lmk123/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)里的解决方案了吗？

**Comment by lmk123** [comment]
没反馈，应该是解决了吧。

**Comment by gqbre** [comment]
对的，Gmail不常用，谢谢！
