### ISSUE TITLE
隐身模式下打开 pdf 网址会出现“无法显示网页”

### ISSUE THREAD

**Issue by kite8** [lmk123/crx-selection-translate#164]
貌似是我刚才自动更新到6.1版本了，
发现一些网页 在开启这个功能后，出现无法显示网页
比如这个
http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00-introduction-to-computer-science-and-programming-fall-2008/assignments/pset3.pdf
或者这个网页http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00-introduction-to-computer-science-and-programming-fall-2008/assignments
里面包含pdf的页面均出现这样的状况0 0
一直在用作者的划词翻译，非常感谢~~帮了我不少的忙~~再次感谢~~

**Comment by lmk123** [comment]
咦，我点了你发的这两个链接，都是可以正常打开的。能提供你的操作系统及 Chrome 版本号吗，另外，你删除扩展后重新安装试试看？

**Comment by kite8** [comment]
貌似是因为chrome的隐身模式造成的？ 因为现在用的是公司电脑，我一般都是隐身模式，用正常模式浏览，是正常的
chrome版本 48.0.2564.109
电脑是win7 32版本

**Comment by lmk123** [comment]
已确认，这是一个 bug，我会尽快修复
