### ISSUE TITLE
美音 & 美音音标，Please！

### ISSUE THREAD

**Issue by 10v3** [lmk123/crx-selection-translate#165]
如题，有道自带英音和美音的，但划词翻译只显示出英音

**Comment by fleetingoo** [comment]
同求, 还有必应的单词翻译, 没有单词的音标, 希望考虑一下.

**Comment by mcxinyu** [comment]
怎么连音标也不提供啊？有语音不如有音标。！

**Comment by ivu4e** [comment]
@lmk123 如果我想实现显示音标的功能，应该修改哪个文件的哪个方法？
以及要添加这样一个配置项的话，应该修改哪里？

**Comment by lmk123** [comment]
v7.0 已支持美音和音标显示，将在近期发布。
