### ISSUE TITLE
安装了<划词翻译>后会导致inoreader经常崩溃

### ISSUE THREAD

**Issue by joeycold** [lmk123/crx-selection-translate#166]
已测试没有安装的情况下正常使用。一旦安装了插件，就会很导致inoreader网页版崩溃.具体表现为:当从inreader点开6，7个要读的网页的tab后,inoreader开始卡顿,然后所有从inoreader点开的网页tab跟inoreader的tab会同时crash，请问作者如何才能得到一些具体的信息,比如分析出是什么具体的代码最后会导致这种情况啊?

**Comment by chaleaoch** [comment]
遇到类似问题.
猜测和flash有关.
打开网易163等带图的网站会遇到这个问题.
现已从chrome中移出...

**Comment by lmk123** [comment]
我现在用划词翻译 v7.3.3、Windows 10、Chrome 87 按照你的重现步骤没有重现你的问题，具体步骤为：

1. 打开 https://inoreader.com/dashboard
2. 在我的订阅源中选择了 7 个要读的网页，每个都是在新的标签页里打开的

在打开了 8 个甚至更多的 tab 之后，没有任何标签页崩溃。

**Comment by lmk123** [comment]
> 遇到类似问题.
> 猜测和flash有关.
> 打开网易163等带图的网站会遇到这个问题.
> 现已从chrome中移出...

我同时在 10 个标签页中打开了网易新闻的 10 条新闻也没有重现这个问题。

**Comment by lmk123** [comment]
我另外又用 v6.4.12 重新试了一遍，也没有这个问题。

如果你们能提供稳定重现此问题的更多信息，例如你们使用的操作系统、划词翻译版本、浏览器版本等，可以继续留言。
