### ISSUE TITLE
可否在默认翻译引擎翻译失败后自动更换翻译引擎

### ISSUE THREAD

**Issue by horcruxen** [lmk123/crx-selection-translate#175]
一般某个翻译引擎翻译失败后需手动切换其他引擎，可否在翻译失败后自动切换？

**Comment by lmk123** [comment]
如果是我在翻译失败的时候，我会先重试一遍到两遍，然后才回尝试切换其它引擎翻译——所以说“一般”这个词太个人了，并不是每个人都会在引擎翻译失败后就立刻换成其它引擎了。

所以我不会加入这个功能 😄

**Comment by horcruxen** [comment]
确实考虑得太“个人”了:-) 不过我常常遇到的情况是一段时间内会一直翻译失败，所以切换引擎是更常见的情况，若能考虑在“重试”按钮旁加一个“切换”也是不错的吧（一个建议：p
