### ISSUE TITLE
開一律禁用後，沒辦法在需要翻譯時於個別頁面解除禁用

### ISSUE THREAD

**Issue by ChenTinLuo** [lmk123/crx-selection-translate#176]
設定一律禁用，想要在需要時才開啟翻譯功能，但是設定完後在其他頁面要開啟翻譯時，沒辦法開啟，是我理解錯誤還是BUG@@

**Comment by lmk123** [comment]
现在的划词翻译的“翻译筛选”相当于是“黑名单”模式，即只有列出来的域名才会被禁用，但“一律禁用”相当于切换到了白名单模式，但是我忘了添加这个功能。

我会进一步完善这个功能的，出了提供黑名单，再提供一个白名单。

你这个 issue 应该是跟 #139 重复了，所以我会先关闭你的 issue，后续进展都会发布在 #139 中。
