### ISSUE TITLE
喜欢之前版本的一键off，而不是仅对当前网站off

### ISSUE THREAD

**Issue by adi1625** [lmk123/crx-selection-translate#178]
大部分时间用不到这个软件，于是需要每一个网站都添加到“对当前网站启用”列表，否则就会每次选中文字就弹出翻译

**Comment by lmk123** [comment]
或许我可以加一个临时开启的功能，这样的话你全局禁用之后，仍然可以临时在当前页面启用。

**Comment by adi1625** [comment]
这样就放便多了:)

**Comment by lmk123** [comment]
v7.0 已经支持添加一条黑名单规则即在所有网站中禁用，将在近期发布。
