### ISSUE TITLE
启用pdf翻译功能会导致Chrome PDF Viewer工作异常

### ISSUE THREAD

**Issue by C9Z** [lmk123/crx-selection-translate#183]
启用pdf翻译功能后会导致：
1.Chrome PDF Viewer 无法禁用，即使在chrome://plugins/禁用pdf viewer插件，网页上点击pdf链接还是会直接打开pdf viewer。
2.Gmail中的pdf附件无法下载，其他格式附件不受影响。
3.在Chrome PDF Viewer中下载/保存pdf时文件名丢失，所有pdf文件均会被命名为document.pdf。
在扩展设置中关闭pdf翻译功能后以上三点均恢复正常。

**Comment by lmk123** [comment]
是的，这是因为开启 PDF 翻译功能后，划词翻译会使用自带的 PDF 预览工具替代 Chrome PDF Viewer。

无法下载 pdf 的问题应该是已经修复了，你有升级到最新版吗？

**Comment by C9Z** [comment]
经测试，gmail中的pdf附件还是无法直接下载，就是在邮件界面或者pdf预览界面点击下载无响应，但是如果选择在弹出窗口中显示附件，则pdf文件可以正常下载，但还是有文件名丢失的问题。
我的chrome版本是51.0.2704.84，扩展版本是6.1.2。

**Comment by lmk123** [comment]
我会抽空调查一番

**Comment by crack888wei** [comment]
Dear 我發現一個有趣的解決方法(开启 PDF 翻译功能)將勾勾拿掉就可以下載了~

**Comment by lmk123** [comment]
下个版本会默认关闭 PDF 翻译功能，并给出显眼的提示将此功能标识为“实验性功能”

**Comment by mingchau** [comment]
当开启PDF翻译的时候，会使用此扩展打开PDF这个到没什么问题，只是通过此扩展打印出来的文档会变模糊，这是一个问题？希望可以解决。

**Comment by lmk123** [comment]
v7.0 中已尝试解决 PDF 无法下载的问题，将在近期发布。

对于可能出现的打印模糊的情况，建议不要勾选自动打开 PDF，新版本支持通过右键菜单进入划词翻译内置  PDF 阅读器，所以可以同时使用 Chrome 和划词翻译查看 pdf，你可以用 Chrome 打印，用划词翻译进行翻译。
