### ISSUE TITLE
关于谷歌翻译和谷歌翻译（国内）

### ISSUE THREAD

**Issue by Veeson** [lmk123/crx-selection-translate#184]
您好，我想在android移动端开发一款支持多个翻译接口的翻译软件，比如可以支持有道、百度、必应等，就像您的开发的划词翻译那样。我现在遇到了一个问题，就是如何开发谷歌翻译和谷歌翻译（国内）功能，我找不到相关官方的开发文档，请问您在开发划词翻译的谷歌翻译和谷歌翻译（国内）功能时参考的文档在哪里找的，可否发个链接给我，谢谢！

**Comment by lmk123** [comment]
我没有使用官方文档的 API，因为那是收费的。我是通过分析这些翻译引擎的网页翻译的网络请求得出它们的网页翻译接口，然后使用在划词翻译里的。

查看这个项目的代码你就明白要怎么使用这些网页翻译接口了：https://github.com/lmk123/translation.js

**Comment by Veeson** [comment]
@lmk123 谢谢，已经成功移植到手机app的开发上面了，不过不知道是什么原因，如果请求翻译的是中文的话返回的结果乱码，目前正在找方法解决。

**Comment by lmk123** [comment]
安卓开发我不是很懂，但在浏览器里，如果要发送一个请求需要把汉字转码一下：`encodeURI('汉字')`

**Comment by Veeson** [comment]
@lmk123 试了好几种方法都不行，但是直接在浏览器里面打开返回结果的就不是乱码。
