### ISSUE TITLE
提供更多翻译接口

### ISSUE THREAD

**Issue by jiangjiji** [lmk123/crx-selection-translate#186]
期望：使用非有道翻译的时候 popup都能显示出单词音标

**Comment by lmk123** [comment]
除了有道翻译，其他翻译接口都没有给划词翻译提供音标，翻译接口如果不提供，划词翻译也没有办法显示出来。

**Comment by jiangjiji** [comment]
那是否可以考虑研究一下加入其他的翻译引擎，是否有提供音标的接口 

参考：
http://www.dictionary.com/
http://www.oed.com/
https://www.vocabulary.com/dictionary/
http://www.yourdictionary.com/
https://hk.dictionary.yahoo.com/

**Comment by iTofu** [comment]
+1

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，你提供的几个翻译接口都列在了上面。
