### ISSUE TITLE
快捷键Ctrl + q

### ISSUE THREAD

**Issue by epluguo** [lmk123/crx-selection-translate#187]
我也不知道这个是什么功能，按下ctrl + q，会响应划词搜索的一个功能，这个功能其实我并不需要，但是它占用了这个快捷键，而这个快捷键是我在其他网页里面有需要的。
所以能否出个快捷键自定义，或者提供一个选项让我关闭这个功能?
我不想每次打开那个网页时，把划词搜索关闭，这样太麻烦了。
望改进

**Comment by lmk123** [comment]
- 打开 chrome://extensions/
 - 点击最右下角的“键盘快捷键”
 - 在弹框中找到划词翻译的 “Ctrl + Q”快捷键并点击右边的 “X”
 - 点击“确定”按钮
