### ISSUE TITLE
怎么在chrome PDF viewer中使用划词翻译呢？

### ISSUE THREAD

**Issue by z3v1nic** [lmk123/crx-selection-translate#188]
“开启PDF翻译功能”选项已经勾选了呀
可是在PDF页面依然是 右上角图标依然是“OFF” 没有权限
求解~

**Comment by lmk123** [comment]
能截张图吗，或者告诉我如何重现？

**Comment by KaneGreen** [comment]
就是用Chrome打开一个PDF电子书，然后用这个插件，会发现划词之后仍然没有出现那个“译”的按钮
我的Chrome是52.0.2743.82m  64-bit，插件是6.1.2

**Comment by lmk123** [comment]
你是用 Chrome 打开的本地 PDF 文件吗，有勾选 “允许访问文件网址” 吗？

**Comment by KaneGreen** [comment]
打开之后确实可以了。但是存在PDF打开缓慢的问题，用起来就不太舒服了。恩，差不多PDF有1500多页，我还有个3000多的。
好像PDF查看功能是Chrome内部的一个插件的功能吧？（我也不懂，猜测而已）
好像很多Chrome扩展都没法在PDF查看页里面使用。

顺便一说，能否考虑加入金山词霸的翻译功能。我觉得金山词霸在科学文献翻译（机翻）上还是比较好用的。

当然，知网翻译助手，这个在科学文献中是最好的了。但是目前好像没有插件支持，只有一个网页。

2016年7月28日 下午5:53，"李名凯" <notifications@github.com>写道：

**Comment by lmk123** [comment]
@KaneGreen 划词翻译内置了一个 PDF 查看器，当你开启 PDF 翻译功能的时候，划词翻译会使用内置的 PDF 查看器而不是 Chrome 自带的那个。

1500 多页的 PDF 要想打开不慢是非常困难的。

金山词霸的功能会考虑的。
