### ISSUE TITLE
能否增加一个快速切换按钮或者自动双翻?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [lmk123/crx-selection-translate#196]
比如翻译的是英文>中文
那能不能增加一个双箭头按钮,俩个语言互相切换成中文>英文?

**Comment by lmk123** [comment]
已有功能。

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
我的意思是在不展开的情况下双翻

**Comment by lmk123** [comment]
如果所有按钮都放在外面，那界面就太杂乱了，所以才设计了展开的功能。

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
你可以弄俩个选项  一个展开 一个不展开  让用户自己选择呗~

**Comment by lmk123** [comment]
我觉得最好的软件就是选项越少越好，现在选项已经够多够杂了

**Comment by blacksheepaul** [comment]
请问在哪里可以快速从“中翻英”切换成“英翻中”？v11.0.1 独立翻译窗口点击齿轮后是单箭头

**Comment by blacksheepaul** [comment]
> 请问在哪里可以快速从“中翻英”切换成“英翻中”？v11.0.1 独立翻译窗口点击齿轮后是单箭头

在”设置 - 翻译面板 - 语种“这里把“源语种“设成自动检测，目标语种设成中文和英语，关闭“动态设置”，这样已经基本满足了我的需求

**Comment by lmk123** [comment]
这是 8 年前的 issue 了，那个时候的划词翻译是双箭头，但是后来我发现其实双箭头的本质是为了解决“中文被翻译成了中文”的问题，所以在后来改成了“主要语种和次要语种”这种方式来解决，于是箭头就改成单箭头了
