### ISSUE TITLE
本地html文件用chrome打开，划词翻译不能工作，只能自己粘贴

### ISSUE THREAD

**Issue by yunwuzhan** [lmk123/crx-selection-translate#197]

**Comment by yunwuzhan** [comment]
本地html文件用chrome打开，划词翻译不能工作，只能自己粘贴翻译

**Comment by lmk123** [comment]
见[常见问题](https://github.com/lmk123/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BD%95%E5%9C%A8%E6%9C%AC%E5%9C%B0%E6%89%93%E5%BC%80%E7%9A%84-html-%E6%96%87%E4%BB%B6%E5%8D%B3%E4%BB%A5-file-%E5%BC%80%E5%A4%B4%E7%9A%84%E7%BD%91%E5%9D%80%E9%87%8C%E5%A4%B1%E6%95%88)。
