### ISSUE TITLE
单词翻译， 设置显示英语释义和详细释义

### ISSUE THREAD

**Issue by fangxing204** [lmk123/crx-selection-translate#198]
一个单词有很多意思，如果所给的释义刚好不包含该但粗在当前语境中的含义，就完全看不懂。
我一直使用必应词典，就是应为它的英文释义比较易懂详细。

**Comment by lmk123** [comment]
有道与必应翻译是有详细释义的。其他翻译没有是因为这些翻译引擎没提供。
