### ISSUE TITLE
font-family 被覆盖

### ISSUE THREAD

**Issue by liukangle** [lmk123/crx-selection-translate#202]
在该网页中出现乱码：https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=map_simple
![12312](https://cloud.githubusercontent.com/assets/16165470/17356179/79a3a848-5988-11e6-8017-a1747bfb456d.png)

PS：火狐中没有比较好用的翻译插件。你懂的！

**Comment by lmk123** [comment]
`font-family` 被覆盖了 :joy:

**Comment by lmk123** [comment]
v6.4.10 已修复了这个问题。

另外，火狐版本已经上架了。
