### ISSUE TITLE
翻译盒子打不开

### ISSUE THREAD

**Issue by yjh126yjh** [lmk123/crx-selection-translate#203]
划词翻译功能是正常的，但是点击工具栏里的按钮打不开翻译盒子
浏览器是Chrome 52，插件是6.1.2，重装多次都没用。
![screenshot](https://cloud.githubusercontent.com/assets/17328101/17364522/37d50d8c-59b3-11e6-91bc-a12e77132a6d.png)

**Comment by Admin94** [comment]
我也遇到了这个问题。能打开，就是有点慢。比较卡的感觉。
版本 52.0.2743.82 m

**Comment by lmk123** [comment]
#169
