### ISSUE TITLE
查询失败时自动重试几次

### ISSUE THREAD

**Issue by caca2331** [lmk123/crx-selection-translate#208]
和一两年前刚下载的时候相比好用多了, 感谢!
1. 单词翻译一般用的是必应, 不过少数词汇和词组不支持, 需要手动切到谷歌翻译. 建议增加次选项,当首选项不支持时自动在次选项的搜索引擎里搜索
2. 其他的搜索引擎没试过, 这几周用下来必应经常出现服务器连接问题. 建议当出现连接问题时自动重连3次左右, 如果仍连不上再报告问题
3. 可以在1)的基础上增加模糊查询. 若google为搜索结果提供拼写建议的话, 加以显示

---

以上1)和2)的改进省去了偶尔要用鼠标切换引擎或点击刷新刷新的尴尬, 3)提高了手打单词的效率; 配合快捷基本实现了全键盘操作

再次感谢contribution!

**Comment by lmk123** [comment]
自动重连的优化已添加到 v7.5.0 的计划当中（虽然已经过去 5 年了，不知道你还有没有在用
