### ISSUE TITLE
改为使用一个单独的页面打开划词翻译的设置页

### ISSUE THREAD

**Issue by czmecho** [lmk123/crx-selection-translate#213]
不止一次出现了，以前版本的chrome也出现过。
现在用的是win10 14393.105 chrome 53

**Comment by lmk123** [comment]
“卡着”具体是怎样的表现？

另外，你所说的“设置页”指的是点击右上角的按钮弹出来的页面吗？

**Comment by czmecho** [comment]
右上角点击该图标的【选项】，然后页面卡在这：
![](http://ww2.sinaimg.cn/large/7df5111fgw1f7m7dr2br6j216u0imwg2.jpg)

**Comment by lmk123** [comment]
为什么关闭这个问题？

**Comment by lmk123** [comment]
Chrome 新的设置页打开方式似乎不兼容，新版本中我会改成用新标签页打开设置页的

**Comment by lmk123** [comment]
v7.0 已改为使用单独的标签页打开设置。
