### ISSUE TITLE
增加一个设置项用于设置弹窗显示的方向

### ISSUE THREAD

**Issue by mucunmjin** [lmk123/crx-selection-translate#215]
划词弹出的翻译界面 能不能小点，而且可以在翻译词的上方。在下放老是遮住下面的连续阅读。
猎豹的划词翻译就很简洁 在上方很小的窗口 大概单行。
以上建议 请供参考。谢谢

**Comment by lmk123** [comment]
新版本中我会提供一个设置项用于设置窗口显示的方向的

**Comment by lmk123** [comment]
v7.0 会自动根据页面滚动位置调整弹窗显示的方向，所以没有加入这个设置。新版本发布之后你先体验一下看看能否满足你的要求。
