### ISSUE TITLE
屏幕在放大的时候翻译的按钮位置不对

### ISSUE THREAD

**Issue by freshcn** [lmk123/crx-selection-translate#216]
在Mac下，两根指头双击放大浏览器文字后，会出现翻译的按钮显示的位置对不上的问题。

**Comment by freshcn** [comment]
![qq20160913-0](https://cloud.githubusercontent.com/assets/1764041/18465487/a1f36eee-79c9-11e6-9f9e-277043dfd193.png)
如图所示。

**Comment by lmk123** [comment]
v7 版本已经没有这个问题了
