### ISSUE TITLE
新增「超时时间」设置项

### ISSUE THREAD

**Issue by WayneYue** [lmk123/crx-selection-translate#217]
添加过两个有道翻译API，这两天突然不好使了，点翻译按钮显示“查询超时了，请稍后再试。”
翻译来源改成其他的比如谷歌都好使，就是有道不行。
肉身在美国，看大家都没有反应这个问题，不知道有没有影响。

**Comment by lmk123** [comment]
我在国内，测试了有道是可以用的。

有道翻译的超时时间是 4 秒，如果 4 秒还没有得到结果，划词翻译就会提示“查询超时”，有可能是从美国访问有道翻译的时候会有点慢。

下一个版本将会放宽超时时间。

**Comment by cegedr** [comment]
我的有道也不行了……最喜欢用的就是有道 : (

查什么都是显示超时；如果用代理，会显示我的api key被封禁（新注册的key也会这样显示）。

**Comment by lmk123** [comment]
@cegedr 新版本里我会改进这个问题的。 v6.1.2 的版本不打算更新了，新版本 v7.0 正在不紧不慢的开发当中 😂

**Comment by lmk123** [comment]
当时我本来时打算添加超时时间来解决这个问题，但现在回想起来，超时时间的选项没必要加，因为如果你在国外用国内的接口，可能再试一次还是会超时。。
