### ISSUE TITLE
用了插件自带的pdf浏览器，划词方便了，但是不能用evernote的浏览器插件对pdf内容收藏！

### ISSUE THREAD

**Issue by GitOffice** [lmk123/crx-selection-translate#227]
用了插件自带的pdf浏览器，划词方便了，但是不能用evernote的浏览器插件对pdf内容收藏！如果是chrome自带的pdf viewer可以。

**Comment by lmk123** [comment]
我会抽空检查一下的

**Comment by lmk123** [comment]
我想可以加个设置项，不要默认用划词翻译内置的 PDF 阅读器打开 PDF，可以做成点击 pupup 里的按钮之后再用划词翻译的 PDF 翻译

**Comment by lmk123** [comment]
划词翻译内置的 PDF 阅读器，其它扩展是没法注入进来的。在 v7.0 中你可以关闭自动在划词翻译中打开 PDF 的功能，这样用浏览器自带的 PDF 可以用 evernote 收藏内容，然后你还是可以在右键菜单中选择“在划词翻译中打开”来进入划词翻译内置的  PDF 阅读器进行翻译。
