### ISSUE TITLE
划词翻译按钮错位

### ISSUE THREAD

**Issue by hsj1992** [lmk123/crx-selection-translate#240]
地址：https://cloudfour.com/thinks/ios-doesnt-support-progressive-web-apps-so-what/
现象：
1. 轻微的，仅仅是错行
![2016-12-19_171332](https://cloud.githubusercontent.com/assets/4816005/21307133/28682cb2-c60f-11e6-9969-1f07d14fbe6d.png)

2. 严重的，错开了整整一个viewport大小
![2016-12-19_171740](https://cloud.githubusercontent.com/assets/4816005/21307169/4cb70bd8-c60f-11e6-8513-2311b19bd614.png)
![2016-12-19_171606](https://cloud.githubusercontent.com/assets/4816005/21307175/539cf23c-c60f-11e6-9ca7-fbb5e6c7453a.png)

**Comment by lmk123** [comment]
v7.0 已没有这个问题，将在近期发布。
