### ISSUE TITLE
功能请求: 历史查询记录

### ISSUE THREAD

**Issue by hanFengSan** [lmk123/crx-selection-translate#242]
我希望能在popup上加个历史查询记录orz
...我觉得还是蛮有用的...有个历史查询记录的话.  不然有时候由于单词太长什么的....查后老没记全, 又得再查询一遍.

**Comment by gggccc44** [comment]
我在想加这功能到底是手工保留还是自动保留更合适。。。

用户一句话码农累出血，so捐助了10块表示支持o(∩_∩)o 哈哈，毕竟用了这么久了

**Comment by lmk123** [comment]
v7.3.0 已加入历史记录功能

**Comment by hanFengSan** [comment]
感谢！

mingkaili <notifications@github.com> 于 2020年12月2日周三 20:14写道：
