### ISSUE TITLE
Bing 翻译无法使用

### ISSUE THREAD

**Issue by reaCodes** [lmk123/crx-selection-translate#250]
提示“必应翻译不支持此语种。重试”
或者提示“服务器出错啦，请稍后重试。重试”

**Comment by greatghoul** [comment]
必应翻译的 API 现在必须使用 https 才能调用。

**Comment by lmk123** [comment]
v6.4.0 修复了有道和百度翻译，必应翻译暂时不打算支持了，但这个问题我还是会开着，以后有空了也可以再把必应加进来。

**Comment by vungsung** [comment]
(Private?) API
---
Request:
```
https://www.bing.com/tdetect
text: Can I test?","Please, thank you!
```
Response:
`en`

---
Request:
```
https://www.bing.com/ttranslate
text: Can I test?","Please, thank you!
from: en
to: zh-CN
```
Response:
`{"statusCode":200,"translationResponse":"我能测试一下吗?\" \"请,谢谢!"}`

**Comment by lmk123** [comment]
后面准备加入彩云、腾讯和搜狗，不打算加入必应了。
