### ISSUE TITLE
希望改进下性能，通过浏览器开发者工具观察发现开启此扩展后网页加载速度慢250ms

### ISSUE THREAD

**Issue by kunanaxp** [lmk123/crx-selection-translate#257]

**Comment by lmk123** [comment]
请问你是如何观察到开启划词翻译后网页加载速度慢 250ms 的，能告诉我你的观察方式吗？

**Comment by qishibo** [comment]
同，有些日子了，新开tab时网页响应较慢，左下角状态栏显示正在加载划词翻译啥的，，不知道是不是引入了啥被墙的库了吧，没细研究，临时禁用了

**Comment by lmk123** [comment]
这个版本不会大改了，因为新版本已经在计划开发中了，我会在新版本中留意这个问题的。

**Comment by lmk123** [comment]
加载速度慢的原因见 #250 新版本中会修复这个问题。
