### ISSUE TITLE
希望在翻译结果中增加 wiki 解释

### ISSUE THREAD

**Issue by cutd** [lmk123/crx-selection-translate#263]
首先是感谢作者的付出，最近在阅读一些文档的时候希望能够直接翻译某些专业词汇，百科或者wiki都可以，能够快速了解某个词汇的意思就好。

**Comment by lmk123** [comment]
下一个版本 v7.5.7 添加了快捷链接的功能，可以自行配置要跳转的网址，例如如果你想用维基百科搜索划选的文本，那么就可以添加一个快捷链接 `https://zh.wikipedia.org/w/index.php?search=%s`。
