### ISSUE TITLE
提供调节翻译窗口宽高的功能

### ISSUE THREAD

**Issue by jelipo** [lmk123/crx-selection-translate#267]
文本较多时，框体的高度很高，而宽度很窄，不便于看翻译。

**Comment by liwilly** [comment]
强烈建议开发者能够允许**用户自行调整**翻译框的宽度，多谢。

希望能够提供以下两种方式：
- 按住原始语言文本框右下角拖拽时，允许横向拖拽，目前只能纵向拖拽。
- 在插件设置里调整宽度数值。

**Comment by lmk123** [comment]
v7.0 已经支持调整宽度。高度不支持调整，因为我觉得根据翻译内容自动设置高度就好。v7.0 已开发完成，将在近期发布。
