### ISSUE TITLE
关于功能改进和用户体验的几条建议

### ISSUE THREAD

**Issue by bluer007** [lmk123/crx-selection-translate#271]
插件很不错, 赞一个, 不过使用过程中发现有些小地方可以做得更好, 特提以下建议, 按本人认为的优先级排序, 希望采纳:
1. 增加选定单词后, 鼠标移动到翻译按钮就自动翻译, 减去点击的操作
2. 增加鼠标移动到"朗读"或"复制"就自动执行"朗读"或"复制"操作, 减去点击的操作
3. 有少数情况, 翻译窗口会出现关闭不了的情况, 建议右上角增加关闭窗口按钮
4. 整个翻译窗口的配色不够美观, 可以参考有道翻译的网页插件, 值得说下, 有道翻译的网页插件在操作体验和UI上还是值得学习的
5. 少数情况, 网络不稳定, 点击翻译按钮后, 会一直转啊转, 等不到翻译结果, 建议增加转啊转的时候, 单击或移动到翻译按钮的图标时, 就自动再次发送请求, 和点击翻译按钮时, 同时发送多个请求来规避网络不稳定的问题
6. "朗读""复制"按钮可以找喇叭等图标代替

**Comment by lmk123** [comment]
建议不错，我会在新版本中酌情改进的

**Comment by Dust1989** [comment]
整体的感觉已经挺不错，如果声音能独立调大小就好了！！

**Comment by eightHundreds** [comment]
借地留建议。
首先这些建议是满足的我“私人需求”的
就是最近在用在线协同翻译软件，但是一般他们不提供翻译。用划词翻译操作上比较复杂。
我希望
有个快捷键能帮我把选中的文本翻译
还有个快捷键能复制翻译后的文本

**Comment by bluer007** [comment]
@lmk123   哈哈, 想不到有人借地留建议了. 这段时间又想到了一个功能.
    有些页面的文字或者链接是不能选中的, 一点击就会跳转等, 所以建议新增"按住alt键+划词" 就可以强制选中那些单词/句子来翻译.

**Comment by EcoRIIHC** [comment]
nice extension，感谢作者，同样借地留言，能否增加音标显示呢，不看音标不舒服斯基😁

**Comment by greatghoul** [comment]
链接的划词翻译，我的做法是

按下快捷键时，给 body 元素添加一个 css 类 cst-link-inspect-mode

然后样式里面设置。

```css
body.cst-link-inspect-mode a {
  text-decoration: none !important;
  pointer-events: none !important;
}
```

这样链接就可以选中了。

划词或者按 ESC 时去除这个类，恢复到原始状态。

@lmk123 要做这个功能的话，可能参考一下。

**Comment by lmk123** [comment]
> 插件很不错, 赞一个, 不过使用过程中发现有些小地方可以做得更好, 特提以下建议, 按本人认为的优先级排序, 希望采纳:
> 
> 1. 增加选定单词后, 鼠标移动到翻译按钮就自动翻译, 减去点击的操作
> 2. 增加鼠标移动到"朗读"或"复制"就自动执行"朗读"或"复制"操作, 减去点击的操作
> 3. 有少数情况, 翻译窗口会出现关闭不了的情况, 建议右上角增加关闭窗口按钮
> 4. 整个翻译窗口的配色不够美观, 可以参考有道翻译的网页插件, 值得说下, 有道翻译的网页插件在操作体验和UI上还是值得学习的
> 5. 少数情况, 网络不稳定, 点击翻译按钮后, 会一直转啊转, 等不到翻译结果, 建议增加转啊转的时候, 单击或移动到翻译按钮的图标时, 就自动再次发送请求, 和点击翻译按钮时, 同时发送多个请求来规避网络不稳定的问题
> 6. "朗读""复制"按钮可以找喇叭等图标代替

第 1 点和第 2 点似乎仅仅只是免去了点击的操作，但是少一次点击似乎没有太大的必要。

对于第 3 点，现在已经加上翻译按钮了
对于第 4 点，v7.3.3 已经全面更改了界面和配色，应该比 v6 版本要美观吧 :joy:
对于第 5 点，v7.3.3 应该已经没有这个问题了
对于第 6 点，v7.3.3 也已经用图标替代文字了

**Comment by lmk123** [comment]
> 有些页面的文字或者链接是不能选中的, 一点击就会跳转等, 所以建议新增"按住alt键+划词" 就可以强制选中那些单词/句子来翻译.

即将发布的 v7.4.0 会加上这个功能

**Comment by lmk123** [comment]
@eightHundreds

> 有个快捷键能帮我把选中的文本翻译

翻译选中文本的快捷键是有的，默认是 Alt + A，或者如果你开启了“配合辅助键使用”，按一下 Ctrl / Command 就行

> 还有个快捷键能复制翻译后的文本

这个提议不错，我会考虑的

**Comment by lmk123** [comment]
@Dust1989

> 整体的感觉已经挺不错，如果声音能独立调大小就好了！！

即将发布的 v7.4.0 会添加调整音量的设置项

**Comment by lmk123** [comment]
如果大家还有新的提议，欢迎再开新的 issue 反馈给我。
