### ISSUE TITLE
在划词翻译不可用时，将图标改为灰色

### ISSUE THREAD

**Issue by czgczg** [lmk123/crx-selection-translate#278]
就是扩展程序的图标上一直有个off，感觉有点别扭。我点击或者右键也没找到关闭或开启的办法。按ctrl+q它的状态也没什么变化。

**Comment by lmk123** [comment]
off 字样是用来指示划词翻译对当前页面是否启用了翻译功能的。在一些 Chrome 内置的页面中由于没权限，它一直会显示 off（比如在以 chrome:// 开头的各种页面里）。可能会有点别扭吧，我在新版里改进一下。

**Comment by luoboYe** [comment]
同样也是使用ctrl+q无法切换开关。我觉得这个插件设计应该是默认的时候的关闭的，只是浏览某些网站需要用到翻译的时候才会手动开启，不然有浏览每个网站都自动翻译体验很不好。

**Comment by greatghoul** [comment]
给一个建议，如果在页面没有启用，将图标替换成一个灰色的，这样比显示个 off 好看一些。
