### ISSUE TITLE
同时展示所有接口的翻译结果

### ISSUE THREAD

**Issue by DIYer22** [lmk123/crx-selection-translate#304]
我笔记本的网络环境经常变化 翻译速度最快的引擎也随之变化 每次都要切换引擎较为麻烦
所以 我建议
将翻译引擎选择变为复选框
使用多线程来融合
显示最先callback的结果

**Comment by lmk123** [comment]
这个提议不错。

划词翻译最初引进多个翻译接口的原因是希望能让用户对比得出最准确的解释，但现在的模式下要挨个切换确实繁琐了。

新版本中我可能会同时显示所有接口的结果，并用合适的方式展示出来。

**Comment by lmk123** [comment]
v7.0 已改为同时显示三个翻译服务的结果，将在近期发布。
