### ISSUE TITLE
勾选了「配合 Ctrl 键使用划词翻译」后，不按住 Ctrl 键划词仍然会弹出翻译按钮

### ISSUE THREAD

**Issue by ZengAtHere** [lmk123/crx-selection-translate#305]
我喜欢看网页的时候用鼠标划、或者选中文本进行复制，但这时会跳出绿色的图标，请问能关闭吗，理想情况的我Ctrl+划显示翻译，而不是每次划词都触发图标，一个个添加网站白名单也太麻烦了
一个建议

**Comment by lmk123** [comment]
这似乎是一个 bug，理论上来说勾选了「配合 Ctrl 键使用划词翻译」后就只会在按下 Ctrl 键划词的时候才弹出结果。

**Comment by lmk123** [comment]
在新版本中，勾选"在所有网站中禁用网页划词"就可以了。
