### ISSUE TITLE
感觉bin的词典对于网络来说更加准确，同时希望提供更多的翻译信息

### ISSUE THREAD

**Issue by qidizi** [lmk123/crx-selection-translate#32]
建议：
1 尽量提供更多的信息，如读音什么，尽可能的多。查看更多的url==
2 如何有时间，可以增加一个主来源，然后其它来源会相应的出现在下面（ajax延后处理）；

信息量还是比较少。

**Comment by lmk123** [comment]
1、信息量是由各个翻译接口提供的，所以能出现多少信息不是由我决定的
2、你的意思是同时显示三种翻译接口的结果？

**Comment by qidizi** [comment]
对于这句：
Attach images by dragging & dropping,  selecting them, or pasting from the clipboard.
有道都说成了

附加图片拖&下降,选择它们,或者从剪贴板粘贴。

谷歌还好。所以，翻译的质量还是很关键，否则就更加迷糊不懂说什么了；

1.  对于单词，有更多信息，比如最重要的读音是有助于记忆的；
2. 更多的接口可以提高准确性；

**Comment by lmk123** [comment]
一次性显示三种接口的翻译结果是很**浪费**的，因为有道与百度对接口的使用频率都有限制，如果频率过高，会导致接口被封，那样所有用户都无法正常使用了。
