### ISSUE TITLE
窗口大小与字体大小

### ISSUE THREAD

**Issue by bitweng** [lmk123/crx-selection-translate#323]
希望有设置窗口大小和字体大小的功能。
比官方的翻译扩展赞 👍

**Comment by lmk123** [comment]
谢谢，你的提议我会考虑的

**Comment by JonasGao** [comment]
+1。翻译内容较多时，就变得较长。建议增加宽度控制

**Comment by TongxinV** [comment]
+1，窗口边框可以小一点

**Comment by lmk123** [comment]
重复 #267，后续进展会更新在 #267 中

新版本会提供调节宽高的功能，并且会改进翻译窗口样式，将边框调窄一点。
