### ISSUE TITLE
希望开发者增加英英字典

### ISSUE THREAD

**Issue by chen7410** [lmk123/crx-selection-translate#328]
类似于
![capture](https://user-images.githubusercontent.com/27870739/31877193-684734be-b78a-11e7-9f0d-a3c29ea41974.PNG)
，不想又另外安装一个插件，而且安装的插件不能用在网上的pdf。
谢谢了！

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，里面有几个英英词典，你可以看一下哪个是你希望添加的。
