### ISSUE TITLE
建议添加自定义翻译引擎，方便镜像translate.google.com的网站使用

### ISSUE THREAD

**Issue by fbigun** [lmk123/crx-selection-translate#337]
例如镜像网站 fanyi.xxxx.com 由源站 translate.google.com完成。现在自定义添加fanyi.xxxx.com也能完成相应翻译。

**Comment by lmk123** [comment]
对划词翻译来说没有意义，因为本身就支持了 translate.google.cn

**Comment by fbigun** [comment]
我们这边的translate.google.cn全部会跳转到ipv4.google.cn  根本不能使用

**Comment by fbigun** [comment]
杭州移动的屏蔽了

**Comment by lmk123** [comment]
我考虑看看

**Comment by lmk123** [comment]
我加个新选项吧，针对谷歌翻译添加一个镜像选项

**Comment by lmk123** [comment]
Ref: Selection-Translator/translation.js#24

**Comment by lmk123** [comment]
后面的版本我会考虑加个设置项，可以自行设置谷歌翻译的接口域名，这样就可以自己设置个代理来使用谷歌翻译了。

**Comment by rfire-sun** [comment]
哈哈 现在加了吗？   我也遇到类似的问题
![微信图片_20201212224018](https://user-images.githubusercontent.com/28004217/101986795-21524700-3ccb-11eb-9bb6-eb9f5f2dcc35.png)
这个我没猜错的话应该是使用google.com的api，但是我在translate.google.cn可以进行正常的翻译，想着可否自己设置一下翻译的api试一下，发现不能，(((φ(◎ロ◎;)φ)))晕
从产品的角度应该算是比较高级的功能吧
感觉可考虑加在一个高级功能选项的标签里

**Comment by lmk123** [comment]
> 这个我没猜错的话应该是使用google.com的api

不是的，translate.googleapis.com 这个 api 无论你是否 FQ 都是可以用的，而且这个问题并不是把 googleapis.com 改成 googleapis.cn 就能解决的。

出现这个问题是因为你所在的网络不能访问到这个接口地址，我收到过反馈，在有的大学里面这个地址是访问不了的，但用手机的 4G 信号是可以正常打开这个接口地址的，你也可以试试。

> 但是我在translate.google.cn可以进行正常的翻译

translate.google.cn 现在改版了，以前那个区分国内/国外的谷歌翻译接口已经不能用了，所以换用了 translate.googleapis.com，详情见 #797

**Comment by lmk123** [comment]
很抱歉这个 issue 过了好些年都没处理 :joy:

translate.google.cn 的**接口**现在会自动跳转到 .com 去了（[见说明](https://hcfy.app/blog/2021/09/22/google-force-com)），所以我感觉这个选项没必要了，issue 我先关了。
