### ISSUE TITLE
牛逼哥，全文 全页面翻译，能做吗？

### ISSUE THREAD

**Issue by mapleshadow** [lmk123/crx-selection-translate#34]
目前有款插件，有道翻译，不过是2013年开发的，时不时的就不能工作了。。。。。。
蛋疼，期待你出手了

**Comment by lmk123** [comment]
划词翻译里面不是带网页翻译的吗，用的就是有道网页翻译

**Comment by mapleshadow** [comment]
不是，哥们，我知道是快捷键  alt+z 全页翻译。
我的意思是不是能增加一个按钮，因为快捷键这玩意太不明显了，我不去看帮助还真不知道呢。
