### ISSUE TITLE
关于 全页翻译 的建议

### ISSUE THREAD

**Issue by mapleshadow** [lmk123/crx-selection-translate#35]
目前全页翻译用的是快捷键alt+z
很不明显，不看帮助还不知道，建议点击《插件图标（是插件图标，不是划词后出来的译，图标）》后，能够增加一个全页翻译的按钮。

**Comment by lmk123** [comment]
好的，我会添加的。顺便把翻译盒子里的划词翻译开关也做得明显一点。

**Comment by mapleshadow** [comment]
好人！感谢！！！
2015年4月9日 下午2:44于 "Milk Lee" <notifications@github.com>写道：

**Comment by lmk123** [comment]
Fixed in c5abe1d
