### ISSUE TITLE
突然無法使用pdf取辭了

### ISSUE THREAD

**Issue by grass805** [lmk123/crx-selection-translate#355]
大概在上星期，我移除掉iciba愛詞霸的擴充軟體，後來就發現劃詞翻譯的pdf取詞功能故障了
打開pdf檔後，出現的畫面一樣，也可以劃詞，但點劃詞旁邊綠色方格"譯"之後，就卡住了，不會出現翻譯；
之後往下滾動，"譯"會一直維持在螢幕的同個地方，劃了新的詞也一樣，好像這個程式卡住了的感覺
不知道是什麼原因，應該和愛詞霸沒有關係(?)
這個插件很好用，希望能夠趕快解決此問題><

![default](https://user-images.githubusercontent.com/35034106/34486449-0239bdcc-f00b-11e7-812b-d19703d36727.jpg)

**Comment by lmk123** [comment]
在我这里是正常的：

![image](https://user-images.githubusercontent.com/5035625/34496967-8dd833d8-f036-11e7-8b43-f9d3c3256870.png)

你可以尝试重启浏览器或者重装划词翻译试一下，如果还是不行，你能提供一下你的 PDF 文档让我试一下吗？

**Comment by grass805** [comment]
我是用每一個pdf文件都這樣
已經重裝過chrome也重裝過劃詞翻譯了
還是一樣，每個pdf檔都無法使用翻譯
但是網頁就沒有問題，只是不能翻pdf
但是這個功能我常需要用到><

**Comment by lmk123** [comment]
有更新，但是 PDF 这一块一直都没有动过，不太会出现这种情况才对。

会不会是其他扩展影响了划词翻译？你尝试过关掉其他扩展只开启划词翻译吗？

我是用[这个 PDF](https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf) 测试的，你也打开这个 PDF 试试看？

**Comment by grass805** [comment]
這個PDF也是一樣情況，
我關掉所有擴展指開啟劃詞，
結果還是一樣QQ

**Comment by lmk123** [comment]
那就比较棘手了，我需要你提供一些额外的信息来帮助我查找错误原因：

1. Chrome 的版本号与划词翻译的版本号
2. 打开 PDF 选择一个单词翻译一次，然后鼠标右键->选择「检查」，在弹出的面板中切换到 「Console」面板，将里面的内容截图给我
3. 进入「扩展程序」页（chrome://extensions/），勾选「开发者模式」，找到划词翻译并点击「背景页」链接，将打开的面板切换到「Console」面板，将里面的内容截图给我

**Comment by grass805** [comment]
1. Google Chrome 版本 63.0.3239.108 (正式版本) (64 位元)
    划词翻译 6.3.3

2.
![1](https://user-images.githubusercontent.com/35034106/34564051-3c050aee-f190-11e7-9a1a-9f6d970c2fdf.jpg)

3.
![2](https://user-images.githubusercontent.com/35034106/34564069-51524218-f190-11e7-8200-13745eb4ec1e.jpg)

**Comment by lmk123** [comment]
从截图上来看没有任何错误，Chrome 和划词翻译的版本跟我也是一样的……

能提供你测试用的 PDF 给我试试吗？我想不出来还有其他能造成这个问题的差异了 😂

**Comment by grass805** [comment]
我用所有pdf都這樣欸QAQ
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5480083/pdf/CAS-108-1109.pdf
這個連結可以試試
我一選詞就卡住了==

我第一次裝的時候是用https://github.com/Selection-Translator/crx-selection-translate/issues/69
這個網頁教的，下載pdf.js，
但我後來發現好像完全沒有作用，
因為我只有下載下來然後隨便解壓縮到資料夾而已==
但那時候是可以翻譯pdf檔的

http://mozilla.github.io/pdf.js/web/viewer.html
目前這個頁面可以翻譯
擴充功能頁面就不行

**Comment by kaviami** [comment]
出现了相同的情况 不能在pdf取词翻译 重装插件以后还是一样

**Comment by kaviami** [comment]
我尝试了多个pdf文件 都是在划第一个词的时候卡住  浏览器版本是 63.0.3239.132

**Comment by lmk123** [comment]
我会在新版中升级内置的 PDF 阅读器的版本，到时候再看看还会不会有问题

**Comment by kaviami** [comment]
使用新的6.4.0版本试了一下 还是会出现卡住的情况

**Comment by kaviami** [comment]
翻译完第一个词后就不能翻译下一个词了 但是这个版本在翻译完第一个词后框可以移动，之前不行

**Comment by kaviami** [comment]
更新6.4后 在网页和pdf都只能划第一个词 划第二个词就没有反应了

**Comment by kaviami** [comment]
chrome版本67

**Comment by lmk123** [comment]
v7.0 将内置的 PDF 阅读器升级到了最新版本，将在近期发布。如果新版本还是有这个问题，欢迎新开一个工单反馈。
