### ISSUE TITLE
谷歌翻译的结果和谷歌翻译网站上翻译的不一样

### ISSUE THREAD

**Issue by reaCodes** [lmk123/crx-selection-translate#364]
![image](https://user-images.githubusercontent.com/13817254/35223961-4e6b0e86-ffbe-11e7-94b7-81e090b48813.png)

**Comment by lmk123** [comment]
感谢反馈，之前都没注意到

**Comment by lmk123** [comment]
我试了几段英文，现在在 v6.4.9 中已经没有这个问题了
