### ISSUE TITLE
能不能增加中文划词出拼音的功能

### ISSUE THREAD

**Issue by scetus** [lmk123/crx-selection-translate#367]
很多时候会遇到不懂怎么念的汉字，虽然可以复制以后到搜索引擎搜索，但太麻烦了。
是否可以增加中文划词出拼音的功能？

我觉得出拼音就可以了。倒不用出汉字或名词解释。

**Comment by greatghoul** [comment]
http://www.zdic.net/

**Comment by reaCodes** [comment]
这只是外文翻译软件，功能也不能太臃肿吧

**Comment by gs1223** [comment]
选中中文，可以直接发音啊。

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，汉典已经列在了上面。
