### ISSUE TITLE
添加一个设置项

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#37]
打开右上角的翻译盒子时，会自动将剪切板的文本粘贴到翻译框并翻译。为这一行为添加一个设置项，默认开启。

**Comment by GH01** [comment]
翻遍新版(7.0.5)，已无此项？
希望尽快恢复。

建议：
▲默认停用（因为涉及隐私/信息安全，哪怕只是一次）。
▲除选项外，在各弹窗中都添加[来自剪贴板]命令（不是选项），以便随时随处可用，但只应是一次性的。

本issue的标题应该更明确一点。

**Comment by lmk123** [comment]
将在下个版本中加入 #733
