### ISSUE TITLE
右键菜单项快捷键（无处切换界面语言？）

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#385]
希望(中文版)右键菜单项有快捷键，比如 (&T)，便于用键盘选择。
或者允许切换界面语言（若已有，烦请告诉我，谢谢。但希望不是要我去删/改文件。）

**Comment by GH01** [comment]
关于此需求，我这里还有一个重要原因：
我的主浏览器Vivaldi“扩展快捷键”功能整体无效（除非设成“全局”，但那样显然不合适）：
https://forum.vivaldi.net/topic/8364/keyboard-shortcuts-for-extensions-is-ineffective

即使浏览器的“扩展快捷键”功能可用，右键菜单中的加速键（accelerator key）也是有必要的，并行不悖的。

进一步想法：
右键菜单中的加速键最好能自定义，以避开重复。

现状：
自己改了一下bg.js，z打头，很方便。
自己改当然很简单，但毕竟每次更新都要维护。

**Comment by lmk123** [comment]
> 希望(中文版)右键菜单项有快捷键，比如 (&T)，便于用键盘选择。

你是希望能通过键盘快捷键展开切换语言的区域吗？

> 或者允许切换界面语言

你指的是直接在邮件菜单中添加切换语种的菜单项吗？

**Comment by GH01** [comment]
我是指 界面语言。
我开始以为只要切换 界面语言，右键菜单项的“翻译”二字就会变成“Translate”。
后来发现你的界面只有中文（歪果仁没得用？）

关于 菜单项的加速键(accelerator key)：
假设菜单如图：
![menu_acceleratorkey](https://user-images.githubusercontent.com/19272301/37384522-6c8658d2-278a-11e8-9878-7ff4f8fa37cd.gif)

加速键优先，所以：
按E键触发①
按X键触发③
按Y键触发⑤

剩下的就以首字触发：
按Z键触发④
（②无法用字母键触发，因为E已被加速键占据）

按T键，就会在⑥⑦间跳，须用Enter确认。
这样就不爽利。
所以最好能避免与其他菜单项的重复。
两个加速键相同时 同理。

键盘党喜欢这样用。快捷，盲选。

**Comment by GH01** [comment]
补充：
首字若是汉字，又没有加速键，那这个菜单项就对键盘党不友好了。

**Comment by lmk123** [comment]
划词翻译确实不支持多语言，所以——是的，歪果仁没得用 😂

键盘快捷键的想法不错，我会酌情考虑的

**Comment by GH01** [comment]
> 划词翻译没有权限操作的页面只能使用右键菜单翻译的方式

▲这样挺好。
▲建议这句再详细点：
`划词翻译没有权限操作的页面只能使用右键菜单翻译的方式（会打开独立窗口）`


所以希望尽快加个加速键，只是举手之劳。
我的建议是：
`翻译这段文本(&Z)`
▲这样加速键就是Z。
如果有人认为Z不合适，再改也不迟。

**Comment by lmk123** [comment]
如果是在划词翻译没有权限的页面使用了右键菜单翻译，那么加上快捷键是没有用的，因为用户必须要通过右键菜单点击了，Chrome 才会提供页面上选中的文本给我

**Comment by GH01** [comment]
也许您还是没明白“加速键”的意思。

加速键 就是加在菜单里的。
我在上面详细说了：https://github.com/lmk123/crx-selection-translate/issues/385#issuecomment-372908658

**Comment by lmk123** [comment]
扩展程序本身并不支持“加速键”，举例：划词翻译 v7 有一个“翻译选中的文本”的菜单项，只有用户用鼠标点击了这个菜单项之后，划词翻译才能在没有权限的页面（例如 chrome://extensions 这种页面）获取到被选中的文本，而扩展程序是不支持“加速键”的，所以，你的需求现阶段无法实现

**Comment by lmk123** [comment]
我明白你加速键的意思了，你是想说对于“翻译页面中选中的文本”这种右键菜单，可以直接通过按下键盘按键的形式触发，而不需要在右键菜单中点击。

v7 实际上只有两个菜单项：

1. 翻译选中的文本：这个其实有一个“加速键”，即 Ctrl，选中文本后按下 Ctrl 就会触发翻译；它还有一个扩展程序快捷键 Alt + A
2. 在划词翻译中打开此 PDF：这个没有“加速键”

“加速键”是可以实现的，但是有一些局限性：

1. 只能在划词翻译有权限的页面才有用。例如在 chrome://extension 这种页面，按下 Ctrl 是不能触发“翻译选中的文本”的
2. 一些信息需要用户按下右键菜单才能获取到。例如在一个指向 PDF 文件的链接上单击右键，会有“在划词翻译中打开此 PDF”的选项，但只有用户用鼠标点击了，Chrome 才会把这个链接提供给我；如果使用“加速键”，我是获取不到的

总的来看，加速键是一个挺好的设计，不过我觉得现阶段右键菜单数量并不多，且其中一个其实已经有了加速键，所以我可能会在未来有了更多右键菜单的时候，单独用一项右键菜单的设置来控制每个右键菜单选项的加速键。

**Comment by GH01** [comment]
好像还是不完全对。
大概您从来不用键盘操作菜单。
请容我用拙劣的文字再解释一番：

`“直接通过按下键盘按键的形式触发，而不需要在右键菜单中点击”`看上去有歧义。
其实是：
**在菜单打开之后，用加速键完成点选。**

**加速键的使用 依赖菜单打开，
加速键也只是为了点选菜单项，
加速键 = 更快的点选**
加速键的结果就像：用↑↓键在菜单中选项，然后回车。
您可以打开任一程序的任一菜单，注意那些 **加了下划线的字母**（如果有），用键盘操作，实际体会一下。

电脑上，越是做得好的软件，菜单里的加速键(**加了下划线的字母**)就越完善（直至 每项都有）。

**加速键只是加在菜单项名称中的文字（& + 字母），不消耗资源，无需额外编程。（不像 快捷键 或Ctrl键）
只需把您的菜单项文字改成比如：
`翻译这段文本(&Z)`
`在划词翻译中打开此 &PDF`
这样，打开菜单（就会显示 加了下划线的Z和P），按下Z或P，就完全等同于鼠标点选。
所以我说：加上加速键，只是举手之劳。
几乎不算改动，却大利键盘党，何乐而不为。
无论有多少菜单项，都加上 &字母 就OK了。**

快捷键 或Ctrl键 受权限限制。
**而 加速键 只是菜单项的附属。哪里能打开菜单，哪里就能用加速键。且只有打开菜单才能用加速键。
▲正是想要在 chrome://extension , view-source: 等等页面中 加快查询速度/频繁查询，我才再提此需求。
▲PDF链接上也完全不是问题。**

>一些信息需要用户按下右键菜单才能获取到。例如在一个指向 PDF 文件的链接上单击右键，会有“在划词翻译中打开此 PDF”的选项，但只有用户用鼠标点击了，Chrome 才会把这个链接提供给我；如果使用“加速键”，我是获取不到的

▲不，**加速键 = 鼠标点击！**

也许您会认为：既然打开菜单依赖鼠标，那有什么必要再用键盘去操作菜单呢？
理由：
▲其实打开菜单也可以用键盘（Application键，或叫Menu键），即使是在链接上（当然说这个咱就显得太矫情了，因为要先(用键盘)转焦到链接上）。
▲熟练用户常常是 一手打开菜单，另一手按键，左右配合，更快。
▲鼠标点选 是依赖视觉的精确动作；加速键点选 可以（因熟练/常用而）盲打。
▲加速键点选 更快更省事（因为不用看），尤其当菜单项很多时。**虽然您自己的菜单项只是一两个，但处于浏览器的长菜单中，与其他扩展的菜单项混在一起……所以这就是一个独特的加速键的意义所在（即使加速键有重复，也会加快“眼扫”的速度）。**

当然，如果能实现自定义，也就万事大吉了。

**Comment by lmk123** [comment]
> “直接通过按下键盘按键的形式触发，而不需要在右键菜单中点击”看上去有歧义。
> 其实是：
> 在菜单打开之后，用加速键完成点选。

如果是这样的话，那更加不用讨论了，因为扩展程序做不到这点。。

**Comment by GH01** [comment]
唉，我只是打了个比方……
您该不会只是看了个开头吧？

请回看我的第二帖结尾。
我现在直接改好给你（完全没有技术含量的事）：
在 background.js 中：
把 `翻译这段文本` 改成 `翻译这段文本(&Z)`
把 `在划词翻译中打开此 PDF` 改成 `在划词翻译中打开此 &PDF`
完成了。

结果如图（**不是P的！实际我就这样在用**）：

在PDF链接上（**打开菜单，按P键就触发该菜单项，等同点击**）：

![划词翻译_菜单项_加速键_3](https://user-images.githubusercontent.com/19272301/95403265-50071680-0944-11eb-8d5c-5b1d59567d28.png)

在内置页面(如 扩展页/源代码页)中（**打开菜单，按Z键就触发该菜单项，等同点击**）：
（普通页面就不用说了）

![划词翻译_菜单项_加速键_2](https://user-images.githubusercontent.com/19272301/95403289-63b27d00-0944-11eb-8c8e-5d598454c414.png)

![划词翻译_菜单项_加速键_1](https://user-images.githubusercontent.com/19272301/95403300-6b722180-0944-11eb-99e6-6696d81b5480.png)

改好的文件：
[background_js.zip](https://github.com/lmk123/crx-selection-translate/files/5344817/background_js.zip)

**Comment by lmk123** [comment]
！！！！厉害了，Chrome 扩展程序的开发文档上并没有告之过右键菜单还能这么玩，你是怎么知道的。。。

原来如此简单，我会在下个版本中加入

附：Chrome 扩展程序右键菜单的技术文档 https://developer.chrome.com/extensions/contextMenus

**Comment by lmk123** [comment]
翻译选中的文本的加速键我准备用 T
在划词翻译中打开此 PDF 的加速键我准备用 O

这是考虑到以后划词翻译添加英语界面时，这两项估计会分别翻译为 “Translate this...” 和 "Open in Highlight Transaltor..."，而 T 和 O 是它们的首字母

**Comment by GH01** [comment]
我以为会编程的人都知道这个，所以开头说得很简单，认为你肯定心领神会，讨论中又猜想你是不是怪癖嫌难看才不愿加……

我只懂点皮毛。这是通用方法（依赖系统转义），所以各处都能用。（除了&，有些语言用_）
Chrome文档中没提，我想也是因为这只是个基础知识。
你大概是跳过了一些东西。

在我想来，编程者都会偏爱甚至依赖键盘操作。
如果你有 用键盘操作菜单 的习惯，你可能早就自己补上这一课了。
例如：几乎所有常规窗口都有File菜单，Alt+F就是打开File菜单，然后可以用键盘继续操作……
你的编程工具肯定也是如此设计。

时间久了，我的概念也有点混乱。
搜索相关文档，&字母 称为 menu access/mnemonic key 更好：
https://docs.microsoft.com/en-us/windows/win32/menurc/about-menus#menu-access-keys

这种小细节关乎 User Experience，不见得不重要：
https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus
If possible, choose mnemonic key assignments, especially for frequently used commands.

**至于用哪个字母，让用户自定义 是最好的解决方式。**
否则不可能完美（为这小细节我都要图穷匕首见了，也不吝惜这最后一梭子了）：

加速键是为了加速，所以最好是避免与其他项重了（详见4楼说明：https://github.com/lmk123/crx-selection-translate/issues/385#issuecomment-372908658 ）。
翻译扩展的菜单项一般都以T打头，如果别人也加&，用户这边就不爽利了。
而O，即便别家不用，却会干扰到Chrome自身的菜单项（键盘党往往是用O来遍历那批菜单项的）。
所以最好是个性化，用别人不用的。甚至还应兼顾键盘位置的便利性。
当然，若为英文界面，另加字母 你肯定会认为难看（而我认为是有个性）。
但不见得非得使用首字母。（请观察一下其他程序的各菜单项，包括Chrome。）
其实若用首字母，可以不加&，降低“掠夺性”。

加速键也可以不是字母，可以是符号（如/.=）或空格。全看作者的巧思与个性。
加速键是为会用的人设计的，用者肯定会去适应/记住，没必要考虑太多逻辑性，方便 避重 更重要。

最后一枚子弹：
不会同时出现的菜单项（就像你这两个），可以统一用同一个加速键，这样用户只需记住一个键，不假思索地盲击。

（其实吧，我Z键已经用惯了，你要是不加自定义，我还是有自改的冲动……）

**Comment by lmk123** [comment]
> 我以为会编程的人都知道这个，所以开头说得很简单

然而我并不知道 :joy:

> 其实吧，我Z键已经用惯了，你要是不加自定义，我还是有自改的冲动……

行，看在你为这个加速键打了这么多字，我给你全用 “Z” 键吧

**Comment by GH01** [comment]
在PDF页内选中文本，打开右键菜单，
你把两个菜单项放在子菜单里（且加速键相同），且父项没有加速键，这就太不方便了。

建议：
▲此时的右键菜单，总项数并不多。所以你的两项完全可以直接摊放，没必要用子菜单。（别的扩展也有这么做的。）
▲既然两项并列，加速键最好不同。（加速键相同 是供用户遍历(以慎选)的。）
▲如果一定要用子菜单，那么父项最好也有加速键（或首字母）。

**Comment by lmk123** [comment]
> 此时的右键菜单，总项数并不多。所以你的两项完全可以直接摊放，没必要用子菜单。（别的扩展也有这么做的。）

不应该，因为如果一个扩展有多个菜单项，那么浏览器会强制提供一个父项，且这个父项的名字一定是扩展的名字，不可配置（也就是我也没法给它加加速键），所以每个扩展在右键菜单的一级菜单中最多只占用一项。你看到哪个扩展是同时有多个项的？我可以研究一下

> 既然两项并列，加速键最好不同。

其实只有在 pdf 页内才会出现两项并列的情况，所以我当时觉得这样应该也没啥问题。当然我也可以把加速键改成不同的，你觉得分别用什么加速键比较好？

**Comment by lmk123** [comment]
另外，我发现用 &Z 的方式在 MacOS 中无效，下次我用你提到的 _Z 试试

**Comment by GH01** [comment]
看来是我记错了，别人也是子菜单……
原来Chromium这样安排，有点霸道……
那有个英文名字就变得重要起来，首字母还得特别点儿……

这样的话，我的建议是：
在有选中文字时，就别显示“打开PDF”那项了。
反正不选中文字时可以打开。

至于“用不同的加速键”，我个人觉得P更好。
当然这个无所谓，随你定。

https://discussions.apple.com/thread/7983221
原来macOS没这特性，幸好没钱不冲动……

**Comment by GH01** [comment]
原文已有P，直接加&岂不更好（通常都是这样做的），显示会更清爽不累赘：
`在划词翻译中打开此 &PDF`

**Comment by lmk123** [comment]
我是为了跟 Chrome 自己的菜单项保持一致，即都在最后用括号将加速键包裹起来，所以就统一都用这种形式了

![image](https://user-images.githubusercontent.com/5035625/99141847-1daab080-268a-11eb-934f-67a2791c5683.png)

**Comment by GH01** [comment]
Chromium/Chrome的汉译也是特别（我注意到它们的“关于”项）……
通常都是 有则用，没有才加：
![menu access~mnemonic key](https://user-images.githubusercontent.com/19272301/99143945-bf3afd80-269c-11eb-8063-fdef7b49d9f2.png)
