### ISSUE TITLE
三击选段时不要触发双击划选

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#388]
网页中，双击选词，三击选段。

所以，最好能实现：
先等待三击事件，若无三击，才响应双击。

或者，能允许自定义 自动拾取 的时间。

**Comment by lmk123** [comment]
我不觉得先双击选词有什么问题，这对你造成了什么困扰吗？

**Comment by GH01** [comment]
现状：
在三击选段时，必然先触发双击事件（先去译词），无谓地多连接1次，浮窗(内容+大小)多变化1次，感受不舒服。

**Comment by lmk123** [comment]
我理解你的意思了，新版本中会优化这种情况

**Comment by GH01** [comment]
这种情况还是不能完善吗？

**Comment by lmk123** [comment]
在 v7 中我其实研究过这个问题，但最终的解决方案是双击的时候用户需要多等待 500ms；当然也可以像你说的那样加个选项，由用户来判断要不要在双击时多等待 500ms。

但最终我还是把这个功能去掉了，原因如下：

1. 首先，让所有用户双击时都等待 500ms 肯定是不能接受的
2. 其次，如果加个选项，我又觉得这个选项加的不值——前面提到过，我不想加很多选项，让划词翻译变得复杂。我觉得大部分用户双击或三击后都是先弹出翻译按钮的，而三击时多触发一次双击造成的浮窗宽高变化一次我觉得体验上并没有很难以接受。

如果后面有更多用户提到了这个问题，我还是会考虑加个选项的。

**Comment by GH01** [comment]
试想，如果实现并开启了 #389 (非仅针对词)，
三击时，浮窗会有更多 忽闪+尺寸开合，
段落越大，会越感觉稀里哗啦……

然而连 #389 也被关闭了……

**Comment by lmk123** [comment]
#389 关闭的原因也是我觉得大多数人取词就够了，再给他们加上取句子、取段落但大部分人又不用，就会要求我加选项把这些功能关闭。。

这样的话，为了加这些不常用的功能还得加设置项关闭，我的时间消耗了、大部分人又不用、软件变复杂了，总觉得得不偿失
