### ISSUE TITLE
+ 选项：浮窗固定时自动拾取

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#389]
+ 选项：当浮窗被固定时，自动拾取选中文本
（固定期间，无需Ctrl键配合，不显[译]按钮）

**Comment by lmk123** [comment]
v7.0 已支持鼠标悬浮取词，不过是需要开启一个开关的。这个问题先暂时关闭，等 7.0 发布之后你再看看新版本的体验如何。

**Comment by GH01** [comment]
鼠标悬浮取词 只能针对词，
在频繁操作 句子/大段文字/任意选块 时不适用。

而且此选项还有赖 #472 #729 #388 等的完善。

**Comment by GH01** [comment]
这个“鼠标悬浮取词”要怎样设置才能出来？
没见有开关或说明……

**Comment by lmk123** [comment]
![image](https://user-images.githubusercontent.com/5035625/100088790-a5af6800-2e8b-11eb-9c29-95915418ca24.png)

**Comment by GH01** [comment]
呃……用过竟忘了……痴呆前兆…… :face_with_head_bandage:
