### ISSUE TITLE
访问电商网站自动跳转?

### ISSUE THREAD

**Issue by avkiller** [lmk123/crx-selection-translate#39]
禁用掉发现正常

**Comment by lmk123** [comment]
是的，在 v5.1 以前是会跳转的，但是之后我就把代码开源并删除了相关跳转代码。你大概是没有升级到最新版 :)

**Comment by lmk123** [comment]
没有回应，假设问题已解决

**Comment by avkiller** [comment]
不是很清楚之前是多少版本,今天看到了下是5.6 没发现问题

建议添加一个选项来处理这些,这样会好一点

**Comment by lmk123** [comment]
就像我上面所说的，跳转代码已经被完全移除了，所以没必要加选项了 :) 当然，不仅仅是扩展，某些电脑上的软件也会造成电商网站跳转的。
