### ISSUE TITLE
关/开“所有网站禁用”须刷新页面才能完全起效

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#390]
我平时用得少，所以日常设置是：所有网站禁用 + 右键菜单项
这样，平时只用右键菜单项（我想这样是最省资源的吧）。
但有时，需要（在非汉非英网页上）持续频繁使用。

设想：
所以，我非常希望弹窗中能有个开关，当我需要持续频繁使用时才开（自动拾取），用后即关（但不影响右键菜单项）。

现状1：
目前，我若临时去关/开“所有网站禁用”，则须刷新页面（可能导致内容改变）才能完全起效。（若能解决这个问题也行）

现状2：
工具栏按钮弹窗中的“已对当前网站启用/禁用”只是用来添加/删除 禁用项 的。
即使能添加 启用项，我个人也不喜欢这种管理方式。

**Comment by lmk123** [comment]
启用项后面会改成黑/白名单模式，你可以按照自己的喜好选择。

也许加一个全局开启/关闭的快捷键会更方便？

**Comment by GH01** [comment]
>也许加一个全局开启/关闭的快捷键会更方便？
我目前就是这样用了，连右键菜单项都关掉了。
（只是我的常用程序把方便的键位都用完了……当然这个可以自己慢慢调整。也等着Vivaldi解决故障，那样就不用设为全局了。）

**Comment by lmk123** [comment]
v7.0 要发布了，v6.x 的 bug 我就直接关闭了。
