### ISSUE TITLE
+ 结果侧增设：首选语言/辅助语言

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#391]
比如：
首选语言：中文
辅助语言：英文
这样，平时，结果侧显示中文。
而当来源侧为中文时，则结果侧显示英文。
这样便于用户查询第二语言。

现状：
如果结果侧设为 自动选择 或 中文，则来源侧“不忽略中文”显得没有意义。
结果侧的 自动选择 也显得没有意义。

FYI：
Rememberry的设计：
Webpage/Popup 可以分设不同的语言对。
其Popup中可以切换模式(用途)，这一点也值得参考。一些必要的选项最好放到弹窗/浮窗中，便于切换。

**Comment by lmk123** [comment]
跟我的想法不谋而合 😂

**Comment by lmk123** [comment]
v7.0 中将首选语言改为了全局设置，不过没有加入“辅助语言”的设置，我感觉只是多了一次首选语言的切换。这个问题我先关闭，等新版本发布后你再看看体验如何。
