### ISSUE TITLE
处理下划线/中划线分隔或驼峰式的单词形式

### ISSUE THREAD

**Issue by yang7951** [lmk123/crx-selection-translate#395]
AbilityTextureName
DOTA_ABILITY_BEHAVIOR_PASSIVE
这种特殊情况无法翻译

**Comment by lmk123** [comment]
也许我可以加个设置项用于处理这种分隔的单词的形式

**Comment by yang7951** [comment]
非常希望能改进，我试过啊其他翻译软件都不能识别，谷歌可能还好点，它会提供建议，但也很麻烦。
