### ISSUE TITLE
是否可以增加历史翻译保存功能？

### ISSUE THREAD

**Issue by Ctipsy** [lmk123/crx-selection-translate#399]
个人觉得是一项不错的功能，积累词汇

**Comment by perfectZh** [comment]
建议增加

**Comment by lmk123** [comment]
重复 #242，后续进展会更新在 #242 中

新版本中会加入翻译的历史记录。

**Comment by Ctipsy** [comment]
> 重复 #242，后续进展会更新在 #242 中
> 
> 新版本中会加入翻译的历史记录。

期待更新！
