### ISSUE TITLE
建议添加划词联想，可以不需要将单词完整划下

### ISSUE THREAD

**Issue by tiger-ll** [lmk123/crx-selection-translate#40]
有时候操作的很快，或者使用触摸板来划词，将词完整划出来很不方便，是否可以添加联想option来提高使用的灵活和敏捷度？

**Comment by tiger-ll** [comment]
补充一个问题：划词翻译和其他即时翻译应用都有需要等待翻译时间的问题，如果是偶尔查一个词这样的等待没有什么影响。但是如果要进行长篇的阅读这样的一个响应时间其实会对阅读流畅度有一定的干扰。而且其实在阅读长篇时会停留在网页上很久，要是能利用阅读的时间完成文章中单词的翻译，然后快速对接下来的划词翻译做出响应会不会使得在长篇阅读中用起来更顺手一些？是不是能增加一个功能，将全篇的词语翻译都缓存起来，然后划词翻译时快速读取缓冲中的翻译。

**Comment by lmk123** [comment]
联想划词真是一个很酷的想法，但是从程序上来实现没有意义。划词翻译仅仅是一个 75KB 的小程序，不想再附带完整的英汉词典来进行联想。

预先分析出文章里面所有的单词并缓存翻译结果也是不可行的，因为翻译接口有使用频率限制，如果每打开一个网页都要消耗20次翻译次数，那么在划词翻译近两万的用户基数下，翻译接口很快就会被封禁；更何况划词翻译并不知道用户将要翻译单词、短语还是句子，即使保存了“hello”的翻译结果，翻译“hello world”的时候还是要再查询一次。

综上所述，划词翻译可能并不适合你，也许你可以下载一个有道词典客户端，它能满足你对阅读流畅度的要求 :)
