### ISSUE TITLE
希望能加入单词本和词频功能

### ISSUE THREAD

**Issue by kyleinfo** [lmk123/crx-selection-translate#41]
希望能够让查询过的单词自动加入单词本，并且在单词本中可以查看、删除查询的单词，再配合记录单词本中每个单词被查询的次数的功能。这样的话，使用者通过单词本自动收集不认识的单词，再通过记录每个单词被查次数的功能筛选出对用户而言的高频词，便可以针对性的记忆这些高频词。
这个想法是在参照知乎里如何学英语的话题时根据透析法修改来的，浏览器承担着用户接触英语的责任，在查词的过程中，生词本会容纳对用户而言的生词，但生词有高频和低频，这样就得用记录查询次数的方法透析出高频词。
假如能够实现这些功能的话，就是真的是学英语者福音了。

**Comment by cenxun** [comment]
+1024 赞赞赞，生词本功能。

**Comment by cenxun** [comment]
可以考虑下扇贝网  :)

**Comment by lmk123** [comment]
好的，我会找个时间去看看扇贝网的 api 的 :)

**Comment by isevenfox** [comment]
求同单词本功能。。做好能够有道连接起来。。。。 作者辛苦了！！

**Comment by forecho** [comment]
同求此功能

**Comment by lmk123** [comment]
各位，我考虑了一下，决定不实现单词本功能了。

划词翻译的定位是一款多语言翻译工具，虽然用户使用它翻译的最多的语言可能就是英语，但这并不意味着划词翻译就应该_顺便_充当一个学习英语的工具。我认为，一款软件应该有它的核心功能并**保持简单**，而不是变得大而全（或者说_臃肿_）。

我先关闭这个问题，但如果你们有不同意见，欢迎在下面留言 :)

**Comment by GameRisker** [comment]
大家都有兴趣，可以一起重开个新项目，两个项目都独立，依赖一套API就好！

**Comment by wangshifeng** [comment]
感谢作者，这是我最喜欢的chrome插件之一。看老外写的文章遇到不会的单词查起来很方便。但是当一个单词划了10遍都没有记住，就下定决心一定要记住这个单词。用有道单词本背单词体验很不错，建议做个把单词添加到有道单词本的功能。

**Comment by EasyChris** [comment]
> 

不知道这么多年过去了，作者还有没有想法开发一个跟划词同步的记单词软件

最近又碰到这个痛点了，开始看纯英文的技术文档，有一些高频词，还是希望能独立出来去记，但是划词只有收藏功能。

收藏是存在indexdb中，其实通过相应的接口应该能直接访问到，然后是不是进行卡片式的回忆？如果我尝试去读取划词的indexdb，会侵权么？

划词也上线了会员功能，这个会不会是一个付费的痛点呢？

**Comment by lmk123** [comment]
> 如果我尝试去读取划词的indexdb，会侵权么？

不会。如果你想的话，你完全可以从 indexdb 里读出你收藏的单词。其实一直有用户希望我加一个导出功能，我一直没加 :joy:

> 不知道这么多年过去了，作者还有没有想法开发一个跟划词同步的记单词软件

目前没有。我现阶段最主要关注的仍然是划词翻译的核心翻译体验，毕竟还有一百来个 issue 没处理 😂 

我可能会加一些功能，将收藏夹里的单词导出到别的软件里，例如 anki #1265
