### ISSUE TITLE
请加进腾讯翻译君，ipad上的取词翻译应用多看阅读就是用的这个还不错哦

### ISSUE THREAD

**Issue by pendave** [lmk123/crx-selection-translate#414]
请加进腾讯翻译君，ipad上的取词翻译应用多看阅读就是用的这个还不错哦
看书的时候，翻译的效果不错，应该是神经网络翻译的效果。

谢谢啊

**Comment by drogga** [comment]
同求 腾讯的日语翻译质量是目前最好的了

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，腾讯翻译君已经列在了上面。
