### ISSUE TITLE
临界超长(?)时，会不再显示浮窗，除非刷新

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#418]
做了一个极限测试：

选中文字 超长时会显示：（这个我视为正常）
> 接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。 重试

但在**临界**超长(?)时，会不再显示浮窗，除非刷新页面。

测试所用网址：
http://www.english-for-students.com/english-blog.html

**Comment by lmk123** [comment]
能确认一下 v7 目前还有这个问题吗？

**Comment by GH01** [comment]
在该页试了几次，未发生。
反正也没人这么虐……

**Comment by lmk123** [comment]
那我就先关闭了，如果有的话可以再留言
