### ISSUE TITLE
添加更多的网页翻译工具

### ISSUE THREAD

**Issue by An0nymous0** [lmk123/crx-selection-translate#42]
希望可以加入网页翻译的默认翻译引擎。 现在默认alt+z网页翻译是有道吧。 
有的时候有道感觉并不准确。 但是速度比较快。 翻译不准确的时候我一般都会去用必应翻译 去翻译网页。bing感觉比有道准确一些。 
功能大概就是 alt+z可以用预设的网页翻译引擎

**Comment by lmk123** [comment]
目前划词翻译里只有 有道网页翻译，看来有必要多加几个其他的网页翻译了。
我会把 必应、谷歌、微软的网页翻译加进来的，并给出一个设置来设置使用 alt + z 时的默认网页翻译。

**Comment by An0nymous0** [comment]
@lmk123 Thanks！

**Comment by lmk123** [comment]
已添加[必应网页翻译](http://www.bing.com/widget/translator)（eb363d2）与[谷歌网页翻译](http://translate.google.com/manager/website/?hl=zh-CN)（9f73360）。

现在需要在弹出页那里加一个选择列表，让用户可以从有道、必应、谷歌这三种网页翻译中选择一项。

还需要添加一个设置项，用于指定 Alt + Z 时的默认网页翻译。
