### ISSUE TITLE
关于界面上的一点小小的建议

### ISSUE THREAD

**Issue by missuor** [lmk123/crx-selection-translate#421]
你好,插件写的很棒,用起来很流畅,谢谢, 有一点小小的建议:能不能把界面做的更简洁一些呢?或者部分元素做成可配置的,这样对于像我这样的比较喜欢简单风格的用户来说还是挺不错的,今天第一次装,直接控制台简单的删了点元素,改了几个样式,类似这样的效果(只是作了个示范,好不好看另外再说,哈哈)
![image](https://user-images.githubusercontent.com/4561294/39299326-0c508c5e-497b-11e8-8afd-33db1b17042b.png)
下面这张图是谷歌词典的界面,非常非常简单,基本上有点无侵入试的感觉了
![image](https://user-images.githubusercontent.com/4561294/39299448-4bb291d0-497b-11e8-91c6-6d36cdea04b9.png)
![image](https://user-images.githubusercontent.com/4561294/39299638-cc381226-497b-11e8-9cb4-93ff9ed10a50.png)
红框里面基本上是很少用到的元素,是不是可以拿掉或者做成可配置的
![image](https://user-images.githubusercontent.com/4561294/39299747-10c780c0-497c-11e8-9695-17043c0a01b7.png)
两个朗读是不是重复了,暂时就想到这么多.

**Comment by missuor** [comment]
![image](https://user-images.githubusercontent.com/4561294/39506378-b6c73258-4e0a-11e8-8f3e-02700333a493.png)
顺便贴一下今天在qq邮箱里面看到的界面,也挺简洁的
http://dict-co.iciba.com/api/dictionary.php?w=corporation&key=71C35ABEBD38D433050C0D472F46F216&type=json

**Comment by lmk123** [comment]
v7.0 已经完全重新设计了界面，但由于会同时展示三个翻译服务的结果，尽管我已经尽可能的缩小了元素之间的间隙，但看起来不会像你希望的那样简洁，先用用看吧。。

**Comment by missuor** [comment]
干得漂亮！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "github"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 凌晨4:59
收件人: "lmk123/crx-selection-translate"<crx-selection-translate@noreply.github.com&gt;; 
抄送: "Mr.Hu"<sayseesea@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lmk123/crx-selection-translate] 关于界面上的一点小小的建议 (#421)





 
v7.0 已经完全重新设计了界面，但由于会同时展示三个翻译服务的结果，尽管我已经尽可能的缩小了元素之间的间隙，但看起来不会像你希望的那样简洁，先用用看吧。。
 
&mdash;
