### ISSUE TITLE
总是从提供音标的翻译接口里（例如百度）获取音标提供给其它接口

### ISSUE THREAD

**Issue by bagualing** [lmk123/crx-selection-translate#423]
除了百度翻译引擎外，其它几个都不能显示单词的音标？？

**Comment by akokak** [comment]
而且百度显示的音标有的时候还是乱码，请在下一版改进吧，谢谢！
或者可以在设置里选择要使用的音标字体。

**Comment by lmk123** [comment]
这里面只有百度提供了音标，其他几个都没有提供。

后面会尝试总是通过百度翻译去获取音标显示出来。

**Comment by changxinjie** [comment]
+1, 国内谷歌.

**Comment by lmk123** [comment]
谷歌翻译的结果是从 https://translate.google.cn/ 获取的，但是它没有提供音标，所以目前划词翻译在用谷歌翻译的时候没有显示音标。

但我想了想，其实可以总是从百度翻译获取音标显示出来。

**Comment by yixvan6** [comment]
加上音标更好，最好美式和英式都有

**Comment by wayone** [comment]
> 这里面只有百度提供了音标，其他几个都没有提供。
> 
> 后面会尝试总是通过百度翻译去获取音标显示出来。

现在有音标了，能否在音标上面一行把单词再写出来，这样上下单词和音标对齐，方便识别和学习。

**Comment by lmk123** [comment]
新版本已经快开发完了，关于音标这个问题，目前在新版本里会同时显示多个翻译接口的结果，如下图：

![image](https://user-images.githubusercontent.com/5035625/86766961-d5e1a000-c07d-11ea-8ae7-d2b0608c45e7.png)

这样的话就能同时看到有道的翻译和百度的音标了。

大家有啥想法欢迎留言

**Comment by lmk123** [comment]
v7.0 已经改为了同时显示三个翻译服务的结果，所以会一直有音标，将在近期发布。
