### ISSUE TITLE
划词翻译没有权限操作当前网页

### ISSUE THREAD

**Issue by mapleray** [lmk123/crx-selection-translate#425]
URL: http://www.bottomupcs.com

在该网站上划词翻译显示：划词翻译没有权限操作当前网页

这个页面有什么特别的地方吗？

**Comment by mapleray** [comment]
页面结构问题导致插件没法正确获取元素

**Comment by lmk123** [comment]
重复 #135，后续进展会更新在 #135 中。

新版本会修复这个问题
