### ISSUE TITLE
将两个朗读做下区分？

### ISSUE THREAD

**Issue by CHN-STUDENT** [lmk123/crx-selection-translate#438]
![tim 20180607063453](https://user-images.githubusercontent.com/21209416/41068628-f4c787d2-6a1c-11e8-9b6d-f431c5102c15.png)
如图，上面那个朗读应该是朗读原文（选中内容），下面那个应该是朗读翻译。
而在显示时候没做区分？
有没有必要做下区分？

**Comment by lmk123** [comment]
有

**Comment by lmk123** [comment]
v7.0 中删除了阅读原文，改为给每个翻译服务提供了翻译译文的按钮。
