### ISSUE TITLE
建议增加翻译盒子实时翻译功能

### ISSUE THREAD

**Issue by zhangnew** [lmk123/crx-selection-translate#44]
就是点击浏览器右上角插件图标时出现的翻译盒子，可不可以检测一下用户1秒（或者0.5s ?）内停止输入的话，就自动查询并返回结果，而不是每次输入都要手动点击 “翻译” 按钮。

另外翻译盒子中可不可以通过按 Enter 回车键来关联 “翻译” 按钮呢？

PS：插件很好用，感谢作者！

**Comment by lmk123** [comment]
第一个功能很好，我会添加进去的 :)
第二个也可以做到，可是我觉得回车键一般都是用来换行的，让我考虑一下吧 :)

**Comment by zhangnew** [comment]
第一个功能有了就不用 Enter 了。（刚发现Ctrl+Enter可以快速翻译，也不错。）

用了半天，又发现一点小建议：
1、网页中的翻译结果界面宽度不能调整，应该在界面右下角增加一个可调整界面大小的功能，就像 github 这个输入框一样。
2、还是点击图标出现的翻译盒子的问题，这个目标语言『自动识别』在『谷歌(国外)』的时候无效，我输入中文返回的还是中文。(环境：windows8.1，Chrome42，校园网ShadowSocks翻墙，看你的文档说谷歌国内不能用，另外我这里必应也不能用，仅供参考。)

**Comment by lmk123** [comment]
因为谷歌的默认目标语言就是中文，所以它把中文翻译成中文是“正常行为”，毕竟谷歌面向的是全世界的用户，有太多语种了；然而有道和百度基本上就是面向中国用户的，所以可以安全的做些符合中国用户的使用习惯，即把中文自动翻译成英文之类的。

必应翻译的问题我也收到反馈了，我会抽时间看看的。
