### ISSUE TITLE
翻译窗口中选择了源语言和目标语言后，下次翻译时保持不变

### ISSUE THREAD

**Issue by chaoyenjau** [lmk123/crx-selection-translate#445]
使用过很多个划词翻译插件后,发现这款最赞,不过还是有一些使用体验上的小建议:
自动判断的待翻译语言很多时候并不准确, 明明是英语却发出各种奇奇怪怪的音.在窗口中设置后只能在当前页面有效.所以建议在设置中添加待翻译语言的手动选择项,以提高使用体验,适应更多用户.
如能增加这个功能,简直完美!

**Comment by lmk123** [comment]
设置之后有个问题是如果换了个语言环境——例如你设置里设置的英语，但当你划词划的是法语的时候——那么就会出现翻译不准确的情况，你还是需要在窗口里改一下。

不过我可以保留在窗口里选中的语言。

**Comment by vungsung** [comment]
希望划词弹窗Pop-Up也能设置默认的目标语言

**Comment by lmk123** [comment]
v7.0 已实现了这个功能，将在近期发布。
