### ISSUE TITLE
翻译框溢出？

### ISSUE THREAD

**Issue by Hircine** [lmk123/crx-selection-translate#449]
![snipaste_2018-07-09_03-49-43](https://user-images.githubusercontent.com/15918987/42423342-5b2b17f6-832b-11e8-9cdb-0a912a39a8b5.jpg)
以上。

**Comment by Famine-Life** [comment]
![image](https://user-images.githubusercontent.com/26076994/49203495-702e2c00-f3e3-11e8-98a7-90966e78224e.png)

是的，以上。怎么截断才比较完美呢 0.0

**Comment by lmk123** [comment]
新版本中已经没有这个问题了
