### ISSUE TITLE
Alt+A 快捷键翻译，翻译框不跟随

### ISSUE THREAD

**Issue by KiraSabbah** [lmk123/crx-selection-translate#458]
![7 6i1bvn 6_ 3m4vfueyri4](https://user-images.githubusercontent.com/10340697/43250710-8bf437f0-90f0-11e8-8b2d-4a8745072e84.png)
Chrome版本：67.0.3396.99，插件版本：6.4.0

**Comment by lmk123** [comment]
我在 v7.0 中把这个快捷键删除了，因为感觉用快捷键翻译的场景较少，右键菜单翻译比快捷键更便捷一些。v7.0 将在近期发布。
