### ISSUE TITLE
建议加入彩云小译

### ISSUE THREAD

**Issue by eminemcola** [lmk123/crx-selection-translate#466]
中英互译最好的应该是搜狗了吧，无奈收费，跟它有个差不多的是彩云小译，英译中也是不错的，加不了搜狗建议加一个彩云小译的翻译

https://caiyunapp.com/fanyi/
https://wiki.swarma.net/index.php/%E5%BD%A9%E4%BA%91%E5%B0%8F%E8%AF%91API

还有建议可以美化一下样式外观配色，好丑- -

**Comment by butaixianran** [comment]
**再次建议，希望优先加入彩云小译。原因是：彩云小译在部分日文翻译上，比所有其他AI翻译准确。**

举例01：
日文：しゅうまい，是中国食物“烧卖”的意思。
但，包括百度、阿里翻译、腾讯翻译、deepl在内，全都翻译错误。百度翻译为：善于应酬。
所有基于机器学习的翻译工具中，只有“彩云小译”准确翻译为：烧卖。

举例02:
日文：マーメイド，是美人鱼的意思。
但，包括百度、阿里翻译、腾讯翻译、deepl在内，全都翻译错误。百度翻译为：同士。
只有“彩云小译”准确翻译为：美人鱼。

以上只是冰山一角。虽然大家都是机器学习的翻译工具，但小云彩译的日文词汇量，明显大于其他几个翻译工具。

**Comment by lmk123** [comment]
@butaixianran 收到。添加更多翻译源已在开发计划当中，我会优先将彩云小译加进去。

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，彩云小译列在了上面。
