### ISSUE TITLE
翻译多行文本时没有译文

### ISSUE THREAD

**Issue by 17279909** [lmk123/crx-selection-translate#469]
Google Chrome版本 68.0.3440.84（正式版本） （32 位）
插件版本V6.4.0
翻译后不显示译文，其他功能都可用(包括朗读，复制)
重启(或过一段时间)后就好了，不过过一段时间又会这样
https://www.codecademy.com/courses/learn-html/quizzes/intro
是在这个网站出错的，其他的就不知道了，是这个网站的问题吗？

**Comment by lmk123** [comment]
重现了，在翻译多行文本的时候，百度和谷歌都会空白，但其实接口是有数据的。

你试试翻译一下下面这些文本是不是也是没有译文

```
Interactive Lesson
HTML Document Standards
Interactive Lesson
PRO
Pro
Fashion Blog
Freeform Project
PRO
Pro
Introduction to HTML
```

**Comment by 17279909** [comment]
是的，的确没有译文

**Comment by 17279909** [comment]
加油ヾ(◍°∇°◍)ﾉﾞ

**Comment by GH01** [comment]
也不必然，有时可以。

不过测试中发现另一问题：
以lmk123那两行中文为例：
三击选中一行，然后按下快捷键，结果(有时)浮窗就永久显示：正在查询，请稍候……
此时浮窗无法用Esc键关闭（其他操作也无效，除了齿轮），除非刷新页面。

**Comment by lmk123** [comment]
在新版本中已经没有这个问题了
