### ISSUE TITLE
之前给划词翻译做的皮肤，让作者赶紧更新出来吧。

### ISSUE THREAD

**Issue by strongshuai** [lmk123/crx-selection-translate#473]
![Image of Yaktocat](http://thyrsi.com/t6/357/1534367317x-1404755690.jpg)
之前给划词翻译做的皮肤，让作者赶紧更新出来吧。

**Comment by strongshuai** [comment]
还有希望可以出一个firefox版本，现在新版的firefox比chrome好用多了，速度快还不怎么吃内存。

**Comment by lmk123** [comment]
我打算写一个新版了，所以旧版不想动了。

**Comment by strongshuai** [comment]
@lmk123 出一个firefox版吧。。新版的firefox真的不错。用了几个月，前几天换回firefox发现太吃内存了，开了十几个页面一定会卡，新firefox一点不会。。老的firefox不行，新的真的行！

**Comment by realchoi** [comment]
嗯，同希望能出一个更好看的皮肤，另外翻译有时候会卡死。

**Comment by eyezion** [comment]
@lmk123 旧版再更新一版先把这楼主的皮肤更新出来吧

**Comment by lmk123** [comment]
v7.0 已经完全重新设计了界面，将在近期发布。
