### ISSUE TITLE
无论使用哪个翻译引擎，朗读时都是谷歌的美式朗读，怎么更换为百度的朗读呢？

### ISSUE THREAD

**Issue by Monster0303** [lmk123/crx-selection-translate#475]
如题，当前版本：v6.4.0，

**Comment by lmk123** [comment]
划词翻译默认会使用当前翻译引擎的朗读，但如果当前的朗读失败了，就会回退到谷歌的朗读。

出现这个问题可能是百度的朗读挂了，我检查看看

**Comment by ljf0717** [comment]
ok~~所以目前来看朗读依然都是google的，所以百度的朗读彻底挂了。。？

**Comment by lmk123** [comment]
新版本里已经没有这个问题了
