### ISSUE TITLE
改动快捷键 不能立即生效

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#482]
将"翻译网页中选中的文本"快捷键从 Ctrl+D 改为 Ctrl+Shift+Space
重启程序才生效

**Comment by GH01** [comment]
Chrome中也一样。
这是必然吗？

**Comment by lmk123** [comment]
我感觉这是 Chrome 的 bug，最新版 Chrome 还有吗？

**Comment by GH01** [comment]
这个问题同样符合我在 https://github.com/lmk123/crx-selection-translate/issues/731#issuecomment-686431445 说到的情况（是Chrome自身的毛病）。

改前若先关掉“全局”，则改动立即生效。
若保持“全局”直接改，则须重启程序才生效。（此时用 HotKeysList 观察，本轮会话期间，旧键已无法被移除，导致新键注册不了。）

**Comment by lmk123** [comment]
我估计也只能在常见问题提醒一下用户了
