### ISSUE TITLE
划词翻译后，弹出框被页面其他元素覆盖

### ISSUE THREAD

**Issue by ladyrick** [lmk123/crx-selection-translate#488]
划词翻译后，弹出框被页面其他元素覆盖。而且由于标题栏被覆盖，也没有办法移动弹出框。

这说明z-index设置得还不够大。建议将z-index设置成100个9，问题解决。
更好的解决办法是，在选项里设置默认的弹出框位置。或者可以记住上次弹出框的位置也可以。

**Comment by lmk123** [comment]
能提供一下URL 吗？我检查一下

**Comment by ladyrick** [comment]
https://www.journals.elsevier.com/microelectronics-journal/call-for-papers/special-issue-of-mej-on-approximate-computing-co-design-of-c
谢谢

**Comment by lmk123** [comment]
v7.0 中已解决这个问题，将在近期发布。
