### ISSUE TITLE
建议：翻译结果窗能够跟随页面滚动

### ISSUE THREAD

**Issue by wuqiling97** [lmk123/crx-selection-translate#493]
希望翻译的结果窗能在滚动网页的时候跟随网页的元素。现在的情况是会固定在屏幕的某个位置，如下图，查询 "provides" 之后向下滚，结果窗仍然停留在原位。

![bug](https://user-images.githubusercontent.com/19304928/46002064-94b61100-c0df-11e8-8dea-39f0655964cf.PNG)

可以参考另一个划词翻译项目[ChaZD](https://chrome.google.com/webstore/detail/chazd/nkiipedegbhbjmajlhpegcpcaacbfggp)

**Comment by lmk123** [comment]
v7.0 已将翻译结果改为了跟 ChartZD 类似的跟随页面滚动的弹窗，将在近期发布。

**Comment by GH01** [comment]
7.0.5：
把浮窗拽到网页的边角之外，浮窗会自动回移贴边。

找个有横滚条的网页，
向右横滚，
然后选中文本，打开浮窗，把浮窗拽到左/右边之外，
▲这时回移的定位就不对了（算反了?）
（当心：若是左边，很有可能就救不回了：固定按钮/抓手 全都够不到了……）
