### ISSUE TITLE
翻译弹窗加上关闭按钮

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#495]
Esc键很常用，且易误触。
当窗口固定时，也许应该换个更稳妥/明确的关窗方式。

**Comment by lmk123** [comment]
我右上角加个关闭按钮吧

**Comment by lmk123** [comment]
v7.0 已加入关闭按钮，将在近期发布。

**Comment by GH01** [comment]
但是我希望 在非固定时Esc键仍然可用。

**Comment by GH01** [comment]
相关归并：#130

**Comment by lmk123** [comment]
> 但是我希望 在非固定时Esc键仍然可用。

将在下个版本中重新加入 #733

**Comment by GH01** [comment]
但是，我本是希望：在固定时，Esc键不可用。（回到1楼）
