### ISSUE TITLE
设置页的关于中应该显示当前版本，检查到更新后才显示新版本提示

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#498]
若遇到众所周知的原因，[关于]中似乎永久显示：
当前版本：v6.4.2， 正在检查更新……

这是在持续尝试，还是只是个显示？
希望能快速显示“失败”，以免用户操心。

每次打开都要尝试吗？
没必要。

**Comment by lmk123** [comment]
你一直显示“正在检查更新…”是因为你没有翻墙，不然过一会儿就显示“当前已是最新版本”

我改进一下吧，默认显示当前版本，检查到有更新了再提示

**Comment by lmk123** [comment]
v7 的划词翻译已经没有在关于页面里检查更新了。
