### ISSUE TITLE
国内的谷歌翻译经常出错，不稳定

### ISSUE THREAD

**Issue by glkappe** [lmk123/crx-selection-translate#500]
接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。 重试

**Comment by lmk123** [comment]
国内的谷歌翻译确实不稳定，经常会出现这个问题，但过会儿会恢复。有空了我看看这个问题

**Comment by 2236zml** [comment]
我也是

**Comment by lixin888888** [comment]
我的也是

**Comment by jinxin95** [comment]
是的 ，比较着急

**Comment by GavinZhengOI** [comment]
我也是的。切换引擎到GOOGLE国外翻译挂梯子就好了。只是速度慢了些

**Comment by GavinZhengOI** [comment]
国内翻译https://translate.google.cn/网页版也能正常翻译。应该是bug，不是服务器的锅

**Comment by jinxin95** [comment]
今天又出现了：“接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。”

**Comment by JustinDoIt** [comment]
我的也是

**Comment by lirushi** [comment]
抓找之后看到出现了人机验证，应该频繁请求导致的，重新拨号后可以解决。

**Comment by lmk123** [comment]
> 抓包之后看到出现了人机验证，应该频繁请求导致的，重新拨号后可以解决。

是的，我发现这是谷歌翻译服服务器做的限制，如果同一个 IP 在一段时间内频繁使用，就会出现这个错误，一般半小时之内就会恢复，或者换一个 IP 再使用。

而且我发现谷歌官方的谷歌翻译扩展程序也是有这个问题的，所以这个问题估计解决不了。
