### ISSUE TITLE
应减少无谓的重连（建议优先处理这类问题）

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#505]
▼1▼
在 来源侧 中只是 改变选块/移动光标（文字保持不变），也会导致重连（结果侧有提示）。
▲建议：来源侧激活时(光标在内时)须Ctrl+Enter才连接，或添加[翻译]按钮以手动连接。

发生重连的情况 可能还不仅如此，
我在标签A中打着来源侧(光标在内)，在标签B做别的事，过后回到A，已显示接口错误。

导致接口拒访的原因，可能有一大部分来自这类无谓的重连。

▼2▼
当接口拒访时，开着窗（文字保持不变），期间会有自动重连吗？
有种感觉：如果开着窗，恢复可访 要等更长时间。

**Comment by lmk123** [comment]
v7 中应该已经没有这类问题了吧？
