### ISSUE TITLE
PDF翻译能不能显示下原网址

### ISSUE THREAD

**Issue by a819721810** [lmk123/crx-selection-translate#508]
![image](https://user-images.githubusercontent.com/10041362/47067684-c3c22d00-d21c-11e8-9812-bbdd2e1aeb7c.png)
你看这个上面有时候找不到原网页，就有点麻烦

![image](https://user-images.githubusercontent.com/10041362/47067722-e0f6fb80-d21c-11e8-9e28-c524d988193a.png)
这个就能直接看出来

**Comment by a819721810** [comment]
还有能不能添加翻译本地的PDF文件的功能

**Comment by lmk123** [comment]
本地 PDF 要在扩展设置页勾选「允许访问文件网址」

**Comment by lmk123** [comment]
我会在 v7.2.0 版本中给内置 PDF 阅读器加上“复制 PDF 网址”的按钮，后续进展请关注 #800
