### ISSUE TITLE
🆕希望增加一个配置项，针对不同语言用不同的翻译引擎

### ISSUE THREAD

**Issue by justwezzz** [lmk123/crx-selection-translate#514]
最近在看一些日文资料，发现google的日译中没有baidu的日译中准确，但是google的英译中又把baidu的英译中吊打，导致我看日文就需要切到百度翻译，看英文就要切到谷歌翻译，能不能增加一个配置项可以针对不同语言用不同的翻译引擎🙏

**Comment by lmk123** [comment]
好提议

**Comment by lmk123** [comment]
v7.0 同时展示了三个翻译服务的结果，我觉得这应该能解决你的问题。新版本将在近期发布。
