### ISSUE TITLE
文本太长时不翻译

### ISSUE THREAD

**Issue by linvar** [lmk123/crx-selection-translate#52]
经常需要copy网页上的一大段英文, 
我觉得这个时候没有必要执行翻译请求(结果也是翻译不了),

所以可以考虑增加一个配置项目: 当超过一定长度时不翻译.

thx

**Comment by lmk123** [comment]
首先，只有有道翻译是有翻译长度限制的，而且我无法将这个限制硬编码进代码中，因为长度限制可能会改变；

其次，你可以开启翻译按钮功能，这样划选文字之后只会出现一个翻译按钮，而不会直接翻译。

**Comment by linvar** [comment]
只是增加一个配置项, 不会硬编码到代码中. 
默认不限制, 用户可以配置. 
超过字数则不发出翻译请求, crx插件应该可以控制吧.
