### ISSUE TITLE
翻译的时候，突然原文朗读不了，翻译后的可朗读。

### ISSUE THREAD

**Issue by qingfengfenga** [lmk123/crx-selection-translate#521]
翻译的时候，突然原文朗读不了，翻译后的可朗读。不知道是插件原因还是浏览器或者系统的原因。而且所有的翻译引擎都试过了，一样的结果

**Comment by lmk123** [comment]
我试了一下，所有朗读功能都是正常的，能否给出更详细的信息，例如版本、出现问题的 URL、浏览器版本等帮助我重现你的问题？

**Comment by Jar711red** [comment]
出现了同样的问题 是不是接口的原因？

**Comment by lmk123** [comment]
@Jar711red 我也觉得是接口偶尔不稳定造成的问题，但还需要提供更多信息让我综合判断一下

**Comment by Ed-zlz** [comment]
一样的问题，重启浏览器无效，所有的翻译引擎原文朗读不了，翻译后的可朗读
Google chrome 71.0.3578.98
划词翻译v6.4.3

**Comment by KyleWangLTG** [comment]
一样的问题，原文无法朗读，译文可以朗读。
1. 开始可以正常朗读原文，使用的是google国内翻译，中途google国内翻译出现 ”接口返回了错误的数据 ” ，切换到其他翻译后发现无法朗读原文，重启重装都无法解决。
![image](https://user-images.githubusercontent.com/25734983/50624730-f9de9580-0f5d-11e9-9016-623b4943a8ec.png)

2. 如果把翻译的语言由自动选择，换成英文后，原文可朗读，换回自动选择又无法朗读原文。
![image](https://user-images.githubusercontent.com/25734983/50624701-aec48280-0f5d-11e9-8e74-92bc8f168307.png)

3. google国内翻译可以正常使用后，原文朗读正常了。

Google chrome 71.0.3578.98
划词翻译v6.4.3

**Comment by lmk123** [comment]
看起来跟网络环境有关，朗读跟翻译用的其实都是谷歌翻译的接口，所以如果翻译挂了，那么朗读也会挂。

现在我又试了一下，朗读是没有问题的，如果还会出现类似问题，可以继续留言。
