### ISSUE TITLE
希望能在结果显示窗口中提示一下源语言被识别成什么了

### ISSUE THREAD

**Issue by FlatMapIO** [lmk123/crx-selection-translate#529]
Pulsar 这种单词都检测成西班牙语了.  

**Comment by lmk123** [comment]
自动检测不是一个可以关闭的功能，或者你的意思是提供一个选项，让你每次翻译的时候都需要你自己手动选择语种再翻译？

**Comment by huodon** [comment]
在扩展选项或翻译结果卡中能切换语言就可以. 毕竟90%以上的场景都是英文到中文.  目前只有扩展按钮点击后显示的翻译窗口可以切换语言, 但是又没有记忆功能.  

我有个建议就是翻译结果窗口可以借鉴一下 Google 翻译的界面.  

![image](https://user-images.githubusercontent.com/1720349/49557738-999b0a80-f943-11e8-9b63-8d6bb2cd2c78.png)

**Comment by huodon** [comment]
抱歉没有讲清楚, 语言切换暂时没什么问题. 就是希望能在结果显示窗口中提示一下源语言被识别成什么了. 以及对应的音标也能显示出来.

**Comment by lmk123** [comment]
发现跟 #386 重复了，后续进展会更新在 #386 中

新版本会加入这个功能
