### ISSUE TITLE
能否添加支持系统自身的语音引擎?

### ISSUE THREAD

**Issue by ghost** [lmk123/crx-selection-translate#53]
网络语音似乎没那么快...能否设置使用系统的语音引擎呢?

**Comment by lmk123** [comment]
我查了一下文档，发现 [chrome.tts API](https://crxdoc-zh.appspot.com/extensions/tts) 可以调用系统自身的语音，这真是省了好多事了，我会在目前正在开发中的 v6.0 版使用系统语音的。

**Comment by Hircine** [comment]
Ghost ... - -

**Comment by lmk123** [comment]
虽然报告问题的人已经是 Ghost 了，呃。。。

因为本地语音有各种各样的问题，我刚才又重新使用网络语音了。 #92
