### ISSUE TITLE
能不能设置只自动朗读单个单词（每次要选一段东西复制的时候不停的读）

### ISSUE THREAD

**Issue by knightshaw** [lmk123/crx-selection-translate#531]
开了自动朗读后，有时候在浏览器中要复制一段文字，句子很长的话选中后不停的读，烦死，能不能设置自动朗读的词数，大部分人一般开自动朗读都是听一个单词啊，没有哪个取词软件有这个设置，希望作者能加上

**Comment by lmk123** [comment]
很好的提议

**Comment by lmk123** [comment]
在 v7.0 中我把自动朗读功能去掉了， 但给每个翻译服务都加了一个朗读按钮，这个问题我就先关闭了。
