### ISSUE TITLE
划词翻译与知网冲突

### ISSUE THREAD

**Issue by Pliosauroidea** [lmk123/crx-selection-translate#532]
在知网（cnki.net）下载论文等时，下载按钮会跳转到一个带有插件图标的界面并显示pdf损坏，禁用插件后可正常下载

**Comment by lmk123** [comment]
这是 PDF 功能的已知问题，可以在设置里临时关闭 PDF 功能

**Comment by lmk123** [comment]
新版本已修复了 PDF 不能下载的问题，将在近期发布。之后如果仍有类似问题，欢迎反馈。
