### ISSUE TITLE
希望添加金山词霸翻译接口

### ISSUE THREAD

**Issue by barrer** [lmk123/crx-selection-translate#534]
金山词霸接口：http://open.iciba.com/huaci_new/dict.php?word=test

百度的简明翻译是金山词霸提供的数据，百度划词翻译速度比较慢。若是能直接掉用金山词霸这个接口，速度应该会提升明显。

**Comment by lmk123** [comment]
已在开发计划中

**Comment by siyuan-zhang** [comment]
能不能添加一个腾讯云选项，对于中文翻译成英文，腾讯云翻译比较准确

**Comment by yinzishao** [comment]
搜狗翻译呢？

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，金山词霸、腾讯翻译君、搜狗翻译列在了上面。
