### ISSUE TITLE
翻译PDF有时无法识别换行处的空格

### ISSUE THREAD

**Issue by Nguyendream** [lmk123/crx-selection-translate#536]
![20181223172850](https://user-images.githubusercontent.com/33228912/50382370-a6a45180-06d8-11e9-8299-3613f9e30bb6.png)

**Comment by lmk123** [comment]
下次我会升级内置的 PDF 阅读器到最新版，到时候再看看还有没有这个问题

**Comment by jackwener** [comment]
到了现在还是有这个问题

**Comment by jackwener** [comment]
另外，不是有时，应该是基本上无法识别，希望作者大大及时Fix这个bug

**Comment by lmk123** [comment]
v7.0 使用了最新版本的 PDF 阅读器，将在近期发布。
