### ISSUE TITLE
希望能加入音量控制功能，现在的朗读声音有点大

### ISSUE THREAD

**Issue by MoonCandlen** [lmk123/crx-selection-translate#546]
可能每个电脑都不太一样，我这里的朗读音效超大，开了朗读会超级吵……如果能调节音量就再好不过了！

**Comment by lxr0630** [comment]
我倒是不觉得声音大，我觉得中文朗读的声音太难听了，只有我一个人这么认为吗？

**Comment by MoonCandlen** [comment]
> 我倒是不觉得声音大，我觉得中文朗读的声音太难听了，只有我一个人这么认为吗？

反正也不会拿来朗读中文嘛……无所谓了。但是声音在我这里确实是特别大- -

**Comment by lmk123** [comment]
即将发布的 v7.4.0 会加入调节音量的设置项，具体进展可以看 #851
