### ISSUE TITLE
 划词后的翻译按钮 会跟其它的插件按钮重叠

### ISSUE THREAD

**Issue by zpengcom** [lmk123/crx-selection-translate#554]
划词后的翻译按钮 会跟其它的插件按钮重叠
能否添加一个可以修改位置显示

**Comment by ljlong2006** [comment]
也有这方面的需求，跟划词翻译的一个插件弹出框重叠了，如果能把显示的框修改到鼠标箭头左下显示就好了。可惜自己没接触过代码，在bundle文件夹里找了半天都不知道修改哪个px数字。

**Comment by lmk123** [comment]
我在新版本中会提供两个选项：

1. 设置翻译按钮的偏移位置。现在固定是鼠标的右下角，可以通过设置偏移位置移动到其他地方。
2. 设置翻译结果面板的弹出位置。现在固定是鼠标的右下角，在新版本中翻译结果面板默认会出现在**被划选的文字**的下方，也可以通过设置改为上、右等位置

**Comment by lmk123** [comment]
划词翻译 v8.4.3 添加了下面两个选项用于调整翻译按钮的位置：

![image](https://user-images.githubusercontent.com/5035625/127624511-66fab326-3fb1-41fe-8d5a-e9058110e77a.png)
