### ISSUE TITLE
翻译弹窗样式建议

### ISSUE THREAD

**Issue by Source-Code-Gotterdammerung** [lmk123/crx-selection-translate#558]
尊敬的作者，您好，能否将翻译窗口的样式更改为这样？这样看起来简洁漂亮，译文也是跟随原文长度，可以很好的与原文对照。
![default](https://user-images.githubusercontent.com/47558436/52690812-d9ace800-2f99-11e9-8b2a-6b66d3528405.png)

**Comment by Source-Code-Gotterdammerung** [comment]
或者您能否授权并告知，修改翻译弹窗的样式都需要改动哪些文件，我自己动手来改动。

**Comment by onloner2012** [comment]
> 或者您能否授权并告知，修改翻译弹窗的样式都需要改动哪些文件，我自己动手来改动。

兄弟，你获得了授权了吗？好期待你这个功能啊，这样网页阅读就非常方便了

**Comment by onloner2012** [comment]
> 或者您能否授权并告知，修改翻译弹窗的样式都需要改动哪些文件，我自己动手来改动。

兄弟，你获得了授权了吗？好期待你这个功能啊，这样网页阅读就非常方便了

**Comment by sq800** [comment]
border-radius:10px; 圆润一点也挺好的

**Comment by lmk123** [comment]
v7.0 已经完全重新设计了界面，将在近期发布
