### ISSUE TITLE
建议：建议添加剑桥翻译接口

### ISSUE THREAD

**Issue by epluguo** [lmk123/crx-selection-translate#562]
说实话，百度翻译等翻译的语法、音标多少有些不正确，就目前而言，我发现剑桥的翻译还是比较正确的，特指单词。

我一般只查询单词，不知道大家是不是这样。所以我也没去看剑桥这个是否支持段落翻译

当然，牛津也是比较正确的，只是没有找到免费接口。

下面的是剑桥的翻译接口，希望能加上。
https://dictionary.cambridge.org/dictionary/english-chinese-simplified/hello

当然，如果能开放自定义配置翻译接口及正则识别内容，那就再好不过了。后面大家只要共享配置就行了。

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，剑桥词典列在了上面。
