### ISSUE TITLE
能不能记住上次选择的翻译选项

### ISSUE THREAD

**Issue by lovekobeme** [lmk123/crx-selection-translate#564]
能不能记住上次选择的翻译选项
每次都要点一下百度翻译
想学英语的话 是希望可以看到音标的，所以我每次都要重新点百度翻译

**Comment by oreak** [comment]
the same to me

**Comment by canglan00** [comment]
附议

**Comment by zhangxiusen123** [comment]
新打开一个页面都要选一下英文翻译成汉语，可不可以默认选择英语翻译成汉语或者汉语翻译成英语

**Comment by lmk123** [comment]
新版本中已计划记住源语种和目标语种，后续进展更新在 #445
