### ISSUE TITLE
对于本地markdown文件会提示“连接到翻译引擎时发生了错误”

### ISSUE THREAD

**Issue by McJevons** [lmk123/crx-selection-translate#566]
对本地markdown文件内容选词翻译时，翻译窗口正常显示，但就是无法翻译，提示“连接到翻译引擎时发生了错误”，但对于本地txt文件可以正常翻译

**Comment by lmk123** [comment]
我用划词翻译 v7.0.6 试了一下，用本地 markdown 没有出现这个问题。

出现这个错误一般是因为划词翻译自动更新了，通常重启下浏览器就可以解决。你可以再试一下，如果还是有问题，可以继续留言
