### ISSUE TITLE
系统 125% 缩放后，弹出框模糊

### ISSUE THREAD

**Issue by madokaa** [lmk123/crx-selection-translate#569]
Chrome 版本 73.0.3683.75（正式版本）（64 位）
插件 6.4.3
系统缩放125%后出现很大概率(90%+)的模糊现象，如图：
![模糊](https://user-images.githubusercontent.com/16538800/54593040-93e7b180-4a68-11e9-9560-98a468545241.png)
模糊↑

![不模糊](https://user-images.githubusercontent.com/16538800/54593041-94804800-4a68-11e9-8171-f1a60ea16540.png)
不模糊↑

**Comment by 1476935597** [comment]
为什么有些人喜欢缩放网页。。。

**Comment by madokaa** [comment]
@1476935597 首先缩放的是系统，浏览器没有设置缩放。其次如果你用过高DPI屏幕就不会这么问了。

**Comment by lmk123** [comment]
操作系统是 Windows 10 吗？

**Comment by madokaa** [comment]
> 操作系统是 Windows 10 吗？我在 macOS 上没有重现这个问题，等我找台 Windows 试试

是的

**Comment by bowencool** [comment]
> 为什么有些人喜欢缩放网页。。。

你用4k屏不缩放？

**Comment by melodicule** [comment]
经过测试跟窗口的translate属性有关系，当 (X，Y值 * 浏览器缩放 *系统缩放) 不为整数时，会导致原来的一个像素渲染为两个“半像素”，看起来就模糊。我不太了解那些名词，描述可能不太准确。

**Comment by JmLding** [comment]
我也遇到了相同的问题，同一个单词，我翻译很多次，大概率是模糊的。

**Comment by JmLding** [comment]
> 我也遇到了相同的问题，同一个单词，我翻译很多次，大概率是模糊的。

win10 1909 chrome79

**Comment by kunanaxp** [comment]
划词翻译版本 7.0.1，系统版本 Windows 10 1909，浏览器版本 Chrome 84，系统缩放设置为 125%
依旧存在该问题
![批注 2020-08-29 144515](https://user-images.githubusercontent.com/12630683/91630717-44c6df80-e9c3-11ea-8cab-9538b7768de8.jpg)

**Comment by lmk123** [comment]
是的，这个问题我尝试在新版本中解决过，但调查了一下发现这其实是浏览器的 bug，修改的方式还要再研究一下

**Comment by lmk123** [comment]
我用划词翻译 v7.3.3、Chrome 87 和 Windows 2004 重新试了下，现在没有这个问题了，虽然有点奇怪的是截图的时候会是模糊的，所以我没有放图上来。

我没有针对这个问题做过任何修改，所以我猜测可能是 Chrome 修复了模糊问题，大家可以把 Chrome 升级到最新版试试看。

**Comment by lmk123** [comment]
划词翻译 v7.5.4、Chrome 89 和 WIndows 10 再次尝试了下，我这边没有这个问题了。鉴于也没有类似的反馈了，所以我觉得模糊的问题应该已经不存在了，这个 issue 我就关闭了。

如果还是有类似问题，可以继续留言。
