### ISSUE TITLE
google翻译不显示音标

### ISSUE THREAD

**Issue by sunkyzz** [lmk123/crx-selection-translate#573]
RT 希望加上这个功能

**Comment by ffsxsy** [comment]
我也希望有这个功能

**Comment by nalido** [comment]
我也强烈希望带音标

**Comment by oufu99** [comment]
我觉得不需要,要看音标可以去贩毒翻译之类的地方看,这种小巧的软件就不应该添加那么多功能,现在刚刚好

**Comment by Lord-Fec** [comment]
我也强烈要求加上这个功能，这些音标的显示不会占用什么资源的，而且还有助于学习。（体贴一些那些不喜欢戴着耳机学习的同学们吧）

**Comment by yiwanzi** [comment]
推荐使用百度翻译，带音标

**Comment by Butinc** [comment]
我也强烈建议加上音标，不看音标不容易记忆

**Comment by MaxSherry** [comment]
百度翻译 我这里显示的是"[object Object]"
有道翻译接口有问题,返回数据有误,不显示

**Comment by lmk123** [comment]
跟 #423 重复，后续进展会同步在 #423 中。

新版本中会考虑用合适的方式给不支持音标的翻译接口（例如谷歌）加入音标。
