### ISSUE TITLE
希望别把这款小巧的软件搞得太过臃肿,做到小而美已经很棒了

### ISSUE THREAD

**Issue by oufu99** [lmk123/crx-selection-translate#578]
这划词翻译是我见过最小巧,完全符合一般使用场景的划词翻译了,这和作者定位也应该是有关系的,其他的软件翻译接口多的,有音标的像有道,沙拉都是有的,但是他们太重了,为什么不选择他们呢对于一般的用户来讲(比如我),我就只需要看看翻译结果就行了,他们就显得太重了
   软件的定义如果是小巧,支持大部分人的话就不应该加入太多功能  比如论坛上说的音标,我觉得要看音标,多种翻译结果的大部分都是比较专业的人士,完全可以去百度翻译的网页或者其他的翻译网页去单独查询
   个人觉得这软件最大的特点就是小而美,如果变大了就和那些形成不了差异化了,相反还可能造成满足小部分,牵连了大部分的情况,个人之见,希望作者大人也能参考参考

**Comment by lmk123** [comment]
很巧，这也是我最近在考虑的问题。

最近我一直在计划开发新版本的划词翻译，对要不要全部实现用户的功能需求很纠结。我内心是希望它是一个小而美的软件，但有很多功能确实也比较有用。新版本还是会适当的添加一些功能，不过我能保证的是，我会尽量选择一个平衡点，保持划词翻译“小而美”的核心理念不会改变。

**Comment by tortoo** [comment]
我差不多各种翻译插件都试了，最后留用的是划词翻译。把我对比后认为的优点说下，供作者参考，希望后续的新版也能保留这些。我的设置里，只勾选了配合 ctrl使用划词翻译这一项，其实也是要关闭划词自动翻译的功能，这样就不会对正常划选构成干扰。划选后，如果需要翻译，我会触控板三指轻轻左滑，翻译结果一下就出来了，因为把快捷键给了触控板来触发。基本上，划词翻译就像嵌入了 chrome，平时感受不到存在，需要的时候划一下唤出来，应该没有比这更自然的了。同时，翻译弹框的前景背景颜色和页面保持一致，尤其用了护眼插件修改前景背景后，形式上也和 chrome 页面一体，堪称完美。

总结下优点：响应快，不干扰，颜色和页面一致。

我理解，翻译插件的受众有两类，一类是当即时翻译工具，即划即译，阅读为主，需要响应速度，流畅至上。一类是当英语学习工具，需要音标、词性，需要对比不同引擎翻译结果，需要生词本等等，这种就谈不上流畅了，属于慢工出细活。新功能添加没问题，小众功能但呼声高的话也应该支持，但关键在提供不同细化功能的开关，这样不同人各取所需而且互不干扰。

我对小而美的理解，不是功能少就是小，而是经过优化后资源占用少，响应速度快，即便有新功能加入。用开关关闭某项功能后就能释放这部分的资源占用和响应时间

**Comment by bowencool** [comment]
其他扩展都不能配合ctrl使用，严重影响正常划词，无法忍受

**Comment by lmk123** [comment]
v7.0 已完全重新设计，并且我（自认为）遵循了“小而美”的理念。新版本将在近期发布，欢迎大家发表使用感受。
