### ISSUE TITLE
显示 PDF 原网址及界面优化

### ISSUE THREAD

**Issue by 1269976077** [lmk123/crx-selection-translate#584]
1、翻译失效信息
页面提示如下：
PDF.js v1.4.20 (build: b15f335)
信息：Unexpected server response (0) while retrieving PDF "http://ww1.microchip.com/downloads/en/DeviceDoc/50002539A.pdf".

PDF来源网址：
MPLAB PM3 Universal Device Programmer
https://www.microchip.com/DevelopmentTools/ProductDetails/DV007004

2、要是能有框选PDF文字的选择方式就更好了。
另外貌似PDF翻译的时候会更改整体页面布局和网址，与360极速浏览器默认的PDF页面不同。但是很细心的处理了PDF的换行，夸。

3、翻译乱码
部分翻译时会出现“动词ï¼š俾,使 ... 能够”

4、界面可参考“co-trans-ext 浏览器翻译扩展”，基本上就是原生的谷歌翻译界面，感觉更友好。

**Comment by 1269976077** [comment]
希望不要改变PDF页面的原始网址，不便于网址的保存和分享。

**Comment by 1269976077** [comment]
能显示原文，并支持修改会方便一些。有时候多选了一个字母，重新选会比较麻烦。

**Comment by 1269976077** [comment]
今天试了，那个网址不会报错了。

**Comment by 1269976077** [comment]
![搜狗截图20190523154023](https://user-images.githubusercontent.com/50696163/58234532-59a0d600-7d71-11e9-9283-5dd7a9682c8d.png)
这个右键菜单也太长了吧？

**Comment by lmk123** [comment]
“框选PDF文字的选择方式” 具体指的是什么方式？

显示 PDF 文件原网址、界面在新版本中会进行优化。

乱码的问题我在百度贴吧里试了一下，没有重现。

**Comment by lmk123** [comment]
显示 pdf 原网址的进度后续更新在 #508

其它问题在 v7 版本中应该都没有了，所以这个工单我就关闭了。
