### ISSUE TITLE
显示原文

### ISSUE THREAD

**Issue by cxhttt233** [lmk123/crx-selection-translate#585]
问题：
1. 有道翻译不了
建议：
1.希望可以自定义翻译个数，也就是既可以谷歌，也可以百度，两个可以比较
2.希望可以显示原文

**Comment by lmk123** [comment]
有道翻译的问题已在 v6.4.9 中修复，升级到最新版本即可。

并排显示翻译结果的功能已经计划在新版本中实现，后续进展请关注 #304 

显示原文……其实我觉得没有太大必要，原文就是在网页里的，能告诉我需要在翻译结果里显示的原因吗？

**Comment by cxhttt233** [comment]
非常感谢作者的回复。显示原文我发现其实已经有了，就是展开就有原文了。至于原因，应该是翻译英文文献时候更好看一点吧，我也搞不清楚当时怎么想的了。这绝对是我遇到的最好的划词翻译的插件，非常感谢你的工作！！

**Comment by cxhttt233** [comment]
另外给作者推荐一个翻译网站，我觉得还是挺好的，你可以看下翻译准确性，然后如果你觉得合适可以加入，如果不合适就算了https://www.mdbg.net/chinese/dictionary?page=translate
