### ISSUE TITLE
英文转中文的时候，朗读翻译内容时，建议可以朗读要翻译的英语，以便于加深理解

### ISSUE THREAD

**Issue by tansuoboy** [lmk123/crx-selection-translate#587]
Now , I had a worry , That is when i understand what's means with this English , Not Only i want to konw this English means , But also I want  konw how to speak this English.

**Comment by setion** [comment]
+1

**Comment by TheOnlyBeliever** [comment]
+1

**Comment by lmk123** [comment]
朗读原文的功能是有的，只是隐藏的比较深，需要你把鼠标移动到翻译窗口里，然后会出现朗读按钮：

![image](https://user-images.githubusercontent.com/5035625/80201868-6439ae80-8657-11ea-86e0-2bdb72f62851.png)

新版本会把这个朗读按钮一直显示，避免找不到
