### ISSUE TITLE
SCi-hub打开的网页pdf文件翻译失效，划词后不显示图标

### ISSUE THREAD

**Issue by siyuan-zhang** [lmk123/crx-selection-translate#588]
Chrome 版本为Version 74.0.3729.169 (Official Build) (64-bit)。
用Sci-hub打开网页pdf时，鼠标选词后，不显示图标，好像对网页pdf失效了

**Comment by lmk123** [comment]
你在公众号里问过我这个问题吧？我在公众号里回复过你了，不过我忘了是怎么回复的了。。

问题我就关闭了，如果还有疑问可以新开 issue
