### ISSUE TITLE
对于英文希望显示音标

### ISSUE THREAD

**Issue by Maxingguang** [lmk123/crx-selection-translate#589]

**Comment by yiwanzi** [comment]
选择百度翻译，是可以显示音标的

**Comment by yiwanzi** [comment]
> _No description provided._

选项里选择百度翻译，是可以显示音标的

**Comment by setion** [comment]
+1

**Comment by whtiehack** [comment]
希望有音标。  

@yiwanzi  百度的翻译个人感觉没有谷歌的翻译好。尤其是对一起专业名词，差很远。

**Comment by lmk123** [comment]
跟 #423 重复，后续进展会同步在 #423 中。

新版本中会考虑用合适的方式给不支持音标的翻译接口（例如谷歌）加入音标。
