### ISSUE TITLE
悬浮窗无法关闭

### ISSUE THREAD

**Issue by hongjin95** [lmk123/crx-selection-translate#591]
在查询无结果或者网络不好时，悬浮窗会卡住，无法退出。很影响使用。建议加入超时，或者关闭悬浮窗按钮。

**Comment by cuilibao** [comment]
同意~~~~

**Comment by noisky** [comment]
遇到这个问题了，离线的状态下悬浮窗无法关闭，只能刷新网页，希望能添加关闭按钮，考试的时候不小心碰到了关不了，很蛋疼
![Cannotclose](https://img.ffis.me/images/2019/08/22/0b5639d682d0b856c973a4e9c0d45029.png)

**Comment by lmk123** [comment]
跟 #515 重复，后续的进展会更新在这个 issue 中

**Comment by lmk123** [comment]
新版本中会修复这个问题
