### ISSUE TITLE
翻译切换引擎后卡住无法关闭

### ISSUE THREAD

**Issue by AllenZyy821** [lmk123/crx-selection-translate#593]
某一段文字进行从百度到谷歌翻译转换（已翻墙），卡住无反应，关也关不掉
这段文字是韩语夹杂英语

**Comment by lcyan** [comment]
同问，除了刷新页面，要不没法关闭

![20191028112641](https://user-images.githubusercontent.com/3824082/67649932-ef224080-f975-11e9-914a-3c2deeb31280.png)

**Comment by lmk123** [comment]
跟 #515 重复，后续进展会更新在 #515 中。
新版本会修复这个问题
