### ISSUE TITLE
能不能设置默认翻译成什么语言

### ISSUE THREAD

**Issue by JqrSo** [lmk123/crx-selection-translate#597]
能不能设置默认翻译成什么语言
![QQ截图20190718001204](https://user-images.githubusercontent.com/52708641/61392922-86e1ae80-a8f2-11e9-936f-8e7de7e0e498.jpg)

**Comment by cj2012cj** [comment]
左边那个自动判断最好也能预设置一下，经常有单词默认判定为法语，OTZ

**Comment by zeteticl** [comment]
同意

**Comment by lmk123** [comment]
新版本中会提供这个功能，进展会更新到 #445
