### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by Juddd** [lmk123/crx-selection-translate#598]
第一，我特意申请了个有道智云的翻译api，但我不知道应该从哪里填写key啊
第二，我想让有道和谷歌翻译直接并排显示而不是要这么费事的去挨个切换，可以实现一下吗？

**Comment by lmk123** [comment]
> 第一，我特意申请了个有道智云的翻译api，但我不知道应该从哪里填写key啊

划词翻译使用的不是有道智云的官方 API，而是 http://fanyi.youdao.com 里的网页翻译接口，所以不需要填写有道智云的 key

> 第二，我想让有道和谷歌翻译直接并排显示而不是要这么费事的去挨个切换，可以实现一下吗？

这个我其实也有考虑过，新版本中我准备做个优化，把切换翻译接口的按钮放在外部，这样切换起来会更方便

**Comment by lmk123** [comment]
关于第二点的并排显示的进展会更新在 #304
