### ISSUE TITLE
希望在使用谷歌翻译单词时，也能够显示音标，谢谢作者。

### ISSUE THREAD

**Issue by battleon** [lmk123/crx-selection-translate#608]
如题。

**Comment by mabenteng** [comment]
确实啊,不然知道意思不会读啊,麻烦作者关注一下

**Comment by llittlerachel** [comment]
复议，然而一个月过去了也没增加

**Comment by lmk123** [comment]
跟 #423 重复，后续进展会同步在 #423 中。

新版本中会考虑用合适的方式给不支持音标的翻译接口（例如谷歌）加入音标。

@llittlerachel 别急，这次我不会鸽了，新版本真的在开发中了 :joy:
