### ISSUE TITLE
在「印象笔记-悦读」模式中，无法使用，而其他插件可以使用

### ISSUE THREAD

**Issue by zhangnew** [lmk123/crx-selection-translate#61]
在「印象笔记-悦读」模式中，无法使用，而其他插件可以使用，比如「PushBullet」，「右键搜」。

**Comment by lmk123** [comment]
[印象笔记-悦读](https://www.yinxiang.com/clearly/) 是指这个吗？它似乎已经从 Chrome 网上应用店里下架了。

**Comment by lmk123** [comment]
无反馈。

**Comment by zhangnew** [comment]
确实没有了，谢谢。
