### ISSUE TITLE
The icon NOTsupport chrome dark theme

### ISSUE THREAD

**Issue by jacksonyin** [lmk123/crx-selection-translate#610]
![image](https://user-images.githubusercontent.com/8662732/66895784-2879b880-f026-11e9-8b31-fed5426685db.png)

**Comment by lmk123** [comment]
我计划在新版本发布之后完全支持深色模式，不仅仅是 icon，也会为翻译界面、PDF 阅读器等提供深色模式支持。你可以关注我新开了一个工单查看进展：#688
