### ISSUE TITLE
网上下载的PDF打开后缩放问题，需要将 pdf.js 更新到最新版本

### ISSUE THREAD

**Issue by rhua0012** [lmk123/crx-selection-translate#617]
双指在触控板上面缩放效果不太自然。。稍微动一下就放大缩小很多倍。很难控制。。不知道是bug还是就是这样_

**Comment by lmk123** [comment]
确实有这个问题。划词翻译内置的 pdf 阅读器版本很低了，在新版本中我会更新到最新版本，看看还有没有这个问题

**Comment by dengbuqi** [comment]
确实要更新PDF.js啦，我现在在Ubuntu16.04, chrome Version 84.0.4147.125 (Official Build) (64-bit)下，看IEEE的论文的时候，必须要下载下来打开本地文件才能看了(例：https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8237506)。
在线观看pdf文件会显示：
```
无效或损坏的PDF文件
PDF.js v1.4.20 (build: b15f335)
信息：Invalid PDF structure
```

**Comment by rhua0012** [comment]
这个缩放问题还没有解决？

**Comment by dengbuqi** [comment]
唉，毕竟也是免费的公益项目，祈求作者有时间解决就好了～期待7.0出来，嘻嘻嘻嘻！

**Comment by lmk123** [comment]
v7.0 已经更新至最新版本，将在近期发布。

**Comment by dengbuqi** [comment]
Respect!!!!^_^
