### ISSUE TITLE
希望增加翻译窗口的宽度功能！！！

### ISSUE THREAD

**Issue by luoweiyi** [lmk123/crx-selection-translate#622]
翻译长段落时候显示不完整，观感很受影响，希望可以适当加宽（用户手动设置宽度就更好了）

**Comment by SparksFlyMe** [comment]
附议！！！

**Comment by NoahApostle** [comment]
要增加宽度功能，如果可以类似mac平台polyglot就好了，划词后根据所选宽度显示翻译内容

**Comment by ThinkZ** [comment]
安装stylus插件
添加规则 
`
#__selection-translator__ > .__st-box__ {
    width: 450px !important;
    background-color: #32cd74;
    border: 1px solid #32cd74
}
`

**Comment by lmk123** [comment]
重复 #267，后续进展会更新在 #267 中

新版本会提供调节宽高的功能。
