### ISSUE TITLE
激活扩展程序的快捷键无法清除

### ISSUE THREAD

**Issue by wkingnet** [lmk123/crx-selection-translate#625]
试了chrome商店的几个翻译插件，就作者这个做的最好最简洁实用且还在更新！感谢作者！

然后想提一个建议和不知道是不是BUG

建议：网页中翻译单词时，弹出的绿色翻译小窗口，顶部和底部绿色部分太大了，看着很不协调，也占地方，建议缩短上下绿色部分的高度。而且中间白底黑字的翻译文字，上下白色部分也留的太多，个人认为没有必要。我知道鼠标移上去会显现朗读等功能。但从使用者逻辑角度讲，这个白色对话框会给人一种“这是个消息提示框，告诉我结果”，而不是“这是一个可交互的操作对话框”，所以我建议或者直接去掉朗读功能精简缩小窗口，或者一直显示朗读功能。显示朗读功能，也最好是在翻译文字的下一行，用 朗读(原文)  朗读(译文) 这样

BUG：快捷键设置里，划词搜索的激活次扩展程序快捷键，默认CTRL+Q，无法删除。点X清掉以后，再打开快捷键设置页面，又变成CTR+Q了。而且CTRL+Q在英文网页里也唤醒不了？

**Comment by lmk123** [comment]
关于界面的建议很好，新版本中已经计划对界面进行改造了，就像你说的那样，减少边框的面积，始终显示朗读按钮等。

关于快捷键的问题，确实有这个问题，我会在新版本中修复这个问题

**Comment by lmk123** [comment]
v7.0 已经完全重写了翻译界面。

另外，快捷键不能清除的问题我发现是 Chrome 自身的问题，它默认就是不让清除快捷键的。
