### ISSUE TITLE
建议增加腾讯翻译君接口

### ISSUE THREAD

**Issue by static7** [lmk123/crx-selection-translate#626]
接口地址:https://fanyi.qq.com/translateapi
我发现谷歌翻译 有些翻译并不准确了

**Comment by melodicule** [comment]
腾翻译讯的日译中比谷歌好，希望加入

**Comment by lmk123** [comment]
跟 #414 重复，后续进展会同步在 #414 中。

新版本中会加入腾信翻译君的。
