### ISSUE TITLE
增加网页翻译功能

### ISSUE THREAD

**Issue by m1517** [lmk123/crx-selection-translate#630]
有时候需要用到页面翻译，我用的360急速，自动的不能用。
还有就是翻译偶尔会卡主，窗口不能关闭，只能刷新页面，极度不便。

**Comment by lmk123** [comment]
关闭按钮的问题其实是个 bug，见 #515 ，新版本中我会修复这个问题。

至于网页翻译…之前其实是有的，后来因为一些原因我去掉了。感觉可以重新加入进来。

**Comment by small-ora** [comment]
您好,请问有计划什么时候把网页翻译增加回来吗,我是新用户,很多网页都是全英文的,大部分都看不懂,所以急需,谢谢开发者.

**Comment by small-ora** [comment]
> 您好,请问有计划什么时候把网页翻译增加回来吗,我是新用户,很多网页都是全英文的,大部分都看不懂,所以急需,谢谢开发者.

我看了您别的Issues,好像是因为有道API的原因所以停掉了网页翻译,我以前用的别的翻译插件的方案是,逐段翻译,一段文本请求一次api,现在的接口应该就可以满足,翻译的文本展示在原文段落的下方,这个方案供您参考,辛苦了.

**Comment by cp19890714** [comment]
> 关闭按钮的问题其实是个 bug，见 #515 ，新版本中我会修复这个问题。

谷歌网页翻译有两种实现方案:
1. 直接使用谷歌翻译的网页,例如  https://translate.google.com/translate?hl=en&sl=en&tl=zh-CN&u=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMain_Page 
2. 参考"google translate"插件, 使用api翻译. 例如 https://translate.googleapis.com/translate_a/t

**Comment by lmk123** [comment]
网页翻译功能已在 v7.5.4 版本当中加入，欢迎体验。
