### ISSUE TITLE
支持自定义 Ctrl 辅助键

### ISSUE THREAD

**Issue by zzzgit** [lmk123/crx-selection-translate#631]
<img width="201" alt="Screen Shot 2019-12-09 at 23 36 26" src="https://user-images.githubusercontent.com/1060733/70449403-e0828980-1adc-11ea-9d42-9a360e584556.png">

除了Ctrl鍵，希望也能支持alt鍵。

**Comment by lmk123** [comment]
我比较好奇，为什么会需要自定义 Ctrl 键？用 Ctrl 或者 Alt 键会有什么区别吗

**Comment by tjx666** [comment]
和 wikiwand 冲突, wikiwand 不支持其它键

**Comment by fjqingyou** [comment]
mac 的 command 键 是复制粘贴经常用的键。。明明我要的是复制，，但是经常弹出翻译。。如果只要复制一次还好没太大影响。。但是一旦需要一个页面复制多次。。。总是被这个翻译窗口弹出来挡着也是挺尴尬的！

**Comment by lmk123** [comment]
已加入开发计划，将在下个版本中添加，同时去掉针对 Ctrl/Command 键做的 workaround（即  #730）

**Comment by lmk123** [comment]
针对辅助键的改进，我专门开了一个 issue #855 ，其中包含自定义辅助键。后续进展会更新在 #855 中，这个就先关闭了。
