### ISSUE TITLE
划词翻译在tensorflow的官方网站上用不了，插件没有显示翻译按钮

### ISSUE THREAD

**Issue by jingyuhe123** [lmk123/crx-selection-translate#632]

**Comment by lmk123** [comment]
我在 tensorflow 官网 https://www.tensorflow.org/ 里试了下，是可以使用的，如图：

![image](https://user-images.githubusercontent.com/5035625/80198794-2f2b5d00-8653-11ea-9845-a80b32d81bf5.png)

可能是官网中途改版了之后划词翻译又能正常使用了，如果你还是不能正常使用，麻烦贴一下重现你的问题的步骤，比如你用的浏览器版本、划词翻译版本、访问哪个网页、划选了哪里没有弹出翻译按钮等。
