### ISSUE TITLE
按下 Ctrl 键后翻译网页内选中的文本

### ISSUE THREAD

**Issue by ghost** [lmk123/crx-selection-translate#634]
将鼠标放在单词上（无论是否选中）,当下ctrl键即可翻译该单词
当页面中有选中的文体时,按下ctrl即可翻译选中文本
这种方式，超级舒服（特别是当你设置了一个鼠标侧键为ctrl的时候）。

**Comment by lmk123** [comment]
你说的其实分为两个功能：鼠标悬浮取词和用快捷键触发网页上选中文本的翻译。

鼠标悬浮取词已经计划在新版本里做了，进展会更新到 #88 

快捷键触发翻译其实已经有快捷键了，就是 Alt + A，只不过确实没有按一下 Ctrl 方便，新版本我把触发翻译的键改成 Ctrl 吧

**Comment by bestpika** [comment]
@lmk123 先選取再按下快捷鍵的方式拿掉之後用起來好不舒服，請問能夠加回去嗎？

**Comment by lmk123** [comment]
> @lmk123 先選取再按下快捷鍵的方式拿掉之後用起來好不舒服，請問能夠加回去嗎？

v7.0.4 已经加回去了，但是 Chrome 审核太慢了，还在审核 v7.0.2，等审核通过了我就发布 v7.0.4
