### ISSUE TITLE
悬框怎么关掉？

### ISSUE THREAD

**Issue by venberliu** [lmk123/crx-selection-translate#639]
每次用完之后，悬框就一直在页面悬挂，请问怎么关掉？

**Comment by yangjingchuang** [comment]
I also encountered this problem, how can I solve him

**Comment by lmk123** [comment]
这其实是个 bug，见 #515，刷新一下页面就恢复了

这个 issue 我就先关闭了，后续有进展会更新到 #515

新版本中会修复这个问题。
