### ISSUE TITLE
配合 Ctrl 键使用划词翻译在 mac os 下不可用

### ISSUE THREAD

**Issue by livelazily** [lmk123/crx-selection-translate#64]
mac os 下 ctrl + 鼠标点击相当于鼠标右键功能
希望能自定义组合快捷键

**Comment by lmk123** [comment]
嗯，这是一个已知的 bug，在新版中已经修复了，只是没有应用到 v5.6.1 里。

我会将这个 bug 修复后推上商店的。

**Comment by lmk123** [comment]
v6.0 已经要开发完成了，所以将不会在 v5.6.1 中修复这个 bug，你可以等到我发布 v6.0 之后再测试看看是否还有这个问题 :) 见 lmk123/selection-widget@603009c
