### ISSUE TITLE
请问能不能增加搜狗翻译？

### ISSUE THREAD

**Issue by scientificamer** [lmk123/crx-selection-translate#641]
搜狗翻译的效果要好很多。如果用搜狗翻译最好可以自己添加api，现在用的搜狗划词经常要输入验证码。

**Comment by lmk123** [comment]
新版本中已经打算加入了

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，搜狗翻译列在了上面。
