### ISSUE TITLE
[feature request] 能否支援星际翻译王（sdcv）？

### ISSUE THREAD

**Issue by Trumeet** [lmk123/crx-selection-translate#643]
很棒的插件，不过我觉得用 Google Translate 有的时候不能得到最想要的答案。况且我正在用星际翻译王（sdcv）查单词，也下载了一些比较合适的离线词典。能否提供一个选项，支持加载星际翻译王本地词典，或调用 sdcv 命令行等等来查词，而不是用在线查询？这样会更快一些，而且也能解决我的问题。多谢（

**Comment by lmk123** [comment]
星际翻译王看起来是很老的翻译软件了，暂时不打算加入。
