### ISSUE TITLE
有道或百度无法翻译的时候，提示用户先访问一下 http://fanyi.youdao.com 和 http://fanyi.baidu.com

### ISSUE THREAD

**Issue by cloudhill04** [lmk123/crx-selection-translate#644]
今天刚刚装了这个软件，就遇到了这个问题，无法解决，收到这样的信息“接口返回了错误的数据，请稍候重试。 重试”， 或另外一个问题“无法连接网络，请稍后再试”，不知道无法解决

**Comment by linexu** [comment]
因为你使用的是局域网。

**Comment by lmk123** [comment]
如果你用的是有道翻译或百度翻译，那么你需要先访问一下 http://fanyi.baidu.com 和 http://fanyi.youdao.com  ，之后才能正常使用有道和百度。

这确实是个问题，我需要跟用户说明一下。

**Comment by jacksonyin** [comment]
> 如果你用的是有道翻译或百度翻译，那么你需要先访问一下 http://fanyi.baidu.com 和 http://fanyi.youdao.com ，之后才能正常使用有道和百度。
> 
> 这确实是个问题，我需要跟用户说明一下。

建议把这个说明可以加到设置里，这样比较方便

**Comment by lmk123** [comment]
v7.0 里添加了重试功能，我试了下在无痕模式中第一次使用有道确实会报错，但点一下重试就正常了，所以就不再额外说明了。v7.0 正在三大商店审核中。
