### ISSUE TITLE
朗读功能失效

### ISSUE THREAD

**Issue by frf12** [lmk123/crx-selection-translate#645]
翻译后有音标，有朗读按钮，点击后没有朗读。勾选自动朗读依旧无效。

**Comment by frf12** [comment]
开启代理后能正常朗读了。也就是说朗读使用的是谷歌？我设置的翻译引擎是百度。希望朗读功能也能像翻译引擎一样能选择，或者与翻译引擎保持一致

**Comment by lmk123** [comment]
朗读的逻辑是这样的：比如你选择了百度翻译，那么优先会使用百度翻译朗读，但如果百度翻译不支持你要朗读的文本，那么就会用谷歌翻译朗读。

我刚才试了用百度翻译朗读英文，是能正常朗读的，你是朗读的什么文本？

另外，我也试了用谷歌翻译（国内）朗读英文，没有开启代理，也是能朗读的。

**Comment by frf12** [comment]
就很普通的单词。我刚才关掉代理，就选择“ago”，能翻译出来，悬浮框显示是百度翻译，设置里也是百度翻译，没有自动朗读，点击朗读也没有声音。开启代理有就有朗读了。

**Comment by lmk123** [comment]
v7.0 中改为了为每个翻译服务提供朗读功能，会使用服务自身的朗读，而不是现在的统一使用谷歌翻译。新版本将在近期发布。
