### ISSUE TITLE
希望可以增加自定义设置：鼠标放在“译”上时自动翻译，无需单击

### ISSUE THREAD

**Issue by NyaaGitty** [lmk123/crx-selection-translate#648]
在设置中增加一项自定义设置：当鼠标放在划词后出现的“译”上时自动翻译，无需单击
或者当将翻译结果的窗口固定以后，当鼠标放在划词后出现的“译”上时自动翻译，无需单击
感谢作者的卓越工作，谢谢

**Comment by NyaaGitty** [comment]
这样一来就不需要时不时进入拓展设置页，勾选或取消勾选“划词后显示翻译按钮”这个选项了

**Comment by lmk123** [comment]
“无需单击”只是省了一次鼠标点击，我没明白为什么省了这一次单击，你就不需要时不时进入扩展设置页去改选项了，这一块能详细解释一下吗？

**Comment by NyaaGitty** [comment]
【需要持续翻译的时候】自动翻译很方便，每次都使用鼠标点击比较累，
。
但【不需要持续翻译，同时日常需要时不时进行文字选择、拖曳的时候】。自动翻译就比较打扰了，适合先允许翻译再进行翻译。
。
持续翻译和间断翻译分别适合两种不同的翻译模式，彼此更换模式需要【进入扩展设置页去关闭自动翻译】
。
如果可以【当鼠标放在划词后出现的“译”上时自动翻译，无需单击】，那么无论是持续还是间断翻译都可以可以保持插件的翻译功能打开。而不需要【进入扩展设置页去开关自动翻译】。
。
因为【需要持续翻译的时候】在一天中的分布比较零碎，还有阅读外文时突发需要查词的情况。导致一天有十几次【进入扩展设置页去开关自动翻译】
。
抱歉回复较晚，不知是否说明清楚了，感谢您对此问题的关注。

**Comment by lmk123** [comment]
这个问题在 v7 的版本中应该得到解决了。

当你把窗口切换成固定状态时，双击文本会自动翻译，不会显示翻译按钮，所以【需要持续翻译的时候】就切换成固定状态，【不需要持续翻译，同时日常需要时不时进行文字选择、拖曳的时候】只需要切换回弹窗模式就可以了。
