### ISSUE TITLE
插件使用有道翻译的时候，出现错误“接口返回错误数据，请稍后重试”

### ISSUE THREAD

**Issue by cverzq** [lmk123/crx-selection-translate#649]
![selection_translation](https://user-images.githubusercontent.com/49152476/75405117-9d9bb980-5947-11ea-89a4-1a1ead008aab.png)
我用的是google浏览器，内核是80的，插件也是最新的6.4.8版本的，大佬，可以修复下这个问题吗？

**Comment by yelw145** [comment]
我的也是一样

**Comment by DicerZHQ** [comment]
> 我的也是一样

@lmk123 希望大佬空闲的时候能修复下有道翻译出现的“接口返回错误数据，请稍后重试的错误”哈

**Comment by lmk123** [comment]
有道翻译的问题我发布了新版本 v6.4.9 修复了，但是受疫情影响，审核时间会变长

**Comment by cverzq** [comment]
> 有道翻译的问题我发布了新版本 v6.4.9 修复了，但是受疫情影响，审核时间会变长

嗯嗯，谢谢大佬，大佬辛苦了哈！

**Comment by lmk123** [comment]
v6.4.9 已经发布，这个问题已经修复了
