### ISSUE TITLE
腾讯企业邮箱出现乱码

### ISSUE THREAD

**Issue by v-ickyy** [lmk123/crx-selection-translate#650]
划词翻译插件启用的情况下，通过腾讯企业邮箱发送邮件，对方接收的邮件下方出现了这些乱码，但是在我的已发送的邮件里就只有正常的个性签名。收件人收到的邮件里多出了这部分内容。
![1](https://user-images.githubusercontent.com/39686846/75432038-c09a8d80-5988-11ea-9ead-5e8396f0c227.png)
后续我禁用了这个插件，在发送邮件后，对方接收到的邮件下方依然出现了图片中的信息
不知道这是什么问题呢~有什么解决办法吗

**Comment by lmk123** [comment]
禁用了插件之后，你还需要刷新一下腾讯企业邮箱的网页才能把这些乱码清除掉。

其实划词翻译有做过 QQ 邮箱的判断，但没有做过新出的企业邮箱的判断，新版本中我加一下

**Comment by v-ickyy** [comment]
好的，谢谢谢谢！

**Comment by lmk123** [comment]
v7.0 中已经针对这种情况做出了改进，应该是不会再有这个问题了。新版本将在近期发布，如果发布之后还有类似问题，欢迎反馈。
