### ISSUE TITLE
建议：翻译弹窗优化

### ISSUE THREAD

**Issue by hanshuixin** [lmk123/crx-selection-translate#651]
1、当鼠标松开时，弹窗没有及时关闭，需要点一下其他地方才会关闭，使用起来极为不便；
2、弹窗边框太宽，遮挡了正文，建议设计地窄一点，可以自定义透明度。

**Comment by lmk123** [comment]
> 当鼠标松开时，弹窗没有及时关闭

鼠标松开的时候正是显示按钮/弹窗的时候，当然是需要点击一下其他地方才会关闭，没明白你指的是什么情况

**Comment by lmk123** [comment]
> 弹窗边框太宽，遮挡了正文，建议设计地窄一点，可以自定义透明度。

新版本中边框会调窄一点，窄了之后应该也用不着自定义透明度了

**Comment by lmk123** [comment]
v7.0 中已完全重新设计了翻译界面，将在近期发布。
