### ISSUE TITLE
firefox 里搜不到，给出的链接也是找不到页面，是不打算维护ff版了吗？

### ISSUE THREAD

**Issue by MoCongxin** [lmk123/crx-selection-translate#657]

**Comment by lmk123** [comment]
会继续维护的。

之所以找不到了是因为火狐要求我提供详细的源码、构建方式等英文文档，另外一些代码上有安全隐患的地方要求提供原因或整改，在完成这些之前火狐不会重新让我上架划词翻译。

这些内容整改起来还挺花时间的，我完成了之后就会重新上架。

**Comment by fbion** [comment]
> 会继续维护的。
> 
> 之所以找不到了是因为火狐要求我提供详细的源码、构建方式等英文文档，另外一些代码上有安全隐患的地方要求提供原因或整改，在完成这些之前火狐不会重新让我上架划词翻译。
> 
> 这些内容整改起来还挺花时间的，我完成了之后就会重新上架。

那firefox对安全很负责哦👍🏿

**Comment by lmk123** [comment]
这个问题我重新打开了，火狐版上架后再关闭

**Comment by wuyuansushen** [comment]
> 
> 
> 会继续维护的。
> 
> 之所以找不到了是因为火狐要求我提供详细的源码、构建方式等英文文档，另外一些代码上有安全隐患的地方要求提供原因或整改，在完成这些之前火狐不会重新让我上架划词翻译。
> 
> 这些内容整改起来还挺花时间的，我完成了之后就会重新上架。

希望能够尽快上架，并提一个小建议:能否在输出框里面添加 音标 的标识，在 朗读 字段所在的那一行即可

**Comment by lmk123** [comment]
划词翻译已重新上架 Firefox 商店。
