### ISSUE TITLE
希望加上音标显示

### ISSUE THREAD

**Issue by jianwi** [lmk123/crx-selection-translate#658]
有时候发音听的不太清晰，这时候配合音标显示就完美啦。

**Comment by wayone** [comment]
特别需要音标，它是英语单词的灵魂！

**Comment by lmk123** [comment]
跟 #423 重复，后续进展会同步在 #423 中。

新版本中会考虑用合适的方式给不支持音标的翻译接口（例如谷歌）加入音标。
