### ISSUE TITLE
提一个功能需求：自动判断复制的内容进行翻译

### ISSUE THREAD

**Issue by ifyour** [lmk123/crx-selection-translate#66]
需求：
1.当我复制的内容是英文时，自动翻译剪切板内的文本。`英 -> 中`
2.当我复制的内容是中文时，自动翻译剪切板内的文本。`中 -> 英`

**Comment by ifyour** [comment]
![image](https://cloud.githubusercontent.com/assets/15377484/12070600/bb479fde-b0b9-11e5-892b-9aec00724e85.png)

**Comment by lmk123** [comment]
第二个功能已经添加进 v6.0 中了，见 0125b69

**Comment by lmk123** [comment]
第一个问题我没法重现。无论是使用有道、百度还是谷歌，当输入英文时都是自动翻译成中文的。

另外，不同的功能请分别开启 issue，而不要集中在一个 issue 里，这样比较方便管理和跟踪 :smile:
