### ISSUE TITLE
感谢开发者，希望加入“DeepL翻译”

### ISSUE THREAD

**Issue by linexu** [lmk123/crx-selection-translate#663]
迄今为止发现的最准确最合适的中英翻译工具，希望加入到“划词翻译”里的工具选择中，谢谢。
https://www.deepl.com/translator
https://www.xiaxiaoqiang.net/google-crushed/.html

**Comment by lmk123** [comment]
看起来挺不错的，我会考虑的

**Comment by linexu** [comment]
感谢回复，感谢您的付出。希望能尽快在您的工具中使用到它，谢谢！

**Comment by fonlan** [comment]
这个翻译引擎相当NB啊，强烈建议加入

**Comment by 2609665** [comment]
强烈建议加入

**Comment by abcfy2** [comment]
投票+1，这两天我也在关注DeepL，相当的赞，我甚至将一篇中文blog翻译成英文，居然发现错误相当少，仅需要稍作改动就变成了一篇英文文档，太赞了

**Comment by wllenyj** [comment]
> 投票+1，这两天我也在关注DeepL，相当的赞，我甚至将一篇中文blog翻译成英文，居然发现错误相当少，仅需要稍作改动就变成了一篇英文文档，太赞了

Vote +1, I've been following DeepL for the past two days too, pretty awesome, I even translated a Chinese blog into English. It's great to find out that there are quite few errors and only minor changes were needed to make it an English document!

**Comment by linexu** [comment]
> 迄今为止发现的最准确最合适的中英翻译工具，希望加入到“划词翻译”里的工具选择中，谢谢。
> https://www.deepl.com/translator
> https://www.xiaxiaoqiang.net/google-crushed/.html

3個月過去了，不知道開發者考慮的如何了？
希望能盡快的使用到。謝謝

**Comment by lmk123** [comment]
@linexu 目前我的主要精力投入在新版本的开发当中，新版本完成之后，会先把腾讯翻译君、彩云小译和搜狗翻译加入进来，所以 deepL 还要再等一段时间了

**Comment by Raychanan** [comment]
强烈建议DeepL，翻译效果最好的

**Comment by daf3707** [comment]
最牛翻译，没有之一

**Comment by bestpika** [comment]
DeepL 翻譯的結果把大部分翻譯都甩得老遠連車尾燈都看不到

**Comment by chenjingyuanku** [comment]
我也+1，DeepL是我用过最好的翻译工具之一

**Comment by xiekeyi98** [comment]
我看到必须是订阅用户才能使用： https://www.deepl.com/zh/docs-api/
目前也不支持中国的付款方式
![image](https://user-images.githubusercontent.com/7782671/95980799-41db5d80-0e50-11eb-9845-070c38356ed6.png)

如果要支持的话，估计也需要填写用户自身的 SecretID 和 SecretKey 来实现吧。

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，DeepL 列在了上面。
