### ISSUE TITLE
增加一个强制关闭吧

### ISSUE THREAD

**Issue by Kumiko-git** [lmk123/crx-selection-translate#665]
经常遇到持续卡在“正在查询，请稍候……”的情况，不能关闭也不能再开新窗口翻译其他词，只有刷新页面才能去掉，

**Comment by lmk123** [comment]
这本质上其实是一个 bug，解决了 bug 的话也就不需要关闭按钮了。这个 bug 我会在新版本中修复

**Comment by lmk123** [comment]
跟 #515 重复，后续进展会更新在 #515 中。
新版本会修复这个问题。
