### ISSUE TITLE
确保自动更新后，已经打开的页面不需要刷新也能继续使用划词翻译

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#666]
不知能否改进？

**Comment by lmk123** [comment]
这个没法改进，因为这是浏览器的机制，扩展程序方面是做不到自动的。

我能想到的就是更新之后提醒用户需要刷新已打开的页面

**Comment by GH01** [comment]
好像刷新就够了吧。

那能否续用旧版，直至刷新/重启呢？

**Comment by lmk123** [comment]
> 那能否续用旧版，直至刷新/重启呢？

应该是可以的，我会在新版本中改进这个问题

**Comment by lmk123** [comment]
尝试了一下，是做不到的，所以这个问题只能关闭了。

**Comment by GH01** [comment]
https://chrome.google.com/webstore/detail/simpleextmanager/kniehgiejgnnpgojkdhhjbgbllnfkfdk
这个扩展看上去是 保持旧版，直至浏览器重启的。

发生更新后，我打开它的Changelog，仍是旧版的；
浏览器重启后，Changelog才变新版。

**Comment by lmk123** [comment]
设置页是属于扩展本身的一个单独的页面，但是划词翻译是在你平常浏览的页面中注入了代码，没法在更新的时候先把代码去掉然后重新注入新版本的代码

**Comment by GH01** [comment]
正是在说保持旧版啊

**Comment by lmk123** [comment]
我没解释清楚，我详细解释以下

划词翻译注入到页面中的代码的作用就是将用户选中的文本发送到划词翻译的后台（Chrome 称之为“背景页”），后台去翻译服务器获取到结果后返回给页面中的代码，也就是说，页面中注入的代码跟划词翻译的后台是有一个传递消息的“通道”的。

当划词翻译更新之后，Chrome 会先卸载掉旧版本的后台，然后安装新版本的后台，在这个过程里，页面中注入的代码跟后台之间的“通道”已经被切断了。

这跟重启网站服务器的概念不太一样。传统的 B/S 结构下，服务器停止了，网页会获取不到结果，但服务器重启了，网页还是可以做到不刷新、继续通过 HTTP 协议访问到服务器。

但  Chrome 给页面注入的脚本跟 B/S 似乎不太一样，我的理解是页面中注入的脚本跟后台是有强绑定，一旦后台“重启”了，页面中注入的脚本跟后台的连接就已经断开了，就需要刷新下网页跟新的后台重新连接

**Comment by GH01** [comment]
就是说，扩展更新后，尽管旧文件都在，却已完全无用了？
那旧文件为何要到浏览器重启时才会被删除？
似乎不是因为文件正被占用，
因为我注意到 卸载扩展时（即便扩展正在运行）总是立即删除文件的。

**Comment by lmk123** [comment]
注入进去的代码跟文件没关系，代码已经在之前的页面中运行了，即使文件删除了，代码还是在之前的页面中的
