### ISSUE TITLE
是否要提供固定源语种的功能？

### ISSUE THREAD

**Issue by KKKKKKYYYY** [lmk123/crx-selection-translate#667]
我就是用这软件来翻译中文简体的，把翻译源改成中文简体后，重启了路由器又变成了"自动检测“好烦啊！！！希望优化。

**Comment by KKKKKKYYYY** [comment]
我主要用来翻译中文繁体，自动检查他会弄成英文的。我就想单独固定成中文简体。

**Comment by lmk123** [comment]
今天刚好跟另外一个人也聊过这个问题，固定也是有问题的。

比如你固定了源语言为繁体中文，如果你一直都只翻译繁体中文，那就还好，但如果有一天你进入了一个英文或者日语网站，那你首先得把繁体中文切回自动判断，等你离开英文网站回到繁体网站了，你又得切回去。

**Comment by KKKKKKYYYY** [comment]
> 今天刚好跟另外一个人也聊过这个问题，固定也是有问题的。
> 
> 比如你固定了源语言为繁体中文，如果你一直都只翻译繁体中文，那就还好，但如果有一天你进入了一个英文或者日语网站，那你首先得把繁体中文切回自动判断，等你离开英文网站回到繁体网站了，你又得切回去。

你好我说的不是源语言，而是翻译语言。用户可以自己选定翻译语言然后固定，源语言还是为自动判断。
![@K$V2VSE28KR%$Q0})_BDXP](https://user-images.githubusercontent.com/55151709/80171003-e6a47d00-861b-11ea-9500-0dec6a9ba2e7.png)

**Comment by KKKKKKYYYY** [comment]
就是我希望能够一直固定这种格式。

**Comment by KKKKKKYYYY** [comment]
就是我希望能够一直固定这个格式。
无论英文，中文繁体，还是其他语言，都能翻译成中文简体！
主要是能够固定，重启浏览器后设置不变，谢谢了！
![RE~GDU3 JYEJ$)` {{ETS5X](https://user-images.githubusercontent.com/55151709/80171288-8c57ec00-861c-11ea-9434-b278f6a02ac5.png)

**Comment by lmk123** [comment]
如果是固定翻译目标语种的话，已经计划在新版本中加入了，后续进展会更新到 #402
