### ISSUE TITLE
后续是否会增加显示音标选项?

### ISSUE THREAD

**Issue by wpwing123** [lmk123/crx-selection-translate#668]
你好,这个划词经过试用后非常方便,再也不用边看网站边复制单词进行翻译了,但不知后续可否增加音标显示功能呢?对于记忆单词很有帮助.

**Comment by lmk123** [comment]
跟 #423 重复，后续进展会同步在 #423 中。

新版本中会考虑用合适的方式给不支持音标的翻译接口（例如谷歌）加入音标。
