### ISSUE TITLE
擴充套件圖示點下去可以直接翻譯選取文字

### ISSUE THREAD

**Issue by bestpika** [lmk123/crx-selection-translate#669]
您好，請問是否能夠讓選取的文字也能直接點擴充套件的圖示進行翻譯？
（關閉網頁劃詞翻譯的狀況）

謝謝

**Comment by lmk123** [comment]
关闭网页划词的情况下，你可以通过下面的方式翻译：

- 鼠标右键选择“翻译 xxx”
- 使用 Alt + A 快捷键

这两种方式应该比点击右上角的按钮更便捷
