### ISSUE TITLE
总会在 Outlook 邮件中插入“译”字

### ISSUE THREAD

**Issue by h404bi** [lmk123/crx-selection-translate#67]
RT. 在网页版 Outlook 中写邮件时会在邮件内容中插入“译”字。停用扩展后就不会了。e.g.:
![qq 20160103160414](https://cloud.githubusercontent.com/assets/5764917/12077864/a9f2b360-b233-11e5-9a76-dfafee910782.png)

**Comment by lmk123** [comment]
我添加了一个新的设置项：“在邮件编辑区域禁用划词翻译”，当勾选此选项后，右键末尾就不会被插入“译”字了。这个设置项默认是没有勾选的，你需要去设置页勾选一下。

ae09de6

**Comment by lmk123** [comment]
发布之后我会关闭这个 issue。
