### ISSUE TITLE
接口返回了錯誤的數據，請稍後重試

### ISSUE THREAD

**Issue by bestpika** [lmk123/crx-selection-translate#673]
![image](https://user-images.githubusercontent.com/5698157/80434510-83bd2980-892c-11ea-8a11-2b1627a282a1.png)
每次遇到這個就必須去有道的首頁一次之後才會正常
從開發人員工具看到傳回來的結果是這樣
![image](https://user-images.githubusercontent.com/5698157/80434799-5d4bbe00-892d-11ea-9551-50bb846cf5a8.png)

**Comment by bestpika** [comment]
原來你在 #644 講了

**Comment by lmk123** [comment]
是的，这严格来讲是一个 bug，我会在新版本中修复这个问题
