### ISSUE TITLE
控制台无用警告：Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by tjx666** [lmk123/crx-selection-translate#674]
查了一下发现是这个扩展输出的。

![screenshot_2020-04-29_22-16-18](https://user-images.githubusercontent.com/41773861/80606625-21b50f00-8a67-11ea-9a82-7de4209bb88f.png)
![screenshot_2020-04-29_22-15-52](https://user-images.githubusercontent.com/41773861/80606629-24176900-8a67-11ea-9439-823c4ee9978c.png)

**Comment by lmk123** [comment]
收到，我会在新版本中避免划词翻译污染控制台

**Comment by tjx666** [comment]
老哥，这个问题能不能快点解决，作为一个前端开发真的忍不了控制台有多余的警告。要是老哥觉得麻烦的话，我可以帮忙解决这个问题提个 PR。

**Comment by lmk123** [comment]
v7.0 已经没有无用的警告了，将在近期发布。如果之后还有类似问题欢迎反馈
