### ISSUE TITLE
+选项：按钮弹窗(翻译盒子) 也用于 网页内的选块翻译

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#675]
场合1：
在[划词翻译]的页内浮窗中点选文字，网页中的选块就会消失。
而在 按钮弹窗(翻译盒子)中操作，就不用担心这个。

场合2：
这样就可以解决一部分我在 #468 中提到的需求，比如：
在[划词翻译]的页内浮窗中划词，用快捷键让按钮弹窗(翻译盒子)翻译，
这样，页内浮窗保持全文，按钮弹窗(翻译盒子)查看局部。

**Comment by lmk123** [comment]
> 在[划词翻译]的页内浮窗中点选文字，网页中的选块就会消失。

你的目的是想解决选块消失的问题吗？

另外，在新版本中，我准备把按钮弹窗(翻译盒子)抽离出来成为一个独立的翻译面板，这样用户就可以翻译浏览器之外（比如我在其他软件内）的文本了，这是不是也能解决你的问题？

**Comment by GH01** [comment]
不光为选块。
两种（或更多）场合。

能解决问题，怎么都行。

独立窗口 肯定受欢迎！
但可能在不同壳器上表现不同……
比如我用Vivaldi，套壳独特深重，别家如SalaDict设计很棒的独立窗口 在Vivaldi上就成了普通窗口……
已向Vivaldi反馈，但从原理上是不是希望不大？

顺便一提：
SalaDict是3种窗口皆有：页内浮窗，按钮弹窗，独立窗口。

**Comment by lmk123** [comment]
v7.0 已经改成了独立翻译窗口，先用用看有没有解决你的问题吧
