### ISSUE TITLE
【Edge-快捷键】edge浏览器上快捷键失效

### ISSUE THREAD

**Issue by NICK-DUAN** [lmk123/crx-selection-translate#676]
edge浏览器上快捷键不起作用。使用Ctrl + Q 无法调用划词翻译的窗口

**Comment by jiahe224** [comment]
哥们，Edge上叫啥呢？商店搜“划词翻译”没有的

**Comment by NICK-DUAN** [comment]
上这个[链接](https://microsoftedge.microsoft.com/addons/detail/oikmahiipjniocckomdccmplodldodja?hl=zh-CN)看看

**Comment by lmk123** [comment]
v7.0 已经在 edge 商店上架了，我修改了扩展程序的快捷键，并且试了一下是没有问题的，你可以更新到 v7.0 后再试试。
