### ISSUE TITLE
对于快捷键的一些建议

### ISSUE THREAD

**Issue by xyzyx233** [lmk123/crx-selection-translate#680]
先用的快捷键如果可以修改键位的话体验变很多，有些页面上的快捷键和现在有的快捷键冲突(网页形式的控制台界面)，如果能够修改绑定的快捷键或停用快捷键的话就好了。

**Comment by lmk123** [comment]
现在划词翻译只有两个快捷键，而且是可以改的，见 https://hcfy.limingkai.cn/manual.html#%E5%BF%AB%E6%8D%B7%E9%94%AE
