### ISSUE TITLE
更新后偶尔还是有卡在正在查询的情况

### ISSUE THREAD

**Issue by Kumiko-git** [lmk123/crx-selection-translate#682]
如题的情况，大部分时候超时了能显示五秒中断的，但尚未完全杜绝
不如还是加入一个强制关闭吧

**Comment by lmk123** [comment]
看来强制关闭按钮还是要加。。

不过卡在正在查询毕竟是一个 bug，如果你下次遇到这个问题了，能提供一些信息给我吗？比如重现问题的步骤、可能的网络因素、控制台的报错截图等，我希望能从根源解决这个问题

**Comment by Kumiko-git** [comment]
我感觉可能和科学上网不稳定有关。
控制台报错截图是什么东西，不懂啊

**Comment by beikege** [comment]
当前版本：v6.4.11
一直卡住,无法关闭,只能刷新网页.
![image](https://user-images.githubusercontent.com/9634079/82733976-417be200-9d4a-11ea-9521-2cc13787f8e1.png)

![image](https://user-images.githubusercontent.com/9634079/82733966-332dc600-9d4a-11ea-827c-1fdfd5619e5a.png)

**Comment by Kumiko-git** [comment]
![捕获](https://user-images.githubusercontent.com/63497822/82806302-11eae800-9eb8-11ea-8e2f-eb2495c721a3.JPG)
再遇到一次 控制臺截图是这个吗

**Comment by frei-x** [comment]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
背景页中显示这个
![image](https://user-images.githubusercontent.com/32102526/82981033-825f4980-a01d-11ea-9f0e-78bd904ed6bf.png)


翻译响应慢 ,不想翻译这个地方了 ,没发停止

**Comment by lmk123** [comment]
@frei-x 这个报错跟卡死应该没关系，而且现在如果响应时间超过 5 秒会显示超时的。

**Comment by lmk123** [comment]
这个问题我现在没法复现，光看代码也没法看出来问题出在哪。按照报错截图，我估计加了关闭按钮可能还是关不掉 :joy:

所以如果这个不能稳定复现，大家还是等一下我正在开发的新版本吧，估计六月中旬就会发布了

**Comment by NyaMisty** [comment]
为什么一定要等五秒啊，这五秒中就直接关不掉了
能不能像查询好了之后一样，直接点击页面其他地方就关掉呢？

**Comment by bestpika** [comment]
我在 v6.4.11 也是偶而會遇到
來看 v6.4.12 還會不會……

**Comment by bestpika** [comment]
很遺憾地，我在 v6.4.12 還是會遇到
而且短時間遇到超過兩次，兩次都是在 Gmail 裡面遇到的

**Comment by Kumiko-git** [comment]
6.4.12 如果没有翻墙而不小心点到了GOOGLE翻译就很可能会卡住。

**Comment by bestpika** [comment]
問題是我又不在牆內 ¯\_(ツ)_/¯

**Comment by NyaMisty** [comment]
可以解释一下为什么一定要等loading变成falst后才会关掉弹窗吗？
![image](https://user-images.githubusercontent.com/5344431/85349815-01b73e80-b532-11ea-9022-73ea321b9162.png)

**Comment by NyaMisty** [comment]
我可以复现上面的stacktrace，用的是最新的master branch，触发条件是非常快的打开然后再关闭划词翻译
![image](https://user-images.githubusercontent.com/5344431/85355208-b192a900-b53e-11ea-8dc4-6e3463e4bcbf.png)

![image](https://user-images.githubusercontent.com/5344431/85355316-f28abd80-b53e-11ea-8295-473361a64efb.png)

**Comment by NyaMisty** [comment]
根据https://blog.csdn.net/musicwind/article/details/50519471和https://www.oudahe.com/p/48463/，极大有可能和template.html里面的v-for="text in result.result"相关
（上面图里的common1.js里面的代码也正是在设置result）
![image](https://user-images.githubusercontent.com/5344431/85355989-5e215a80-b540-11ea-9323-16709404c482.png)

**Comment by lmk123** [comment]
完全重写的 v7.0 没有这个问题了，将在近期发布，所以这个问题我就关闭了。

**Comment by NyaMisty** [comment]
ok辛苦
