### ISSUE TITLE
建议增加UI更换颜色功能

### ISSUE THREAD

**Issue by Potat0Servers** [lmk123/crx-selection-translate#685]
现在这个绿色，emm有点刺眼，不太好看，希望能至少提供几个颜色选项。黑色灰色白色，或者一些深色就比较好。

**Comment by lmk123** [comment]
新版本会更新界面，不会有绿色背景了 😂 

目前打算使用白色背景加灰色边框线，如果新版本发布后，你还是觉得颜色不好看，可以再新开一个工单。
