### ISSUE TITLE
请教一下，有什么方法可以修改pdf浏览界面的主题颜色吗,比如night mode

### ISSUE THREAD

**Issue by kite8** [lmk123/crx-selection-translate#686]
因为长时间看pdf文档，白色主题太伤眼，我尝试用过[darkreader](https://github.com/darkreader/darkreader)修改页面主题颜色，但是会提示此页面受到浏览器保护，不知是否可以增加一个night mode，谢谢了，虽然这个好像和翻译插件无关了，23333

**Comment by lmk123** [comment]
目前没有。

在新版本开发完成之后，我会让划词翻译支持深色模式（Dark Mode），我新开了一个工单，你可以在这个工单关注划词翻译深色模式的进展：#688
