### ISSUE TITLE
双击选中一行文字时，翻译结果不正确

### ISSUE THREAD

**Issue by ChloeKurumi** [lmk123/crx-selection-translate#689]
前提：关闭划词后显示翻译按钮
同样一行文字，必须划词才能显示正确结果，希望双击选中一行或一段文字时，能显示正确的翻译结果

**Comment by lmk123** [comment]
我猜你说的应该是有道翻译只翻译部分文本的问题吧？如果是的话，我已经发布了 v6.4.12 修复了这个问题，等审核通过之后，更新到最新版试试。

如果不是，那就继续在这个工单下留言，提供一下详细的重现信息，比如你用了什么翻译接口（有道？百度？谷歌？）、翻译了哪个网页里的哪段文字等。
