### ISSUE TITLE
翻译 PDF 内的文本

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#69]
在 Chrome 中打开 PDF 文件时，Chrome 默认会使用一个插件来渲染而不是用 DOM，所以划词翻译无法获取用户在插件内选中的文本，**但是**，我可以使用 [pdf.js](http://mozilla.github.io/pdf.js/) 在一个新的页面打开 PDF，这样划词翻译就能正常获取到页面上选中的文本了。（至少在这个[演示页面](http://mozilla.github.io/pdf.js/web/viewer.html)是能正常使用的）

顺便将上面提到的演示页面用的 pdf 文件写上，可以用来测试。
http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf

一个官方提供的结合 webpack 使用的例子：
https://github.com/mozilla/pdf.js/tree/master/examples/webpack

**Comment by henices** [comment]
期待这个功能。

**Comment by lmk123** [comment]
实际上你现在就可以体验这个功能了。

[pdf.js](http://mozilla.github.io/pdf.js/) 有发布一个[官方的 Chrome 扩展](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm)，你安装之后， Chrome 就会使用这个扩展打开 PDF 文件，那么划词翻译就会生效了。

**Comment by henices** [comment]
我的chrome没有装 pdf.js 拓展但是在chrome中也能直接打开PDF文件，但是划词翻译用不了。

**Comment by lmk123** [comment]
是的，因为 Chrome 自带一个显示 pdf 文件的 PPAPI 插件，你可以打开 chrome://plugins/，然后搜 `Chrome PDF Viewer`。

这个插件其实隔绝了浏览器环境，扩展的代码没法注入到插件里面去，所以划词翻译也就无能为力了。

但如果使用 pdf.js 来显示 pdf 文件，而不是使用这个插件，那划词翻译就能正常使用了 :)

**Comment by henices** [comment]
确实存在  *Chrome PDF Viewer* 插件，等你的新功能了。

我js不熟悉，不然一定贡献点代码，插件写的不错 :+1:

**Comment by tangshi** [comment]
[StackOverflow: How extension get the text selected in chrome pdf viewer？](https://stackoverflow.com/questions/15527095/how-extension-get-the-text-selected-in-chrome-pdf-viewer)
这个帖子里提供了一种获取PDF文件文本的方法，不知道可行否？我对前段不熟，sorry

**Comment by lmk123** [comment]
@tangshi 谢谢你帮我找到了这个方案，我刚才试了一下，不可行。

**Comment by lmk123** [comment]
刚才我花了点时间找到了让划词翻译支持 PDF 文件的方法，在这里记录一下。

### 详细步骤

 1. 在 https://github.com/mozilla/pdf.js/releases/tag/v1.3.91 下载 `pdfjs-1.3.91-dist.zip` 并解压到 `./src` 的 `pdfjs-1.3.91-dist` 目录下
 2. 打开 `./src/pdfjs-1.3.91-dist/web/viewer.js`，注释掉其中的第 7157-7159 行。这是为了避免 view.js 在检测到不同源的 PDF 文档时报错——在 Chrome 扩展程序里是可以进行跨域请求的。
 3. 打开 `./src/pdfjs-1.3.91-dist/web/viewer.html`，并在 `</body>` 前加上下面几行代码：

```html
<link rel="stylesheet" href="../../bundle/commons1.js.css">
<script src="../../bundle/commons3.js"></script>
<script src="../../bundle/commons2.js"></script>
<script src="../../bundle/commons1.js"></script>
<script src="../../bundle/content.js"></script>
```

现在，在浏览器内打开 `chrome-extension://bocneeaaedgmgcehokhbgffchgbbhllk/pdfjs-1.3.91-dist/web/viewer.html?file=http%3A%2F%2Fmozilla.github.io%2Fpdf.js%2Fweb%2Fcompressed.tracemonkey-pldi-09.pdf 就能预览 http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf` 的 PDF 文件，并且划词翻译能正常工作。

### 工作原理

 1. 要让划词翻译能翻译 PDF 内的文本，首先要使用 pdf.js 自带的 viewer 打开 PDF 文档。
 2. 然后，因为内容脚本不会被插入到 `chrome-extension://*` 类的网页里，所以要手动在 viewer.html 底部加上内容脚本的代码。
 3. 最后，在打开 viewer.html 的网址后加上 `?file=pdf文件的URL`（pdf 文件的 URL 需要使用 `encodeURIComponent()` 编码），viewer.html 就会加载 PDF 文件了。

### 需要解决的问题

 - `pdfjs-1.3.91-dist.zip` 里有近 400 个文件，但需要改动的只有两个文件，所以我需要使用编程的方式将它下载到项目中及改动文件（使用 `postinstall`）。
 - 需要在检测到即将访问一个 PDF 文档时跳转到 viewer.html 并带上 PDF 文档的 URL。可以在内容脚本内判断当前 URL 是否以 `.pdf` 结尾，或者使用 [chrome.webRequest](https://developer.chrome.com/extensions/webRequest#event-onBeforeRequest) 检测（后者好些）

我会在近期实现这个功能。

**Comment by lmk123** [comment]
已完成，将在 6.1.0 中发布。

**Comment by leemmy** [comment]
我下载了6.10版本还是不能翻译本地PDF啊···

**Comment by leemmy** [comment]
另外之前我是选中PDF文本按Ctrl+c再按ctrl+q 右上角会弹出翻译窗口并自动翻译 今天使用不行了

**Comment by lmk123** [comment]
@leemmy 你需要先在扩展程序页勾选划词翻译的“允许访问文件网址”。另外，点击一下扩展程序页右下角的“键盘快捷键”，看看划词翻译的快捷键还有没有。

**Comment by leemmy** [comment]
在pdf中可以使用了。但是打开翻译盒子时候不能自动翻译剪切板的内容，我检查了设置前面选项已经勾选，键盘快捷键也没问题

**Comment by lmk123** [comment]
@leemmy 设置里的 “打开翻译盒子时，自动翻译剪切板内的文本” 这个选项有勾选吗？如果有勾选仍然出现这个问题，那就删除了重新安装一次吧。

**Comment by lmk123** [comment]
@leemmy 我刚才发现你这个问题是一个 bug 😂 我会修复

**Comment by leemmy** [comment]
问题也有bug?-.-
