### ISSUE TITLE
Discuz!l论坛编辑帖子会有一堆语言

### ISSUE THREAD

**Issue by pongfcnkl** [lmk123/crx-selection-translate#690]
![QQ截图20200609211205](https://user-images.githubusercontent.com/24273319/84151416-ec540600-aa95-11ea-9f6c-f58bd8378967.png)
如题，每次一编辑就会有一堆语言
浏览器 firefox 77.0.1

**Comment by lmk123** [comment]
已知问题。。月底发布的新版本中会修复这个问题

**Comment by lmk123** [comment]
v7.0 已经针对这种情况做了优化，应该不会有类似问题了，将在近期发布。
