### ISSUE TITLE
有道翻译复制翻译显示不全

### ISSUE THREAD

**Issue by iwoorst** [lmk123/crx-selection-translate#691]
![image](https://user-images.githubusercontent.com/21360958/84591382-7faf8180-ae70-11ea-8707-a60f159ca57f.png)
![image](https://user-images.githubusercontent.com/21360958/84591436-e6349f80-ae70-11ea-9d7c-42a918860202.png)
百度和其他显示正常，浏览器是chrome 版本 83.0.4103.97（正式版本） （64 位）

**Comment by bestpika** [comment]
我也有遇到同樣的問題，翻譯都只剩一小段

**Comment by lmk123** [comment]
已发布 v6.4.12 修复这个问题，等审核通过之后更新一下试试
