### ISSUE TITLE
无法打开本地pdf

### ISSUE THREAD

**Issue by fishyboy** [lmk123/crx-selection-translate#692]
在给予划词翻译访问本地文件的能力后，当我打开本地pdf的时候，虽然划词翻译会加载pdf-viewer的界面，但是不能加载pdf内容。但是用pdf-viewer这个单独的extension就可以打开本地pdf。

**Comment by lmk123** [comment]
方便提供一下不能打开的 pdf 文件给我么？

**Comment by fishyboy** [comment]
下载链接在这个网页https://libgen.lc/ads.php?md5=7291dbe553a4ccab4da5c39b6c8766b7  
系统是macos high sierra
事实上不仅是这一个pdf,, 任何pdf都打不开

**Comment by lmk123** [comment]
现在我已经发布了新版本 v7.0.5，你试试看还有没有这个问题

**Comment by fishyboy** [comment]
我换回win10了，没法用mac测试，但是我记得前几天神奇的发现好像win10可以，新版本很炫酷！多谢～
