### ISSUE TITLE
提示网络错误，无论是选择百度或者有道都不可以

### ISSUE THREAD

**Issue by haominzheng** [lmk123/crx-selection-translate#696]
使用的edge谷歌版游览器，是可以正常游览网络的，但是使用划词翻译就回应 网络错误，请检查你的网络设置。网络错误

**Comment by lmk123** [comment]
先打开一下 http://fanyi.youdao.com 和 https://fanyi.baidu.com 再试试

**Comment by haominzheng** [comment]
> 先打开一下 http://fanyi.youdao.com 和 https://fanyi.baidu.com 再试试

不可以，试了下到现在还是网络错误，但是这两个链接是可以打开的

**Comment by lmk123** [comment]
我用 edge 卸载了划词翻译后重新安装试了下，第一次使用有道或百度确实会提示网络错误，但打开一下 http://fanyi.youdao.com 和 https://fanyi.baidu.com 之后就恢复正常了；另外，如果开了梯子又没有把这俩连接加入 pac，偶尔也会导致这个问题。

你可以再按照下面的步骤尝试一下：

1. 卸载划词翻译重新安装
2. 关闭梯子
3. 重启浏览器后，打开一下 http://fanyi.youdao.com 和 https://fanyi.baidu.com
4. 再找一个网页试试恢复正常没有

**Comment by haominzheng** [comment]
> 我用 edge 卸载了划词翻译后重新安装试了下，第一次使用有道或百度确实会提示网络错误，但打开一下 http://fanyi.youdao.com 和 https://fanyi.baidu.com 之后就恢复正常了；另外，如果开了梯子又没有把这俩连接加入 pac，偶尔也会导致这个问题。
> 
> 你可以再按照下面的步骤尝试一下：
> 
> 1. 卸载划词翻译重新安装
> 2. 关闭梯子
> 3. 重启浏览器后，打开一下 http://fanyi.youdao.com 和 https://fanyi.baidu.com
> 4. 再找一个网页试试恢复正常没有

卸载之后重新使用确实可以了，感谢
