### ISSUE TITLE
希望域名筛选匹配任意端口号或者支持通配符

### ISSUE THREAD

**Issue by mxalbert1996** [lmk123/crx-selection-translate#697]
我想排除所有地址为 localhost 的网页，无论端口号是多少，但我只能为所有可能的端口号添加一条规则，很不方便。所以希望域名筛选里的网址能匹配任意端口号或者支持通配符。

**Comment by lmk123** [comment]
正在开发的 v7.0.0 版本已包含此功能，预计 7 月底发布，敬请期待。

**Comment by lmk123** [comment]
v7.0 已经支持了黑、白名单，且支持通配符，将在近期发布

**Comment by mxalbert1996** [comment]
新版好像并不支持在域名的末尾使用通配符，也不能匹配任意端口号？
<img width="543" alt="截屏2020-08-31 10 08 48" src="https://user-images.githubusercontent.com/9391933/91674122-4be02000-eb72-11ea-9a7a-aa60a77f90db.png">

**Comment by lmk123** [comment]
是的，不支持在域名的末尾使用通配符，你需要把端口号也写进规则中

**Comment by mxalbert1996** [comment]
那我这个问题并没有解决呀，我还是得为所有可能的端口号添加一条规则。

**Comment by lmk123** [comment]
7.1.5 之后，网址筛选的规则将会匹配所有端口号
