### ISSUE TITLE
有道翻译显示不全

### ISSUE THREAD

**Issue by iwoorst** [lmk123/crx-selection-translate#699]
之前出现过这样的问题，后来更新修复了，今天又出现了   https://github.com/lmk123/crx-selection-translate/issues/691#issue-638329882 
其他翻译引擎正常，当前版本：v6.4.12，Google Chrome版本 84.0.4147.105（正式版本） （64 位）

**Comment by bestpika** [comment]
我也有遇到這個問題

**Comment by cxhttt233** [comment]
[https://www.kanjiantu.com/image/00XOCS](url)
[https://www.kanjiantu.com/image/00XZNP](url)
只显示第一行

**Comment by lmk123** [comment]
已知问题，这个问题已经在 v7.0 中解决，将在近期发布。
