### ISSUE TITLE
自行选择翻译方式及样式建议

### ISSUE THREAD

**Issue by SupermanPro** [lmk123/crx-selection-translate#706]
如题，我前面有提过 (#558)的样式，但很幸运的是您刚好打算做7.0的版本，不过样式上我还是有些小小的简易，劳烦您耐心看完，谢谢。
1、自行选择翻译方式：谷歌和有道的翻译接口很大概率的老是抽风翻译不了，但是又不能选择不调用它们的翻译接口，所以就导致了实际只有百度翻译翻译出来了内容，但实际的显示面板显示了3个，导致面板有效利用率低。
建议：方案一、自动判断翻译状态，成功翻译的才加载出来，这个状态判断现在应该就有的，不然也不会提示让刷新重试；
           方案二、可以自行选择自己喜欢的翻译方式，有些人喜欢百度、有些人喜欢谷歌、有些人喜欢有道，不能笼统的将所有翻译方式都放出来，自行的选择自己喜欢的方式，才是有效利用率最高的。
           方案三、在方案二的基础上，增加自定义翻译接口配置页，这个看您的时间，因为我看到好多朋友提出加这个翻译加那个翻译，所以建议您可以做一个翻译接口的配置页，即可以解决很大一部分市面上的翻译接口。

2、样式建议：翻译窗口页面上方、下方，按钮功能区的按键图标和选中的翻译语句，这三项不常用的功能，就占据的翻译窗口的50%（在第一项建议方案二的基础上）。
建议：方案一、可在插件配置页设置隐藏，因为这些内容，在配置也设置好后，一般很少有人去动这些东西。
           方案二、可以修改小一些，不至于喧宾夺主，将主要需要的翻译区突出显示。
和修改小一些。
在第一项建议方案二的基础上的显示效果：
![image](https://user-images.githubusercontent.com/47558436/91254651-82debc00-e795-11ea-9e8f-427560cfc90d.png)

在第一项建议方案二的基础上，隐藏功能键的显示效果：
![image](https://user-images.githubusercontent.com/47558436/91254812-e537bc80-e795-11ea-9497-5361196dbf59.png)

**Comment by lmk123** [comment]
第一点将在下个版本加入。

关于第二点，我觉得在第一点的基础上（即你发的第一张图）已经够精简了，另外，固定图标、关闭按钮、鼠标悬浮取词是很多用户都希望有的功能，一刀切的隐藏并不合适。

**Comment by IEXPECTATION** [comment]
请问，独立窗口的输入框能不能直接输入呀，不想点画笔。

**Comment by lmk123** [comment]
> 请问，独立窗口的输入框能不能直接输入呀，不想点画笔。

在下个版本中会将独立窗口改为直接输入的

**Comment by lmk123** [comment]
7.1.0 版本将语种切换、翻译文本和悬浮取词开关收纳进了设置按钮中，也减少了面板各元素的间距，界面如下：
![image](https://user-images.githubusercontent.com/5035625/92768980-1a195580-f3cb-11ea-9126-8f6207ddf24d.png)

头部确实无法隐藏掉，拖动窗口的留白和一些功能按钮都需要头部来承载。不过，我觉得这样已经很精简了

**Comment by SupermanPro** [comment]
感谢您的无私付出，这样已经是很完美了o(^_^)o
