### ISSUE TITLE
firefox 插件快捷键与 macOS X 下 firefox 退出的快捷键冲突

### ISSUE THREAD

**Issue by sbilly** [lmk123/crx-selection-translate#707]
firefox 插件快捷键与 macOS X 下 firefox 退出的快捷键冲突

当按下 command+Q 的时候，预期正常操作是退出 firefox，但实际呼出了 firefox 插件的翻译界面。

**Comment by lmk123** [comment]
我刚才发布了 v7.0.4，把 macOS 的快捷键改回 Ctrl + Q 了，你可以试试还有没有问题，如果还有的话可以继续留言。

**Comment by sbilly** [comment]
firefox 下我验证已经好了，但在 chrome 下按 ctrl+q 插件没有反应。

**Comment by lmk123** [comment]
很抱歉过了这么久我才处理这个问题 :joy:

我用划词翻译 v8.6.6 在 macOS 12.0.1 的 Chrome 95 试了一下，control + Q 可以正常弹出扩展页。如果你仍然不能弹出，欢迎继续留言！
