### ISSUE TITLE
能否给一个开关让用户自己选择，开启或关闭选取文字后的翻译图标

### ISSUE THREAD

**Issue by Miss0you** [lmk123/crx-selection-translate#708]
![s1](https://user-images.githubusercontent.com/42348861/91629985-4ebb0380-ea00-11ea-987b-fe5abef2bb1f.png)
理由：
1.选取时，会遮挡第二行的显示
2.选中文字后，想取消选中状态容易误点击（主要还是遮挡）

能否给一个开关让用户自己选择，开启或关闭选取文字后的悬浮图标，（可以默认为展示状态，熟练的用户其实是可以通过快捷键翻译的，不需要这个图标）

**Comment by vvyoko** [comment]
以前有开关的，现在要么自动弹出来，要么弹出个图标。
对我这种只用右键的有点不友好了。。。

**Comment by wolfbolin** [comment]
更新前可以设置只有配合Ctrl滑词才弹出翻译，现在不管划啥都会弹出，真的很难受。（没事瞎划词用户的怨念

**Comment by lmk123** [comment]
其实你是想要在所有网站中都禁用划词翻译吧？

之前的版本有一个全局开关，现在的版本改为了在黑名单中添加一条规则 `*/*`。新版本的规则确实挺不直观的，我会在后面的版本加几个常见规则，点击即可启用，比如你需要的“在所有网站中禁用划词翻译”
