### ISSUE TITLE
新版插件在mac上拖动翻译窗口时总是跑到左上角

### ISSUE THREAD

**Issue by eightHundreds** [lmk123/crx-selection-translate#709]
今天刚自动更新的插件，在无痕窗口中也能复现

- 浏览器是最新的edge 
5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
chrome也试过
- 系统 macos 10.14.4 (18E226)
- 使用mac 三指拖拽

**Comment by mritd** [comment]
chrome 浏览器出现相同问题

**Comment by laozhangjia** [comment]
mac 版Chrome三指拖动同样问题

**Comment by lmk123** [comment]
已在 v7.1.7 版本中修复此问题，v7.1.7 版本已提交审核
