### ISSUE TITLE
帮忙测试划词翻译 v6.0 Beta 版吧！

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#71]
经过两个多月的开发（v6.0 的第一条 commit 是 1b2a632），划词翻译今天发布 v6.0 Beta 版了！

v6.0 有这些改进：

 + 简单调整 UI 为（自认为的）扁平化风格
 + 网页划词翻译也能像翻译盒子那样输入待翻译的文本、选择源语种与目标语种了
 + v5.x 中划词翻译只能全局开关，现在可以使用黑名单模式在指定网站里禁用

由于是 Beta 版，所以难免会有一些小问题，我需要你帮忙找出这些问题，并[将问题提交给我](https://github.com/lmk123/crx-selection-translate/issues/new)。

## 如何参与测试

首先，你需要有一个 Google 账号。

其次，将你的 Google 账号（一个电子邮箱）在下方留言，或者[发送邮件给我](mailto:me@limingkai.cn)

最后，我会将你的账号添加进测试人员列表，然后你才能在 Chrome 网上应用店里安装划词翻译 Beta 版，添加后我会在此问题下方或邮件通知你。

划词翻译 Beta 版安装地址：**注意：只有测试人员才能看到**
https://chrome.google.com/webstore/detail/aemnpdhnnlgmalcakbnjkoomgfbgppah

**Comment by kangnixi** [comment]
kangnixi@gmail.com

**Comment by lmk123** [comment]
@kangnixi 已添加

**Comment by kangnixi** [comment]
@lmk123 提示『未找到相关项目，该项目可能已被作者删除。』

**Comment by lmk123** [comment]
@kangnixi 过两分钟再刷新

**Comment by ifyour** [comment]
wmm.joan@gamil.com

**Comment by GameRisker** [comment]
jamesyang686@gmail.com

**Comment by kangnixi** [comment]
@lmk123 能不能写一个 6.x 版本 如果使用开发版本？我想本地研究研究源码

**Comment by lmk123** [comment]
@kangnixi 好的，我会把步骤写在 README.md 里的。

**Comment by kangnixi** [comment]
@lmk123 你回复速度真快，谢谢咯！赞一个你写的插件，确实用了不少新技术，有些技术我也刚开始接触

**Comment by lmk123** [comment]
@ifyour @GameRisker 已添加

**Comment by henices** [comment]
zhouzhenster@gmail.com

**Comment by lmk123** [comment]
@henices 已添加

**Comment by p0we7** [comment]
pan2266813@gmail.com

**Comment by lmk123** [comment]
@p0we7 已添加

**Comment by vvyoko** [comment]
vvyoko@gmail.com

**Comment by KylinJ** [comment]
kylin0j#gmail.com

**Comment by lmk123** [comment]
@vvyoko @KylinJ 已添加。

另外，我刚才更新了测试版（v6.0.0.114），大家最好手动更新一下，谢谢。

**Comment by alanturing722** [comment]
zhyxingh@gmail.com

**Comment by dudong0726** [comment]
dudong0726#gmail.com

**Comment by tasselx** [comment]
tasselx@gmail.com

**Comment by allenwoods** [comment]
warmanlyl@gmail.com

**Comment by lmk123** [comment]
@alanturing722 @dudong0726 @tasselx @allenwoods 已添加，谢谢参与 :)

**Comment by mapleshadow** [comment]
请加入我的测试，谢谢。
mapleshadow@gmail.com

**Comment by lmk123** [comment]
@mapleshadow 已添加

**Comment by isClumsyBird** [comment]
isClumsyBird@gmail.com

**Comment by mapleshadow** [comment]
@lmk123 好的谢谢，但为什么点击测试版地址后提示，错误？找不到

**Comment by lmk123** [comment]
@mapleshadow 我确认过一遍了，确实已经把你加入到测试人员账号列表里了。你检查一下你是否已经登录到 Chrome 网上应用店，并且确保你是用你发给我的账号登录的。

**Comment by mapleshadow** [comment]
@lmk123 我有多个谷歌帐号，确实是帐号问题导致，现在好了，谢谢了哈

**Comment by lozzo** [comment]
wuyouget@gmail.com

**Comment by iLtc** [comment]
i#iltc.io

**Comment by lmk123** [comment]
@lozzo @iLtc 已添加

**Comment by lmk123** [comment]
各位，我刚才更新了 v6.0.0.125 版本，这次主要是加快了第一次划词时翻译按钮或窗口的弹出速度。
如果没发现什么重大问题，那预计这个星期内会正式发布。

**Comment by lmk123** [comment]
谢谢大家参与测试，现在我准备将划词翻译发布至 Chrome 网上应用店了。:smile:

**Comment by isClumsyBird** [comment]
@lmk123 添加我一个呗，谢谢，一直在用这个插件，很爽，想体验一下新版本，谢谢。isClumsyBird@gmail.com

**Comment by lmk123** [comment]
@isClumsyBird 已经发布了。
