### ISSUE TITLE
图标和快捷键

### ISSUE THREAD

**Issue by luchenhao** [lmk123/crx-selection-translate#710]
1.划词后显示翻译按钮开关没了，现在关闭后会直接弹出翻译窗口，那个图标有时候会发生遮挡。
2.快捷键打开独立翻译窗口没反应，原来的翻译网页中选中的文本：Alt + A这个没了，希望能恢复。
![snipaste_20200829_201951](https://user-images.githubusercontent.com/16728827/91636702-4335ff80-ea35-11ea-8c32-9c48f937bf93.png)

**Comment by luchenhao** [comment]
新版能显示多个翻译源这个还不错

**Comment by lmk123** [comment]
关于第一点，新版本里是有控制翻译按钮显示/隐藏的设置的，你想说的是没有“配合 Ctrl 键使用划词翻译”这个设置了吧？

在新版本中，你可以将 `*/*` 这个规则添加进黑名单， 这样的话只有当你使用 Ctrl + 鼠标划词时才会弹出翻译结果。

第二点见我刚才发的公告：#712

**Comment by lmk123** [comment]
v7.0.5 已经上架了，如果这个问题还是有的话，可以继续留言。

**Comment by luchenhao** [comment]
问题7.0.5都解决了，谢谢！
