### ISSUE TITLE
v7.0.2 已上架，v7.0.5 已提交审核

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#712]
由于失误，我误将没有开发完整的 v7.0.1 版本发布在了 Chrome 商店中，这些功能是缺失的：

- 点击扩展图标后的翻译弹窗没有加上
- Alt + A 的快捷键没有加上
- 扩展图标的快捷键被错误的设置成了 Ctrl + Shift + Q（以前是 Ctrl + Q）

**这些缺失的功能和问题已经在 v7.0.2 中解决，v7.0.2 已上架，目前我已经将 v7.0.5 提交给了 Chrome 和 Edge 审核，Firefox 已上架 v7.0.5。**

v7.0.5 集中解决了跟 v6.x 版本使用体验上不一致的问题：

1. 复制按钮直接显示在了面板上，且复制的内容去掉了翻译来源提示；
2. 翻译窗口已经重新加入到点击扩展图标后出现的弹窗中，并且快捷键也改回了旧版本的 Ctrl + Q，同时修复了不能输入空格/换行、打开时没有自动聚焦、没有自动读取剪切板的问题；
3. 中文现在会自动翻译成英文；
4. 支持按下 Ctrl 键翻译页面中的文本，并且提供了设置项开关；
5. 给翻译结果添加朗读功能；
6. 翻译面板界面改进：图标默认隐藏、鼠标移动到翻译结果上才显示、菜单只需要鼠标移动上去就会自动打开，无需点击；

至此，新版本的使用体验跟旧版已基本一致，之后的版本会进一步优化黑/白名单和翻译面板的使用体验，也欢迎大家继续在商店评论和公众号中向我反馈问题。

**Comment by xiekeyi98** [comment]
感谢开发者优秀的软件～

**Comment by Humsan** [comment]
我说怎么都要打开独立的一个翻译窗口了....

**Comment by consatan** [comment]
自动升级到 7.0.1 版本后，删除了，然后手动安装了 6.x 版本，但还是会自动升级到 7.0.1，这要咋整？

**Comment by fa1c0n1** [comment]
7.0.1版本的翻译输入窗口，竟然不能输入空格..

**Comment by tortoo** [comment]
自动升级后瘫痪了😹……的确，chrome的插件会自动更新，安装6.x版本后还是会自动升级。希望作者能放出7.0.2的离线版，多谢哈~

**Comment by tortoo** [comment]
或者帮忙加一个自动更新的开关，可能有不少人还是更喜欢6.x的简约界面，它能在通过css改动页面背景的情况下和页面背景色调保持一致

**Comment by consatan** [comment]
@tortoo 
先卸载从 chrome store 里下载的扩展

在 release 页面下载 6.x 版本，修改后缀为 zip 然后解压，编辑里面的 manifest.json 文件，搜索 update_url，将这个字段里的 url 替换为 任意 url （比如 https://httpbin.org/status/200）

在扩展页面里打开“开发者模式”，然后“加载已加压的扩展程序”，这样就可以保留在 6.x 版本而且不会自动升级了（以后也不会自动升级了，必须手动删除然后从 chrome store 里重新下载才可以）

**Comment by tortoo** [comment]
@consatan 多谢哈！我刚还想@你，说我又卸载了一遍，然后安装，到现在还没发现它自动升级。我先静观一下，它要是不自动升就不动了。你说的办法，我看到了，但是[这里](https://zhidao.baidu.com/question/618602795919122492.html?qbl=relate_question_0&word=chrome%E4%AF%C0%C0%C6%F7%B2%E5%BC%FE%BD%FB%D3%C3%D7%D4%B6%AF%B8%FC%D0%C2)面有人评论，说chrome会校验插件资源文件是否被篡改。我们都观察一段，如果还是会自动更，我就用你的办法，如果你的也自动更了，就只能等作者了😹

**Comment by consatan** [comment]
@tortoo 开启开发者模式就不会检测了

**Comment by tortoo** [comment]
@consatan 囧，才反应过来，你改的是源文件，应该有效

**Comment by tortoo** [comment]
@consatan OK，就是得一直开着对吧

**Comment by consatan** [comment]
@tortoo 理论上安装完就可以把开发者模式关了，不过我一直都是开着开发者模式的，所以不是很确定

**Comment by tortoo** [comment]
@consatan 那我也开着，好像之前也没关😹

**Comment by PaulXu-cn** [comment]
我个人感觉还漏了一个功能：
1. 仅在 “划词时按住Ctrl键不放” 才触发 翻译。

也就是这个功能：

启用：划词后，先弹出翻译按钮，点击按钮后再弹出翻译结果。
关闭：_划词后直接弹出翻译结果。_ 

> 原来是关闭就关闭了。需要又见触发。

必须通过：

划词时按住Ctrl键不放
从右键菜单中选择“翻译选中的文本”

才能触发。

**Comment by lmk123** [comment]
@PaulXu-cn 你需要的其实是在黑名单中添加一条规则“*/*”，这样就能在所有网站中禁用网页划词，然后只有通过 Ctrl + 划词才会弹出翻译结果。在 v7.0.5 我把“在所有网站中禁用网页划词”做成了一个勾选框，已经提交审核了，目前你可以手动添加下黑名单规则来达成同样的效果。

**Comment by xx10n31y** [comment]
以前应该是没有直接读取系统剪切板的? 是否开启可选项好点?

**Comment by lmk123** [comment]
v7.0.5 已上架三大商店，这个公告我就关闭了。

@xx10n31y 开一个新的工单吧
