### ISSUE TITLE
深色模式开关无效

### ISSUE THREAD

**Issue by xiezibuyongbi** [lmk123/crx-selection-translate#714]
由于阅读需要装了一款浏览器全局深色模式插件"super dark mode"，但是只要这个插件启用（无论是否启用了"super dark mode"的深色模式），划词翻译按钮、翻译框都是深色模式，只有停用插件才能恢复正常。之前用的绿色边框的划词翻译未出现此问题

**Comment by lmk123** [comment]
感谢反馈，此问题已在 v8.6.7 中修复。

cc @wisecrick
