### ISSUE TITLE
新版本划词后，按 command+c 复制也会弹出翻译框，希望可以优化下

### ISSUE THREAD

**Issue by catcto** [lmk123/crx-selection-translate#716]

**Comment by lmk123** [comment]
提供一下浏览器名称、版本和划词翻译版本

**Comment by aweiu** [comment]
我也有这问题：

系统：Mac OS 10.15.6 (19G2021)
浏览器：Chrome 85.0.4183.83
划词翻译：7.0.2

看起来是选中词后 `Command` 快捷键导致的，没找到在哪关掉

**Comment by lmk123** [comment]
你们的复制操作是不是按下 Command 后划词，然后按下 C 键复制？

如果是这样的话，这是因为 Command + 划词会自动触发翻译，可以将划词翻译更新到 v7.0.5，并在设置中关闭“配合辅助键使用”即可。

如果这样还是没能解决你们的问题，可以继续留言。
