### ISSUE TITLE
建议对输入内容进行预处理

### ISSUE THREAD

**Issue by ascii-10** [lmk123/crx-selection-translate#717]
我一直使用这个翻译插件的很大一个原因，就是我复制进去一段话后，可以将行尾的回车删去，这对于进行整段文字的翻译非常有帮助。除此之外，原来的翻译源相当专业（插件选项里使用的是国内谷歌，但是效果比网页版谷歌翻译好得多），现在变成百度、谷歌、有道，那我还不如直接用网页版，这里文本框还那么小。

**Comment by lmk123** [comment]
现在的谷歌就是以前的国内版谷歌，只是我没有区分国内和国外了。

文本是有预处理的，可能是你遇到了 bug，提供一下浏览器版本、划词翻译版本，我重现一下

**Comment by ascii-10** [comment]
浏览器：chrome&nbsp;84.0.4147.135（正式版本） （64 位）
插件：7.0.2

非常感谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmk123/crx-selection-translate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 下午4:34
收件人:&nbsp;"lmk123/crx-selection-translate"<crx-selection-translate@noreply.github.com&gt;;
抄送:&nbsp;"610869676"<610869676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lmk123/crx-selection-translate] 建议对输入内容进行预处理 (#717)





 
现在的谷歌就是以前的国内版谷歌，只是我没有区分国内和国外了。
 
文本是有预处理的，可能是你遇到了 bug，提供一下浏览器版本、划词翻译版本，我重现一下

**Comment by ChenChenGith** [comment]
同样的需求。
在之前的版本中（就是不能打开单独翻译窗口的版本），是可以自动去除段落之后的回车的，在对从pdf中复制的内容进行翻译时特别方便。现在这个功能没有了。

浏览器：ms edge
插件版本：7.0.2

**Comment by lmk123** [comment]
你们的问题是不是跟 #724 是重复的？

**Comment by ascii-10** [comment]
是的，就是这个问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmk123/crx-selection-translate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上10:43
收件人:&nbsp;"lmk123/crx-selection-translate"<crx-selection-translate@noreply.github.com&gt;;
抄送:&nbsp;"610869676"<610869676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lmk123/crx-selection-translate] 建议对输入内容进行预处理 (#717)





 
你们的问题是不是跟 #724 是重复的？

**Comment by lmk123** [comment]
那这个工单我就关闭了，问题的进展可以关注 #724
