### ISSUE TITLE
翻译按钮图标过大

### ISSUE THREAD

**Issue by capitalwell** [lmk123/crx-selection-translate#718]
新版的翻译按钮图标过大，普遍比行距大，会遮挡文字，以前旧版的翻译按钮的大小就很合适
![feedback1](https://user-images.githubusercontent.com/22556759/91696181-c83e2780-eba1-11ea-8bc9-7a17083e51ac.PNG)

**Comment by lmk123** [comment]
收到，后面的版本中会把大小调小

**Comment by SouthLink** [comment]
能不能优化一下，ctrl+鼠标划词的时候才出现按钮或者翻译框，有时候很多英文选中情况不需要翻译

**Comment by lmk123** [comment]
> 能不能优化一下，设置一个快捷键ctrl+鼠标划词的时候才出现按钮或者翻译框，有时候很多英文选中情况不需要翻译

设置里勾选”在所有网站中禁用网页划词“即可

**Comment by lmk123** [comment]
v7.1.0 已经将按钮尺寸从 30 x 30 调整为了 22 x 22（旧版本的尺寸为 20 x 20）
