### ISSUE TITLE
改版不如之前的好用.特别是复制按钮隐藏到菜单里面了.

### ISSUE THREAD

**Issue by lexluthors** [lmk123/crx-selection-translate#719]
实在是想不明白为啥把复制按钮隐藏起来,放到外面就两个字,占你多大地方了?特别影响体验!还要多点一次打开菜单才能复制,体验糟糕透了.

**Comment by xx10n31y** [comment]
确实是习惯7.0.1之前的版本之后，突然来了个大变化，有点难适应！

**Comment by lmk123** [comment]
看一下公告 #712
