### ISSUE TITLE
v7.0.2版本问题反馈

### ISSUE THREAD

**Issue by xx10n31y** [lmk123/crx-selection-translate#720]
1. 输入框无法输入空格
![wrong_input.png](https://i.loli.net/2020/08/31/enURbICmzOyKETt.png)
2. 选择语言样式问题
![choice_language.png](https://i.loli.net/2020/08/31/wiX8EaTYtMxAgv7.png)

**Comment by lmk123** [comment]
第 1 点已经在 v7.0.5 中改好了，正在审核；第 2 点是已知问题，后面的版本会修复
