### ISSUE TITLE
建议还原6.x版本中，不按ctrl键就不会弹窗的功能

### ISSUE THREAD

**Issue by wuqiling97** [lmk123/crx-selection-translate#721]
6.x版本当中，勾选“配合 Ctrl 键使用划词翻译”，不勾“划词后显示翻译按钮”，就可以实现选中文本时不会弹出翻译按钮或翻译窗口，只有按下ctrl时才能翻译。

但是v7.0.4选中文本后，翻译按钮或翻译窗口必定会弹出一个，有些恼人，某些网站（比如QQ邮箱）在取消选择之后翻译按钮还在，但是我没注意到当时这个bug是怎么出现的。

所以希望能还原v6.x的这个功能

**Comment by liguobao** [comment]
同意，当前版本选中文本之后直接有个图标，让人疑惑。

**Comment by lmk123** [comment]
最新的 v7.0.5 已经把这个规则做成了一个设置项，正在审核中，在上架前你可以手动在黑名单中加入一条规则 */* 即可在所有网站中禁用划词翻译，然后就只有 Ctrl + 划词才会弹出翻译结果了。
