### ISSUE TITLE
开放自定义翻译接口

### ISSUE THREAD

**Issue by NewConn** [lmk123/crx-selection-translate#722]
公司内网在测试自己的翻译服务，打开Google翻译会强制跳转到自己的翻译服务，请问能不能开放自定义翻译接口

**Comment by lmk123** [comment]
你的需求应该跟 #722 是一样的，你这个工单我就关闭了，可以去 #722 跟踪进展。

后面的版本我会考虑加个设置项，可以自行设置谷歌翻译的接口域名，这样就可以自己起个代理来使用谷歌翻译了。
