### ISSUE TITLE
图标是真的丑

### ISSUE THREAD

**Issue by devinlee24** [lmk123/crx-selection-translate#723]

**Comment by lmk123** [comment]
你完全可以提一些建议、或者干脆设计一个你觉得好的让图标更好看，只是吐槽一句我能帮到你什么呢。。到时候我换了一个你还是说丑，那到底丑在哪里？

**Comment by devinlee24** [comment]
> 你完全可以提一些建议、或者干脆设计一个你觉得好的让图标更好看，只是吐槽一句我能帮到你什么呢。。到时候我换了一个你还是说丑，那到底丑在哪里？

我并不是有别的意思哈 我也一直在用你的作品 当然是希望它越来越好。比如图标不用这么大，也可以重新设计一个清新一点的

**Comment by lmk123** [comment]
那么你直接说图标太大了不就好了。。

后面我会调小的
