### ISSUE TITLE
使用谷歌翻译选取多行文本时每一行末尾带有换行空格

### ISSUE THREAD

**Issue by jase11** [lmk123/crx-selection-translate#724]
目前在Chrome上使用 **v7.0.5** 的扩展。对于大多数网站, 选取网页上的多行文本时, 每一行并不会被隔开, 文本是连续的. 但对于一些网站 (尤其是 [Documentation](https://docs.python.org/3/tutorial/index.html) 类型的网站), 选取多行文本时, 每一行被末尾的换行空格分隔开了 (类似于选择 PDF 中的文本), 这将对翻译造成影响, 因为完整的句子被隔开了. 
看起来这像是网站的原因. 然而, 使用旧版扩展 (**v6.4.12.1**) 访问上述网站并不会遇到这一问题. 当然, 从上述网站直接复制下来的文本也是没有换行空格的.

**v7.0.5**

![new version](https://user-images.githubusercontent.com/27488572/91855333-9e672c80-ec97-11ea-83a6-0485e0c34e46.gif)

**v6.4.12.1**

![old version](https://user-images.githubusercontent.com/27488572/91855361-a757fe00-ec97-11ea-903f-a792d71bf98c.gif)

**copy text**

![copy](https://user-images.githubusercontent.com/27488572/91855421-bdfe5500-ec97-11ea-9bf0-f680db487fd5.gif)

**Comment by lmk123** [comment]
计划在下个版本（也就是 v7.0.6）中修复。

另外，你的问题反馈很细致，有新旧动图对比，很赞！希望大家都能像你这样反馈问题 :joy:

**Comment by GH01** [comment]
注意看 图2：旧版会 自动断句。
我个人挺喜欢那样的。
不知能否保留此特性？

**Comment by lmk123** [comment]
> 注意看 图2：旧版会 自动断句。
> 我个人挺喜欢那样的。
> 不知能否保留此特性？

 @GH01 在 v7.0.6 中我将翻译结果的断句去掉了。如果你觉得有必要保留，可以开个 issue 单独讨论

**Comment by lmk123** [comment]
已在 v7.0.6 中修复。

下面技术相关的细节：

新版本中使用了 `window.getSelection().getRangeAt(0).toString()` 获取选中的文本，但是这个方法返回的文本中会“自以为是”的给句子进行断句，所以修复的方法是换回了之前版本使用的 `window.getSelection().toString()`
