### ISSUE TITLE
不习惯新的UI和把百毒强硬放第一个不能设置，表示墙裂反对

### ISSUE THREAD

**Issue by yygcom** [lmk123/crx-selection-translate#725]
希望换回经典界面

**Comment by luchenhao** [comment]
![123](https://user-images.githubusercontent.com/16728827/91936301-27c34100-ed22-11ea-8a06-c10851501935.png)

**Comment by lmk123** [comment]
切换翻译源的方式楼上已经贴图了。

另外，不打算回退到旧版本了，如果你觉得新版本不好用，你可以反馈给我，我会持续改进。
