### ISSUE TITLE
翻译面板有遮挡

### ISSUE THREAD

**Issue by qwertxyz** [lmk123/crx-selection-translate#726]
### 版本：
- Chrome 版本 85.0.4183.83（正式版本） （64 位）
- 划词翻译 7.0.5
- Octotree 5.4.1

![aaa](https://user-images.githubusercontent.com/6167082/91930354-38b88600-ed13-11ea-9f86-4304a11dc99b.gif)

应该 Octotree 插件导致的，获取鼠标的位置不正确

![bbb](https://user-images.githubusercontent.com/6167082/91930592-d3b16000-ed13-11ea-8ff9-8fb480020e6d.gif)

**Comment by qwertxyz** [comment]
虽然现在不遮挡了，但是位置还不正确。

**Comment by lmk123** [comment]
位置不正确的问题我单独开了一个工单 #776
