### ISSUE TITLE
建议：[选项]的左栏：当前所在类别 最好能高亮

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#727]
建议：
[选项]的左栏：当前所在类别 最好能高亮。

**Comment by GH01** [comment]
[设置]中，子类别的高亮 最好能跟随用户的滚动操作。

另外，
[设置]中，各块的标题（通用，网页划词，翻译面板，语音朗读）应该增大区别（比如：居中/+灰色/+背景色）。
目前这样，会被当成子类别，点击却不应，让人愣神儿……

**Comment by lmk123** [comment]
我打算在未来的版本中改变一下设置页的布局，不使用左侧菜单的形式了，太长了。

我准备改成 tab 的形式，每个大功能就是一个 tab

**Comment by lmk123** [comment]
设置页左栏现在已经会高亮了，这个 issue 我就关闭了。

P.S. 好久没看到你提问题了 :joy:
