### ISSUE TITLE
+选项：记住上次窗口位置（全局+永久）

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#729]
当前设置：
所有网站禁用，
只用快捷键调用。

操作：
在页面A选中文字，用快捷键打开页面浮窗，拖到一角，关掉；
在页面B选中文字，用快捷键打开页面浮窗。

▲我希望此时能自动沿用上次关掉时的位置，全局表现一致。
▲永久(跨会话)记住位置，直至下次改动。

**Comment by GH01** [comment]
独立窗口 也应记住 位置+大小。

**Comment by lmk123** [comment]
网页划词面板的固定状态和位置已经在 v7.2.0 中改成了全局同步的。

独立窗口的将在后续版本中加入 #787
