### ISSUE TITLE
删除“打开独立翻译窗口”快捷键后 会显示“快捷键冲突”

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#731]
删除“打开独立翻译窗口”快捷键，
打开按钮弹窗，
打开底部的“试不试独立翻译窗口吧”，
里面显示“独立窗口快捷键冲突”。

**Comment by lmk123** [comment]
这是我有意为之的，因为如果在安装扩展的时候，全局快捷键 Ctrl + Shift + 1 已经被占用的话，Chrome 不会添加这个快捷键，所以我给出了这样的提示。

你觉得这样有什么问题或可以改进的地方吗？

**Comment by GH01** [comment]
哦，这样简单省事。
那说明中可以包含置空这种情况：
:warning: 独立窗口快捷键**不存在**
……快捷键已被占用**或清除**……

P.S.
其实Chrome的快捷键，局限、毛病很多，举一个，也许可以帮人解解惑：
如果设了一个 全局快捷键（或称 热键），
然后想把此键改给别的扩展用，或者删除，
要记得先把它的“全局”关掉，再改(或删)，
否则，浏览器本轮会话期间，这个热键谁也用不了了，
原因是：此键还挂在系统里，但变成无主了，浏览器退出时才会被清除。
（注意：在同一扩展上 先改掉再改回 同理。）

可以用 HotKeysList 这类工具查看当前被占用的所有热键：
https://www.nirsoft.net/utils/hot_keys_list.html

**Comment by lmk123** [comment]
我改一下提示

**Comment by lmk123** [comment]
Done.
