### ISSUE TITLE
“返回了错误的数据”导致“查看详细结果”菜单项也变灰

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#732]
当(反复测试导致)谷歌翻译 显示“返回了错误的数据”后，其“查看详细结果”菜单项也变灰。
这个没必要吧。
此项应该永久可用。

**Comment by GH01** [comment]
7.1.0
百度 发生网络错误时，[查看详细结果]按钮 也不会显示。

其实发生网络错误时，[复制]按钮 也没必要隐藏。

这些悬停才显示的按钮，我好奇触屏用户怎么用？

**Comment by lmk123** [comment]
> 这些悬停才显示的按钮，我好奇触屏用户怎么用？

触屏用户点击一下翻译结果区域，按钮应该是会显示出来的。

目前没有收到触屏用户的相关反馈，如果有会再改进。

**Comment by GH01** [comment]
#892 时也同样遇到这个问题：翻译结果未显示时，“查看详细结果”按钮就不会出现。
我希望是：“查看详细结果”按钮 无条件 始终 可用。
建议把标题改一下，让我们知道你的目标是怎样的。

**Comment by lmk123** [comment]
已在即将发布的 v8.2.0 中改进了这个问题，之后即使翻译报错了，此按钮也不会变灰。

但是，在 loading 过程中它仍然是灰色的，不过只有 deepl 才会 loading 很久，所以……先这样吧 :joy:
