### ISSUE TITLE
翻译窗口不可关闭

### ISSUE THREAD

**Issue by edte** [lmk123/crx-selection-translate#734]
突然无法关闭这个窗口

![](https://img2020.cnblogs.com/blog/1823594/202009/1823594-20200903114621468-2143487023.png)

每次选中都会弹出这个窗口
![](https://img2020.cnblogs.com/blog/1823594/202009/1823594-20200903114731683-138240597.png)

我想要关闭这个窗口，只有想要翻译的时候才按 Ctrl 来使用，但是我没有找到关闭的方法。

**Comment by lmk123** [comment]
在设置中开启“在所有网站中禁用网页划词”即可
