### ISSUE TITLE
输入需要翻译的文本末尾不能输入空格

### ISSUE THREAD

**Issue by wz828** [lmk123/crx-selection-translate#736]
输入需要翻译的文本末尾不能输入空格

**Comment by lmk123** [comment]
v7.0.5 已经修复了这个问题，如果你的划词翻译版本是 v7.0.5 但还有这个问题，请按照官网的说明补充信息。https://hcfy.limingkai.cn/issues.html

**Comment by wz828** [comment]
ok，v7.0.5没问题
