### ISSUE TITLE
刚看见有人提了个单词本的功能，有没有兴趣一起组建一个新的项目？

### ISSUE THREAD

**Issue by GameRisker** [lmk123/crx-selection-translate#74]
看见还是有很多朋友和我有一样的想法，可能大家也都发现，每次都划词翻译，导致始终无法记得这些单词，或许我们可以再开一个基于crx-selection-translate的 单词本项目，来做一些背单词、复习单词、学习单词的功能。把我们经常划过的单词给牢牢的掌握。有共鸣的朋友么，也希望@lmk123 给予支持！
感兴趣的加群：497502134

**Comment by lmk123** [comment]
cc #41

**Comment by lmk123** [comment]
长时间无人响应 :joy:

其实我在考虑做一个收藏功能，可以把划过的词收藏起来，但是不会实现__背单词、复习单词、学习单词的功能__。

**Comment by lmk123** [comment]
因为几乎没人响应，我把这个讨论关闭了。

**Comment by shuaiwww** [comment]
我是很想参与，就怕能力不够。收藏功能也很好啊，太复杂没必要。
