### ISSUE TITLE
辅助按键设置无效

### ISSUE THREAD

**Issue by op69qs** [lmk123/crx-selection-translate#741]
在打开 配合辅助按键使用 后通过按住command才翻译的效果不生效，任意网站下都可以重现
系统 macos
浏览器 EDGE 86.0.601.1 
划词翻译：7.0.6

**Comment by Famine-Life** [comment]
chrome出现同上问题，
划词翻译：7.0.6

这个是在这两天我更新后出现的问题，原有的好用。

**Comment by op69qs** [comment]
应该算是bug了

**Comment by lmk123** [comment]
这个问题已经在 v7.1.5 中修复了，大家可以测试一下还有没有，如果还有的话欢迎继续留言让我知道。

**Comment by lmk123** [comment]
我在 MacOS 的 Chrome 和 Edge 上安装了 v7.1.5 试了下，是没有这个问题的，可能是在 v7.0.6 之后的版本又修复了，大家可以升级到 v7.1.5 之后再试一下有没有，如果还是有的话可以继续留言。

另外，也可以尝试一下卸载之后重新安装看看会不会修复这个问题。

**Comment by lmk123** [comment]
或者是不是按下右边的 Command 没有用，左边的是好的？如果是的话，那就是跟 #742 是同一个问题，这个问题会在 v7.1.6 中修复

**Comment by lmk123** [comment]
这个问题已经在 v7.1.4 中修复了

**Comment by lmk123** [comment]
我在 v7.1.5 中试了下，没有重现；然后我又打了个 v7.0.6 的包试了下，也没有重现。。。

这也可能是因为我尝试的时候不是从旧版本升级上来、而是直接安装的 v7.0.6 / v7.1.5 来试的，你们现在应该已经自动升级到 v7.1.5 了，如果你们还是有这个问题，也可以尝试卸载之后重新安装试试。

另外，如果你们在 v7.1.5 还是有这个问题，希望你们能打开代码控制台，如果有红色的报错截图给我，我可以进一步检查一下。

代码控制台打开方法：

1. 鼠标右键点击页面，点击“检查”，页面底部会弹出开发人员面板
2. 将选项卡切换到 Console
3. 如果有红色的字，截下图发在这里
