### ISSUE TITLE
将次要语言作为设置项，而不是默认英文

### ISSUE THREAD

**Issue by KKKKKKYYYY** [lmk123/crx-selection-translate#743]
中文情况下自动翻译成英文，那我翻译繁体字时他也识别为中文自动翻译成了英文，而不会翻译成简体中文。

**Comment by KKKKKKYYYY** [comment]
![image](https://user-images.githubusercontent.com/55151709/92677162-bd2f8800-f355-11ea-8a67-5975028714e7.png)

**Comment by lmk123** [comment]
v7.1.0 版本中可以设置次要目标语种，你可以将默认的英文设置成中文，这样就不会自动将中文翻译成英文了。
