### ISSUE TITLE
翻译源只有谷歌翻译了吗？

### ISSUE THREAD

**Issue by Daotin** [lmk123/crx-selection-translate#745]
如图：
![image](https://user-images.githubusercontent.com/23518990/92841197-997f4700-f414-11ea-9b9f-7e57d811a139.png)

**Comment by GH01** [comment]
说细了就不好玩了，移动鼠标在网页浮窗中慢慢找吧。
（对触屏用户，这算不算是彩蛋？……）

**Comment by lmk123** [comment]
这里只是单独给谷歌提供了设置项，翻译源可以在面板上点设置图标设置

![image](https://user-images.githubusercontent.com/5035625/92934058-9a968f80-f479-11ea-863a-a96c2a058789.png)
