### ISSUE TITLE
希望换回之前的UI界面

### ISSUE THREAD

**Issue by ihexIE** [lmk123/crx-selection-translate#746]
一直使用这款划词翻译插件，好像最近发现界面变了。已经习惯了之前的绿色简约普通的界面了，现在的划词后的按钮感觉变大了，窗口界面感觉变的太大了有些繁琐。希望能给个换回之前界面UI的选项。谢谢！

**Comment by GH01** [comment]
我也是更喜欢旧版的朴素风格……
其他的，改了也就改了，我个人无所谓；
就是颜色受不了：深色太滞郁，白色又太刺眼（且在白色网页中显得边界不清）……
原本的绿色则（个人感觉）清新淡雅，又不分散注意力。

我的建议是：
加个 自定义色，随用户喜欢。（现在很多软件这样做）

**Comment by lmk123** [comment]
最新发布的 v7.1.0 已经跟旧版本的界面差不多了：

1. 翻译按钮的尺寸调整为了 22 x 22（旧版本为 20 x 20）
2. 界面上的语种切换、翻译源选择跟旧版本一样收纳在了设置中

翻译按钮截图

![image](https://user-images.githubusercontent.com/5035625/92934422-0c6ed900-f47a-11ea-9f6b-86ef2ac38696.png)

翻译面板截图

![image](https://user-images.githubusercontent.com/5035625/92934461-15f84100-f47a-11ea-984f-4acd936a0a6a.png)

点开设置后的截图
![image](https://user-images.githubusercontent.com/5035625/92934492-227c9980-f47a-11ea-9364-5b8e0bd4fc6d.png)


唯一的问题就在于 2 楼提到的颜色问题，但在这方面我没有太多经验，可能会像 2 楼那样说的，提供一个设置由用于自行设定颜色

**Comment by lmk123** [comment]
另外，翻译面板的最小宽度也从 300px 改为了跟旧版一样的 250px 。。现在跟旧版除了颜色，其它都一致了
