### ISSUE TITLE
将“配合辅助键使用”设置项默认改为关闭

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#747]
v7 默认启用了“配合辅助键使用”，但部分用户的复制操作会触发 Ctrl + 划词导致弹出翻译窗口，所以我决定将这个设置项改为默认关闭。

- [ ] 默认值由 true 改为 false
- [ ] 当用户升级到 v7.1.1 时，如果用户这一项的值为 undefined，则显式设置成 true，确保之前的用户不受影响
- [ ] 在启用“配合辅助键使用”时，当弹窗打开的同时检测到复制操作时，提示用户可以关闭“配合辅助键”使用

**Comment by GH01** [comment]
所以 #631 还是有必要的。
而我个人更希望是 双击某键。

**Comment by lmk123** [comment]
针对辅助键的改进，我专门开了一个 issue #855 ，其中包含默认关闭辅助键。后续进展会更新在 #855 中，这个就先关闭了。
