### ISSUE TITLE
开启后,和layui的日期选择器冲突

### ISSUE THREAD

**Issue by 974988176** [lmk123/crx-selection-translate#748]
划词翻译7.1.0,谷歌浏览器和edge浏览器都会,禁用了扩展就好了.具体情况为:我一开始划词翻译是选择的全部开启,在本地开发项目时,或者访问 https://www.layui.com/demo/laydate.html  时,laydate都不会弹出日期选择页面,清除浏览器记录和cookie还是不行,后来,在隐私窗口中打开 https://www.layui.com/demo/laydate.html  这个网站,发现可以了,在隐私窗口中,访问自己本地的项目,也是可以的,开始排查问题,关闭所有扩展,一个个的尝试,最后,将问题锁定在了划词翻译,只要开启了,laydate日期选择器就不会弹出日期选择页面,现在的做法是手动点击开启,而不是全部默认开启.

**Comment by lmk123** [comment]
v7.1.1 中已修复这个 bug，具体情况见 #749

**Comment by 974988176** [comment]
感谢,耐心等待
