### ISSUE TITLE
【已在 v7.1.1 中修复，审核大约需要 1 天】更新7.1.0版本后哔哩哔哩、yt等视频网站搜索栏记录不能显示

### ISSUE THREAD

**Issue by smdx** [lmk123/crx-selection-translate#749]
更新7.1.0版本后哔哩哔哩、yt等视频网站搜索栏记录不能显示，禁用划词翻译扩展后正常。

浏览器：Cent Browser 版本 4.2.10.171（正式版本） （32 位） (portable) (Chromium 80.0.3987.163)
系统：Win10_64_19042.508

**Comment by echonlyou** [comment]
还有微博网页版热搜也显示不出来！！！

**Comment by lmk123** [comment]
已确认有这个 bug，我会尽快修复发布一个新版本

**Comment by lmk123** [comment]
已在 v7.1.1 中修复，版本已提交审核，大约需要 1 天

**Comment by smdx** [comment]
感谢，等待更新。
