### ISSUE TITLE
文本输入框遮挡了语种切换弹窗

### ISSUE THREAD

**Issue by leoyim** [lmk123/crx-selection-translate#750]
在chrome下进行输入文字翻译时，点击设置图标切换语言，输入框仍会显示在下拉框上方，遮挡下拉选项。
![image](https://user-images.githubusercontent.com/21982542/92988585-71204700-f4ff-11ea-9279-80b984976ac9.png)
同时，当翻译中文时，百度翻译对于一些文字翻译不正常，希望能添加对异常情况的处理。
![image](https://user-images.githubusercontent.com/21982542/92988643-f99ee780-f4ff-11ea-9dee-58c07607865f.png)

**Comment by ESWZY** [comment]
出现问题可以到`#常规设置`切换语言救急

**Comment by lmk123** [comment]
今晚发布的 v7.1.3 会修复这个问题，审核大概需要一天时间。

另外，百度翻译“中文”现在能正确的返回翻译结果，如果之后还是有问题，可以新开一个 issue 反馈
