### ISSUE TITLE
把cn谷歌和com谷歌也放到悬浮窗的快速设置里

### ISSUE THREAD

**Issue by Kumiko-git** [lmk123/crx-selection-translate#751]
前几天刚更新的时候，习惯性摁住ctrl选词，没想到蹦出来的是新UI，真是耳目一新。
体验很好了很多

**Comment by GH01** [comment]
>把cn谷歌和com谷歌也放到悬浮窗的快速设置里

我觉得这个有必要。
而且我的建议是：这两个与其他引擎并列。

好处：
▲方便切换，尤其当其中一个不稳定时#797。
▲可以同时使用。（两者译文好像会有差异，想对比查看具体细节）
▲完整设置中，两块便可合并。

**Comment by lmk123** [comment]
v7.2.0 使用了新的谷歌翻译接口，这个接口已经不区分国内和国外版本了，所以这个 issue 就先关闭了。
