### ISSUE TITLE
Gmail收件人栏无法输入

### ISSUE THREAD

**Issue by xinxijishuwyq** [lmk123/crx-selection-translate#752]
7.1.0版开启后导致Gmail收件人栏无法输入，经检验关闭插件可解决，如图
![image](https://user-images.githubusercontent.com/1755898/92989467-302c3080-f507-11ea-81c8-0e1e345c8c5d.png)

**Comment by ZechenHuang** [comment]
我也是同样的问题，希望可以修复一下。
具体描述：
chrome version 85.0.4183.102
划词翻译 version 7.1.0
问题描述：
点击左上角写邮件按钮后，右下角邮件界面会显示。在收件人栏会跳动一下光标，无法输入，然后立马变成上图所示状态。
移除插件可解决，说明应该是插件的问题。
如果需要知道同时安装的插件，请回复。
谢谢！

**Comment by lmk123** [comment]
跟 #749 是同样的问题，进展会更新到 #749，这个就先关闭了
