### ISSUE TITLE
插件速度很快，希望美化一下界面

### ISSUE THREAD

**Issue by Justin-Young** [lmk123/crx-selection-translate#753]
下面两张图是Google翻译和划词翻译的对比，总体来说插件很不错，速度也很快，但是，看起来不是很舒服，可以考虑将翻译的格式改成谷歌翻译的格式，尤其是中文的冒号、逗号、分号，不太太美观，有点喧宾夺主，看起来有点凌乱。希望将中文逗号改为英文逗号，去掉冒号、分号（分号可以用逗号代替），不同词性换行，词性用字母表示也很好看或者像谷歌那样的斜体，谷歌翻译后面的一些翻译可能不太恰当，可以考虑保留前几个，去掉后面的，另外背景色是否能自定义，添加豆沙绿（白色略刺眼）。非常感谢大佬写出这么好用的插件，也希望大佬考虑下我的建议，现阶段囊中羞涩，日后工作一定支持
![image](https://user-images.githubusercontent.com/53030626/92992068-9bcbc900-f51a-11ea-9cb6-4d6286e6baad.png)
![image](https://user-images.githubusercontent.com/53030626/92992081-b30ab680-f51a-11ea-8c7b-c83752ef90a7.png)

**Comment by lmk123** [comment]
7.1.4 中将边距调小了，也将按钮缩小了，整体看上去布局更加紧凑了；中文的分号已经改为英文的逗号；背景颜色会在未来的版本中推出自定义功能
