### ISSUE TITLE
chrome 上focus事件失效

### ISSUE THREAD

**Issue by zczhangchao51** [lmk123/crx-selection-translate#754]
安装插件后，在chrome上input的focus事件失效

复现链接： https://codepen.io/zczhangchao51/pen/abNGYGr?editors=1010

**Comment by lmk123** [comment]
我试了一下，似乎没有问题，你说的“失效”具体是指什么？

![image](https://user-images.githubusercontent.com/5035625/93009955-6cb86480-f5b9-11ea-9096-0eb6b5ebfe5e.png)

**Comment by lmk123** [comment]
另外，是不是跟 #749 有关系？

**Comment by lmk123** [comment]
虽然我在 codepen 上没有重现你的问题，但基本可以确定跟 #749 是同一个问题
