### ISSUE TITLE
希望在启用了“配合辅助键使用之后”不要默认划词后显示翻译按钮

### ISSUE THREAD

**Issue by bycen** [lmk123/crx-selection-translate#755]
也不是默认直接翻译效果
更多的时候划词不需要翻译，只是选中后注意文字

![Tu_2020-09-13_22-01-30](https://user-images.githubusercontent.com/41324481/93020044-9f8c4800-f60d-11ea-8758-e6dc57150da0.png)

**Comment by lmk123** [comment]
启用了“配合辅助键使用”是增加了两种划词方式： Ctrl + 划词 和 划词后按下 Ctrl 都会直接弹出翻译结果，并不是说普通的鼠标划词就无效了。如果你不希望普通的鼠标划词后弹出按钮或窗口，可以勾选“在所有网站中禁用网页划词”，这样就只有用辅助键的方式会弹出结果了
