### ISSUE TITLE
开启划词翻译后，某些vue页面渲染有问题

### ISSUE THREAD

**Issue by sasayaku** [lmk123/crx-selection-translate#756]
![企业微信截图_16000538052537](https://user-images.githubusercontent.com/7899927/93040763-5673dc80-f67d-11ea-98ec-3317c89a0c35.png)
![企业微信截图_1600053842701](https://user-images.githubusercontent.com/7899927/93040769-58d63680-f67d-11ea-8b04-6e2ada6bfcfa.png)

**Comment by lmk123** [comment]
见 #749，应该是同一个问题
