### ISSUE TITLE
如何不让旧版的更新呢 喜欢旧版的版本

### ISSUE THREAD

**Issue by qq514444957** [lmk123/crx-selection-translate#759]
新版翻译慢 用着不习惯  喜欢用6.几的版本   求回复  很急  研究了很久  找到了官方这 问一下

**Comment by take-it-out** [comment]
https://github.com/lmk123/crx-selection-translate/releases
在Asserts里面点开，下载crx后缀文件就行了 @qq514444957

**Comment by qq514444957** [comment]
我知道 但是他会每天自动更新 很烦  还得删除重新安装  没有设置按键 设置不让他更新

**Comment by qq514444957** [comment]
Asserts 这个是什么 没懂

**Comment by qq514444957** [comment]
![image](https://user-images.githubusercontent.com/56515945/93664569-80286b80-faa2-11ea-84ce-d8c33caa8e0e.png)
是这个吗  没有用啊  他会自动更新

**Comment by qq514444957** [comment]
6.4.11 版本 下载了 zip格式 解压后，不知道怎么用  360浏览器
![image](https://user-images.githubusercontent.com/56515945/93665841-40668180-faac-11ea-810e-fc816dd22cff.png)这个xua选项也没法安装
v6.4.12这个版本安装了就会每天自动更新 太难了 我就想用  v6版本的

**Comment by huangdongjie** [comment]
下载 6.x 版本的 crx 文件之后重命名为 zip 格式，解压之后找到 manifest.json 文件修改 update_url 字段为随意一个网址，然后浏览器开启开发者模式就可以直接选择文件夹安装了

**Comment by lmk123** [comment]
1.  下载 v6.4.12 安装包
2. 将 .crx 重命名改为 .zip 格式，然后解压
3. 打开扩展程序页（chrome://extensions/），开启右上角的【开发者模式】，点击【加载已解压的扩展程序】，选择刚才解压的文件夹

这样 v6.4.12 就不会自动更新到 v7 了。
