### ISSUE TITLE
悬浮窗口显示有问题

### ISSUE THREAD

**Issue by henices** [lmk123/crx-selection-translate#76]
6.0 beta (v6.0.0.107)

Linux chrome 49.0.2612.0 dev (64-bit)

![bug](https://cloud.githubusercontent.com/assets/929715/12226629/de217a32-b859-11e5-8ddb-bd3bbc16e5c2.png)

**Comment by henices** [comment]
主要问题有下面几个：

1. 太大了
2. 奇怪的黑色区域
3. 最上面的文字显示有问题

**Comment by lmk123** [comment]
谢谢你的反馈！这应该是样式冲突造成的，能提供一下出现此问题时的网址么？

**Comment by henices** [comment]
http://www.fuzzysecurity.com/tutorials/expDev/8.html

**Comment by henices** [comment]
github 上也有问题

![bug1](https://cloud.githubusercontent.com/assets/929715/12226718/39dd3a4a-b85b-11e5-83de-9501c493f9b8.png)

**Comment by lmk123** [comment]
问题已确认，我会在下一次发布到应用店之前修复的

**Comment by henices** [comment]
确认已修复。

**Comment by lmk123** [comment]
谢谢 :)
