### ISSUE TITLE
改进建议：希望划词翻译弹出的翻译按钮整合到MacOS中的popclip里。这样弹窗减少页面更加整洁了。如图示

### ISSUE THREAD

**Issue by BlinVin** [lmk123/crx-selection-translate#761]
<img width="638" alt="弹窗" src="https://user-images.githubusercontent.com/67635827/93527300-3ab55280-f96b-11ea-8adb-61e350fcc438.png">

**Comment by lmk123** [comment]
浏览器的扩展程序目前是整合不进这里面去的。

**Comment by tortoo** [comment]
这个需要单独做popclip的扩展，唉，目前popclip也没个合用的翻译扩展
