### ISSUE TITLE
改进建议：希望弹窗性状可以自定义，这样弹窗界面就更加整洁了，如图示

### ISSUE THREAD

**Issue by BlinVin** [lmk123/crx-selection-translate#762]
在翻译弹窗的顶部加上划词翻译和百度翻译的logo，其他的元素全部隐藏(这个建议忘记加到图里了，就以文字形式给出)
<img width="652" alt="美观" src="https://user-images.githubusercontent.com/67635827/93527804-fd04f980-f96b-11ea-8ae3-65b8279fbf09.png">

**Comment by lmk123** [comment]
我目前觉得现有的布局是很常见并通用的，再加一些设置项用于自定义界面可能只能满足少部分用户，所以暂时不打算添加自定义界面的功能。不过作为“补偿”，我在 v7.1.4 进一步缩小了尺寸，如下图：

![image](https://user-images.githubusercontent.com/5035625/95287647-04e3f980-0899-11eb-83cb-4609ecb0391b.png)

具体表现为：

1. 音标上下的边距减少了
2. 按钮尺寸减少了，所以按钮的间距和上下边距都减少了（由原来的 24x24 变成了 20x20）
3. 段落之间的边距减少了，你应该可以看出来“have的过去分词和过去式”下面的空白边距减少了
