### ISSUE TITLE
希望能加入新的翻译源

### ISSUE THREAD

**Issue by FranYanRC** [lmk123/crx-selection-translate#763]
希望能加入deepl和Yandex的翻译源
Yandex翻译俄语更精确（感觉），deepl针对长句的翻译也很不错

**Comment by xiekeyi98** [comment]
Partial duplicate of #663

**Comment by lmk123** [comment]
关于翻译源的添加我单独开了一个工单 #854 用于集中反馈，DeepL 和 Yandex 都列在了上面。
