### ISSUE TITLE
部分网页的浮窗会随页面滚动偏移

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#767]
比如此页：
https://forum.vivaldi.net/topic/51084/unable-to-use-drop-down-menus-and-miscellaneous-other-problems

重现步骤：
选中文本，打开浮窗，然后向下滚动页面。
或者：
先向下滚，再选中文本，打开浮窗。

现象：
越向下滚，浮窗错位越远。

**Comment by GH01** [comment]
inc.com 同样现象。

**Comment by GH01** [comment]
再以此页为例：
https://forum.vivaldi.net/topic/51084/unable-to-use-drop-down-menus-and-miscellaneous-other-problems

选中一整段，
打开浮窗（弹窗方向 已设为：左），
浮窗被挤出了左边缘。

**Comment by GH01** [comment]
还是喜欢原来的固定设计。固定就是固定，永久固定。#729

现在这么飘来飘去的，还会飘得遮挡了没影儿了……

旧版的固定，看起段落来很舒服，所以爱用你的扩展。
现在你是只照顾词语了……

**Comment by lmk123** [comment]
> 还是喜欢原来的固定设计。固定就是固定，永久固定。

刚才有一个用户跟我反馈“固定”的问题了，我已经将这个改动加入到下个版本中的开发计划里了，预计两三天内发布

**Comment by lmk123** [comment]
另外，跟问题相关的留言直接发到对应的问题下吧，别在不同的问题之间相互串门了

**Comment by GH01** [comment]
> 另外，跟特定问题相关的留言直接发到对应的问题下吧，别在不同的问题之间相互串门了

是我认为相关，
因为 若能固定，我就不折腾这个飘来飘去了。

**Comment by GH01** [comment]
忽然悟了（前面其实没说到点子上）：
我认为当前的自动定位逻辑其实不对，
看不全甚至看不见的定位还有什么意义。

应该是：
在保证浮窗始终可见的前提下，才考虑避让。


现状：
▲如果选块是 接近页宽/窗宽的整段，浮窗就会出界（无论左右）。
▲如果选块在一个 接近页宽/窗宽的输入框 中（哪怕仅选一个词），浮窗会避让整个编辑框。
　▲设为 上/下：会按整个框宽居中。
　▲设为 上左/上右，下左/下右：会左右反向。

**Comment by lmk123** [comment]
此问题已在 v7.2.4 中修复

**Comment by GH01** [comment]
关于上述“现状”，实测7.2.4并无明显改善。

例：
https://personal.utdallas.edu/~liebowit/book/wordprocessor/word.html
（这样的网页，文字宽度=浏览器窗宽）
选中一整段，用[划词翻译]：

表现1：
方向=左右型(6种)，浮窗就会出界。
▲建议：宁可遮挡选块也要保持可见。

表现2：
方向=上型(3种)，如果下方空间也不够，则会上翻回去，即便下方比上方大很多。
▲想法1：方向=左右型(6种)时，浮窗会随网页(作一定程度的)滚动。方向=上下型(6种)时能否也这样呢（随滚动而上下翻）？
▲想法2：如果下方更大，则强制下翻？（不好判断？）
▲想法3：像 下型(3种) 那样使页面产生纵滚条，使能上滚？（那左右出界是否也应产生横滚条呢？）

表现3：
方向=上左/下左/上右/下右，则会左右反向。

表现4：
例：GitHub中的输入框
浮窗会避让整个输入框（见前“现状”所述）。
▲建议：宁可遮挡输入框/选块也要保持可见。

总的建议：
▲优先确保浮窗可见。在难以定位时就去默认位置，用默认位置workaround一切位置问题，之后再慢慢优化定位判断。首先保证可用性。
　▲如果这样，也许应该允许用户设个默认位置。

**Comment by lmk123** [comment]
v7.2.4 版本里修复的是你在这个工单中反馈的 inc.com 里浮窗会随着网页滚动偏移的问题，并没有对你后面描述的“自动定位问题”进行优化。

**Comment by lmk123** [comment]
另外针对你提出的 4 个表现，我新开了一个 issue 并提出了我的解决方案：#836 我们可以在这个新的 issue 里继续讨论
