### ISSUE TITLE
翻译出来英文的读音跟直接在https://translate.google.cn/翻译的读音完全不一样

### ISSUE THREAD

**Issue by ren-jimmy** [lmk123/crx-selection-translate#768]
呃。。。，例如翻译scheduler，插件翻译出读音吓住了，网站翻译出死get住了

**Comment by lmk123** [comment]
这个读音确实有问题，但是我在  https://translate.google.cn/#view=home&op=translate&sl=en&tl=zh-CN&text=scheduler  里听到的也是一样的读音，所以这应该不是插件的读音问题
