### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by MrSong0607** [lmk123/crx-selection-translate#77]
翻译英文的时候，可以顺便 把音标也打印出来，毕竟有些词不知道怎么发音

**Comment by lmk123** [comment]
我猜你指的是谷歌翻译没有音标吧？原因我在[常见问题](https://github.com/lmk123/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E4%B8%8D%E6%98%BE%E7%A4%BA%E9%9F%B3%E6%A0%87)里已经说明了。

**Comment by MrSong0607** [comment]
@lmk123 是的，原来是官方的问题，那没办法了
