### ISSUE TITLE
建议：引擎各自显示的 源语种 能单独(临时)切换

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#773]
引擎各自显示 源语种。
如果某引擎判断错误，却不能单独改。

希望能 单独(临时)切换 该引擎的源语种。

**Comment by lmk123** [comment]
其实我正在考虑将源语种改为全局设置

![image](https://user-images.githubusercontent.com/5035625/95680415-1700c780-0c0c-11eb-957a-d26d1282f298.png)

也就是这里切换之后在其它窗口里也会切换

这样是不是就可以不需要给每个引擎加临时的语种切换了？

**Comment by GH01** [comment]
其实只有在设为自动检测时才可能判错，才需要个别显示和切换。

而设为自动检测，就是为了多语种。
让用户永久切换成单语种？不合适。

假设一个引擎判错，其他的对。
为少数而改全局且永久？不合适。

假设用户只用一个引擎，改全局（若隐藏）比改下面麻烦。

通常是查词时（因为短）才会判错，
而对陌生语言往往是整段翻译，不容易判错，
如果两种情形都要用，那用户应该怎么设全局呢？

所以，应该能 个别改，临时/一次性的。

**Comment by GH01** [comment]
UI层次问题：
![image](https://user-images.githubusercontent.com/19272301/106746660-ccdd9f00-665d-11eb-8f13-83ef6549d200.png)

最好也能实现 最近使用者上浮。

测试中发现 谷歌翻译 居然把 you 识别为 中文(简体)……

**Comment by lmk123** [comment]
已新开 issue https://github.com/lmk123/crx-selection-translate/issues/896
