### ISSUE TITLE
更新V7之后怎么悬浮窗快速设置，跟随网页滚动按钮都没了？

### ISSUE THREAD

**Issue by Kumiko-git** [lmk123/crx-selection-translate#775]
我觉得很方便的功能的说

**Comment by lmk123** [comment]
你是不是没有升级到最新版？

现在的最新版 7.1.4 是有悬浮窗快速设置的， 如图：

![image](https://user-images.githubusercontent.com/5035625/95409019-5e106380-0953-11eb-99e3-d9134367daa7.png)

你说的“跟随网页滚动按钮”是指在 v6 中，网页滚动的时候，翻译按钮&弹窗都会保持在原本的位置不会跟随网页滚动吗？

在 v7 中确实做了这个改动，让翻译按钮&弹窗都会随着网页滚动而移动位置，让它们始终在被选中文本的附近。但是点击翻译弹窗左上角的图钉还是可以让它固定位置的。

**Comment by lmk123** [comment]
下个版本中，划词翻译会将固定做成全局的，即你在页面 A 移动了窗口的位置 、 将窗口切换为固定状态，在其它所有页面也会同步更新，这样应该跟之前的体验会贴近一些，见 #729

**Comment by Kumiko-git** [comment]
今天才发现是广告屏蔽插件屏蔽了设置那一块，搞错了。。

**Comment by lilpea1213** [comment]
stop
