### ISSUE TITLE
浮窗内划选翻译

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#781]
旧版：可以在浮窗内划选，然后用快捷键翻译。
新版：能划不能译。

这种用法，我在 https://github.com/lmk123/crx-selection-translate/issues/468#issuecomment-611749731 具体提到。

后来，我是希望3种窗口能相互配合来应对这种用法：#675
比如：在网页浮窗中划选，在其他窗口中翻译。

现在的独立窗口只能打开剪贴板内容？

**Comment by lmk123** [comment]
相互配合现在是可以做到的，你可以在网页中划词并复制进剪切板，然后使用全局快捷键在独立窗口中翻译。

当然，技术上也是可以做到在网页中划词，不需要复制进剪切板，然后使用快捷键打开独立窗口翻译的，也许你更希望这样操作？

**Comment by lmk123** [comment]
我也可以给独立窗口加个设置项，“响应网页划词”，勾选后在网页里划的词改为在独立窗口里翻译

**Comment by GH01** [comment]
> 当然，技术上也是可以做到在网页中划词，不需要复制进剪切板，然后使用普通快捷键（也就是作用域不是全局、是在浏览器内）打开独立窗口翻译的，也许你更希望这样操作？

对！

> 我也可以给独立窗口加个设置项，“响应网页划词”，勾选后在网页里划的词改为在独立窗口里翻译

好！

最好是 打通+并存，而不是 非此即彼。

**Comment by lmk123** [comment]
> 当然，技术上也是可以做到在网页中划词，不需要复制进剪切板，然后使用普通快捷键（也就是作用域不是全局、是在浏览器内）打开独立窗口翻译的，也许你更希望这样操作？

这个已经单独开了一个工单 #835 

响应网页划词也单独开了一个工单 #819 

那么这个工单本身我就先关闭了
