### ISSUE TITLE
chromium.org, googlesource.com 的某些页面中无法使用

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#785]
~照理独立窗口应该是百无禁忌的吧？~

**Comment by lmk123** [comment]
https://opensource.google/ 我试了是可以正常网页划词、右键菜单点“翻译选中文本”也是会弹出翻译窗口的（不过不是独立窗口

chromium.org 我打不开

你说的“无法用独立窗口翻译”具体表现是什么？

**Comment by GH01** [comment]
进一步测试结果：

https://www.chromium.org/
https://chromium.googlesource.com/chromium/
▲以上可以

▼以下不行
https://bugs.chromium.org/p/chromium/issues/detail?id=1140996
https://chromium-review.googlesource.com/q/status:open+-is:wip
https://chromium-review.googlesource.com/c/v8/v8/+/2486240

**Comment by lmk123** [comment]
已在 v7.2.4 修复

**Comment by lmk123** [comment]
这也顺便解决了在划词翻译弹窗内划词后按下快捷键没有触发翻译的问题，你好像在哪里提到过，但我找不到了

**Comment by lmk123** [comment]
为了解决 #834 的问题，我对划词翻译进行了一次重构，但这个问题在代码逻辑进行重构之后没有太好的解决，所以我重新打开了

**Comment by lmk123** [comment]
技术相关备注：

这个问题只在 Chrome 里有，在 Firefox 没有；出现问题的原因是这些页面都是由 Shadow DOM 组成的，而在 Chrome 里拿到 Shadow DOM 内划选的文本需要一些特殊处理
