### ISSUE TITLE
PDF划词问题

### ISSUE THREAD

**Issue by xiaoyaotianxiazwy** [lmk123/crx-selection-translate#786]
在PDF文件中划词时，会把换行符给划掉，
比如
 in a
 house
 划词结果为
in ahouse
当前使用版本7.1.7
Chrome浏览器版本86.0.4240.111

**Comment by GH01** [comment]
给出相关链接才好判断吧。

**Comment by xiaoyaotianxiazwy** [comment]
这个怎么给网址，本地打开的PDF文件啊，不过有截图
![微信图片编辑_20201028090900](https://user-images.githubusercontent.com/50730942/97378451-4fd3b880-18fd-11eb-8463-f345f82be806.jpg)

**Comment by GH01** [comment]
> 这个怎么给网址，本地打开的PDF文件啊

你可以上传附件，或用网盘分享。
不过不用费事了，一搜就搜到了，是这个吧：
https://cyberleninka.org/article/n/21529
网页版：
https://www.sciencedirect.com/science/article/pii/S1750583615000304
▲两个都有PDF下载链接。
___
[划词翻译]扩展的内置PDF阅读器 看来毛病多多，
在Chromium自身打开的PDF中就正常，
请看对比图：
![划词翻译_内置PDF阅读器_换行_连字符](https://user-images.githubusercontent.com/19272301/97457483-c19b1900-1974-11eb-8511-d204577b1d83.png)

▲红三角是换行处。（Chromium中只是多一个空格）
有些段落则正常，比如这篇的开头几段：http://www.pdf995.com/samples/pdf.pdf
我想区别在于 行尾是否有真实换行符。▲这篇后面的段落就会出问题。

▲黄字：连字符-后面的一整行会被吃掉空格。（Chromium中则会自动拼接单词）

▲另外，每次首个有格式(如:斜体/粗体)的单词前的空格会被吃掉。（Chromium中则正常）
例见：http://www.pdf995.com/samples/pdf.pdf

**Comment by xiaoyaotianxiazwy** [comment]
是的，谢谢

**Comment by xiaoyaotianxiazwy** [comment]
翻译PDF文件不是要在内置的PDF阅读器 内才能使用吗？或者不能用谷歌浏览器，需要使用Chromium？或者其他以Chromium为内核的浏览器？

**Comment by GH01** [comment]
> 翻译PDF文件不是要在内置的PDF阅读器 内才能使用吗？或者不能用谷歌浏览器，需要使用Chromium？或者其他以Chromium为内核的浏览器？

我越俎代庖答你：
Chromium核（包括但不限于Google Chrome）都可以，只不过要通过右键菜单。

**Comment by lmk123** [comment]
暂时无解，等 [PDF.js](https://github.com/mozilla/pdf.js)（也就是划词翻译的内置 PDF 阅读器）修复这个问题之后我会立刻更新上去，如果无法忍受这个问题，可以用 Chrome 自带的 PDF 阅读器打开 PDF，然后选中文本之后右键单击它，然后选择“翻译这段文本”。

下面是针对这个问题的一点技术性解释。

--------

在 PDF.js 渲染的 PDF 里划选的文本在换行处确实是没有空白的。下面这段选中的文本：

![image](https://user-images.githubusercontent.com/5035625/101027369-e48f9d00-35b2-11eb-889a-bba21336648c.png)

在 PDF.js 的代码里是这么写的：

![image](https://user-images.githubusercontent.com/5035625/101027508-0b4dd380-35b3-11eb-97ef-6d3e6bdb9495.png)

可以看到 `has received</span><span>increased ` 之间是没有空格的，两个 span 元素是紧挨在一起的，所以从代码里读取出来（或者你使用 Ctrl + C 复制出来）它就是 `receivedincreased`。

其实已经有人给 PDF.js 提了这个问题，只是一直没有修复：https://github.com/mozilla/pdf.js/issues/6657

如果用 Chrome 自带的 PDF 阅读器打开 PDF，划选换行处然后使用右键菜单的“翻译这段文本”，此时选中的文本是由 Chrome 提供给我的，它应该是做了处理，会在 `received` 和 `increased` 之间加上空格，所以翻译起来就是正常的。
