### ISSUE TITLE
添加翻译后自动朗读功能

### ISSUE THREAD

**Issue by dadiorchen** [lmk123/crx-selection-translate#789]
以前一直开启直接朗读, 我觉得这个功能很实用, 英文读音比字形更重要, 记住了读音肯定能够差不多的拼出来文字, 可是脑子里有文字不一定能够熟悉的听出来, 这个功能包括有道字典和其他的工具都没有, 就这个工具有.
不过新版本升级以后这个功能没了, 希望能够恢复!

**Comment by lmk123** [comment]
好的，我会尽快恢复
