### ISSUE TITLE
本地 pdf 无法在划词翻译中打开

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#794]
划词翻译版本：v7.1.7
User agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

重现步骤：

1. 在选项中关闭“使用划词翻译的内置 PDF 阅读器打开 PDF 文件”
2. 将本地 PDF 文件拖放到浏览器中，此时浏览器会使用自带的 PDF 阅读器打开此 PDF
3. 在右键菜单中选择“在划词翻译中打开此 PDF”

预期行为：会使用划词翻译内置 PDF 阅读器打开 PDF
实际行为：划词翻译内置 PDF 阅读器跳转到了 chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=about%3Ablank%23blocked 注意 file 后面的地址是 `about:blank#blocked`，按照预期它会是一个 file:/// 开头的指向本地 pdf 文件的地址

**Comment by lmk123** [comment]
备注：开启“使用划词翻译的内置 PDF 阅读器打开 PDF 文件”后将本地 PDF 拖放进去是没有问题的

**Comment by lmk123** [comment]
结论：在 Chrome 自带的 PDF 阅读器里打开本地 PDF 后，鼠标右键点击时，Chrome 提供的地址（即 [info](https://developer.chrome.com/extensions/contextMenus#event-onClicked).srcUrl）会是 `undefined` 或 `about:blank#blocked`

- 这种情况需要提示一下用户
- 加入一个输入地址（在线或本地文件地址）后打开 PDF 文件的功能，这样也能解决自动打开 PDF 不能识别不是以 .pdf 结尾的链接的问题

**Comment by GH01** [comment]
我这里（Chrome/86.0.4240.112 (Vivaldi)）的表现：
开始如你所说，且你的内置PDF阅读器页内会有红条错误信息，
但若再试，URL对了，红条也没了，你的内置PDF阅读器页内却是空的（只有顶部工具栏）。
___
还可以提示用户：你的内置PDF阅读器支持拖放（即使处于上述出错状态，即使没有启用“使用划词翻译的内置PDF阅读器打开PDF文件”选项）。

**Comment by lmk123** [comment]
> 还可以提示用户：你的内置PDF阅读器支持拖放（即使处于上述出错状态，即使没有启用“使用划词翻译的内置PDF阅读器打开PDF文件”选项）。

这个好，出现问题了我就显示这个提示
