### ISSUE TITLE
谷歌翻译（国内）接口数据返回失败

### ISSUE THREAD

**Issue by KiWinger** [lmk123/crx-selection-translate#796]
**现象**
（6412/648）接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。
（717）谷歌翻译不支持该语种。

**已执行操作**
已阅读常见问题，均使用默认设置，尝试三个版本，尝试手机电信蜂窝网络热点，尝试卸载重装。

**问题**
直接打开翻译窗口以及浏览器划词翻译提示都如上一致，无法翻译。

**补充**
- 有道和百度正常。
- 未开启代理软件。
- 浏览器网址打开国内版谷歌翻译正常。
- 已经持续几天了。

**版本**
- Chromium70.0.3538.2(QQBrowser)
- 划词翻译 7.1.7/6.4.12/6.4.8

**Comment by GH01** [comment]
有没试过我在 #797 说的办法？（当然.com要靠翻）
也许你我遇到的是同一个问题。

**Comment by KiWinger** [comment]
![image](https://user-images.githubusercontent.com/49084827/97701364-422e5680-1ae8-11eb-9cf9-6d5ffdcf55d7.png)
失败

**Comment by KiWinger** [comment]
> 有没试过我在#797说的办法？(当然.com要靠翻)
> 也许你我遇到的是同一个问题.

如上，失败哒。
你的详细步骤是：**开代理-切换到com-翻译输出成功-关代理-切换到cn-再次翻译**吗？

**Comment by GH01** [comment]
看上去情况似乎不同。
不过你还是完全按我的步骤试一下吧（使用相同工具便于对比）：

平时我只是靠这个扩展对付事儿：
https://chrome.google.com/webstore/detail/chrome-sync-helper/gbkepcmpjglfonklehdgjnimebhnmlel
启用此扩展（注意关掉其他穿墙扩展/软件，以免互相干扰）
[划词翻译]先用.cn试，失败
[划词翻译]切至.com再试（重试有注意事项，详下）（照理此时应能连通，虽然速度慢）
[划词翻译]切回.cn再试（重试有注意事项，详下）

注意事项：
[划词翻译]新版做了优化：如果划选的文本内容不变，那么再次打开翻译浮窗时内容不会刷新，而是瞬间显示上次的缓存，即：失败仍在，不会重连。
所以，应该划选不同的文本 再重试，
或者，在浮窗中停用+再启用该引擎的选项，这样也能保证重连。

**Comment by KiWinger** [comment]
> 看上去情况似乎不同。
> 不过你还是完全按我的步骤试一下吧（使用相同工具便于对比）：
> 
> 平时我只是靠这个扩展对付事儿：
> https://chrome.google.com/webstore/detail/chrome-sync-helper/gbkepcmpjglfonklehdgjnimebhnmlel
> 启用此扩展（注意关掉其他穿墙扩展/软件，以免互相干扰）
> [划词翻译]先用.cn试，失败
> [划词翻译]切至.com再试（重试有注意事项，详下）（照理此时应能连通，虽然速度慢）
> [划词翻译]切回.cn再试（重试有注意事项，详下）
> 
> 注意事项：
> [划词翻译]新版做了优化：如果划选的文本内容不变，那么再次打开翻译浮窗时内容不会刷新，而是瞬间显示上次的缓存，即：失败仍在，不会重连。
> 所以，应该划选不同的文本 再重试，
> 或者，在浮窗中停用+再启用该引擎的选项，这样也能保证重连。

![image](https://user-images.githubusercontent.com/49084827/98060419-7b6a1c00-1e84-11eb-91ff-910f5eaa3c3d.png)

虽然与之前直接使用代理不同，但com依旧是无法正常翻译，同时cn依旧失效，大概只能等作者回复趴...

**Comment by GH01** [comment]
我这里，此切换法100%有效。
只不过.com今天显得更难连通，更慢，或超时。
但一旦.com连通一次，.cn就能用了。
所以我认为关键是得保证.com至少连通一次。

**Comment by lmk123** [comment]
后续进展同步在 #797 中
