### ISSUE TITLE
【正在解决中】谷歌翻译失效

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#797]
7.1.7
Chrome/86.0.4240.112 (Vivaldi)

似乎是本周才开始的，
.cn那个（首次? +有时）会报：谷歌翻译不支持源语种或目标语种。
发生时持续（多次尝试，结果一样）。
然后我切换为.com只用一下，再切回.cn，就好了。

有没人遇到？

**Comment by GH01** [comment]
补充：
.com当然是靠翻的。
现在.cn这种表现似乎说明它在握手时也得翻一下。

**Comment by DesistDaydream** [comment]
我有同样的问题，大概是最近几天开始的，使用 **国内google** 翻译会提示`谷歌翻译不支持源语种或目标语种。`
如图所示
![image](https://user-images.githubusercontent.com/39847025/97981140-cea08800-1e0c-11eb-902c-0b094f87455b.png)
使用 **国际版 google **翻译正常，所有网站都一样。


**划词翻译**版本：7.1.7
![image](https://user-images.githubusercontent.com/39847025/97981297-04de0780-1e0d-11eb-8891-e2ce845fa2ec.png)

**chrome**版本：86+

**Comment by littlerest** [comment]
版本：7.1.7
网络环境：无墙
Chrome: 86.0.4240.111（正式版本）

谷歌翻译：谷歌翻译不支持源语种或目标语种
同样问题遇到一阵子了。
国内版国外版切换无效。
尝试过重新安装，第一次有效，
第二次问题依旧。
同时其他翻译引擎工作正常。

**Comment by littlerest** [comment]
> 版本：7.1.7
> 网络环境：无墙
> Chrome: 86.0.4240.111（正式版本）
> 
> 谷歌翻译：谷歌翻译不支持源语种或目标语种
> 同样问题遇到一阵子了。
> 国内版国外版切换无效。
> 尝试过重新安装，第一次有效，
> 第二次问题依旧。
> 同时其他翻译引擎工作正常。

回退到6.4.12版本，尝试使用报错：
接口返回了错误的数据，请稍候重试。（切换cn某引擎会出现小提示，而百度有道正常运行）

**Comment by f0ghua** [comment]
7.17 无论国内还是国外google，都显示“谷歌翻译不支持源语种或目标语种”；翻不翻结果都一样

**Comment by f0ghua** [comment]
我抓了一下封包，看起来并不是连不上的问题，应该还是解析上有了变化。等待作者更新。

**Comment by GH01** [comment]
我这里的做法和表现详见#796
如果两个都连不上，那肯定没戏。

**Comment by lmk123** [comment]
> 我抓了一下封包，看起来并不是连不上的问题，应该还是解析上有了变化。等待作者更新。

是的，谷歌翻译的解析方式发生了变化，我会尽快解决这个问题

**Comment by gpqhl0071** [comment]
我也同样遇到了这个问题，期待尽快解决。

**Comment by lxfly2000** [comment]
同样是这个问题，谷歌前几天的翻译界面改了一下（历史记录功能被删除了），然后因为用了一些google.com的api打开速度也慢了一些，但是还是能正常翻译

**Comment by CHN-STUDENT** [comment]
也不知道什么时候能够审核通过呢...希望尽快呢

**Comment by higker** [comment]
不支持 语音和原词 用个毛啊 卸载换其他插件了差劲

**Comment by DesistDaydream** [comment]
维护者辛苦了，谢谢你们，期待后续有更好的解决办法。不用在意喷子~~~
现在能翻译了，只是响应时间有点长~

**Comment by lmk123** [comment]
> 不支持 语音和原词 用个毛啊 卸载换其他插件了差劲

@higker 你作为一个全职开源程序员，难道不应该比其他人更能理解独自维护一个开源项目、回过头来还被喷是什么感受吗？

本是同根生，相煎何太急。

**Comment by GH01** [comment]
之前，.cn那个是100%不用穿墙的，速度快，且不受穿墙程序影响，
现在的麻烦是：新接口会受穿墙程序影响。

比如（我在 #796 中提到）我平时总是挂着这个Chrome Sync Helper扩展：
https://chrome.google.com/webstore/detail/chrome-sync-helper/gbkepcmpjglfonklehdgjnimebhnmlel
然而现在，开着它就会导致[谷歌翻译]变慢，慢到受不了，甚至失败……
（感觉Google这次的变动对Chrome Sync Helper也有影响，致其变得几乎无用）

@lmk123
你这边能否实现 保证直连，不受穿墙程序影响？

@DesistDaydream
你那里慢，是否也是这方面原因？

**Comment by lmk123** [comment]
我把新的谷歌翻译接口的语音朗读功能加回来了，今天会发布 v7.2.1

**Comment by lmk123** [comment]
> 你这边能否实现 保证直连，不受穿墙程序影响？

@GH01 不能

**Comment by higker** [comment]
> @higker 你作为一个全职开源程序员，难道不应该比其他人更能理解独自维护一个开源项目、回过头来还被喷是什么感受吗？
> 
> 本是同根生，相煎何太急。

> 做到向前兼容就好，如果前面功能都不能兼容........

**Comment by CHN-STUDENT** [comment]
@GH01 我在高科技程序排除列表里加了 translate.google.cn 排除，感觉还是有用的，要不试试？

**Comment by DesistDaydream** [comment]
> 之前，.cn那个是100%不用穿墙的，速度快，且不受穿墙程序影响，
> 现在的麻烦是：新接口会受穿墙程序影响。
> 
> 比如（我在 #796 中提到）我平时总是挂着这个Chrome Sync Helper扩展：
> https://chrome.google.com/webstore/detail/chrome-sync-helper/gbkepcmpjglfonklehdgjnimebhnmlel
> 然而现在，开着它就会导致[谷歌翻译]变慢，慢到受不了，甚至失败……
> （感觉Google这次的变动对Chrome Sync Helper也有影响，致其变得几乎无用）
> 
> @lmk123
> 你这边能否实现 保证直连，不受穿墙程序影响？
> 
> @DesistDaydream
> 你那里慢，是否也是这方面原因？
是的，我也是开启代理后，会变慢

**Comment by lmk123** [comment]
新版本谷歌翻译使用的接口地址是 https://translate.googleapis.com 你们可以把这个地址加在直连规则里试试

**Comment by lmk123** [comment]
另外，我把 v7.2.1 的离线安装包上传到网盘了，想立刻使用的话可以按照官网步骤安装 https://hcfy.limingkai.cn/install.html

**Comment by GH01** [comment]
@CHN-STUDENT 
SwitchyOmega能设置，问题不大，实测也没有快慢变化（事实上我用的列表已经排除了 translate.google.cn 及 translate.googleapis.com）。

平时不想火力全开，所以用Chrome Sync Helper这种小口径、没设置的简单工具。
Chrome Sync Helper这些天貌似不行了，刚才换了个iGuGe先用着。

**Comment by GH01** [comment]
解决“[Google翻译]变慢/失败”（及此类问题）的其他办法：
https://www.appinn.com/how-to-fix-g-cn-translate-slow/
原帖：
https://meta.appinn.net/t/topic/20364
（留言中可能会有更多信息）
