### ISSUE TITLE
有没有方法从插件pdf阅读退出，我需要那个链接，点到pdf上层课程网址

### ISSUE THREAD

**Issue by fengmao31** [lmk123/crx-selection-translate#800]
有没有方法从插件pdf阅读退出，我需要那个链接，点到pdf上层课程网址。
每次切换好麻烦。

**Comment by fengmao31** [comment]
可读取和更改的网址数据，不在所有网址启动插件后，重新打开链接才能拿到网址。之后再次启用会翻译无法连接报错。重启浏览器才能翻译。
这样切换太麻烦了。

**Comment by lmk123** [comment]
我会在内置的 PDF 阅读器里加上“复制 PDF 网址”的按钮
