### ISSUE TITLE
google翻译错误，请经快修复谢谢

### ISSUE THREAD

**Issue by Kumiri** [lmk123/crx-selection-translate#804]
划词翻译内部出现了一个错误，这可能是划词翻译自动更新了导致的，刷新网页即可恢复。
版本号：7.1.7
浏览器：火狐 82.0.2
![图片](https://user-images.githubusercontent.com/32268477/98453326-dce6ff00-2192-11eb-9c3a-8b07e0521eaa.png)

**Comment by lmk123** [comment]
#797
