### ISSUE TITLE
edge版本中谷歌翻译源不能使用了

### ISSUE THREAD

**Issue by Julianduu** [lmk123/crx-selection-translate#808]
edge版本中谷歌翻译源不能使用了

**Comment by lmk123** [comment]
那是因为 edge 迟迟不审核通过，edge 上现在是 v7.1.7，但 Chrome 上已经发布了 v7.2.0 解决了这个问题，只能等 edge 审核通过了，我发个邮件去催一下看看。

**Comment by lmk123** [comment]
我刚才把审核当中的离线安装包传到网盘了，你可以先安装上去 https://hcfy.limingkai.cn/install.html
