### ISSUE TITLE
UI重叠处的“竞争性闪烁”

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#809]
![划词翻译_语种_下拉_竞争性闪烁](https://user-images.githubusercontent.com/19272301/99140512-8f303200-267d-11eb-8e8b-afb7ceed2057.png)

比如展开语种列表，鼠标指向图中红框内，
本该属于下层的按钮会浮现，导致竞争。

**Comment by GH01** [comment]
这种问题目前又有新表现：

展开的语种列表被以下元素遮挡：
文本框
各块[源语种]的▼符
各块翻译文字

**Comment by lmk123** [comment]
已提交到 https://github.com/lmk123/crx-selection-translate/issues/1096
