### ISSUE TITLE
悬浮框显示不全

### ISSUE THREAD

**Issue by henices** [lmk123/crx-selection-translate#81]
在页面接近网页底部的时候点翻译，悬浮框显示不全。
![bug2](https://cloud.githubusercontent.com/assets/929715/12319081/900489b0-bada-11e5-8579-5290df91f838.png)

**Comment by henices** [comment]
版本 v6.0.0.114

**Comment by henices** [comment]
确认已修复 commit 653e69f7502d9fc067e3451fef3f745ffe99c6c1

**Comment by lmk123** [comment]
谢谢 :)
