### ISSUE TITLE
谷歌翻译和百度翻译挂了，只能显示有道

### ISSUE THREAD

**Issue by Brando9767** [lmk123/crx-selection-translate#814]
![image](https://user-images.githubusercontent.com/26496074/99227620-73b45b00-2826-11eb-86d6-16f088220870.png)

**Comment by lmk123** [comment]
我这边一切正常，先提供下你的浏览器版本、划词翻译版本吧

![image](https://user-images.githubusercontent.com/5035625/99232433-dc063b00-282c-11eb-8aa2-5f145c2f918b.png)

**Comment by Brando9767** [comment]
划词翻译版本7.1.7
浏览器microsoft edge 86.0.622.69 (最新版)

**Comment by lmk123** [comment]
目前划词翻译的最新版 v7.2.3 已经解决了谷歌翻译不能用的问题，但是 edge 商店一直不给我审核通过，所以仍然停留在 v7.1.7，你可以暂时安装离线安装包安装 v7.2.3 使用，方法见 https://hcfy.limingkai.cn/install.html

**Comment by lmk123** [comment]
另外，我在 edge 上用划词翻译 v7.1.7 测试了一下，百度和有道是正常的，可能是因为你开了梯子导致的不能连接

**Comment by lmk123** [comment]
无回应，先关了
