### ISSUE TITLE
加一个设置项，在拖动浮窗后不要自动切换为固定状态

### ISSUE THREAD

**Issue by yygcom** [lmk123/crx-selection-translate#815]
拖动后窗口被置顶是否可以加个开关，不希望拖动后置顶
另外goolge不能用国际的啊

**Comment by lmk123** [comment]
拖动后被置顶是个 bug，你用的是不是 macOS 且不是最新版 v7.2.3？

如果是，那可能跟这个问题重复 #709 （在mac上拖动翻译窗口时总是跑到左上角），你升级到最新版就可以了；

如果不是，我需要你提供你浏览器的版本、划词翻译的版本、使用的操作系统进行排查。

另外，最新版的谷歌翻译已经不区分国内、国际了，在国内或国外都是可以用的，你应该是没有更新到最新版

**Comment by yygcom** [comment]
版本是7.2.3 ，win和mac都是一样，浏览器是chrome ，
现象为拖动后就置顶了，如果点一下那个按钮窗体会跳动位置，还有一个问题是阴影很大一块不好看

**Comment by GH01** [comment]
楼主说的“置顶”其实是指“固定”吧？
这是目前的设计。

虽然我也倾向于 将拖移与固定分开操作，
但目前这样设计，我也能适应。
（毕竟两种方案都会增加点击次数。）

楼主不妨说说为何要拖移。
如果是因为 #767 这类问题，作者正在改进。
如果是因为 遮挡妨碍继续选词/阅读，这其实在所难免，要么拖移以固定到合适位置，要么随时关窗（鼠标随处点，Esc键也可以）。

**Comment by lmk123** [comment]
> 版本是7.2.3 ，win和mac都是一样，浏览器是chrome ，
> 现象为拖动后就置顶了，如果点一下那个按钮窗体会跳动位置，还有一个问题是阴影很大一块不好看

新版本中为了让翻译框指向单词所在的位置且跟随页面滚动，所以区分了两个状态：默认状态，划选之后翻译窗口会跟随被选中的文本；固定状态，窗口会固定在一处。

这跟旧版本是不同的，旧版本的“固定状态”其实仅仅只是点击页面之后不关闭窗口。

从旧版本升级到新版本可能会有一点不适应，但是我已经把固定状态改为跨页面生效的了，即在其中一个页面拖动窗口后，其它所有页面的翻译窗口也会变为固定状态并且在相同位置，我想这样应该能稍微减少一点你的不习惯。

**Comment by yygcom** [comment]
拖移的目的是为了视线的方便，但是希望拖移后不改变被固定操作，而是如果鼠标点击空白地方窗体就隐藏掉

**Comment by lmk123** [comment]
好的，我会加一个设置项，在拖动窗口后不自动调整成固定状态
