### ISSUE TITLE
窗口高度 需优化

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#816]
窗口固定后，就不随网页滚动了，
则下面超出浏览器窗高的部分就永远没法看到了……

建议：
▲最大高度限于可见区域内，必要时显示纵滚条。
▲自动定位时也这样，就只需在自身窗口中滚动，而不必滚动网页了。

**Comment by GH01** [comment]
另一种情况：

## 基本信息
7.3.1
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

## 重现问题的步骤
比如在此页底输入close并选中，翻译，
启用诸选项使浮窗尽量长，
下滚。

### 预期行为
应能看到浮窗底部。

### 实际行为
看不到底部，浮窗就消失了。

**Comment by lmk123** [comment]
> 启用诸选项使浮窗尽量长

这段没看懂。。

**Comment by lmk123** [comment]
如果浮窗是自动消失的，那么可能是因为 v7.3.1 里我新加入的一个改进：当被划选的文本滚动出了网页的可视区域的时候，我会自动隐藏翻译弹窗

**Comment by GH01** [comment]
> > 启用诸选项使浮窗尽量长
> 
> 这段没看懂。。

抱歉，
就是 启用各个与窗高相关的选项：所有翻译源，文本框，快捷设置区。

**Comment by GH01** [comment]
还是先别用自动隐藏吧，除非改进了窗高设计。

**Comment by GH01** [comment]
7.4.4
看不到底部时，那些 跳转链接 也就没法用了……

**Comment by GH01** [comment]
7.4.6
浮窗很长导致下部不可见时，展开靠下的某翻译源的语种列表，列表朝下展开，因显示不完整而无法完成操作。

新想法：
点击各块翻译源的标题，折叠/展开 该源。
（用快捷选项来开关的话，会导致顺序改变。）

**Comment by lmk123** [comment]
已对固定模式下的窗口高度做了优化。固定模式下的窗口会在高度变化时自动调整位置，确保自己始终处于可视区域内，并在高度超过浏览器可视区域高度时显示滚动条，如下图：

![t](https://user-images.githubusercontent.com/5035625/109393304-ca6c1d80-795b-11eb-8a20-43addee95fc4.gif)

**Comment by lmk123** [comment]
浮窗模式下的高度也已优化，会在超出可视范围时自动添加滚动条：

![t](https://user-images.githubusercontent.com/5035625/109395179-02785e00-7966-11eb-8254-c3b7580c0a88.gif)

**Comment by GH01** [comment]
设置：禁用，+用按键触发
浮窗方向：左下

以此页为例，刷新，
在页面中部(或以下)划选一大段，然后多次触发划词翻译（为了反复开/关浮窗），
浮窗初次在侧下，然后产生纵滚条，
之后的反复打开，浮窗每次向上抬升一点，直至到顶。
（或者，在初次触发后，滚动页面，浮窗也会逐渐抬升。）

我觉得更“自然”的方式是：
先抬升，抬升至顶还不够，则加纵滚条。

继续说：
然后在浏览器窗口底部划选一个词，触发，
此时浮窗初始定位已在顶，
如果翻译内容不够长，浮窗不会自动沉降，浮窗和小箭头就“身首分离”了。

**Comment by lmk123** [comment]
按照你的方法尝试了一下，没有出现“浮窗每次向上抬升一点”和“浮窗和小箭头“身首分离””这两种情况。

**Comment by lmk123** [comment]
另外，这种情况会影响到平时的使用吗？感觉像是很少会出现的情况

**Comment by GH01** [comment]
抱歉，忘了回复……

很常见。
在刷新的页面 每首次使用，必现。
以本页为例，刷新，
在窗底划选较多文字，如图：
第1/2/3次触发时的窗位，最终至顶（n）。
然后，在窗底划选较少文字，就会箭头分离（图右2例）。
![划词翻译_窗高_箭头分离](https://user-images.githubusercontent.com/19272301/112408774-5dc62200-8d53-11eb-8038-477e261eb740.png)

影响就是：每首次打开 只能看到很少的内容。
本应是：让用户一眼看到尽可能多的内容。

**Comment by GH01** [comment]
再抱歉，
我的弹窗方向是：左上
