### ISSUE TITLE
建议：抓手区域扩大到整个标题栏

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#818]
如果 #767 这类问题不会很快解决，能否先做这个改动：
把 抓手区域 扩大到 整个标题栏，即 两端按钮周围的间隙也能用来抓手，
这样，只要浮窗有一丝可见，也能方便地用鼠标拖移。

**Comment by lmk123** [comment]
我打算直接解决问题，也就不用把抓手区域扩大到整个标题栏了。

#767 已经在 v7.2.4 解决。

等 #816 也完成了，我就会发布 v7.2.4。
