### ISSUE TITLE
启用辅助键，输入框中划词，快捷键（含Space）抬起时，浮窗被关闭

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#826]
启用：配合辅助键使用
“翻译网页中选中的文本”快捷键：Ctrl+Shift+Space

然后，比如在GitHub的输入框中选择文本，
按下Ctrl+Shift+Space，
当Space键抬起时，浮窗即关闭。

**Comment by lmk123** [comment]
是的，这是因为为了解决 #730 的问题所以做的检测，如果在文本框中按下了 Space 就隐藏窗口。

目前来看只能建议你换一个快捷键了

**Comment by lmk123** [comment]
我准备加个设置项，允许并建议用户修改辅助键，然后取消对 #730 做的检测，这样应该是比较好的方案。

不然 Ctrl 键实在有太多要 workround 的边缘情况了。

**Comment by lmk123** [comment]
后续进度更新在 #631 中，这个就先关闭了
