### ISSUE TITLE
用浏览器自带 PDF 阅读器打开本地 PDF 后，用右键菜单“打开此 PDF”无反应，需要给用户一个提示

### ISSUE THREAD

**Issue by TESJackeyLove** [lmk123/crx-selection-translate#827]
edge打开本地pdf默认为edge浏览格式，右键打开此PDF无反应，只能拖拽进去才能打开，Edge和插件均为最新版，希望作者修复一下

**Comment by lmk123** [comment]
这其实是浏览器自己的安全限制，即如果用浏览器自带的 PDF 阅读器打开了本地的 PDF 文件，那么通过右键菜单选择“打开此 PDF”是拿不到本地文件的地址的，即使开启了“允许访问文件网址”也没用，见 794

我会在下个版本中针对这种情况添加一条说明。

**Comment by GH01** [comment]
▲拖入PDF文件后，此橙色提示应自动消失。
▲点x关掉此橙色提示 等效于 点“不再提示”？那怎样重置(重显)呢？

**Comment by lmk123** [comment]
点 X 只是临时关闭此提示，下次用右键菜单打开本地 PDF 还是会有这个提示，直到用户点击了“不再提示”。

目前，所有点了“不再提示”的提示弹窗都暂时没有办法重新显示出来，因为我感觉似乎没有必要重新显示，当然如果需要的话，我可以加一个“重置所有提示”之类的按钮让它们再重新显示出来。

**Comment by GH01** [comment]
当时，点x后就再也不见出来。
现在再试却没问题。
