### ISSUE TITLE
让词根可以点击翻译

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#833]
## 功能简介

使用百度和有道翻译非词根的英文单词（例如 Projects）时，翻译结果中会有“project的复数”、“project的第三人称单数”这类说明，应该让这类说明中的词根（project）可以点击并直接翻译

## 为什么你觉得需要（改进）这个功能？

省掉一次用户额外翻译的步骤

**Comment by GH01** [comment]
这功能居然还能“拯救”破字典：
用《有道》查close，
要是不点这链接，谁能想到《有道》会把close分两版显示……

---
你顺便看一下：
《谷歌》对close的翻译，最后2行末尾，疑似乱码了？

adverb: 近, 不远, 短, 骈阗
noun: 弥合, 儩

**Comment by lmk123** [comment]
谷歌返回的就是乱码

![屏幕截图 2020-12-09 225952](https://user-images.githubusercontent.com/5035625/101646282-4a2bcf80-3a72-11eb-929e-ada17479c948.png)
