### ISSUE TITLE
窗口自动定位方式需要优化

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#836]
详细描述见 https://github.com/lmk123/crx-selection-translate/issues/767#issuecomment-735728004

总结：

- [x] **针对表现 1 和表现 2**：遮挡选块并让浮窗整个可见
- ~~**针对表现 3**：让方向显示在预期位置。~~ 这个改起来比较麻烦，而且虽然方向不对但浮窗内容是可见的，所以问题不大，先不改了……
- [x] **针对表现 4**：由于文本框内的选块位置不能直接拿到，所以之前的版本暂时以整个文本框作为定位点；目前我已经想到了可以拿到文本框内选块位置的方法。

**Comment by lmk123** [comment]
针对表现 1 和表现 2 的示例图：

**划选整行文本、窗口显示向左，此时浮窗仍然向左显示，但会遮挡选块**：

![image](https://user-images.githubusercontent.com/5035625/101088417-a7490080-35ee-11eb-9a1c-0e20f482e6a6.png)

**划选整行文本、窗口显示向上，且上下空间都不足，此时浮窗仍然向上显示，但会遮挡选块**：

![image](https://user-images.githubusercontent.com/5035625/101088531-ce9fcd80-35ee-11eb-9061-14b0853e8089.png)

这样处理应该能符合你的预期吧？

**Comment by lmk123** [comment]
这些优化已经在 v7.3.1 里解决了，所以这个 issue 就先关闭了。如果有问题可以继续留言

**Comment by GH01** [comment]
对，先这样吧。
也许以后可以进一步优化。
我偷看了你的编辑历史，对，那样才是理想状态：
在保证可见的前提下，哪儿合适去哪儿（不拘于所设方向）。

不管以后做不做，这段你既然写了，就留着吧：
`针对表现 1 和表现 2：目前的定位方式，如果选择了向下，则只会检测上下两个方向是否有足够空间并显示，如果两边都没有就会向下，但是应该扩大检测范围，也就是如果上下两个方向都没有足够空间，则继续检测左右；如果上下左右四个方向都没有，则选择空间最大的那个方向并控制浮窗高度不要超出浏览器可视区域，且在浮窗内部显示纵向滚动条。`

**Comment by lmk123** [comment]
一开始我是打算这么做的，但实现起来是目前这种形式最方便，我只改了一个 true/false 就实现了，所以就先这样了。

原本打算实现的方式我可能会在未来新增一个额外的选项，但目前这样也行，就先放着吧。

**Comment by GH01** [comment]
此处的问题（在窗高优化之后）再次发生：

设置：禁用，+松开辅助键时翻译选块
弹窗方向：左上

https://personal.utdallas.edu/~liebowit/book/wordprocessor/word.html
选中整段，按下抬起辅助键。

你的魅影在左边出现，就是不愿进来……

**Comment by GH01** [comment]
其他UI小毛病不打紧，
就是这个（楼上）时常难受，能否先治一下？
