### ISSUE TITLE
为何7.31版本取消了谷歌国内、谷歌国际源的选择？

### ISSUE THREAD

**Issue by wkingnet** [lmk123/crx-selection-translate#838]
## 功能简介
记得之前的版本翻译源里可以选择谷歌国内google.cn、谷歌国外google.com，请问为什么731版本了没有选择了呢？我试了translate.google.cn在国内是可以正常打开的，无需翻墙，所以用google.cn不是更方便吗，为何要用google.com呢

## 为什么你觉得需要（改进）这个功能？
恢复google.cn选择

![QQ截图20201207173700](https://user-images.githubusercontent.com/57652989/101334978-895ff200-38b3-11eb-93e3-2abfcea9d59b.png)

**Comment by wkingnet** [comment]
因为从使用体验上来说，明显谷歌比百度智能多了……这是我翻墙了后两家翻译的截图

![QQ截图20201207174357](https://user-images.githubusercontent.com/57652989/101335213-dcd24000-38b3-11eb-8801-54a09b7ef9bd.png)

**Comment by GH01** [comment]
translate.googleapis.com 其实无需翻。
在你的代理切换工具（如SwitchyOmega）里，把 translate.googleapis.com 设为直连。

把这楼看完：
https://github.com/lmk123/crx-selection-translate/issues/797

**Comment by lmk123** [comment]
楼上已经回答你了，我简单概括：你现在打开的 google,cn 是改了版之后的 google.cn，原本区分国内国外的谷歌翻译已经失效了，所以用了另一种获取谷歌翻译的方法，即 translate.googleapis.com
