### ISSUE TITLE
历史记录：应增大[所查字符串]的最小宽度，减小[网页标题]的最大宽度

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#839]
## 功能简介
现在的[历史记录]有4列：
时间 | 所查字符串 | 网页标题(链接) | 域名

## 为什么你觉得需要（改进）这个功能？
当[网页标题]很长（或窗宽较小）时，[所查字符串]的宽度会被压缩，最小时变成“单字竖排”状，比如word变成：
w
o
r
d

## 建议：
▲增大[所查字符串]的最小宽度。
▲减小[网页标题]的最大宽度。
　▲[网页标题]也用多行显示（或用 省略号+tooltip 的形式）。

**Comment by lmk123** [comment]
已限制网页标题最大宽度 300px，超出部分显示省略号。鼠标移动上去悬停会有 tooltip 展示全部内容。
