### ISSUE TITLE
翻译结果弹窗被遮挡

### ISSUE THREAD

**Issue by ChangJin0520** [lmk123/crx-selection-translate#840]
## 基本信息

划词翻译版本：v7.3.1
浏览器版本：87.0.4280.88（正式版本） （32 位）
操作系统：windows10

## 重现问题的步骤

1. https://observablehq.com/@d3/learn-d3-data?collection=@d3/learn-d3
2. 翻译结果会被代码行给遮挡到

### 预期行为
翻译结果框应该再最上层

### 实际行为
![image](https://user-images.githubusercontent.com/17997339/101355719-eff40880-38d1-11eb-928c-4dde8207dab6.png)

**Comment by lmk123** [comment]
出现此问题的原因跟 #834 一样，后续进展会同步到 #834，这个 issue 就先关闭了。
