### ISSUE TITLE
按住 ctrl 键 hover 指针自动划词翻译

### ISSUE THREAD

**Issue by clayzhu** [lmk123/crx-selection-translate#847]
## 功能简介

添加一个划词的方式，可以按住 `ctrl`，鼠标指针 hover 过文本时，自动选中单词，划词翻译。类似于有道词典的方式，不过它很久没有更新了。

## 为什么你觉得需要（改进）这个功能？

1. 使用先选中，再按 `cmd` 的方式，容易和复制等操作冲突。
2. 在链接等位置，鼠标左键很难单独先选中要翻译的单词；而右键会把整个链接都选中。

**Comment by lmk123** [comment]
针对辅助键的改进，我专门开了一个 issue #855 ，其中包含按下辅助键时开启鼠标悬浮取词。后续进展会更新在 #855 中，这个就先关闭了。
