### ISSUE TITLE
6.x 版本的所有翻译都提示错误

### ISSUE THREAD

**Issue by consatan** [lmk123/crx-selection-translate#849]
之前因为 7.x 版本有问题所以下载了 6.x 版本的离线版并取消自动更新

划词翻译版本：6.4.12
浏览器版本：Edge 87.0.664.60
操作系统：Windows 10 20H2

大概上周四 （2020-12-10）左右发现所有翻译源都返回错误提示，是不再支持了还是翻译源的 api key 改了？

P.S. 之所以不更新到 7.x 版本是觉得 6.x 版本的 UI 更适合我

**Comment by lmk123** [comment]
v6 版本已经不再继续支持了，所以有问题我也不打算改了。

> P.S. 之所以不更新到 7.x 版本是觉得 6.x 版本的 UI 更适合我

是因为绿色背景吗？我已经计划把绿色背景重新加进来了。
如果是因为 v7 版本的字体和按钮太小了，现在最新版本已经可以调整打消了。

如果是其他原因能告诉我吗？我可以视情况对 v7 版本进行改进

**Comment by consatan** [comment]
我只用过 7.x 的早期版本，最主要的原因是 7.x 的 UI 占用了太多面积

**Comment by lmk123** [comment]
占用面积的问题已经在新版本改过来了，你可以试一下。如果还是觉得有问题，可以反馈给我。
