### ISSUE TITLE
辅助键功能的改进：默认关闭、支持修改辅助键等

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#855]
在 v7.3.3 及以下版本中，启用“配合辅助键使用”（默认启用）后，划词时或划词后按下 Ctrl / Command 键会直接弹出翻译结果。

但这样有一些问题：

- 按下 Ctrl / Command + C 快捷键复制文本时可能会误触翻译。原因是有的人是按下 Ctrl、然后划词、最后再按下 C 来复制文本的，这正好满足了“划词时按下 Ctrl / Command 键”的条件，导致划词翻译直接弹出了翻译结果。
- 为了避免在文本框内按下 Ctrl + Space 切换输入法时误触翻译（#730），我针对这个情况做过改进，当按下 Ctrl 打开了翻译窗口后，又在按下 Space 的时候隐藏了窗口。这种方式其实也触发了翻译，只不过按下 Space 的时候隐藏了，所以看上去像是没有翻译一样，但仍然会触发自动朗读；而且，这种方式会带来另一个问题：用户不能自定义 Ctrl + Shift + Space 这样的快捷键 #826

为了解决这些问题，v7.4.0 准备对辅助键做一个改进：

- #631 允许并建议用户将辅助键 Ctrl / Command 替换成其它键。目前我打算另外支持 Alt / Option 和 Shift
- #747 v7.4.0 之后不默认选择任何键，需要用户自行选择，如果没有选择辅助键，那么其它跟辅助键有关的功能不会生效；在用户选择 Ctrl / Command 时给出用户提示可能会跟复制冲突；从 v7.3.3 及以下版本自动更新上来的用户，如果没有关闭“配合辅助键使用”，则默认选中 Ctrl / Command
- 将“划词时或划词后按下 Ctrl / Command 键会直接弹出翻译结果”拆成两个设置项，分别为“划词时”和“划词后”，可以分开启用或关闭，且默认关闭；从 v7.3.3 及以下版本自动更新上来的用户，如果没有关闭“配合辅助键使用”才默认开启。

另外，还会给辅助键额外添加两个新选项：

- #847 按住辅助键时启用鼠标悬浮取词
- #29 按住辅助键时让链接内的文本可以被划选，不会因为划词跳到新页面

**Comment by lmk123** [comment]
在开发过程中，发现单独使用 Alt 或 Shift 也有各自的问题。

在 Windows 10 Chrome 里，Alt 键放开后，浏览器会将焦点聚焦到地址栏最右侧的菜单按钮上，这导致页面失去了焦点，也就导致了如果启用了”按下辅助键时开启鼠标悬浮取词“，那么此时再按下 Alt，划词翻译不会开启鼠标悬浮取词。

用 Shift + 鼠标单击时，会自动选中这一次单击跟上一次单击这两次单击范围内的文本，如果启用了”按下辅助键时开启鼠标悬浮取词“，会导致划词翻译触发翻译——大部分情况下，这都是不符合预期的。

**Comment by GH01** [comment]
沙拉词典 是允许自定义 多键组合。
有些软件是支持 双击Ctrl。

**Comment by lmk123** [comment]
多键组合是比较好的办法。双击辅助键对于按下辅助键时才开启的功能（例如鼠标悬浮取词、让链接可被划选）不太适用。
