### ISSUE TITLE
PDF阅读器划词出现移位

### ISSUE THREAD

**Issue by TESJackeyLove** [lmk123/crx-selection-translate#857]
![QQ截图20201224090317](https://user-images.githubusercontent.com/53500403/103047574-e7384d80-45c6-11eb-9f60-ab8819e725b6.png)
在原版PDF里划词是正常的

**Comment by lmk123** [comment]
内置 PDF 阅读器使用的是第三方开源的 [PDF.js](https://mozilla.github.io/pdf.js/)，也就是 Firefox 浏览器里的 PDF 阅读器。

它目前确实有很多问题，但我无法对它进行修改、或者给它添加新的功能。如果你遇到了划词相关的问题或者觉得它功能太少，建议使用其它 PDF 阅读器打开 PDF，然后使用全局快捷键打开使用独立窗口进行翻译。
