### ISSUE TITLE
自动发音选择

### ISSUE THREAD

**Issue by yinva** [lmk123/crx-selection-translate#858]
## 功能简介
划词自动翻译可以选择是英式还是美式
## 为什么你觉得需要（改进）这个功能？
对口语方面有要求，而现在是**默认朗读第一个**，在使用百度翻译情况下为美式

**Comment by lmk123** [comment]
v7.4.8 起，划词翻译支持使用系统语音朗读文本了，且可以设定口语，例如用使用粤语朗读中文、或使用美式朗读英文，你可以试一下
