### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by sailxjx** [lmk123/crx-selection-translate#859]
## 基本信息

划词翻译版本：7.3.3
浏览器版本：chrome 87.0.4280.88
操作系统：macos 11.0.1

安装划词翻译当天百度，谷歌，有道翻译都能正常使用，第二天开始百度翻译就始终是未知错误了。
<img width="248" alt="Screen Shot 2020-12-24 at 13 53 44" src="https://user-images.githubusercontent.com/909853/103064815-e9fb6880-45ef-11eb-80f5-6926311488ab.png">

**Comment by lmk123** [comment]
我这里没法重现，你可以点开背景页将报错信息发给我么？

（如果你不想这么麻烦，可以试试访问一下 https://fanyi.baidu.com 或卸载重装划词翻译试试）

方法：

1. 在网页上划一下词，让百度翻译触发一次未知错误
2. 进入 chrome://extensions/ 勾选右上角的“开发者模式”
2. 找到划词翻译并点击划词翻译的“背景页”
3. 切换到 Network，将 https://fanyi.baidu.com/v2transapi 的响应内容截图发到这里

正常情况下，这个响应应该是这样的：

![屏幕截图 2020-12-24 221837](https://user-images.githubusercontent.com/5035625/103093760-45504980-4636-11eb-8e5a-927d3cacf054.png)

**Comment by sailxjx** [comment]
百度返回 401，响应 body 里面没内容
<img width="859" alt="Screen Shot 2020-12-25 at 10 21 59" src="https://user-images.githubusercontent.com/909853/103114801-17512080-469b-11eb-8539-fe6f98313978.png">

**Comment by sailxjx** [comment]
卸载重新安装之后还是这样

**Comment by lmk123** [comment]
麻烦将这次请求的详细请求内容贴在这里，按照这个方法获取：

### 注意：从获取到的 bash 命令里删除掉 `-H 'cookie=...' 的内容

![image](https://user-images.githubusercontent.com/5035625/103138711-3fc73200-4710-11eb-939f-60676ae6e89c.png)

比如我的是下面这样，然后我通过 bash 跑了一下是能正常拿到翻译结果的：

```sh
curl 'https://fanyi.baidu.com/v2transapi' \
  -H 'authority: fanyi.baidu.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"' \
  -H 'dnt: 1' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'accept: */*' \
  -H 'origin: chrome-extension://kbacofinkkgbogbhnjdgedpgajpjmnbd' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: zh-CN,zh;q=0.9,en-GB;q=0.8,en;q=0.7'  \
  -H 'cookie=删除掉'
  --data-raw 'from=zh&to=zh&query=%E6%B5%8F%E8%A7%88&transtype=translang&simple_means_flag=3&token=6df09be285f2841a87fa9d97bc460d93&sign=37110.291783' \
  --compressed
```

**Comment by sailxjx** [comment]
<img width="897" alt="Screen Shot 2020-12-28 at 09 56 40" src="https://user-images.githubusercontent.com/909853/103184398-00a50680-48f3-11eb-99d0-d825489ee305.png">
响应是空的，curl 也是没有响应内容

curl 'https://fanyi.baidu.com/v2transapi' \
  -H 'authority: fanyi.baidu.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'accept: */*' \
  -H 'origin: chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cookie: 删除' \
  --data-raw 'from=en&to=zh&query=bash&transtype=translang&simple_means_flag=3&token=86f6dd22f3945602221b2ba614baefb3&sign=536949.840260' \
  --compressed

**Comment by sailxjx** [comment]
根据 http 状态码 401 判断是未验证，我访问一下 fanyi.baidu.com 之后就可以在划词翻译正常得到结果了，但是不持久，过一天左右又会出现未知错误

**Comment by lmk123** [comment]
会不会是其它扩展把百度相关的 cookies 给删了，所以导致你需要重新访问一下 fanyi.baidu.com 去生成一下？

不过在之后的版本，我会把百度（和有道）翻译替换成官方接口，官方接口就不依赖百度的 cookies 了，所以应该不会有这个问题了，但是官方接口跟现在的接口的翻译结果不太一样，详细说明可以看[从 v7.5.0 开始，划词翻译会逐步将百度和有道翻译替换成官方接口](https://hcfy.limingkai.cn/use-official-api.html)。

**Comment by ChaosZh** [comment]
![image](https://user-images.githubusercontent.com/33629609/104985590-449baf00-5a4c-11eb-827a-fb2321257ef9.png)

**Comment by lmk123** [comment]
401 的问题还是无法重现，先关闭了。如果有更多可以提供的信息可以继续留言。
