### ISSUE TITLE
一直提示已更新，请重启浏览器，但是重启依旧

### ISSUE THREAD

**Issue by Danceiny** [lmk123/crx-selection-translate#86]
如题，对于网页文字，现在无法正常使用了，无法翻译。

**Comment by lmk123** [comment]
有尝试过[常见问题里的解决方案](https://github.com/lmk123/crx-selection-translate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91%E5%8A%9F%E8%83%BD%E5%81%B6%E5%B0%94%E4%BC%9A%E5%A4%B1%E6%95%88%E6%AF%94%E5%A6%82%E5%88%92%E8%AF%8D%E5%90%8E%E6%B2%A1%E5%8F%8D%E5%BA%94)吗？

**Comment by Danceiny** [comment]
这个解决方案看过，表示与我碰到的问题没有什么共同性。在浏览器右上角的插件那里可以正常启用，但是对于网页中的内容，选择翻译后一直提示**划词翻译刚才自动更新了，请重启浏览器后重试**。
了

**Comment by lmk123** [comment]
那你有按照解决方案里说的那样重装过吗？有很多出现同样问题的用户在重装过后都恢复正常了。

**Comment by Danceiny** [comment]
不好意思之前理解错误，我只是禁用再重新启用。刚刚卸载重装后好了，谢谢！再次抱歉！
