### ISSUE TITLE
收藏夹翻译错误！

### ISSUE THREAD

**Issue by Bianr233** [lmk123/crx-selection-translate#864]
看图！

![屏幕截图 2021-01-03 205007](https://user-images.githubusercontent.com/28507180/103479009-64ed2c00-4e05-11eb-90c0-69787038ca50.jpg)

划词翻译版本：740
浏览器版本：版本 87.0.4280.88（正式版本） （64 位）
操作系统：win10

希望能只勾选一个源

**Comment by lmk123** [comment]
这个情况应该跟 #908 是一样的。

> 希望能只勾选一个源

已新开一个 issue #909
