### ISSUE TITLE
关于禁用网页划词后使用辅助键的功能改进

### ISSUE THREAD

**Issue by chenzezec** [lmk123/crx-selection-translate#866]
## 功能简介
禁用网页划词后，使用辅助键进行翻译时，在固定翻译窗口后希望能自动检测用户划的词
## 为什么你觉得需要（改进）这个功能？
当用户固定翻译窗口时，说明用户在这个页面阅读可能需要频繁的划词翻译，这个时候就需要频繁的按ctrl或alt或shift键，而固定窗口后能自动检测就能解放在键盘上的手，在没有固定窗口时，则不需要这样。

**Comment by GH01** [comment]
嘿嘿，还是有人要的嘛！
#389
▲依据以上经验，主人点赞=纠结后放弃……:joy:

建议改一下标题，其实是 固定窗口-划选-按键 间的关系。

**Comment by lmk123** [comment]
主要是如果这么改了的话，其实是改变了之前的用户习惯，估计得靠加一个设置项来避免给其它用户造成不同的使用体验了

**Comment by GH01** [comment]
肯定需要选项，而且应该是 快捷选项。

刚才试的时候，发现一个“很悬的用法”：
勾选“鼠标悬浮取词”，
然后划词，将鼠标停在 字间（或 标点上），
划词（选块）会被翻译！

之所以说很悬，是因为很难掌控……:joy:

**Comment by chenzezec** [comment]
的确需要一个设置项，而且我这里是划词，一般不开启取词的

**Comment by GH01** [comment]
https://github.com/lmk123/crx-selection-translate/issues/911#issuecomment-788068505 被主人一问，我才想到有个变通之法对付这个：
页内浮窗固定后，点击扩展按钮，在弹窗中临时切换一下“全局禁用”就可以了。

对我来说，这样好像就够了，开开关关也不麻烦。
楼主试试？

**Comment by chenzezec** [comment]
不好意思，你说的我不太能理解，全局禁用后那岂不是不能用了？我需要的是固定页内浮窗后，不再需要辅助键，而是直接读取鼠标所划的词

**Comment by GH01** [comment]
我的用法是：
平时，全局(所有网站)禁用 + 辅助键(或快捷键)临时触发。
浮窗固定时（或 不想麻烦键盘触发时），就手动切换到 全局启用，这样就不需要按键了。此时往往是专注于当前页面，对全局影响不大。结束专注后，再手动切回 全局禁用。

看你前面的描述，我以为你也是 全局禁用。
如果你是 分网站禁用，其实同理，只需切换当前网站的启用/禁用。

**Comment by lmk123** [comment]
我准备加个选项，“固定模式下忽略黑名单规则”，勾选之后，只要是在固定模式下，划词后会始终触发翻译，无论当前页面是不是在黑名单规则中

**Comment by lmk123** [comment]
并且，我会在新安装扩展的用户中将这个选项默认勾选

**Comment by chenzezec** [comment]
嗯，这样是可以的，十分感谢
