### ISSUE TITLE
翻译出现（接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。）

### ISSUE THREAD

**Issue by qq514444957** [lmk123/crx-selection-translate#867]
## 基本信息

划词翻译版本：6.4
浏览器版本：12.0
操作系统：win 10 2004

## 重现问题的步骤

1.翻译出现（接口返回了错误的数据，请稍候重试。小提示：使用谷歌翻译（国内）时请确保你没有开启某高科技软件。）
2.
3.

### 预期行为
重装也无法恢复   无法翻译了

**Comment by lmk123** [comment]
升级到最新版本 v7.4 即可

**Comment by qq514444957** [comment]
7..0版本 不好用 我不想用

**Comment by lmk123** [comment]
但是让我同时维护新版本和旧版本两个版本也没那个精力，你能告诉我哪里不好用吗？我可以改进。目前的 v.7.4 版本已经是根据大部分用户的反馈，改进到跟旧版本功能兼容了

**Comment by qq514444957** [comment]
好的，6.0版本 好用在翻译快和 窗口便捷  不像7.0这些翻译 出来个 大窗口 而且还得 等半天

**Comment by lmk123** [comment]
v7.4 的窗口已经调小了，并且可以调整大小。

等半天的问题，我目前没有碰到，不过我确实计划改进一下

**Comment by qq514444957** [comment]
好的 刚下载 了7.4感觉还是挺好用的，有问题我再 反馈
