### ISSUE TITLE
HackNews上划词没有弹出提示

### ISSUE THREAD

**Issue by callmepeanut** [lmk123/crx-selection-translate#87]
版本 47.0.2526.106 (64-bit)
系统：Linux-64bit
首页链接文字，评论页没有问题

**Comment by callmepeanut** [comment]
感觉对于这种链接最好得方式是屏幕取词，不知道小伙伴对这种链接文字得单词翻译是怎么解决的

**Comment by lmk123** [comment]
如果是链接取词的话，你的问题可能重复了 :smile: #29
