### ISSUE TITLE
 希望为有道翻译添加音标

### ISSUE THREAD

**Issue by EPTansuo** [lmk123/crx-selection-translate#870]
## 功能简介
为有道翻译添加音标

## 为什么你觉得需要（改进）这个功能？

我在查词时经常需要查看音标，虽然可以使用百度翻译查看音标，但是百度翻译的准确性不如有道.而且经常出现百度翻译不正常工作的情况
![截图_2021-01-10-16-52-34](https://user-images.githubusercontent.com/38463519/104118455-48507700-5364-11eb-8796-b0aa8b43a5a7.png)

**Comment by lmk123** [comment]
我计划在未来的版本把有道（和百度）翻译替换成官方接口，现在和以后，有道翻译以及百度翻译可能都不会有音标了，但我会加入剑桥词典。

详细说明可以看[从 v7.5.0 开始，划词翻译会逐步将百度和有道翻译替换成官方接口](https://hcfy.limingkai.cn/use-official-api.html)。
