### ISSUE TITLE
百度翻译速度较慢

### ISSUE THREAD

**Issue by EPTansuo** [lmk123/crx-selection-translate#871]
## 基本信息

划词翻译版本：7.4.0
浏览器版本：Firefox 84.0.1 (64-bit)
操作系统：archlinux 5.9.13-arch1-1

## 重现问题的步骤

1.复制一个单词或一个句子
2.启动划词翻译

### 预期行为
百度翻译本应翻译出结果

### 实际行为
百度翻译没有给出翻译结果（如下图）
即使留出很长的等待时间也不会给出翻译结果
不过百度翻译在网页划词中工作正常
![截图_2021-01-10-16-52-34](https://user-images.githubusercontent.com/38463519/104118551-f3613080-5364-11eb-9ab1-4fd216d5f886.png)
![截图_2021-01-10-16-59-42](https://user-images.githubusercontent.com/38463519/104118589-43d88e00-5365-11eb-8489-ecae16cdf196.png)

**Comment by lmk123** [comment]
我在火狐 84 没有重现这个问题，但是百度翻译确实比较慢，遇到网络不稳定的情况可能会卡住，我会在下个版本 v7.4.1 中改进这个问题，到时候你再试试看

**Comment by EPTansuo** [comment]
我之后又试了试，再翻译界面输入英文是可以正常翻译的，但是读取剪切板时百度翻译就不能正常工作，等上半分钟都没反应。
这个好奇怪

**Comment by lmk123** [comment]
百度翻译一直显示 loading 不出现翻译结果的问题我修复了，会在 v7.4.1 发布
