### ISSUE TITLE
翻译按钮定位错误

### ISSUE THREAD

**Issue by pbgf** [lmk123/crx-selection-translate#872]
## 基本信息
翻译按钮定位错误

划词翻译版本：7.4.0
浏览器版本：Google Chrome 版本 87.0.4280.88
操作系统：mac

## 重现问题的步骤

1.浏览 https://rollupjs.org/guide/en/#introduction
2.滑词 没有出现翻译按钮

### 预期行为 
出现翻译按钮
### 实际行为
没有出现翻译按钮

后来看了下 发现翻译按钮是根据transform定位的，但是 https://rollupjs.org/guide/en/#introduction 这个网站给全部div都加上了 position: relative 属性，所以应该只要显示的指定您组件下根元素下面的div元素加上 position: initial属性就可以了，或者其他方式让这个网站的全局position样式不影响到您的组件的重要样式。
![image](https://user-images.githubusercontent.com/30624172/104179625-1b28c500-5447-11eb-8293-0c17d33b8850.png)

**Comment by lmk123** [comment]
感谢反馈，已在代码中修复，会在下个版本中发布上去。
