### ISSUE TITLE
动态插入元素导致Bilibili消息弹窗样式错误

### ISSUE THREAD

**Issue by bruceCzK** [lmk123/crx-selection-translate#873]
## 基本信息

划词翻译版本：7.4.0
浏览器版本：Edge 87
操作系统：Win10

## 重现问题的步骤
PC版B站消息窗口内会多出一个横向滚动条，看了下应该是一个 `id="popper-container"` 的元素导致的，这个元素设置了固定的宽度，没有检测当前窗口的尺寸。因为没有源码，只能贴一下DevTools里面的信息了。
![QQ截图20210112001509](https://user-images.githubusercontent.com/8399711/104207558-5210d200-546b-11eb-8657-523622ca1079.jpg)
![QQ截图20210112001519](https://user-images.githubusercontent.com/8399711/104207603-550bc280-546b-11eb-947c-b89fd83f09c0.jpg)

### 预期行为
![QQ截图20210112001229](https://user-images.githubusercontent.com/8399711/104206764-e3337900-546a-11eb-8fc8-c9d7cf3071a6.jpg)

### 实际行为
![QQ截图20210111235309](https://user-images.githubusercontent.com/8399711/104206718-d57df380-546a-11eb-951d-191b018d4a46.jpg)

**Comment by lmk123** [comment]
感谢反馈，将会在下个版本中修复

**Comment by lmk123** [comment]
看了一下，跟 #834 是同一个问题，也就是由于划词翻译在 iframe 里也插入了翻译窗口导致的，下个版本不会在 iframe 里插入翻译窗口了，这个 issue 就先关闭了，后续进展会更新到 #834
