### ISSUE TITLE
语音朗读第一次的前几秒声音非常小，所以每次朗读都需要点击第二次朗读才能达到效果

### ISSUE THREAD

**Issue by wlioi** [lmk123/crx-selection-translate#876]
## 基本信息

划词翻译版本：划词翻译 v7.4.0
浏览器版本：firefox 84.0.2 (64 位)
操作系统：win10 2004 21277.1000 Windows Feature Experience Pack 220.32303.0.2003

## 重现问题的步骤

1.点击朗读或设置成自动朗读（音量语速设置都是默认）

**Comment by lmk123** [comment]
在 v7.6.0 版本之前，百度翻译、有道翻译使用的是它们网页在线版里的语音朗读，确实是有这个问题的；但是自 v7.6.0 版本之后，这俩翻译服务都改为了使用你的操作系统的语音，所以不会有这个问题了。
