### ISSUE TITLE
PDF阅读器无法根据链接跳转到页码

### ISSUE THREAD

**Issue by wengh** [lmk123/crx-selection-translate#878]
## 基本信息

划词翻译版本：7.4.0
浏览器版本：Chromium 87
操作系统：Win10

## 重现问题的步骤

1. 开启 “自动打开PDF” 功能
2. 打开 https://cses.fi/book.pdf#page=271

### 预期行为
打开文档的第271页（可以用Chrome内置阅读器验证）

### 实际行为
文档打开了，但是却停留在第一页或者上次离开时的页码

**Comment by lmk123** [comment]
内置 PDF 阅读器我基本无法对它进行修改，[常见问题](https://hcfy.limingkai.cn/faq.html)里有说明：

内置 PDF 阅读器使用的是第三方开源的 [PDF.js](https://mozilla.github.io/pdf.js/)，也就是 Firefox 浏览器里的 PDF 阅读器。

它目前确实有很多问题，但我无法对它进行修改、或者给它添加新的功能。如果你遇到了划词相关的问题或者觉得它功能太少，建议使用其它 PDF 阅读器打开 PDF，然后使用全局快捷键打开使用独立窗口进行翻译。

**Comment by wengh** [comment]
> 内置 PDF 阅读器我基本无法对它进行修改，[常见问题](https://hcfy.limingkai.cn/faq.html)里有说明：
> 
> 内置 PDF 阅读器使用的是第三方开源的 [PDF.js](https://mozilla.github.io/pdf.js/)，也就是 Firefox 浏览器里的 PDF 阅读器。
> 
> 它目前确实有很多问题，但我无法对它进行修改、或者给它添加新的功能。如果你遇到了划词相关的问题或者觉得它功能太少，建议使用其它 PDF 阅读器打开 PDF，然后使用全局快捷键打开使用独立窗口进行翻译。

PDF.js 的 [demo](https://mozilla.github.io/pdf.js/web/viewer.html#page=9) 是支持链接页码的。

**Comment by lmk123** [comment]
那我把 pdf.js 升级到最新版本试试

**Comment by GH01** [comment]
应该只是转码导致的问题。

原本这样就不行：
`chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=https%3A%2F%2Fcses.fi%2Fbook%2Fbook.pdf%23page%3D250`

转回来就行了：
`chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=https://cses.fi/book/book.pdf#page=250`

不过楼主的样例，正好前10页是罗马数字，所以跳转会差10，还以为我的浏览器坏了……

有意思的是：
▲在划词翻译的阅读器中，在地址栏改页数，然后回车，会直接跳转。
▲而在浏览器的阅读器中，如上操作，不会跳转，依赖刷新。（我用的是Vivaldi，你们帮我看看Chromium真身是什么情况？）

**Comment by GH01** [comment]
PDF.js也有自己的长处：
分色显示各种链接（红=书签，绿=[注释]，青=URL），很醒目。

相关，都是关于 地址栏的表现：
在阅读器中点击 #类链接（书签/[注释]），跳转之后，能否让地址栏显示 带#的地址？
比如：
`chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=https://cses.fi/book/book.pdf#chapter.1`
`chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=https://cses.fi/book/book.pdf#cite.and79`

**Comment by lmk123** [comment]
> 应该只是转码导致的问题。

你提醒我了，确实跟这个有关。`#page` 是 `viewer.html` 的参数，而转码之后会把它作为 PDF 网址的一部分，所以 `#page` 没有传给 viewer.html

解决方案就是在转码 PDF 网址之前先把 #page 提取出来接到 viewer.html 后面就行了。

**Comment by GH01** [comment]
7.4.4
从 浏览器的PDF阅读器 转到 划词翻译的PDF阅读器，此步貌似没问题，
但地址末尾有2个#page=...，
此时若在地址栏回车，会转到第1页（即 2个#page=... 无效），
要去掉1个#page=...才行。

**Comment by lmk123** [comment]
应该不会有这个问题才对，见下图：
![image](https://user-images.githubusercontent.com/5035625/106772364-e4775080-667a-11eb-90e3-ccee3d9c64e9.png)
确实会有两个 #page，但是第一个 #page 中的 # 已经被我转码成了 %23，所以是不会生效的

**Comment by GH01** [comment]
进一步测试，发现是这样：
Vivaldi地址栏会自动解码，所以回车时已是解码后的URL，便有了2个#page=。
而Chromium本身 地址栏似乎没有自动解码功能，所以你目前的办法没问题。

但这样毕竟不完美，希望能再优化，以适应Vivaldi这样的功能。

**Comment by GH01** [comment]
上面某楼好像没引起注意，删了重写：

pdf.js阅读器 也有自己的长处：
分色显示各种链接（红=书签，绿=[注释]，青=URL），很醒目。

书签/[注释] 还会有状态栏提示，这样的跳转还可以进退（Chromium中无高亮，无状态栏提示，不能进退）。

问题：
书签/[注释]链接跳转 有没可能也反映在地址栏URL中？
比如：
`chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=https://cses.fi/book/book.pdf#chapter.1`
`chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=https://cses.fi/book/book.pdf#cite.and79`

**Comment by GH01** [comment]
Chromium中，地址栏里改页码后，需回车2次才会跳转。
这个该怎么理解？

**Comment by lmk123** [comment]
> Chromium中，地址栏里改页码后，需回车2次才会跳转。

这个我觉得是 pdf.js 自己的实现问题了，我本身除了给 pdf.js 加了个复制网址的按钮以外，没有做任何修改

**Comment by lmk123** [comment]
> 书签/[注释]链接跳转 有没可能也反映在地址栏URL中？

我去看看 pdf.js 的文档，看看它提不提供这样的参数（类似 #page）

**Comment by GH01** [comment]
> > Chromium中，地址栏里改页码后，需回车2次才会跳转。
> 
> 这个我觉得是 pdf.js 自己的实现问题了，我本身除了给 pdf.js 加了个复制网址的按钮以外，没有做任何修改

好像我的表达让你理解反了，
pdf.js 没问题，
我是奇怪 Chromium自身的pdf阅读器 上述方面到现在还这么弱，而且还有这毛病。
