### ISSUE TITLE
添加外部跳转链接

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#879]
## 功能简介

对于暂时没有加入到划词翻译得其它翻译接口（例如 DeepL、腾讯翻译君等等），可以先给它们加入外部跳转链接，点击后直接跳转到相应的网页版翻译地址

## 为什么你觉得需要（改进）这个功能？

可以弥补划词翻译支持的翻译源较少的问题

**Comment by GH01** [comment]
最好允许用户自定义/增减，用户还可以当搜索引擎用了！

形式：（底部?）一排图标。

**Comment by lmk123** [comment]
翻译面板底部会有一排按钮，点击就可以跳转到对应的翻译结果页面。

“当作搜索引擎用”的形式我打算在未来直接做在右键菜单里，这次只是添加了显示翻译结果页面的专用按钮。

**Comment by GH01** [comment]
个人觉得，图标+tooltip 更好，更省地方。
（甚至tooltip都可以不要，因为链接会有状态栏提示。）
用户使用中反正是“一回生二回熟”。

我的建议是：
不要区分 翻译 和 搜索 了，
完全开放自定义，任由用户编排底部按钮。

理由：
▲这种链接形式，翻译/搜索 是一回事，没必要对文本进行预处理。

▲菜单的缺点是 打开一次只能点选一个。
Vivaldi支持 多搜索子菜单（除了搜索，我还加了一些词典/翻译），当想一次打开多个时就不爽了……
而按钮(链接)的优点是 可以用中键（或Ctrl+左键）点，想开几个就几个。

**Comment by lmk123** [comment]
> 图标+tooltip 更好，更省地方

这个提议不错，已加入优先处理 https://github.com/lmk123/crx-selection-translate/issues/895

> 这种链接形式，翻译/搜索 是一回事，没必要对文本进行预处理。

不对的，翻译的外部链接除了选中文本，我还把源语种和目标语种填进去了，这也是我没有把翻译类链接做进右键菜单的原因。

> 按钮(链接)的优点是 可以用中键（或Ctrl+左键）点，想开几个就几个

按钮确实有这样的优点，但如果把外部链接全放到面板上有一个问题，就是用户必须先进行一次翻译才能点击到按钮。

举个例子，比如“使用谷歌搜索选中的文本”的功能，如果做成按钮，那么我必须先翻译它，然后才能点击到，但实际上我并不希望翻译这段文本；如果这个功能在右键菜单里就没有这个问题了。

**Comment by GH01** [comment]
这两个问题，我认为只要开放了自定义，就都解决了：翻译/搜索，菜单/按钮，用户随意。

>>`这种链接形式，翻译/搜索 是一回事，没必要对文本进行预处理。`
>
>`不对的，翻译的外部链接除了选中文本，我还把源语种和目标语种填进去了，这也是我没有把翻译类链接做进右键菜单的原因。`
>
▲用户可以在URL中自定义参数（包括但不限于 语种）。
▲同一引擎，用户可以添加多个（参数不同）。
▲各项加个选项，以决定其是否跟随全局语种设置（跟随时则忽略用户所加语种参数，如果可以实现的话），满足两种需求。
▲另外，外链网站有cookie，会记住“最近语种”等信息，切换也不算麻烦了。

▲各项再加2个复选项，以决定其出现于 菜单/按钮，还是两个都要。
我觉得 翻译类进菜单 是可以的吧。

>>`按钮(链接)的优点是 可以用中键（或Ctrl+左键）点，想开几个就几个`
>
>`按钮确实有这样的优点，但如果把外部链接全放到面板上有一个问题，就是用户必须先进行一次翻译才能点击到按钮。`
>
▲权衡利弊，我个人倒不在乎这个。除了上述优缺点，打开子菜单也是个麻烦，反倒不如一键开窗爽气。
▲我觉得 按钮在顶部显示 也可以作为选项。会更方便醒目些，又能暂时对付 #816 问题。
