### ISSUE TITLE
新功能-鼠标悬浮取词等建议

### ISSUE THREAD

**Issue by yantaozhao** [lmk123/crx-selection-translate#88]
**鼠标悬浮取词**：鼠标悬浮放在单词上面，显示单词释义

Best Regards

**Comment by lmk123** [comment]
嗯……这个功能看起来比较麻烦，我得考虑看看“性价比”是否合适。

**Comment by gggccc44** [comment]
没必要，选中下就累了你了？那种选中都不行的，也没啥用
貌似另外有取词的专门插件吧，lz不如去找那个用

**Comment by 4781121** [comment]
这个功能真的非常需要啊, 开发者可以参考有道的插件, 他们支持这个功能, 真的非常使用, 比如按Ctrl+鼠标悬停就翻译, 特别好使.

**Comment by 4781121** [comment]
我刚才看了下有道插件的代码, 这个功能不复杂, 有道插件lookup.js文件中OnDictEvent function 中有实现过程, 希望开发者赶紧加上这个功能啊, 非常感谢.

**Comment by lmk123** [comment]
v7.0 开发完成，并支持鼠标悬浮取词，将在近期发布。
