### ISSUE TITLE
“鼠标悬浮取词”状态时 能否兼容 用户划词？

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#880]
## 为什么你觉得需要（改进）这个功能？
这样更智能，划了不白划。

**Comment by lmk123** [comment]
在做这个功能的时候我有考虑过，最后的结论是除非加个选项，允许用户配合一些辅助键（比如 ctrl）时才启用悬浮取词，这样才能做到普通划词跟悬浮取词不冲突。

不过我已经给辅助键加上了“按下辅助键时启用鼠标悬浮取词”的功能了。

**Comment by GH01** [comment]
这样不错。
但是否还能优化：

`在按住辅助键不放的情况下：开启鼠标悬浮取词`
`松开辅助键后，翻译页面中选中的文本`
▲同时启用这两项，
划词，然后按下辅助键，用户本意是想翻译划词，
但若在辅助键松开前 鼠标有移动，则常有可能触发 鼠标悬浮取词。
