### ISSUE TITLE
推荐添加 DeepL 翻译

### ISSUE THREAD

**Issue by DesistDaydream** [lmk123/crx-selection-translate#881]
## 功能简介
参考：[Wiki](https://zh.wikipedia.org/wiki/DeepL%E7%BF%BB%E8%AD%AF)
DeepL翻译（英语：DeepL Translator）是2017年8月由总部位于德国科隆的DeepL GmbH（一家由Linguee支持的创业公司）推出的免费神经机器翻译服务[2][3][4]。评论家对于它的评价普遍正面，认为它的翻译比起Google翻译更为准确自然

## 为什么你觉得需要（改进）这个功能？
不好描述，直接上图吧。
![image](https://user-images.githubusercontent.com/39847025/105619349-b6993d00-5e2c-11eb-9c98-8e9d79be7e77.png)
![image](https://user-images.githubusercontent.com/39847025/105619367-ea746280-5e2c-11eb-8296-01951076169b.png)

## DeepL 翻译的缺点
速度较慢

**Comment by lmk123** [comment]
#854
