### ISSUE TITLE
多段翻译，翻译结果不能自动分段显示。

### ISSUE THREAD

**Issue by Daidaiduo** [lmk123/crx-selection-translate#883]
你好，多行翻译，翻译结果不能自动分行显示。
![QQ截图20210128121320](https://user-images.githubusercontent.com/23332018/106089389-d39e7a80-6162-11eb-903e-fec66a35e4af.jpg)

希望可以分行显示。谢谢

**Comment by lmk123** [comment]
这其实是 v7.4.1 引入的一个 bug，感谢反馈！
