### ISSUE TITLE
点击一下翻译框之后 Move 光标无法恢复

### ISSUE THREAD

**Issue by iLtc** [lmk123/crx-selection-translate#89]
![demo](https://cloud.githubusercontent.com/assets/4352234/12570707/b6743e9c-c39f-11e5-8a88-8bec66aa6480.gif)

点击“译”的图标之后，再点击一下翻译框的顶部，鼠标会变成 Move 的形状，如果没有拖动的话，之后没有办法恢复。

**Comment by lmk123** [comment]
嗯，偶尔是会有这个问题，我会修复的
