### ISSUE TITLE
新添的翻译源 DeepL 连不通？

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#892]
## 基本信息
划词翻译版本：7.4.4
浏览器版本：Chrome/88.0.4324.99
操作系统：Win 7

### 预期行为
DeepL 显示翻译结果。

### 实际行为
DeepL框内永远忽闪，永远连不通的样子。

7.4.4已发布多日，却不见有此反馈，只有我遇到吗？
我直接访问deepl.com正常。

**Comment by lmk123** [comment]
这个问题其实已经在 v7.4.5 修复了，只是还没发布。这个问题只在 Chrome 88 才会出现，我也是浏览器自动更新到了 Chrome 88 才发现用不了了

**Comment by abcfy2** [comment]
我也是这个问题，期望尽快能解决

**Comment by GH01** [comment]
DeepL 对 英文单词 的语种误判率似乎很高……
单独人为切换语种后，似乎就又永远忽闪了……

**Comment by lmk123** [comment]
是的，误判率确实高，不过我也只能显示它判断的语种
