### ISSUE TITLE
Subframe: https://deepl.com/ 此进程 始终驻留的必要性？

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#893]
## 基本信息
划词翻译版本：7.4.4
浏览器版本：Chrome/88.0.4324.99
操作系统：Win 7

### 预期行为
相关进程只在必要时驻留。

### 实际行为
无论是否启用翻译源DeepL，
`Subframe: https://deepl.com/` 此进程 始终伴随 划词翻译扩展的启停。

**Comment by lmk123** [comment]
这是因为国内连接  DeepL 非常慢，所以我让它常驻后台，避免每次翻译时太慢，资源占用应该也不高。

**Comment by lmk123** [comment]
我准备做一个改进，在第一次翻译时才启动这个 subframe 进程，并在 1分钟无交互后中断它，在下次翻译时重新启动。

**Comment by GH01** [comment]
确实慢，加载了进程还是慢……

**Comment by GH01** [comment]
v8.6.7.4
此进程现在又改为常驻了？还是因为有bug？

我这里，DeepL现在貌似必须扶墙……

**Comment by lmk123** [comment]
确实又改为常驻了，因为这样能提高deepl的使用速度，不然每次光是加载 deepl 的网页就要 10 ~ 20 秒，再加上请求结果的 5s，查询一次需要十几秒；但是如果常驻之后，每次就只需要花 5 秒请求翻译结果

> 我这里，DeepL现在貌似必须扶墙……

我试了下我这里仍然不需要fq就能用

**Comment by GH01** [comment]
我这里，翻则5秒，不翻无期……

**Comment by lmk123** [comment]
http://ping.chinaz.com/deepl.com

看了下好像还行……

> 不翻无期……

现在我加了超时时间的，如果 15 秒没加载完或者 10 秒没出来结果会显示错误的。难道你仍然会一直处于加载中、既不显示结果也不报错吗？

**Comment by GH01** [comment]
新版有报错。

**Comment by lmk123** [comment]
我下个版本打算把这个超时时间翻个倍，好像有的地区就是需要二三十秒才出结果。。

**Comment by GH01** [comment]
折叠停用或完全不用DeepL，此进程仍不停，这就不合适了吧

**Comment by lmk123** [comment]
我下个版本做个改进吧：

- 只有第一次调用 DeepL 的时候才会创建此进程
- 如果折叠或者取消勾选了 DeepL 就关掉此进程

**Comment by lmk123** [comment]
不过话说回来，持续开启一个这个进程在后台会有什么问题吗？其实这个进程就相当于持续开着一个 deepl 的标签页没有关闭

**Comment by GH01** [comment]
主要是Vivaldi在进程起始时会写盘（Temp夹内）。这是不是Chromium的特性？
我有时要用软件监视程序行为，这半分钟一次显得很烦，但我又不想添加永久的排除规则……

要不你就改成：
不用时停止，启用时持续（别跳）。
（别的扩展/网页 好像都是持续的。）

我这边，DeepL看来一般是要爬梯了，所以其实运行这进程对我没意义。

**Comment by lmk123** [comment]
实际操作过程中，我发现何时关闭此进程的时机不太好掌握……

当用户未启用、或者折叠了翻译面板里的 DeepL 的时候，用户仍然有可能通过网页全文翻译使用 DeepL；

反之，当用户未启用网页全文翻译的 DeepL 时，也可能在划词面板里启用了 DeepL；

换句话说，只有当用户在网页划词面板和全文翻译里都不启用 DeepL 时才应该杀掉此进程，但是这种情况我感觉少之又少。

鉴于此，我觉得做到`只有第一次调用 DeepL 的时候才会创建此进程`应该就够了。只要你不用 DeepL，那么就不会创建这个进程。如果你不小心用了 DeepL，那就重启一下浏览器，进程就没了。
