### ISSUE TITLE
PDF阅读器 能否充分利用缓存（而不是重新下载）？

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#894]
## 功能简介
先在浏览器中打开 网上的pdf，
然后转到 划词翻译的PDF阅读器。
此时能否利用缓存（而不是重新下载该pdf）？

## 为什么你觉得需要（改进）这个功能？
重新下载耗时耗力。

**Comment by lmk123** [comment]
缓存这部分，扩展程序无法进行操控，这完全是浏览器和服务器之间的行为。如果服务器给pdf文件设置了缓存，那么理论上在内置pdf阅读器打开就会很快。
