### ISSUE TITLE
Chrome版v7.4.5离线安装包存在bug

### ISSUE THREAD

**Issue by Daidaiduo** [lmk123/crx-selection-translate#898]
## 基本信息
划词里面的小写字母a会被自动过滤掉，导致单词出错并错误翻译。

划词翻译版本：v7.4.5
浏览器版本：88.0.4324.146（正式版本） （64 位）
操作系统：windows 10 64位

![QQ截图20210205121251](https://user-images.githubusercontent.com/23332018/106988802-8c8c3700-67ab-11eb-9da7-4691dff6e723.jpg)

**Comment by lmk123** [comment]
感谢反馈！已重新发布 v7.4.6 解决了这个问题。
