### ISSUE TITLE
部分网站不弹出翻译按钮

### ISSUE THREAD

**Issue by jdnx** [lmk123/crx-selection-translate#899]
## 基本信息

划词翻译版本：v7.4.4
浏览器版本：chrome 79
操作系统：win10

## 重现问题的步骤

1. 自从自动升级到此版本后部分网站复制文本后不弹出翻译按钮, 右键菜单翻译此文本点击后也无反应
之前版本偶尔也会出现此问题, 有时是等待一段较长时间后可出现按钮,或者disable再enable插件后就好了,但此版本反复试验均不行(也有可能是否部分网址始终无法加载完毕?), 请问加载和翻译按钮显示是否有先后关系? 谢谢!

**Comment by lmk123** [comment]
翻译按钮只会在网页加载完成（也就是当标签页结束转圈之后）才会响应你的划词或者右键菜单的翻译操作。

另外，复制文本是不会触发翻译的，可能是你设置了单独使用 Ctrl 作为辅助键、然后在按下 Ctrl 的情况下划词了，这样才会触发翻译。

如果某些网站可以稳定重现这个问题，请提供网址给我排查问题

**Comment by jdnx** [comment]
感谢作者回复, 升级了7.4.6后有的网站可以了(不知道是不是升级的原因) 有的还是不行, 比如 cnn, 另外关于加载完毕才显示按钮的问题 我一度也以为"标签页结束转圈之后"就可以显示按钮,但多次测试发现也不尽然, 有时还在转圈就可以显示按钮,有时不转圈了却仍然无按钮, 个人感觉问题应该还在页面加载完毕的判断上, 由于众所周知的原因, 连接国外网站有的时候主页面确实加载完毕了,但部分网页内链接可能连不上(可能要等好久才timeout), 是否是这个原因导致的问题, 作者是否能改变下出现按钮的机制,以解决此问题 (因为即使最后出现按钮,可能需等待很长时间的timeout才行),谢谢!

**Comment by lmk123** [comment]
我打开了一个 cnn 的链接  https://edition.cnn.com/2021/02/07/us/dog-rescue-shelter-illinois-trnd/index.html

这个网页是可以正常显示翻译按钮的。我需要你**明确提供一个不能显示按钮的网址**给我，我才能排查这个问题。

另外，“页面转圈结束之后还是无法显示翻译按钮”的情况是可以优化的，实际上在 v6.x 的时候做过这方面的优化，但是在 v7.x 我觉得这没太大必要，因为从我的实际使用情况来说很多网页很快就加载完了。我新开了一个 issue 用于做这个优化（#900），完成之后希望你能给我反馈，看看这个优化有没有解决你的这个问题，毕竟我这边没法重现你的问题。

**Comment by lmk123** [comment]
v7.4.7 进一步尝试解决了部分网页不显示翻译按钮的问题，目前正在商店审核中，你可以去官网下载 v7.4.7 的离线安装包试试看还有没有问题

**Comment by jdnx** [comment]
> v7.4.7 进一步尝试解决了部分网页不显示翻译按钮的问题，目前正在商店审核中，你可以去官网下载 v7.4.7 的离线安装包试试看还有没有问题

@lmk123 , 感谢回复, 还未升级新版, 尝试点击了你给的链接 居然显示按钮了, 于是打开cnn主页 https://edition.cnn.com/,不显示按钮, 随便点一篇文章还是不显示按钮, 然后我再次点击你的链接, 居然又不显示按钮了, 过了几分钟再点击你的链接居然又显示按钮了, 而且不管显示还是不显示按钮, 标签上的圆圈都处于转圈状态, 所以我无法明确给你到底哪个页面一直不行,抱歉(在我写完这段话后再次点击cnn主页发现有按钮了,前次开这个页面等待很久转圈停止了还是没按钮,关闭后再点开,转圈还未停止却有按钮了,再次关闭后再开,又没按钮了)

**Comment by jdnx** [comment]
今天升级到了最新 7.4.7 打开 https://edition.cnn.com/2021/02/09/politics/trump-impeachment-bruce-castor/index.html 
仍然无按钮, 至少好几次是这样, 不知道再尝试几次会不会出现按钮 或者 反而一直无按钮了  @lmk123

**Comment by lmk123** [comment]
我是可以打开的。你的 Chrome 浏览器版本是多少？

**Comment by jdnx** [comment]
chrome 79 , 今天在另一台还没升级到7.4.7的机器上(版本7.4.4)也试验了几次,无按钮, 但马上打开本站(github)的页面或其他开几个页面,比如 www.cgtn.com 就马上出现按钮, 也就是说正常页面都一直没问题, 那些有问题的页面是碰运气,有时有按钮,有时没有,个人觉得随着版本升级, 出现按钮的几率越来越小  @lmk123

**Comment by lmk123** [comment]
我用的是chrome88。如果可以的话，你可以试试升级一下chrome到最新版本看看有没有这个问题，我有空了去下个chrome79试试

**Comment by jdnx** [comment]
> 我用的是chrome88。如果可以的话，你可以试试升级一下chrome到最新版本看看有没有这个问题，我有空了去下个chrome79试试

@lmk123 , 没有升级过chrome,只是自动更新了插件到最新版(不知道是否是今天更新的),今天发现之前所有有问题的页面都可出现按钮,虽然有的网页需要等一会,不知道是否能保持, 前几天试验仍然是没按钮的,特此汇报给作者, 不知道是否和新版本更新有关

**Comment by lmk123** [comment]
感谢反馈，我今天确实发布了新版本，你的版本应该是 v7.5.0。我确实尝试修复了你这个问题，改动了一下可能出现问题的地方，看来起作用了。

那么这个问题我就先关闭了，如果还有问题，欢迎继续提交。
