### ISSUE TITLE
划词进行翻译时文本中的a被自动省略【请下载  v7.4.7 的离线安装包避免这个问题】

### ISSUE THREAD

**Issue by Lin-Your** [lmk123/crx-selection-translate#903]
## 基本信息

划词翻译版本：v7.4.5
浏览器版本：Edge 88.0.705.63
操作系统：Windows 10

## 重现问题的步骤

1.百度搜索add
2.双击选中词add，点击翻译按钮，弹出翻译结果

### 预期行为
显示add的翻译结果

### 实际行为
翻译内容仅包含dd，其他包含a的英文也会自动把a省略掉（如an apple划词后仅剩n pple）
[样例an apple](https://s3.ax1x.com/2021/02/09/ydimOH.png)
[样例e-mail address](https://s3.ax1x.com/2021/02/09/ydiqnH.png)

**Comment by lmk123** [comment]
这个问题已经在 v7.4.6 及以上版本修复了，请先去官网下载 v7.4.7 的离线安装包使用。

我也提交了 v7.4.7 的审核，但估计要 10 个工作日才能审核通过并上架。

当时发现这个问题的时候我就在 edge 取消审核了 v7.4.5，但是过了几天 edge 还是给我发布上去了……

**Comment by lmk123** [comment]
相关 https://github.com/lmk123/crx-selection-translate/issues/898
