### ISSUE TITLE
划词翻译在低Chromium内核版本用不了了（更新至新版没问题），未来的版本还会提供支持吗？

### ISSUE THREAD

**Issue by lulei7471** [lmk123/crx-selection-translate#905]
划词翻译版本：v7.4.7（其实之前的几个版本已经出问题了，由于最近不常用也就没在意）
浏览器版本：cent browser 3.6.8.99（64 位） (portable) (Chromium 69.0.3497.100)
操作系统：win10 ltsb X64

## 重现问题的步骤

1.打开任意网站，选取任意英文单词；
2.打开翻译窗口手动输入或粘贴英文单词；
### 实际行为
默认的几个翻译引擎全部提示：
划词翻译内部出现了一个错误，这可能是划词翻译自动更新了导致的，刷新网页即可恢复。
刷新后问题依旧；也试过将划词翻译移除再全新安装但问题未解决。
![2021-2-16 14-20-33](https://user-images.githubusercontent.com/34099522/108026398-42386f00-7063-11eb-876f-717a1800162f.png)

**Comment by lmk123** [comment]
划词翻译用到了很多新版浏览器内核才提供的特性，这样能减少安装包体积、运行会更快等，但另一方面，也确实可能会在旧版本浏览器上运行出问题。

我先在 chrome 69 上试试这个问题是什么导致的，然后再想想看怎么改。

**Comment by lulei7471** [comment]
> 划词翻译用到了很多新版浏览器内核才提供的特性，这样能减少安装包体积、运行会更快等，但另一方面，也确实可能会在旧版本浏览器上运行出问题。
> 
> 我先在 chrome 69 上试试这个问题是什么导致的，然后再想想看怎么改。

谢谢回复。希望改动的工作量不会太大，未来的版本能够新旧内核通吃。

祝牛年顺利！

**Comment by FreeLoopC** [comment]
@lmk123 你好, 我也碰到了这个问题, 有没有地方可以下载老版本过渡一下, Github我只找到了6的版本, 7的版本谷歌上只有最新版

**Comment by FreeLoopC** [comment]
找到一个7.4.4版本, 完美运行

**Comment by lmk123** [comment]
已在下个版本 v7.4.8 中修复
