### ISSUE TITLE
开着拓展 只要进入b站的一个视频或者电影页面 就会卡死

### ISSUE THREAD

**Issue by kanfeng9** [lmk123/crx-selection-translate#907]
## 基本信息

划词翻译版本：7.4.8
浏览器版本：chrome 88.0.4324.190
操作系统：window10 专业版 20H2 19042.804

## 重现问题的步骤

1.开启拓展
2.进入b站 
3.点击一个视频/电影

### 预期行为
正常播放视频
### 实际行为
直接卡死 浏览器提示该网页无响应 选择退出或者等待

**Comment by lmk123** [comment]
我同样是 Chrome  88.0.4324.190，用 v7.4.8 没有重现这个问题。

卸载了划词翻译再安装看看还有没有这个问题？

**Comment by lmk123** [comment]
另外，可以提供一下出现错误的截图吗

**Comment by lmk123** [comment]
你的情况可能跟 #910 类似，我在 v7.4.10 里尝试解决了这个问题，你可以再试一下，如果有问题欢迎继续留言。
