### ISSUE TITLE
疑似划词翻译影响浏览器播放视频，导致音画不同步和杂音严重

### ISSUE THREAD

**Issue by History-exe** [lmk123/crx-selection-translate#910]
## 基本信息

划词翻译版本：7.4.9
浏览器版本：Firefox 85.0.1
操作系统：Ubuntu 20.04.2

## 重现问题的步骤

1.浏览器插件启用画词翻译
2.打开任意视频，都会出现有杂音和音画严重不同不的问题。
3.插件中禁用画词翻译，音画不同步问题和杂音问题消失。

### 问题疑似的原因
1.**在开启划词翻译的情况下**，查看系统的声音设置面板，发现设置中，**音量级别**处多出来了3个可以单独控制音量的“应用”。如图，浏览器声音就会出现问题：
![2021-02-28 08-27-46 的屏幕截图](https://user-images.githubusercontent.com/33642965/109404227-dfb66b80-799e-11eb-8b03-61e34387adf0.png)

2.**关闭划词翻译的情况下**，打开设置面板是这样的，设置中，**音量级别**仅显示一个firefox。如图，浏览器声音就没有问题：
![2021-02-28 08-24-10 的屏幕截图](https://user-images.githubusercontent.com/33642965/109404241-1c826280-799f-11eb-9b50-a15043cfce38.png)

**Comment by lmk123** [comment]
似乎是有这个可能的。

查了一下关于 speech-dispatcher 的资料，大部分都说这个包有问题，相关链接：

https://bbs.archlinux.org/viewtopic.php?id=222567
https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1736222
https://bugzilla.mozilla.org/show_bug.cgi?id=1252732

我猜测是从划词翻译 v7.4.8 起，为了使用系统语音朗读文本，划词翻译会在浏览器启动的时候调用 [SpeechSynthesis  API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis)（语音合成），导致 Firefox 启动了 speech-dispatcher。

我会尝试进行以下修复：

- 不会在浏览器启动时就调用语音合成的接口，仅仅在要用到系统语音的时候才调用，避免一打开 Firefox 就导致 speech-dispatcher 被启动
- 在系统语音的设置中添加一个新的选项“不使用系统语音”，这样可以完全避免划词翻译调用语音合成的接口

**Comment by lmk123** [comment]
我计划在明天发布 v7.4.10，到时候麻烦你更新一下看看还有没有这个问题并给我一个反馈，我这边没有 Ubuntu 系统，测试不了这个问题。

**Comment by History-exe** [comment]
OK
