### ISSUE TITLE
设置的中栏(增多的子类别)在较低分辨率(高768)时显示不全，需加纵滚条

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#911]
## 为什么你觉得需要（改进）这个功能？
底部的子类别看不到了。

**Comment by lmk123** [comment]
你好像经常需要进设置页，是不是有些设置项是你常用的但没有进快捷选项？

**Comment by GH01** [comment]
看历史/收藏时要路过设置，动眼肌没控制好一不小心瞥到的……
其实是更新后会滚一遍设置，看看变化。
