### ISSUE TITLE
各翻译源 标题栏的UI优化

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#912]
## 为什么你觉得需要（改进）这个功能？
窗高优化后，必要时有了纵滚条。
当 窗宽最小+有纵滚条 时，翻译中文，多个标题栏会变双行，看上去不整洁（如图）：
![image](https://user-images.githubusercontent.com/19272301/109615480-e85d9c00-7b6e-11eb-8ea4-4bc42ebe8206.png)

翻译源/语种 名称还会有更长的。
感觉需要进一步优化，使能整齐一致。

**Comment by lmk123** [comment]
从界面设计上讲，确实应该改进一下，但是……

 - 目前我有其它一些优先级更高的功能性更新
 - 这个问题只需要拖动宽度即可解决。虽然暂时有 #913 的问题，但左边缘 / 没有纵滚条的时候是可以拖动的
 
所以我大概是没有空进行这个界面上的改善了 😂

我打算单独将这类“优先级较低的界面上的改善”列一个 milesone，等哪天优先级高的事项都完成了我再慢慢改善吧 :joy:

**Comment by lmk123** [comment]
做了一下改进，现在只有文字部分会超出显示两行了，如图：

![image](https://user-images.githubusercontent.com/5035625/127603660-544073e9-cce0-4b21-91b6-6508aef6c1b3.png)
