### ISSUE TITLE
浮窗中滚到尽头，继续滚动能否不滚动网页？

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#914]
## 基本信息

划词翻译版本：7.4.10
浏览器版本：Chrome/89.0.4389.53
操作系统：Win 7

## 重现问题的步骤
当浮窗有纵滚条时，用滚轮滚动浮窗，
到达尽头，继续滚动，会导致网页滚动。这能否避免？

**Comment by lmk123** [comment]
应该是有办法的，但是我不太清楚为什么要这样做，毕竟在任何网页这都是默认行为——内部滚动条滚到尽头了就滚动外部滚动条。

**Comment by GH01** [comment]
其实我是不喜欢这种特性的（虽然设计了一个时间间隔），无论在哪个软件……

阅读时，无意识或习惯性地(多)滚了一下，或者下滚时“用力过猛”，子框架就动了，影响阅读……
而划词翻译的浮窗，滚过头了还可能消失……

**Comment by lmk123** [comment]
我在 chrome 89 测试是有效的。 你是什么版本的浏览器？

**Comment by GH01** [comment]
89.0.4389.85
91.0.4443.0

精确重述：
当浮窗有纵滚条时，用滚轮滚动浮窗，
到达尽头，**_等一会儿_**，然后继续滚动，会导致网页滚动。这能否避免？

（有没人知道Chromium是否有flag可以关掉此特性？）

**Comment by lmk123** [comment]
重现了，下个版本会解决这个问题
