### ISSUE TITLE
是否有可能对百度翻译的请求做一个节流？

### ISSUE THREAD

**Issue by whc2001** [lmk123/crx-selection-translate#915]
## 功能简介
请求百度翻译时记录对比这次请求和上次请求的时间，如果距离上一次不超过 1 秒就延时一下再请求

## 为什么你觉得需要（改进）这个功能？
因为自带的百度 APIKey 要停用了就自己申请了免费版的 Key，但是免费版只支持到 1 个请求每秒，有时候不小心选错内容或者三击选择整段文本（点第二下会选择一个单词，第三下才会选中整行）的时候会导致短时间内反复请求，返回错误 54003，必须手动再单击一次重试才能正常显示。而且好像如果短时间内请求太多次会直接被封，就算小于 1QPS 也会一直返回 54003，不小心触发了现在不知道什么时候才能恢复正常

**Comment by lmk123** [comment]
可以。

其实还有一种办法就是将个人版的 api key 升级为高级版的，高级版每秒可以请求 10 次，但是高级版每个月只有前 200 万字符是免费的，超出的部分百度翻译会收取 49 元/百万字符的费用。

**Comment by lmk123** [comment]
我会在未来新增一个选项，如果你申请的是个人版的，我就节流；高级版的，我就不节流。

**Comment by whc2001** [comment]
谢谢，后来发现了，但是平时用的比较多，怕不小心用超了就没有升级
