### ISSUE TITLE
【下载 v7.5.2 离线安装包即可解决】无法正常加载B站、斗鱼、虎牙、Youtube、Pixiv 等网站

### ISSUE THREAD

**Issue by naety4207** [lmk123/crx-selection-translate#916]
## 最新更新：v7.5.2 已解决这个问题，目前 Chrome 商店正在审核 v7.5.2，但你可以去下载[离线安装包](https://hcfy.limingkai.cn/install.html)安装。

最近有很多用户反馈升级到 v7.5.0 之后出现访问部分网站会导致页面无响应的问题，但是我自己没有出现过这个问题，所以找不到问题的根源。

有用户反馈 v7.4.8 是正常的，之后的版本都有问题；也有用户反馈 v7.4.10 是正常的，只有 v7.5.0 及之后的版本有问题，你可以去下载 v7.4.8 或者 v7.4.10 的[离线安装包](https://hcfy.limingkai.cn/install.html)试试看。

浏览器崩溃、网站无响应一般是由于内存泄漏造成的，也就是划词翻译占用了很多内存但并没有释放掉。目前猜测可能有以下原因：

- 可能是系统语音功能造成的。如果是的话，升级到 v7.4.10，然后在划词翻译的设置 - 语音朗读 - 系统语音选择“不使用系统语音”应该就不会出现问题了。
- 可能是截图翻译功能造成的。v7.5.0 内置了一个文字识别引擎，这个引擎使用了不太成熟的技术，所以确实可能会导致浏览器崩溃。如果是的话，那么升级到 v7.5.1 之后且不要使用截图翻译功能就不会出现问题。
- 一个新的猜想：这些问题是不是都发生在搜索行为之后？

但是，以上都只是我的猜测，为了能找到问题的根源，我需要大家提供更多信息。例如，验证一下哪个历史版本是确定不会出问题的、以上两个猜测是否可行等。

由于涉及到内存问题，在提交反馈信息时，除了浏览器版本、操作系统、划词翻译版本，**也请提供你出现问题的电脑的内存容量**。我的电脑是 16GB 的内存容量，这可能是我没有出现这个问题的原因。

## 以下是 @naety4207 写的原文

划词翻译版本：7.5.0
浏览器版本：Edge 88.0.705.81
操作系统：Win10家庭版

划词翻译升级到7.5.0以后，在开启该插件的情况下进入bilibili网站，会导致b站页面信息加载不全、页面卡死，关闭插件后能正常使用b站，将插件降级到7.4.10后也能正常使用b站。尝试卸载后重新安装7.5.0版本仍然出现该问题。

**Comment by lmk123** [comment]
我这边没有重现，但如果是只在 v7.5.0 里出现的问题，我大概能猜到是什么原因。我刚才发布了 v7.5.1 尝试解决这个问题，你可以更新一下试试，无论能否解决都希望你能给我一个反馈。

**Comment by Duskry** [comment]
我也有一个类似的 是导致虎牙全站的崩溃和卡死
划词翻译版本：7.5.0
浏览器：Chrome 89.0.4389.72
操作系统：Win10专业
奇怪的是 我在edge中同样的7.5.0不会出现这个问题

**Comment by killthatshaman** [comment]
我这边的测试,访问Pixiv, `7.4.7`是正常的,从`7.4.8`以及之后包括(7.4.9;7.4.10,7.5.1)就会卡死无响应.
猜测1
> 可能是系统语音功能造成的。如果是的话，升级到 v7.4.10，然后在划词翻译的设置 - 语音朗读 - 系统语音选择“不使用系统语音”应该就不会出现问题了。
我这里在修改设置后还是会卡死.
浏览器版本Chrome 71.0.3578.98 (正式版本) （64 位）
内存32GB

**Comment by lmk123** [comment]
@killthatshaman 如果是这样的话，那看起来跟内存容量也没有关系。我再检查一下 v7.4.7 到 v7.4.8 我都改了些什么

**Comment by yellowko** [comment]
我最近有一台电脑也出现类似问题了，不知道哪个版本时出现的，就最近一星期注意到的。
知网主站没问题，打开知网进行搜索,会出现卡死并且占用大量CPU，F12工具看是Pending了，反正网页不动了，内存在500~1300MB波动。
划词翻译版本：7.5.1
浏览器：Chrome 89.0.4389.72
操作系统：Win10 专业版 20H2 19042.844
内存：8G+16G

但是另外一台机器**没有**出现这个问题
划词翻译版本：7.5.1
浏览器：Chrome 89.0.4389.72
操作系统：Win10 专业版 1809 17763.864
内存：8G

**Comment by lmk123** [comment]
@yellowko 感谢提供反馈信息！

加上你的反馈之后，我发现这些网站都有一个共通点：可能都是在进行搜索之后出现的问题。公众号里也有用户给我发了反馈视频，就是在开启扩展之后在百度进行搜索，百度出现了搜索页但卡死了。

如果是 跟搜索框有关系，那么我又猜到一个可能性了。顺便问一下，在搜索的时候是否有用过 Ctrl + Space 切换过输入法？是否开启了用 Ctrl 作为单独的辅助键？

**Comment by yellowko** [comment]
我用的微软自带的输入法，通常是用win+space切换，在输入过程中并未使用ctrl，系统中和ctrl相关的有双击ctrl启动的Listary，关闭后并没有变化。目前我只在知网搜索时发现了这个问题，我试了试百度也没问题。

**Comment by lmk123** [comment]
我提交了 v7.5.2 的审核，麻烦大家更新或下载离线安装包试试看还有没有问题。

**Comment by killthatshaman** [comment]
更新7.5.2后已恢复正常访问Pixiv.
关于上面说的输入法问题,我一直都是使用Ctrl + Shift切换,但是我这边卡死问题的出现前并未使用过搜索,也没有切换过输入法,而是直接从收藏夹访问的网址.

**Comment by yellowko** [comment]
@lmk123 感谢，更新到7.5.2后可以正常使用知网搜索

**Comment by lmk123** [comment]
@killthatshaman @yellowko 太好了，感谢大家的测试

**Comment by lmk123** [comment]
v7.5.2 现在已上架 Chrome 扩展商店和 Firefox 扩展商店，Edge 商店正在审核中。由于没有再收到过类似反馈，所以我估计这个问题确实在 v7.5.2 中解决了，那么这个 issue 就先关闭了，如果还有类似问题，可以继续留言。
