### ISSUE TITLE
希望收藏夹中单词在不同浏览器的划词翻译插件中能同步

### ISSUE THREAD

**Issue by korrasamiiiii3** [lmk123/crx-selection-translate#917]
功能简介：
                 希望收藏夹中单词在不同浏览器的划词翻译插件中能同步

为什么你觉得需要（改进）这个功能？
                在不同浏览器登录同一个划词翻译会员账号之后，发现各自收藏夹中的内容是独立的，没有完全同步，划词翻译中所谓的同步功能也仅仅是在‘设置’上的同步而已，认为很有必要改进，将收藏夹中单词在不同浏览器的划词翻译插件中能同步

**Comment by lmk123** [comment]
我刚试了一下，你指的”没有完全同步“应该说的是划词翻译没有将你成为会员之前添加的收藏夹内容同步到服务器，只把你成为会员之后的数据同步到服务器了，是吧？

我会在下个版本中做一个改进：当你成为会员时，将浏览器内已有的数据也同步到服务器。

**Comment by korrasamiiiii3** [comment]
> 我刚试了一下，你指的”没有完全同步“应该说的是划词翻译没有将你成为会员之前添加的收藏夹内容同步到服务器，只把你成为会员之后的数据同步到服务器了，是吧？
> 
> 我会在下个版本中做一个改进：当你成为会员时，将浏览器内已有的数据也同步到服务器。

多谢，充了一年的会员才发现以前收藏的单词没有同步

**Comment by lmk123** [comment]
已在 v7.5.3 中做了改进。升级到 v7.5.3 之后，你只需要再添加一个收藏夹和产生一条历史记录，你之前的数据就会被上传上去了。
