### ISSUE TITLE
划词翻译翻译后自动复制翻译结果，关不掉

### ISSUE THREAD

**Issue by world0** [lmk123/crx-selection-translate#918]
## 基本信息
翻译后自动复制内容到剪贴板，在通用设置里面选不选自动复制选项都一样

划词翻译版本：划词翻译 v7.5.0
浏览器版本：Chrome 版本 88.0.4324.190 和Edge 版本 88.0.705.81 (官方内部版本) (64 位)
操作系统：Windows10

## 重现问题的步骤
和网站根目录下的i18n文件夹中。两个文件夹中的翻译
复制上面我随机复制的内容单击浏览器右上角的翻译扩展

### 实际行为
不管通用设置里面的`自动翻译`选中与否，都会在翻译后复制翻译结果到剪贴板
这种情况是开了会员后存在的，之前是正常的

**Comment by lmk123** [comment]
感谢反馈，确实会有这个问题，出现的原因是划词翻译把”自动朗读“和”自动复制“弄混了，你开启了自动朗读就相当于也开启了自动复制。

已在 v7.5.2 中修复。
