### ISSUE TITLE
划词发音失败

### ISSUE THREAD

**Issue by kirito269** [lmk123/crx-selection-translate#92]
点击发音之后没有声音发出

**Comment by lmk123** [comment]
能提供一下发音的文本、划词翻译版本、翻译时使用的翻译引擎吗？

**Comment by kirito269** [comment]
マイページ 划词之后点击朗读没有任何的反应

**Comment by kirito269** [comment]
使用的是谷歌翻译

**Comment by lmk123** [comment]
划词翻译 v6.0 使用了系统自带的语音朗读文本，看样子系统自带的语音功能不够完善。

我可能会重新将各个接口的语音朗读功能添加回来，并给出一个设置项，由用户自行选择是使用系统自带的语音还是网络语音。

**Comment by wujoke** [comment]
语音读不出声。

**Comment by lmk123** [comment]
Done. de01d57dfcab70f37962f537435e00f1ca429dfb
