### ISSUE TITLE
7.5.1版本,在打开Pixiv时出现页面未响应

### ISSUE THREAD

**Issue by killthatshaman** [lmk123/crx-selection-translate#920]
## 基本信息

划词翻译版本：7.5.1
浏览器版本：Chrome 71.0.3578.98 (正式版本) （64 位）
操作系统：Windows10 专业版

## 重现问题的步骤

1.打开Pixiv时出现页面未响应现象 链接https://www.pixiv.net/ 停用插件后恢复正常
同样7.5.1版本,该未响应现象在 `89.0.774.45 (官方内部版本) beta (64 位)` 的Microsoft Edge Beta中未出现,可以正常访问.

**Comment by lmk123** [comment]
未响应问题应该跟 #916 是同一个问题
