### ISSUE TITLE
希望能上架IOS APP STORE

### ISSUE THREAD

**Issue by korrasamiiiii3** [lmk123/crx-selection-translate#923]
## 功能简介
   1会员账号的收藏夹词库能够与iOS上划词翻译同步数据
   2打开ios划词翻译,即可实现跨软件翻译【虽然其他软件也能实现跨软件翻译，但效果都不行】
   3翻译源希望与PC插件中一样可供选择
## 为什么你觉得需要（改进）这个功能？
   希望能实现我在IPAD阅读英文文献的愿景

**Comment by lmk123** [comment]
划词翻译属于浏览器扩展程序，而扩展程序现在不支持安装在 iOS 或 Andorid 系统的浏览器里。
