### ISSUE TITLE
建议增加本地html翻译和支持插件

### ISSUE THREAD

**Issue by fengmao31** [lmk123/crx-selection-translate#924]
建议增加本地html支持，只要改一下适配设置就行。
希望能推出插件功能可以自由增加功能。

另外，感觉有点贵啊，我感觉年会员20，永久会员100左右价格差不多。或者截图翻译和单词本同步分离开来。成本主要也就是截图翻译了。

另外，我感觉看文献速度比知云差一点，可能是字体无法自定义原因，尤其matebook这种高分屏。

软件很好，我在ubuntu系统全靠它，感谢开发者。

**Comment by fengmao31** [comment]
可能是感官问题，我感觉字体大小和字体显示可以调整就好了。楼主可以自己试试知云和插件阅读pdf论文。这样能扩大用户群体。
我感觉这玩意比知云有前途的多。

**Comment by lmk123** [comment]
字体大小和字体显示是可以调整的，在“设置” - “通用设置” - “字体和按钮大小”

我来试试知云看看

**Comment by lmk123** [comment]
永久会员的价格我从 188 元下调到 98 元了

**Comment by fengmao31** [comment]
我感觉可以推出A会员仅有单词本同步，这样成本很低，可以卖出更多，细水长流。
B会员各种高级功能以满足高级需求。
老哥可以在少数派和Linux社区，deepin社区，小木虫科研那些网站宣传一下。
老哥这个是现在唯一Linux端好用的PDF阅读器。
羡慕老哥搞前端还能搞搞副业，计算机偏硬件废物现在工资好低啊，整个机器人行业不景气。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日 02:47:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lmk123/crx-selection-translate] 建议增加本地html翻译和支持插件 (#924)




 
永久会员的价格我从 188 元下调到 98 元了

**Comment by lmk123** [comment]
> 我感觉可以推出A会员仅有单词本同步，这样成本很低，可以卖出更多，细水长流。
> B会员各种高级功能以满足高级需求。

我自己就不喜欢百度网盘那种区分普通会员 / 超级会员的收费方式，所以也懒得搞这么复杂了。

> 老哥可以在少数派和Linux社区，deepin社区，小木虫科研那些网站宣传一下。
> 老哥这个是现在唯一Linux端好用的PDF阅读器。

感谢推荐，等我把计划中的功能实现之后确实打算去各个社区推广一下。

> 羡慕老哥搞前端还能搞搞副业，计算机偏硬件废物现在工资好低啊，整个机器人行业不景气。

我这个副业到现在是亏本的，而且亏了不少，还是别羡慕我了 :joy:

**Comment by fengmao31** [comment]
这个右边靠挂功能，不错，感觉比知云好。我以前没发现，不知道啥时候更新的，我收回我的建议。

我感觉现在开着Google，有道，deepl。但是deepl加载太慢。Google的音标是韦式音标，国内会的很少。
有道现在无音标，百度翻译因为太垃圾所以不用。

advice1
1.还是deepl加载速度有点欠缺。
2.关闭百度之后发现没有音标看了
所以还是感觉需要能嵌套一下有道词典或者欧陆词典，不过这样感觉太乱了。
有道翻译能不能搞出音标来，似乎查词api是有音标的，翻译api可能没有。

advice2
右边窗口边缘感觉还是突兀，是不是能圆润一下，什么的，过渡区域美工我也不懂。
是否能自由改变面板颜色，白色不如绿色，淡粉色，淡黄色，减弱刺眼，我很喜欢淡粉色，有人喜欢黑色和灰色
![image](https://user-images.githubusercontent.com/19343842/111179302-e7088680-85e6-11eb-9435-7c9d60affccd.png)
![image](https://user-images.githubusercontent.com/19343842/111181428-effa5780-85e8-11eb-87bb-ca87f693cb46.png)

PS：感觉我像个“万恶的”项目经理了，哈哈哈。老哥有空就搞，没空也无所谓了。
我改改缓存应该能diy一个改颜色然后分享在github上，同步那些应该还是需要购买你的会员。如果有问题我删掉，反正万一受损的是我的收藏夹，我还需要用它背单词。
![image](https://user-images.githubusercontent.com/19343842/111182834-461bca80-85ea-11eb-80a0-9d92e432a73c.png)

PS：我已经买了个终身会员支持老哥了。

**Comment by lmk123** [comment]
deepl 速度慢的问题我这边做不了什么，因为直接在浏览器里打开 https://www.deepl.com/translator 就是很慢的，不过你自己搭个梯子就会快了。

音标的问题，我打算加入[必应词典](https://cn.bing.com/dict/search?q=test)，这样应该可以替代有道翻译里的词典部分。

面板右侧不够“圆润”的问题其实我也注意到了，包括界面的配色这些其实也是可以改进的，我很早就开了 issue 打算改进（见 #772），不过最近基本在忙着加新功能，所以对于这类界面上的样式啥的就没太上心。近期新功能也加的差不多了，我打算开始处理这类界面改进了。

谢谢支持！
