### ISSUE TITLE
加载页面失败

### ISSUE THREAD

**Issue by lvsj** [lmk123/crx-selection-translate#925]
## 基本信息

划词翻译版本：v7.5.3
浏览器版本：89.0.4389.82
操作系统：Mac

## 重现问题的步骤

1. 设置打开方式为点击后加载；
2. 打开在线pdf文档，点击划词扩展程序图标
3. 确认重新加载

### 预期行为
页面成功加载
### 实际行为
加载失败，截图如下：
![image](https://user-images.githubusercontent.com/5672080/110748644-fd2ae580-827a-11eb-9382-8a4f527a6d88.png)

**Comment by lmk123** [comment]
麻烦把 pdf 的地址提供给我，我重现一下

**Comment by lvsj** [comment]
> 麻烦把 pdf 的地址提供给我，我重现一下
https://recision.files.wordpress.com/2010/12/jens-parsson-dying-of-money-24.pdf

**Comment by lmk123** [comment]
我在 macOS 的 Chrome 89.0.4389.82 中，使用划词翻译 v7.5.4 打开你提供的网址没有出现这个问题。由于我没能重现这个问题，我只能给出几点可能可以解决这个问题的方法：

- 可能由于网络不好加载失败了，一般过会儿就能正常打开了。
- 升级划词翻译到 v7.5.4  试试
- 卸载划词翻译再重新安装试试

如果以上几个方法都没能解决你的问题，你可以继续留言。

附截图：

![image](https://user-images.githubusercontent.com/5035625/111037402-bd245800-845e-11eb-925c-ae7a286746d0.png)

**Comment by lvsj** [comment]
卸载后重新安装后使用默认配置正常使用了
