### ISSUE TITLE
希望恢复谷歌翻译自主选择 .com 或 .cn 的选项

### ISSUE THREAD

**Issue by chengchengXu** [lmk123/crx-selection-translate#927]
## 功能简介

恢复谷歌翻译的访问域名自主选择

## 为什么你觉得需要（改进）这个功能？

我使用的是全局系统代理，无法使用 .cn 网站，需要关闭代理才能使用现在这个版本 7.5.4 的谷歌翻译

因为各家翻译都会有各自的问题，所以我需要看到两道三个翻译来确认具体含义；由于代理和插件突然钉死访问地址的方式很不友好，希望能恢复原来自主选择的方式

**Comment by lmk123** [comment]
重复 #865 

将在下个版本 v7.5.6 中重新添加这个选项。
