### ISSUE TITLE
希望能把单词音标也显示出来

### ISSUE THREAD

**Issue by HuirongWow** [lmk123/crx-selection-translate#932]
## 功能简介
比如某个单词，我在看到它具体意思的同时想知道它要如何读。具体的说我希望也可以展示出它的音标。
## 为什么你觉得需要（改进）这个功能？
目前虽然提供了朗读功能，但是有时在工位不方便打开朗读，如果有音标的话就知道我应该如何“称呼”它

**Comment by HuirongWow** [comment]
抱歉，刚刚尝试了下一个常用词汇发现是有音标的。我的案例是尝试翻译“ciphertext”的时候没有显示出音标而提出了Issue，对于这类不常用词汇能否也支持音标展示呢

**Comment by lmk123** [comment]
你应该是在使用百度翻译“ciphertext”的时候没有出现音标。百度翻译的英语词典支持的词汇较少，我会在最近几个版本中加入必应词典：https://cn.bing.com/dict/search?q=ciphertext

**Comment by LiangWeiCheng** [comment]
google源就不显示音标 尴尬
搞得我现在都是google 百度两个源一起使用

**Comment by lmk123** [comment]
@LiangWeiCheng 把百度换成必应词典吧，下个版本百度翻译就换成官方平台的接口了，到时候百度翻译就没有词典了。

我应该在划词翻译内发了公告的，你没看到的吗，不会是出 bug 了吧 :joy:
