### ISSUE TITLE
希望添加“在当前网站中启用”划词翻译选项

### ISSUE THREAD

**Issue by gwf559** [lmk123/crx-selection-translate#933]
## 功能简介
添加“在当前网站中启用”划词翻译选项
## 为什么你觉得需要（改进）这个功能？
因为划词不想所有网站中启用，只想在部分英文网站，浏览英文网站时，“当前页面选项”范围太小，老是要点，能添加“在当前网站中启用”划词翻译选项吗？

**Comment by lmk123** [comment]
好的，将会在下个版本 v7.5.6 中添加。

由于跟 #922 重复，你这个 issue 就先关闭了，后续进展可以关注 #922
