### ISSUE TITLE
期望划词翻译弹出框可以支持拖动改变弹框大小

### ISSUE THREAD

**Issue by CasualMing** [lmk123/crx-selection-translate#934]
## 功能简介
期望划词翻译弹出框可以支持拖动改变弹框大小

## 为什么你觉得需要（改进）这个功能？
当一次翻译很多的时候，划词翻译的弹框就显得有点小了。查看的时候，还得滚动查看，如果能支持用户自己扩拽改变宽度，那用户体验会更好一些

**Comment by lmk123** [comment]
划词翻译是支持拖动左右边缘调整宽度的，不过目前在出现滚动条的情况，右侧的边缘是不能拖动的（见 #913），但是你可以拖动左边缘

**Comment by GH01** [comment]
> 划词翻译是支持拖动左右边缘调整宽度的，不过目前在出现滚动条的情况，右侧的边缘是不能拖动的（见 #913），但是你可以拖动左边缘

这个其实还跟用户所选的弹窗方向相关：
箭头所在的那一侧是不能拖拽的。

当右侧是可拖状态（鼠标显示双箭头），但滚动条碍事时，可以拖拽 窗顶/底 的右侧。
