### ISSUE TITLE
复制翻译之后的内容，之后无法再进入输入

### ISSUE THREAD

**Issue by CasualMing** [lmk123/crx-selection-translate#935]
## 基本信息

划词翻译版本：v7.5.4
浏览器版本：谷歌浏览器   版本 89.0.4389.90
操作系统：win10

## 重现问题的步骤

1.  输入中文，弹出弹框，查看翻译之后的结果
2.  复制翻译之后的结果、到之后其他的地方粘贴
3.  这个时候 划词翻译 弹框没有消失，再准备输入数据，但是无法输入

### 预期行为
可以重新输入，重新翻译
### 实际行为
无法重新输入，只有点击划词翻译icon，重新加载，才能输入

**Comment by lmk123** [comment]
按照你提供的步骤，我没有重现你的问题，如下图：

![t](https://user-images.githubusercontent.com/5035625/111934576-a506a580-8afc-11eb-88c7-83e4e739fe40.gif)

**Comment by CasualMing** [comment]
> 按照你提供的步骤，我没有重现你的问题，如下图：
> 
> ![t](https://user-images.githubusercontent.com/5035625/111934576-a506a580-8afc-11eb-88c7-83e4e739fe40.gif)



不是点击复制按钮复制，是双击选择翻译之后的内容复制

**Comment by CasualMing** [comment]
> 按照你提供的步骤，我没有重现你的问题，如下图：
> 
> ![t](https://user-images.githubusercontent.com/5035625/111934576-a506a580-8afc-11eb-88c7-83e4e739fe40.gif)

![GIF](https://user-images.githubusercontent.com/40878104/111946143-e788ac00-8b15-11eb-904a-5ab129843800.gif)

**Comment by lmk123** [comment]
我知道是什么原因了。

当你切换回划词翻译的弹窗的时候，当前的焦点并不在划词翻译的文本框，所以即使你输入了内容，也不会显示在文本框中。也就是说，你切换回划词翻译的弹窗时需要先点击一下文本框，确保光标在文本框里面才可以输入文本进去。

**Comment by CasualMing** [comment]
> 我知道是什么原因了。
> 
> 当你切换回划词翻译的弹窗的时候，当前的焦点并不在划词翻译的文本框，所以即使你输入了内容，也不会显示在文本框中。也就是说，你切换回划词翻译的弹窗时需要先点击一下文本框，确保光标在文本框里面才可以输入文本进去。

不是没点击文本框。是点击了之后。光标无法在文本框内。也无法输入

**Comment by lmk123** [comment]
这个 issue 我先关了，有新的重现信息可以继续留言。
