### ISSUE TITLE
谷歌翻译的结果跟 translate.google.cn 的不一致

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#936]
## 基本信息

划词翻译版本：v7.5.5
浏览器版本：Chrome 89
操作系统：win10

## 重现问题的步骤

1. 使用划词翻译的谷歌翻译“Lattice dynamics and interatomic force constants”
2. 打开 https://translate.google.cn 翻译同样一句话

### 预期行为
翻译结果一致
### 实际行为
划词翻译显示的翻译结果是“格子动力学和外部部队力量常数”

https://translate.google.cn 的是“晶格动力学和原子间力常数”

**Comment by GH01** [comment]
好奇这是什么原因？

**Comment by lmk123** [comment]
@GH01 
> 好奇这是什么原因？

见[常见问题](https://hcfy.limingkai.cn/faq.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91%E9%87%8C%E6%98%BE%E7%A4%BA%E7%9A%84%E7%BF%BB%E8%AF%91%E7%BB%93%E6%9E%9C%E8%B7%9F%E7%BF%BB%E8%AF%91%E7%BD%91%E7%AB%99%E9%87%8C%E7%9A%84%E4%B8%8D%E4%B8%80%E6%A0%B7)
