### ISSUE TITLE
PDF文件进行划词翻译时，原文中的空格在弹出页面的文本框中不显示

### ISSUE THREAD

**Issue by wang12shuo** [lmk123/crx-selection-translate#938]
win10 Chrome 87 , 划词翻译7.5.2

1.打开一篇来自Elsevier的英文文献
2.使用划词翻译翻译任一原文有空格的长句

预期行为：弹出的翻译页面文本框和原文一致，存在空格
实际行为：划词翻译貌似不识别原文的空格，文本框中原本应该出现的句中空格不见了，影响二次编辑

**Comment by lmk123** [comment]
已知问题，详细解释见 https://github.com/lmk123/crx-selection-translate/issues/786#issuecomment-738022638
