### ISSUE TITLE
无法在jupyter lab中使用

### ISSUE THREAD

**Issue by gegehennb** [lmk123/crx-selection-translate#939]
您好，今天用jupyter lab调试python代码的时候，遇到了报错，就想划词翻译成中文看看，结果就提示："划词翻译内部发生了未知错误，请稍后重试。错误消息：Extension context invalidated."。没办法正常使用，希望您看看能不能解决一下，谢谢。

**Comment by lmk123** [comment]
这个错误是因为划词翻译自动更新了，刷新一下网页就可以恢复。
