### ISSUE TITLE
在朗读被翻译语言(非英语)朗读时错误

### ISSUE THREAD

**Issue by kirito269** [lmk123/crx-selection-translate#94]
类似 何卒よろしくお願い申し上げます 这一段文字会只朗读汉字而没有片假名的读音

**Comment by kirito269** [comment]
还有在朗读翻译之后的中文没有发音

**Comment by lmk123** [comment]
这个问题其实跟 #92 是同一个问题，原因都是因为系统自带的语音朗读功能不够强大。我会把朗读功能替换为以前的朗读方式的。
