### ISSUE TITLE
希望能加入词源辞典

### ISSUE THREAD

**Issue by AndrewXiongGe** [lmk123/crx-selection-translate#940]
## 功能简介
    类似https://www.quword.com/网站的功能....
## 为什么你觉得需要（改进）这个功能？
   个人来说好奇心比较强，查单词的时候常有追根究底的想法

**Comment by lmk123** [comment]
下一个版本 v7.5.7 添加了快捷链接的功能，可以自行配置要跳转的网址，例如如果你想用剑桥词典搜索划选的单词，那么就可以添加一个快捷链接 `https://dictionary.cambridge.org/dictionary/english-chinese-simplified/%s`。

**Comment by GH01** [comment]
该站的[英语词源]部分，看上去只是 购买(?)了 etymonline.com 的 旧?简版内容。

我倒是挺喜欢该站的这种形式，有这么多知名的第三方链接。
一枚加入浏览器，省了一堆搜索引擎项。
而且这样的信息量大的网站，更适合用作 快捷链接/搜索引擎，开页访问。

感谢分享，欢迎更多。
我在Discussions里加了个《分享 快捷链接/搜索引擎》。 #945
