### ISSUE TITLE
关闭按钮的边缘无法点击

### ISSUE THREAD

**Issue by sour-lemon** [lmk123/crx-selection-translate#941]
## 基本信息

划词翻译版本：v7.5.6
浏览器版本：FireFox 86.01
操作系统：Win10 20H2

## 重现问题的步骤

1.在任何页面进行划词翻译
2.点击翻译窗口的关闭按钮的边缘部分

### 预期行为
翻译窗口被关闭

### 实际行为
关闭按钮有动画，但悬浮窗没有被关闭

**Comment by lmk123** [comment]
感谢反馈，将在下个版本 v7.5.7 中修复。
