### ISSUE TITLE
Firefox 无法在 mozilla.org 中正常使用划词翻译

### ISSUE THREAD

**Issue by lomirus** [lmk123/crx-selection-translate#942]
浏览器： Firefox Developer Edition 88.0b3(64-bit)
系统：Windows 10 x64 19042.867
插件：7.5.6

在 https://support.mozilla.org/en-US/questions/1279094 页面中无法正常使用划词翻译，提示：
> 在浏览器的内置页面中，只能使用划词后在右键菜单中选择“翻译这段文本”的翻译方式。

但是显然该页面不算是内置页面，因为它在其他浏览器中也可正常访问。
附图如下：
![附图](https://ftp.bmp.ovh/imgs/2021/03/598e60183de94325.png)

**Comment by lmk123** [comment]
除了内置页面，各个浏览器的这类网址也是不让扩展访问的，比如在 Chrome 里不能在 https://chrome.google.com/webstore/ 里划词、在 Firefox 里不能在 https://addons.mozilla.org/zh-CN/firefox/ 里划词一样。这里只是为了简化了这一概念，只写了内置页面，没有把这种情况写出来。
