### ISSUE TITLE
没有注册 google API。

### ISSUE THREAD

**Issue by joy-yi0905** [lmk123/crx-selection-translate#95]
划词翻译时，面板显示 “没有注册 google API。”请问是什么情况啊？

**Comment by lmk123** [comment]
我自己使用的时候是完全正常的。能提供详细的重现步骤吗？

**Comment by lmk123** [comment]
你使用的是哪个版本的划词翻译？

我检查了一下，这条消息是在[这行代码](https://github.com/lmk123/translation.js/blob/master/lib/translation.js#L129)产生的。

当使用了划词翻译不支持的翻译接口时就会产生这条错误，从你的错误信息来看，划词翻译使用了名为 `google` 的翻译接口，但是在划词翻译中谷歌翻译的代号是 `Google`（首字母大写）。

我会检查一下代码的。

**Comment by lmk123** [comment]
我知道了。

划词翻译 v5.x 时，默认翻译接口使用的是小写形式的接口名，你将默认接口设成了谷歌，那么就会变成 `google`。

在升级到划词翻译 v6.0.0 时，这个设置会被继承，但是在 v6.0.0 中我将接口名称全都改为了首字母大写的形式，于是有了这个错误。

我会立刻修复这个 bug 的。

**Comment by lmk123** [comment]
我已经修复这个 bug 了。不过这个问题很好解决，你只需要在设置里重新选择一下默认的翻译接口就可以了。

**Comment by joy-yi0905** [comment]
好的，非常感谢啦！
