### ISSUE TITLE
希望不翻译指定页面

### ISSUE THREAD

**Issue by e-yi** [lmk123/crx-selection-translate#953]
## 功能简介
对用户指定的页面及下属页面不进行翻译

## 为什么你觉得需要（改进）这个功能？
我使用jupyter notebook进行开发，常常在运行代码时（快捷键ctrl+enter）弹出翻译。

希望达成的结果与 #363 有点像，不过更容易一点？功能类似adblock的“不在此网页上运行”。

**Comment by lmk123** [comment]
已有功能， 如下图：

![image](https://user-images.githubusercontent.com/5035625/113112900-4a77f280-923c-11eb-8f7e-4bef2ef11674.png)

**Comment by lmk123** [comment]
突然想起来你是因为快捷键触发的翻译，那么黑白名单加了也不行。

你应该是单独使用 Ctrl 作为辅助键盘，这样的话无论当前页面在不在黑名单里，跟 Ctrl 有关的快捷键（例如 Ctrl + C）都会触发翻译，建议你再加个 Alt 键作为辅助键
