### ISSUE TITLE
点不出来啊！！！

### ISSUE THREAD

**Issue by LiveTowardTheSea** [lmk123/crx-selection-translate#954]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.就是选择文字之后，无法出现那个翻译的按钮呢！
2.
3.

**Comment by lmk123** [comment]
你提供的信息太少了，我没法帮你排查问题，不过我猜你是不是勾选了设置页里的“禁用网页划词”选项了？

如果不是这样的话，把上面需要补充的信息都填清楚吧——划词翻译版本、浏览器版本、重现步骤（比如是在哪个网址划词后没有翻译按钮）

**Comment by LiveTowardTheSea** [comment]
你好，版本是7.5.9，浏览器版本是chrome&nbsp;89.0.4389.114（正式版本） （64 位）,浏览了MSRA的官网（https://www.microsoft.com/en-us/research/lab/microsoft-research-asia/），选中文字后并没有出现翻译按钮，是不是我得重新装一次呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmk123/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lmk123/crx-selection-translate] 点不出来啊！！！ (#954)





 
你提供的信息太少了，我没法帮你排查问题，不过我猜你是不是勾选了设置页里的“禁用网页划词”选项了？
 
如果不是这样的话，把上面需要补充的信息都填清楚吧——划词翻译版本、浏览器版本、重现步骤（比如是在哪个网址划词后没有翻译按钮）

**Comment by lmk123** [comment]
我在你提供的网址里是可以正常显示翻译按钮的，如图

![image](https://user-images.githubusercontent.com/5035625/113310180-8a250400-933a-11eb-91bf-31ba5460f9ec.png)

你可以试试卸载了重新安装。
