### ISSUE TITLE
划词中使用DeepL翻译时，翻译结果无法像谷歌或百度一样固定为中文，会随机变化

### ISSUE THREAD

**Issue by txdier** [lmk123/crx-selection-translate#955]
浏览器信息：
Microsoft Edge
版本 89.0.774.63 (官方内部版本) (64 位)

Google Chrome
版本 89.0.4389.90（正式版本） （64 位）

扩展版本：v7.5.9 v7.5.9

划词中使用DeepL翻译时，翻译结果无法像谷歌或百度一样固定为中文，会随机变化。手动修改过多次仍然会自动变化。
![image](https://user-images.githubusercontent.com/30993382/113273598-64363a00-930f-11eb-869d-de8cf18ef3e0.png)

**Comment by lmk123** [comment]
这是 deepl 自己的 bug，不是划词翻译的。你可以打开 https://www.deepl.com/translator 然后输入 comments，你就会发现 deepl 自己把它识别成法语了。
![image](https://user-images.githubusercontent.com/5035625/113310496-e25c0600-933a-11eb-8116-81911e76fbcf.png)

**Comment by lmk123** [comment]
如果你想要划词翻译固定识别成中文，可以点右上角的设置图标，将源语种由“自动判断”切换为“中文”

**Comment by txdier** [comment]
如果我没理解错，这个源语种不应该是选中的语种吗？箭头右边的才是翻译后的语种吧？翻译后的语种我一直都是设置的“中文”

**Comment by lmk123** [comment]
抱歉，是我的理解有误，我以为问题的关注点在翻译源的识别，但其实你的问题是翻译结果不是中文。

这确实是一个  bug。

**Comment by xiaopangju** [comment]
我也可以复现此bug：
浏览器信息：Firefox 87.0（32 bit）
扩展版本：7.5.11

**Comment by lmk123** [comment]
这个问题将在下个版本 v7.6.4 中修复。v7.6.4 大概会在 4 月 29 日前发布，如果更新到 v7.6.4 之后还是有问题，欢迎继续反馈。
