### ISSUE TITLE
自定义面板样式：应能在 提示文 基础上编辑

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#956]
## 功能简介
自定义面板样式：应能在 提示文 基础上编辑。

## 为什么你觉得需要（改进）这个功能？
目前状态：
▲输入时，提示文 被清空。
▲提示文 无法被 全选/复制。
太不方便。

**Comment by lmk123** [comment]
@GH01 你有开通永久会员吗？没有的话我想赠送给你一个永久会员，你一直以来都很支持划词翻译，我想用这种方式向你表示感谢。

**Comment by GH01** [comment]
wow，非常感谢！
惭愧，我连会员都不是…… :sweat_smile: 

我会继续反馈（其实是仅限于自己所涉范围），
不过也可能会见异思迁…… :joy:

**Comment by lmk123** [comment]
你先注册一个账号。点击设置页的登陆，然后点击【会员服务】，然后点击【开通会员】，在第一步注册好账号之后不要进入下一步，然后你把你的邮箱告诉我，我给你配一个永久会员

**Comment by GH01** [comment]
已发至你的me@l...邮箱，谢谢。

**Comment by lmk123** [comment]
好了，你退出账号之后重新登录试试
