### ISSUE TITLE
DeePL会重复显示翻译结果

### ISSUE THREAD

**Issue by mochen91** [lmk123/crx-selection-translate#957]
## 基本信息

划词翻译版本：7.5.10
浏览器版本：Chrome 89.0.4389.114
操作系统：Windows  10

## 重现问题的步骤

1.ctrl+划词 选择deepl 直接显示

**Comment by lmk123** [comment]
你说的重复显示是指这样吗？

![image](https://user-images.githubusercontent.com/5035625/113439496-4bb44580-941d-11eb-9722-0dcfccc2bcea.png)

这是因为 DeepL 提供了多个翻译结果，你可以在 https://deepl.com 里翻译“你好”，会看到下面有“其它翻译结果”这一区域

![image](https://user-images.githubusercontent.com/5035625/113439536-5cfd5200-941d-11eb-932e-30e5df879533.png)

这一块区域的结果我也显示出来了，所以看上去就像是“重复显示”了一样，但我觉得这有助于用户判断哪个翻译更准确。

**Comment by mochen91** [comment]
嗯 ，就是这个，原来如此。没注意到这点，抱歉！ 不过这样直接输出感觉不好，不如也加一个其他翻译结果以便区分。

mingkaili ***@***.***> 于2021年4月3日周六 上午1:39写道：

**Comment by lmk123** [comment]
好的，我会在以后的版本进行改进。

**Comment by GH01** [comment]
这种重复貌似只在查询单词/短语时发生，
我个人迄今尚未观察到有价值的译文。

如果保留，除了用“其他”区分，更希望 分行显示。

**Comment by lmk123** [comment]
将在 v8.4.1 中分行显示 DeepL 的“其它翻译结果”
