### ISSUE TITLE
网页翻译无法翻译youtube相关的页面

### ISSUE THREAD

**Issue by Mjhhh** [lmk123/crx-selection-translate#959]
## 功能简介
网页翻译功能实测不能翻译youtube的页面，当前版本v7.5.12
## 为什么你觉得需要（改进）这个功能？
日常使用youtube较为频繁，所以希望有类似google translation插件那样可以翻译youtube页面的功能

**Comment by lmk123** [comment]
即将发布的 v8.5.0 使用了全新的网页文本识别算法，已确认可以正常翻译 Youtube 页面（特别是评论区）。
