### ISSUE TITLE
麻烦添加一个功能双击鼠标选词翻译

### ISSUE THREAD

**Issue by ld1289551942** [lmk123/crx-selection-translate#960]
看英文pdf文件，用鼠标去划词，没有单词翻译很难受，划线翻译适合长句子，单个词不认识去划线会很烦。其他功能做得挺好。congratulation.真的很赞，这各插件知道谷歌浏览器自带的pdf会出bug，设置了一个拖文件的方式解决了这个问题，不过我还发现了两个可以改进的，就是按F11全屏看pdf文件的时候可不可以把最顶部上面一排功能键遮掉？还有要是可以设置pdf在谷歌网页的位置就好了，因为看英文pdf翻译出来的图标会挡住英文。能做到这些功能我觉得你可以垄断这个pdf翻译功能了。彩云小译目前不可以翻译pdf。如果真的我的建议有效，可不可以给个会员hah...

**Comment by lmk123** [comment]
我猜你说的“双击鼠标选词翻译”是指双击鼠标之后，立刻翻译选中的单词吧？这个功能是有的，你只要把翻译弹窗切换为固定模式，那么你在网页中双击一个单词就会立刻显示翻译结果。点击翻译弹窗左上角的图钉按钮可以切换为固定模式。

> 按F11全屏看pdf文件的时候可不可以把最顶部上面一排功能键遮掉？

这个我会考虑添加的

> 要是可以设置pdf在谷歌网页的位置就好了，因为看英文pdf翻译出来的图标会挡住英文。

你指的是调整翻译按钮出现的位置吗？比如将翻译按钮改为显示在鼠标右上角，避免挡住下方的文本？

或者你指的是调整翻译弹窗显示的位置？翻译弹窗显示的位置是可以调整的，默认向下显示，但也可以调整为上、左、右显示；又或者，你可以把翻译弹窗切换为固定模式，把它固定在角落里，也可以避免遮挡文件内容。

> 如果真的我的建议有效，可不可以给个会员hah...

如果你可以像[这个人](https://github.com/lmk123/crx-selection-translate/issues?q=is%3Aissue+author%3AGH01)一样持续给划词翻译提出建设性的建议，我会免费赠送给你永久会员。

**Comment by lmk123** [comment]
F11 隐藏工具栏已另开 issue https://github.com/lmk123/crx-selection-translate/issues/979

这个我就先关闭了
