### ISSUE TITLE
自动朗读功能改进 - 在显示翻译窗口时，即使跟上一次划选的文本相同也应该自动朗读

### ISSUE THREAD

**Issue by hayesLhy** [lmk123/crx-selection-translate#961]
## 功能简介
在用户选择了单个、或者一定字数以下的词语时，如日语 可以在文本框中显示其假名读法，英语则可考虑显示音标等等。

## 为什么你觉得需要（改进）这个功能？
很多情况下我选择一个词语也是想确认其读音，当前版本选中后会朗读但是只有一次，（未固定插件窗口自动退出后）再次选中同一词便不会自动朗读了。
希望能在新版本考虑改动，感谢。

**Comment by lmk123** [comment]
英语单词是否显示音标要看你使用的翻译源是否提供。

目前支持显示英语单词的翻译源有必应词典、官方版本有道词典和搜狗翻译；支持显示日语假名读法的只有搜狗翻译。你只要选择这些翻译源就能看到音标了。

> 很多情况下我选择一个词语也是想确认其读音，当前版本选中后会朗读但是只有一次，（未固定插件窗口自动退出后）再次选中同一词便不会自动朗读了。

现在确实有这个情况，不过我可以做一个改进，就是在这种情况也进行自动朗读，这样是不是也能解决你的问题？

**Comment by hayesLhy** [comment]
> 英语单词是否显示音标要看你使用的翻译源是否提供。
> 
> 目前支持显示英语单词的翻译源有必应词典、官方版本有道词典和搜狗翻译；支持显示日语假名读法的只有搜狗翻译。你只要选择这些翻译源就能看到音标了。
> 
> > 很多情况下我选择一个词语也是想确认其读音，当前版本选中后会朗读但是只有一次，（未固定插件窗口自动退出后）再次选中同一词便不会自动朗读了。
> 
> 现在确实有这个情况，不过我可以做一个改进，就是在这种情况也进行自动朗读，这样是不是也能解决你的问题？

好快的回复！十分感谢。是的基本就能解决问题了。后续会继续支持

**Comment by lmk123** [comment]
> 好快的回复！

因为我喜欢半夜写代码 :joy:

**Comment by GH01** [comment]
Google(网页版)对日文有罗马注音，能否获取？

**Comment by lmk123** [comment]
可，我开了个工单 #968 来跟进谷歌翻译的改进
