### ISSUE TITLE
截图翻译需要增加入口

### ISSUE THREAD

**Issue by buaachendong** [lmk123/crx-selection-translate#963]
## 功能简介
增加截图翻译的入口，比如在菜单栏，独立翻译窗口或右键菜单中增加入口。
## 为什么你觉得需要（改进）这个功能？
现在的入口只存在于选择文字之后的弹窗中，有些页面（比如整张页面都是不可选的）无法选择文字，因此这个功能无法触发。

**Comment by lmk123** [comment]
我给截图翻译加个右键菜单的入口吧。

另外，截图翻译是可以加快捷键的，但似乎很多用户都不知道，我再加个提示。

**Comment by lmk123** [comment]
同理，网页翻译也需要再右键菜单加入口 + 快捷键提示
