### ISSUE TITLE
google翻译效果比线上差

### ISSUE THREAD

**Issue by Xiaoxiong-Liu** [lmk123/crx-selection-translate#965]
## 基本信息
google翻译出来的结果很差，与translate.google.com和translate.google.cn对比后，结果不一样（差）。
划词翻译版本：v7.5.15
浏览器版本：版本 89.0.4389.90（正式版本） （64 位）
操作系统：Windows 10

## 重现问题的步骤

1. 在pdf中，A potential problem is that some of this information, will have little or no predictive value, that is nodiagnosticity.被翻译为：潜在的问题是一些这些信息，几乎没有预测价值，即结核病。
2. 在网页上翻译结果为：一个潜在的问题是，这些信息中的某些信息几乎没有或没有预测价值，即没有诊断价值。
3. 显然网页版效果好很多。

## 划词翻译：
![image](https://user-images.githubusercontent.com/17966083/113848787-672ba180-97cb-11eb-998e-580a06ca5b8f.png)

## 网页版
![image](https://user-images.githubusercontent.com/17966083/113848861-7ad70800-97cb-11eb-8c9c-e7fafa5125ce.png)

**Comment by Xiaoxiong-Liu** [comment]
很奇怪，关掉划词的google翻译重新点开就好了。
ps 之前不是一句话比较差，是整体翻译结果都比较差。

**Comment by lmk123** [comment]
这个问题在[常见问题](https://hcfy.limingkai.cn/faq.html)里有说明：

![image](https://user-images.githubusercontent.com/5035625/113870781-c944d080-97e4-11eb-9eaa-24cf35f504e3.png)

比如我现在翻译的结果跟网页版就是一样的：

![image](https://user-images.githubusercontent.com/5035625/113870667-a9151180-97e4-11eb-9d00-8fce31ad5c22.png)

但谷歌翻译使用一段时间之后，“准确版”的接口就不让用了，此时会使用备用的谷歌翻译接口。一般过了半小时之后，"准确版"的谷歌翻译就又可以用了，或者你也可以切换你的 IP 地址来突破准确版的频率限制。
