### ISSUE TITLE
谷歌翻译结果跟网页版谷歌翻译不一致

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#968]
## 基本信息

划词翻译版本：v7.5.15
浏览器版本：Chrome 89
操作系统：win 10

## 重现问题的步骤

1.  连续使用谷歌翻译超过半小时之后，会发现谷歌翻译的结果跟网页版不一样，比如 #965

## 原因

谷歌翻译使用了两个接口，第一个接口的翻译结果是准确的，但会在连续使用半小时之后报超出使用频率的错误，需要等待半小时才会恢复；此时，划词翻译会用第二个接口获取结果，但这个接口的结果跟网页版是不一样的。

**Comment by lmk123** [comment]
顺便加个日文罗马音 https://github.com/lmk123/crx-selection-translate/issues/961#issuecomment-814943142

**Comment by imba-tjd** [comment]
作者你好，方便分享该接口超出使用频率后的现象是什么吗？（我指的不是通过本项目，而是直接使用该接口）

**Comment by lmk123** [comment]
> 方便分享该接口超出使用频率后的现象是什么吗？

现象是接口会返回 HTTP 429 响应码

> 第二个接口”指的是client=webapp吗

是
