### ISSUE TITLE
打开无痕模式窗口后，账号就会掉线，需要重新登录

### ISSUE THREAD

**Issue by DesistDaydream** [lmk123/crx-selection-translate#969]
经检查是因为无痕模式的关系。重现步骤如下：

1. 给划词翻译开启【在无痕模式下启用】的选项，然后登陆划词翻译
2. 打开一个无痕模式的窗口

然后就会发现无痕模式窗口中的划词翻译掉线了，回到普通窗口就会发现普通窗口里的划词翻译也掉线了。

以下是原内容
--------------------------------

## 基本信息

划词翻译版本：v7.5.15
浏览器版本：Chronme 88.0.4324.104
操作系统：Windows10

## 重现问题的步骤

1.关闭浏览器
2.打开浏览器
3.查看设置页面，发现已经变成未登录状态

### 预期行为
希望可以持久化保持登录状态，这样，不用每次都要重新登录以便配置会员信息。。。。还好可以同步设置~~~~~

### 实际行为
每次关闭浏览器再开之后，就自动登出了

**Comment by lmk123** [comment]
这就奇怪了，我试了下没有出现这个问题，然后我又把划词翻译卸载了重新安装试了下也没出现这个问题。

等我有空了我试一下把 Chrome 卸载了重新安装、再重新安装划词翻译看看会不会重现你的问题。

**Comment by DesistDaydream** [comment]
我描述有问题。。。实在抱歉。。。让你白试了这么多次。。。准确说应该是关机之后再开机，就自动登出了

**Comment by lmk123** [comment]
这应该是划词翻译服务器的一个 bug，我昨晚修复了，你再试试关机再开机还会不会自动登出

**Comment by DesistDaydream** [comment]
非常感谢！今天再次开机发现已经可以自动登录了~

**Comment by DesistDaydream** [comment]
还是不行。。。。。我昨天在单位登陆完，回家没看有没有效果。。。今天再在单位用。。。就又自动等处了。。。。

**Comment by lmk123** [comment]
你的账号是多少？如果你不方便在这里公开，可以在公众号内私信发我

**Comment by DesistDaydream** [comment]
发过去了~17点11分的消息~~~今天还有个奇葩现象。。。就是会员信息老自己掉。。。。。浏览器也没关。。。我后来试了一下，好像是一开无痕。。。会员就掉了。。。。

**Comment by lmk123** [comment]
破案了，就是无痕模式引起的……确实是一开无痕模式就会掉线，我看看怎么解决
