### ISSUE TITLE
Edge 语音切换的问题

### ISSUE THREAD

**Issue by 0netouch** [lmk123/crx-selection-translate#971]
## 基本信息

划词翻译版本： v7.5.15
浏览器版本： edge 89.0.774.75 
操作系统：win10

## 重现问题的步骤

1.始终使用系统语音朗读
2.将中文 英语语音设置为男声的 kangkang 和 gorgeo
3.尝试朗读

### 预期行为
中文和英语变为男声阅读
### 实际行为
依旧是女声 日文可以正常运行（同时想知道chrome为啥不能选男声）

**Comment by lmk123** [comment]
我的 Edge 里没有 Gorgeo 这个语音，所以我只尝试了 Kangkang 这个语音，但是这个语音本身就是女声。

我打开了 https://hcfy.limingkai.cn/ 然后按下 Ctrl + Shift + U 打开 Edge 的【大声朗读】功能，并在语音选项里选择 Kangkang 这个语音，我听到的声音就是女声，这个声音跟我在划词翻译里选择的 Kangkang 声音是一样的。

如果是我重现步骤有误，你可以继续留言。

> 同时想知道chrome为啥不能选男声

划词翻译里可以选择的语音都是由浏览器提供给划词翻译的，而 Chrome 提供给划词翻译的就这么几种语音。

**Comment by 0netouch** [comment]
![image](https://user-images.githubusercontent.com/82279457/114343531-a7569f80-9b90-11eb-97b0-b81bcd39cad7.png)
![image](https://user-images.githubusercontent.com/82279457/114343550-ae7dad80-9b90-11eb-847a-463a1eb7b6a7.png)
我用来对比的是系统自带的kangkang的语音模块
![image](https://user-images.githubusercontent.com/82279457/114343615-d1a85d00-9b90-11eb-86b9-408e54c8ca9d.png)
有geogio的原因大概是我下载了多个语种的系统语言？
![image](https://user-images.githubusercontent.com/82279457/114343638-e553c380-9b90-11eb-9efa-43cf585ccadf.png)

**Comment by lmk123** [comment]
> 我用来对比的是系统自带的kangkang的语音模块

还真是，我在这里听到的是男声。但是 Edge 浏览器里的 Kangkang 是女声，我再确认一下是怎么回事

> 有geogio的原因大概是我下载了多个语种的系统语言？

是的，你的 Geogio 语音标注的是本地语音，说明是你下载的

**Comment by lmk123** [comment]
大概确认了这是 Edge 浏览器的 bug，见 https://answers.microsoft.com/zh-hans/edge/forum/edge_other-edge_win10/%E6%88%91%E7%9A%84edge%E6%B5%8F%E8%A7%88%E5%99%A8/9c0332d5-7c7b-4ad8-b5f1-d2f1a1b0b96f
