### ISSUE TITLE
提供选项，以禁用选中文本框中的文本时，不触发翻译

### ISSUE THREAD

**Issue by eforlina** [lmk123/crx-selection-translate#973]
## 功能简介
请提供一个开关，以便在开启划词立即显示翻译结果时，当选中的文本位于文本框中时，不触发翻译
## 为什么你觉得需要（改进）这个功能？
经常会需要在文本框中编辑文字，修改搜索关键词等操作，而此时的意图往往不会是翻译。
此时弹出翻译结果，大概率是一种打扰。

**Comment by lmk123** [comment]
v7.6.0 在划词设置里添加了“在文本框中不触发翻译”的选项
