### ISSUE TITLE
新的pdf界面没有夜间模式以及无法翻译部分pdf

### ISSUE THREAD

**Issue by fengmao31** [lmk123/crx-selection-translate#975]
背景颜色
新的pdf没有夜间mo's模式，太刺眼了，不如以前黑色
或者当然能增加粉色，绿色背景更好了。希望能支持插件化。

部分导出pdf无法翻译
可能更新之前老版本能翻译，我不确定这个了。
![image](https://user-images.githubusercontent.com/19343842/114372910-a5063c80-9bb4-11eb-987a-451d8afd241b.png)
![image](https://user-images.githubusercontent.com/19343842/114373323-0d551e00-9bb5-11eb-9415-6d61974b60ab.png)
[Topic 4 Time management.pdf](https://github.com/lmk123/crx-selection-translate/files/6295513/Topic.4.Time.management.pdf)

**Comment by lmk123** [comment]
新版本的 pdf 有夜间模式的，但是它是固定根据你操作系统来的，没法设置，也就是说你要把操作系统设置成深色模式，这个 pdf 阅读器才是深色背景。

独立翻译窗口变白这个问题跟 pdf 阅读器没关系，这是独立翻译窗口的 bug。能提供一下你的浏览器版本、划词翻译版本和使用的操作系统么

**Comment by fengmao31** [comment]
# 1
没法增加此功能吗，没有之前的默认深色模式太难受了。瞎眼。
# 2
设置页面深色模式颜色怪异。
![image](https://user-images.githubusercontent.com/19343842/114444612-aa3da880-9c01-11eb-9e26-d583d6eff0e1.png)
# 3
这个pdf的问题，划词翻译小图标经常不显示，而且点击小图标无反应。独立翻译窗口发白。老哥下载试一试。之前版本应该可以。因为同一个老师上学期的ppt可以用划词翻译，ubuntu20也可以正常使用。

![image](https://user-images.githubusercontent.com/19343842/114445040-289a4a80-9c02-11eb-9135-9c56e46e72d5.png)

系统环境
![image](https://user-images.githubusercontent.com/19343842/114445215-67c89b80-9c02-11eb-9f5b-1618c7d5023e.png)
![image](https://user-images.githubusercontent.com/19343842/114445267-757e2100-9c02-11eb-9b33-950ed84659a7.png)
![image](https://user-images.githubusercontent.com/19343842/114445293-7ca52f00-9c02-11eb-8d70-3a98395b64e4.png)

**Comment by lmk123** [comment]
> 1 没法增加此功能吗，没有之前的默认深色模式太难受了。瞎眼。

这个我再试试看可不可以默认深色模式

> 2 设置页面深色模式颜色怪异。

我看了下你的截图，看着挺正常的啊 😂 

> 3 这个pdf的问题，划词翻译小图标经常不显示，而且点击小图标无反应。独立翻译窗口发白。

我下载了你的 pdf 试过了，但是没有重现你的问题，我的图标能正常显示、点击能弹出翻译、独立窗口也没有发白。

我会在 v7.6.1 版本的时候再更新一次内置的 PDF 阅读器的版本，到时候你可以再看看有没图标经常不显示，而且点击小图标无反应的问题；独立窗口发白的问题，你可以试试拖动一下独立窗口，应该就能显示内容，具体发白的原因我再看看

**Comment by lmk123** [comment]
v7.6.1 已经让内置 pdf 的深色模式跟随划词翻译的设置而不是操作系统的设置了。

**Comment by fengmao31** [comment]
pdf阅读依然不起效。
![image](https://user-images.githubusercontent.com/19343842/114883576-a2674980-9e37-11eb-8afc-a5b1425acb3d.png)
你看这是以前
![image](https://user-images.githubusercontent.com/19343842/114884202-291c2680-9e38-11eb-800d-dad53d399200.png)




这次新加的同步变成深色的是翻译小窗口，那个还是白色或者其他颜色好看，没必要跟随选项界面。

而且那个深色太阴森了，不是黑色，感觉有点墨黑。

**Comment by fengmao31** [comment]
希望能够pdf阅读黑底，翻译面板白底，和以前一样就好。

**Comment by lmk123** [comment]
v7.6.1 我还没有发布，你用的应该还是 v7.6.0 的

**Comment by lmk123** [comment]
v7.6.1 我己经发布上去了，你可以看看还有没有你说的这些问题，有的话欢迎继续反馈

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/115209275-063b8c00-a130-11eb-94f0-213db78db908.png)
![image](https://user-images.githubusercontent.com/19343842/115209795-84982e00-a130-11eb-983b-e406f7848558.png)
颜色和以前不对。这个颜色辣眼睛。

划词面板希望是白色的，不跟随背景。独立开来。以前也是白色的板，背景黑色。
感觉背景板和划词板可以做成vip多种颜色

字体大小调节希望快捷设置里面可以调节。

有道翻译希望vip能给一定每月免费配额。

**Comment by lmk123** [comment]
> 颜色和以前不对。这个颜色辣眼睛。

内置 pdf 用的是第三方的 pdf 阅读器，这次我升级了它的版本之后，它确实调整了配色，但是我不打算改这个配色了，因为每次升级它都可能会改代码， 如果我修改它的代码，以后每次给它更新版本都要保持同样的颜色就会很痛苦了。

> 以前也是白色的板，背景黑色。

那是因为以前是固定黑色背景， 而这次我改成了跟划词翻译的深色模式保持一致。我会在下个版本调整一下，让划词翻译和pdf 的深色模式分开配置。

> 感觉背景板和划词板可以做成vip多种颜色

是有这个打算，但我自己本人没什么设计细胞，设计不出好看的配色。。。

> 字体大小调节希望快捷设置里面可以调节。

可，会在新版本安排

> 有道翻译希望vip能给一定每月免费配额。

vip 和字符数配额的事情确实在考虑中，但是一时半会儿不会改，因为比较“麻烦”。

我单独在 #993 里解释了为什么我将会员和翻译服务分开了，如果你感兴趣的话可以看一看，也可以提出你的想法。
