### ISSUE TITLE
关于[快捷选项]的建议

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#976]
1：觉得有必要将[自动读取剪贴板]放入[快捷选项]（@扩展按钮弹窗 @独立窗口）。

2：觉得把以下选项做成工具栏按钮更好：
▲自动朗读
▲自动复制
▲鼠标悬浮取词（叫“悬停”更准确）
▲显示文本框（@网页浮窗）
▲自动读取剪贴板（@扩展按钮弹窗 @独立窗口）
网页浮窗的拖移抓手 只需一两个按钮的面积就够了。

几个小毛病：
▲各窗为空时，收藏按钮☆应失活，否则点了会添加一条空白收藏。
▲此栏在 扩展按钮弹窗/独立窗口 中不应有“按住不放可以拖动”提示。
▲在独立窗口中点击[打开完整设置]，会在独立窗口中打开。

不好意思，思路下来就写成总结了，麻烦你自己拆分吧……

**Comment by lmk123** [comment]
> 觉得有必要将[自动读取剪贴板]放入[快捷选项]

确实有必要

> 觉得把以下选项做成工具栏按钮更好

不行……这不是抓手面积够不够的问题，而是如果按钮多了，密密麻麻的我感觉用户看了会觉得不够简洁

> 几个小毛病

我会在下个版本中修复这些小毛病

**Comment by lmk123** [comment]
> 在独立窗口中点击[打开完整设置]，会在独立窗口中打开。

这一点我在 chrome 89 里没有重现，我的是可以在正常的窗口里打开的

**Comment by GH01** [comment]
我会觉得 整齐的按钮 比 参差的选项 简洁。+更方便。

我想更好的解决方案是让用户能自定义工具栏按钮的显隐，爱多则多。

**Comment by GH01** [comment]
> > 在独立窗口中点击[打开完整设置]，会在独立窗口中打开。
>
> 这一点我在 chrome 89 里没有重现，我的是可以在正常的窗口里打开的

独立窗口 用的是不是Chromium某种特殊形式的窗体？
而Vivaldi支持尚不完善，导致如此？

这让我想到另一个问题：
在Vivaldi中，独立窗口不能记住 大小/位置。

这些方面，你这边有没办法改进？

**Comment by lmk123** [comment]
> 独立窗口 用的是不是Chromium某种特殊形式的窗体？
而Vivaldi支持尚不完善，导致如此？

我估计是的。独立窗口其实也是窗口的一种，只是它隐藏了地址栏、标签栏这类东西。

> 在Vivaldi中，独立窗口不能记住 大小/位置。

可以改进，我可以在你关闭窗口的时候保存大小和位置

**Comment by lmk123** [comment]
> 在Vivaldi中，独立窗口不能记住 大小/位置。

已新开 issue #986
