### ISSUE TITLE
建议：设置中的[使用方式]与[快捷键]可以合并

### ISSUE THREAD

**Issue by GH01** [lmk123/crx-selection-translate#977]
## 为什么你觉得需要（改进）这个功能？
[使用方式]几乎包含了[快捷键]的全部内容，合并可以减少总长。
[快捷键]版块的清晰形式 应该体现在[使用方式]中。

**Comment by lmk123** [comment]
我打算在文档站里写一块使用说明，然后用链接的形式将【使用方式】指向文档站，快捷键的说明也是

**Comment by GH01** [comment]
7.6.6
目前这样也不错，[快捷键]部分看起来很清晰。

则建议：
[使用方式]中的[辅助键]部分也可以省掉，
[使用方式]中的[辅助键] [快捷键]改为链接形式，可以点击直达。

**Comment by lmk123** [comment]
在 v8.7.0 中我将设置页改版了，现在没有“使用方式”这一块了，而是把快捷键放在了首页最顶部、把辅助键也放在了“网页划词翻译”选项页的最顶部
