### ISSUE TITLE
提供一个将繁体字一律看作日文的选项

### ISSUE THREAD

**Issue by 0netouch** [lmk123/crx-selection-translate#978]
## 为什么你觉得需要（改进）这个功能？
一个比较鸡肋的功能建议 毕竟手动切换成日语转中文就没有这种误差了
![image](https://user-images.githubusercontent.com/82279457/114462890-4671aa80-9c16-11eb-8982-3598eb4990bc.png)
这种类型的翻译还挺常出现的 如果可以实现的话可以听到原文繁体字的发音 偶尔会出现翻译成和原文一样的日文的情况 
![image](https://user-images.githubusercontent.com/82279457/114463326-ddd6fd80-9c16-11eb-8279-00bf2d66c693.png)
如果将主要语言设置为繁体就可能会出现少字的情况（虽然一般都会读 但是反向翻译偶尔会不那么准确）

**Comment by lmk123** [comment]
你需要这个选项的根本原因，是因为有道翻译和腾讯翻译君会把日文识别成繁体中文，所以你希望如果它们识别成繁体中文的时候，就当作日文进行翻译对吗？

如果是这样的话，那这个选项还真不好加，首先感觉不是对大部分用户都通用的选项，其次如果源语种判断有误，推荐做法是切换源语种；最后，加了这个选项还得额外加一个选项比如这个转换对哪些翻译源才生效

**Comment by lmk123** [comment]
又或者说，你是想听到日文的繁体中文读音才想要这个选项的？

如果是这样的话，我感觉还是不太通用，毕竟一般情况下，看到日文是会想听日文读音的

**Comment by lmk123** [comment]
按照以上两种想法，我可能不会加这个功能，但如果我理解有误，你可以继续留言表达你的想法。
