### ISSUE TITLE
可以出一个Safari版的吗

### ISSUE THREAD

**Issue by polin-x** [lmk123/crx-selection-translate#980]
## 为什么你觉得需要（改进）这个功能？
现有版本的太难用了 ==》》》现有的Safari的翻译的插件

**Comment by lmk123** [comment]
这个标题和你的理由似乎有点不相关。。

出个 safari 版的话，我也是把现有版本移植过去，所以如果你觉得现有版本太难用了，那我移植到 safari 你还是会觉得难用。

你能告诉我具体难用在什么地方吗？我可以逐个改进。

**Comment by polin-x** [comment]
一直在使用Safari浏览器，chrome转Safari了；完整的迁移比较难的话，希望大佬能迁移个基础版本的，比如可以同时有两三个翻译接口的，能有读音就挺好了

**Comment by polin-x** [comment]
不好意思，才反应过来，我的理由哪里说的“现有版本太难用了” --我想表达的意思是Safari上现有的插件太难用了。我也是划词翻译的老用户了，用了两年了。还像好多同学推荐过，只有感恩，没有其他的意思，不好意思

**Comment by lmk123** [comment]
哈哈没关系，同时也谢谢你帮忙推荐划词翻译。

Safari 版本的划词翻译是有打算做的，我其实很早就看过了（见 #812），不过看下来 safari 的浏览器扩展比较麻烦（需要注册开发者账号、需要对现有版本做兼容等等），再加上目前的优先级主要是在加新功能、改 bug，所以估计等这一段时间的功能稳定了，我就会开始着手开发 Safari 版的划词翻译。等 Safari 版本上架时，我会发送通知。

由于跟 #812 重复，这个 issue 我就先关闭了，后续进展更新到 #812
