### ISSUE TITLE
使用购买的积分之后，百度翻译结果较之前更简陋

### ISSUE THREAD

**Issue by amchii** [lmk123/crx-selection-translate#981]
## 功能简介
![image](https://user-images.githubusercontent.com/26922464/114502698-c7549480-9c5e-11eb-88ce-4a2c3fadf352.png)
之前是类似有道翻译的结果

**Comment by lmk123** [comment]
从 v7.6.0 开始，百度翻译没有用以前的网页版接口了，而是换用了官方接口，无论你用的是积分、还是自行申请的密钥，它的翻译结果都“简陋”了，这一点我很早就发了公告，具体公告内容见 https://hcfy.limingkai.cn/notices/use-official-api.html

其中关于有道翻译和百度翻译的变化公告中也有提及

![image](https://user-images.githubusercontent.com/5035625/114508084-8fe9e600-9c66-11eb-828d-8b27e4799fc3.png)

**Comment by lmk123** [comment]
不过我比较好奇的是，这个公告应该是在划词翻译的设置页、扩展图标上以及扩展弹窗有显目提示的，但是似乎还是有部分用户没看到，你能看到这个公告吗？如果没有，估计是公告系统出了问题。。

**Comment by amchii** [comment]
> 不过我比较好奇的是，这个公告应该是在划词翻译的设置页、扩展图标上以及扩展弹窗有显目提示的，但是似乎还是有部分用户没看到，你能看到这个公告吗？如果没有，估计是公告系统出了问题。。

是最近几天发布的公告吗？如果是那我没看见，如果不是，那不少天之前我记得有印象，但由于当时还能正常使用，所以没有仔细去看，抱歉。

**Comment by lmk123** [comment]
是的，这个公告我大概是半个月前发的。不用道歉，我以为是我的公告系统出了问题 :joy:

以后有问题也欢迎反馈，感谢你的支持。
