### ISSUE TITLE
怎么在界面显示音标

### ISSUE THREAD

**Issue by hjbj99** [lmk123/crx-selection-translate#982]
## 基本信息

划词翻译版本：7.6
浏览器版本：chrome  89.0.4389.82
操作系统：windows 10

## 重现问题的步骤

1.划词 点翻译后 百度翻译 谷歌翻译 界面没有显示音标
2.怎么设置可以显示音标
3.

**Comment by lmk123** [comment]
必应词典是可以显示音标的，你点击齿轮图标后勾选“必应”即可。

**Comment by hjbj99** [comment]
那想让百度翻译和谷歌翻译显示音标，是不是实现不了了。

**Comment by lmk123** [comment]
无论是在  v7.6.0 之前还是 v7.6.0  之后，谷歌翻译都没有变化，它只对部分单词显示音标。

百度翻译在 v7.6.0 之后已经不再显示音标了，这是因为百度翻译使用了官方接口，而官方接口不再提供英语词典；但是，有道在使用官方接口之后就显示音标了。

具体改变可以查看我之前发过的公告：https://hcfy.limingkai.cn/use-official-api.html

**Comment by hjbj99** [comment]
收到 谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lmk123/crx-selection-translate] 怎么在界面显示音标 (#982)




 
无论是在  v7.6.0 之前还是 v7.6.0  之后，谷歌翻译都没有变化，它只对部分单词显示音标。
 
百度翻译在 v7.6.0 之后已经不再显示音标了，这是因为百度翻译使用了官方接口，而官方接口不再提供英语词典；但是，有道在使用官方接口之后就显示音标了。
 
具体改变可以查看我之前发过的公告：https://hcfy.limingkai.cn/use-official-api.html
