### ISSUE TITLE
Deepl 翻译源指定翻译成固定语言

### ISSUE THREAD

**Issue by Prealez2020** [lmk123/crx-selection-translate#983]
目前没找到相关设置，每次针对不同语言的文本翻译之后结果也是随机显示（我选中俄语他会给我翻译成法语，然后选一段西班牙语 又给我翻译成俄语）。如果可以手动设置为翻译成固定某个语言会更好用一些。

**Comment by lmk123** [comment]
这其实是一个 bug，见 #955 

我会在后面的版本中修复这个 bug，后续进展可以关注 #955，这个我就先关闭了。
