### ISSUE TITLE
自行申请密钥  并且设置完之后速度比原来没设置的还慢 是错觉吗

### ISSUE THREAD

**Issue by wangengzheng** [lmk123/crx-selection-translate#984]
## 基本信息
自行申请密钥  并且设置完之后速度比原来没设置的还慢 是错觉吗

划词翻译版本：划词翻译 v7.6.0
浏览器版本：版本 89.0.4389.114（正式版本） （64 位）
操作系统：win10

### 预期行为
上一个版本不需要设置自己的密钥的时候都很快

### 实际行为
设置了密钥之后很慢

**Comment by lmk123** [comment]
我猜你说的是百度翻译，如果是的话，文档里有写原因：

![image](https://user-images.githubusercontent.com/5035625/114674706-19b6b380-9d3a-11eb-88d9-0a53ebcfc910.png)
