### ISSUE TITLE
设置页面—翻译源—启动翻译源选项中：可以提供 排序选项

### ISSUE THREAD

**Issue by mohanyu** [lmk123/crx-selection-translate#985]
## 功能简介
设置页面—翻译源—启动翻译源选项中：可以提供 排序选项
## 为什么你觉得需要（改进）这个功能？

我使用的是 Windows 10 Chrome 89 和划词翻译 7.5.6，希望提供新的功能改进：

因为平时的划词翻译的使用，我认为  DeepL的翻译最为准确，但是同时希望能看到谷歌翻译、百度翻译做为参考项，但是DeepL的排序优先级小于  谷歌翻译、百度翻译、有道翻译。总是在下拉框的最底层，读写顺序不甚方便，希望能提供自定义排序

**Comment by lmk123** [comment]
排序是可以修改的，你可以先取消所有翻译源，然后再第一个勾选 DeepL，这样的话 DeepL 就会显示在第一个了。我会在设置页当中加一个提示。

**Comment by lmk123** [comment]
v7.6.1 在启用翻译源下方添加了排序的提示，如下图：

![image](https://user-images.githubusercontent.com/5035625/114812482-ad43bf00-9de2-11eb-861d-5869cf575937.png)
