### ISSUE TITLE
让火狐也支持自动保存独立窗口位置

### ISSUE THREAD

**Issue by lmk123** [lmk123/crx-selection-translate#986]
## 功能简介
目前火狐浏览器（以及 Vivaldi）不支持 [chrome.windows.onBoundsChanged](https://developer.chrome.com/docs/extensions/reference/windows/#event-onBoundsChanged)，导致不能自动保存窗口大小和位置，但其实可以改为在关闭独立窗口时保存

**Comment by GH01** [comment]
7.6.1
看来对Vivaldi无效……

**Comment by GH01** [comment]
Chromium 命令行参数 --app=(URL) 所打开的窗口形式，Vivaldi倒是支持。
不知能否专为Vivaldi调用这种形式的窗口？

**Comment by lmk123** [comment]
划词翻译创建的窗口是调用的浏览器提供的 https://developer.chrome.com/docs/extensions/reference/windows/#method-create 这个方法，其中 windows type 为 `popup`，如果 Vivaldi 不支持，那估计没办法。你可以确认一下 Vivaldi 是否支持创建 `popup` 类型的窗口。

**Comment by GH01** [comment]
要不你把设置中的[独立翻译窗口:位置和宽高]开放自定义吧。
这个初始值看上去是有效的。（别的扩展中的表现也能说明这一点。）
这样，另类浏览器用户至少可以控制这个初始值。

**Comment by GH01** [comment]
后来发现：
只动位置，不动大小，Vivaldi就不记改变；
一旦大小有变，Vivaldi就会记住（连同位置）。

这是一只 good bug，是个可以利用的特性（Windows Explorer也是如此）。
当然如果有人想改掉，我也没办法哈哈……

**Comment by lmk123** [comment]
> 只动位置，不动大小，Vivaldi就不记改变；
> 一旦大小有变，Vivaldi就会记住（连同位置）。

我猜是 Vivaldi 的  https://developer.chrome.com/docs/extensions/reference/windows/#event-onBoundsChanged 只会检测窗口大小的变化……

> 要不你把设置中的[独立翻译窗口:位置和宽高]开放自定义吧。
看起来 Vivldi 还是有办法保存大小和位置的，所以我暂时不打算开放了
