### ISSUE TITLE
翻译没有返回音标，希望返回音标

### ISSUE THREAD

**Issue by xiaofang168** [lmk123/crx-selection-translate#987]
## 功能简介
在返回的翻译中增加一个音标显示
## 为什么你觉得需要（改进）这个功能？
1、提供音标可以明确知道怎么发音
2、要知道咋读还得考出来去其他地方再查一下，不太方便（不习惯去点读音）

**Comment by xiaofang168** [comment]
![image](https://user-images.githubusercontent.com/6174626/114809375-a4e88580-9ddc-11eb-9ea4-802237dbc2a4.png)

**Comment by xiaofang168** [comment]
单词 返回音标，句子忽略

**Comment by lmk123** [comment]
百度翻译是不提供音标的，但是你可以勾选必应词典，它是提供音标的。

有道翻译和搜狗翻译也是提供音标的，不过这俩要申请密钥。

**Comment by xiaofang168** [comment]
谢谢^_^

**Comment by lmk123** [comment]
不用谢，有问题欢迎反馈
