### ISSUE TITLE
百度翻译接口 5800报错客户端ip非法

### ISSUE THREAD

**Issue by fengmao31** [lmk123/crx-selection-translate#988]
![image](https://user-images.githubusercontent.com/19343842/114893703-8ddb7f00-9e40-11eb-9cde-8237aefe0c3d.png)

**Comment by lmk123** [comment]
官方文档上的解决方案说让你把 IP 限制留空，但我估计你应该也没有设置过 IP……

如果不是 IP 的问题，那我也不知道怎么解决，估计得找百度翻译的客服问一问了。。

**Comment by lmk123** [comment]
老哥你这个问题还有吗

**Comment by fengmao31** [comment]
没有设置过 IP，也没有找到设置ip的地方。

**Comment by lmk123** [comment]
这个我估计得找百度翻译那边的客服问问了，因为我也不知道他们是怎么判断你的 IP 地址有问题的。如果你找到了问题的原因，可以告诉我，我会在文档里添加说明，免得其他人也遇到同样的问题。

**Comment by lmk123** [comment]
这个问题在划词翻译这边无法解决，先关闭了。

**Comment by lilpea1213** [comment]
I will find u .. and IDC what u think or think you know .. I will get u in
the end
