### ISSUE TITLE
右键翻译增加非独立窗口选项

### ISSUE THREAD

**Issue by ygcaicn** [lmk123/crx-selection-translate#989]
## 功能简介

目前选中后右键翻译选中的文本只能是独立窗口，我想要禁用网页划词后仍然使用右键而不使用独立窗口。

## 为什么你觉得需要（改进）这个功能？

禁用网页划词只能使用独立窗口有所不便。

**Comment by lmk123** [comment]
“右键翻译选中的文本”仅仅只是在浏览器的内置页面中才是独立窗口，因为这些页面划词翻译（应该说所有扩展程序）都没有权限注入翻译窗口，所以只能在独立窗口里打开。如果你在一般的普通页面（比如现在这个工单页面）就是会直接在页面上打开翻译窗口的。

**Comment by ygcaicn** [comment]
> “右键翻译选中的文本”仅仅只是在浏览器的内置页面中才是独立窗口，因为这些页面划词翻译（应该说所有扩展程序）都没有权限注入翻译窗口，所以只能在独立窗口里打开。如果你在一般的普通页面（比如现在这个工单页面）就是会直接在页面上打开翻译窗口的。

发现了，多谢！
