### ISSUE TITLE
6.0.2默认的“译”字和窗口比5.6.1小啊

### ISSUE THREAD

**Issue by gggccc44** [lmk123/crx-selection-translate#99]
一直用5.6.1，今天自动更新了发现已经6.0.2了，功能倒是多了挺不错。但是划词后那个“译”字变小了没以前好点中，窗口貌似也小了。在页面放大的情况下倒是都变大了，以前好像都是固定的。还有5.6.1在划词后旁边可以再选网页翻译我觉得挺方便的，现在得到菜单上去选，虽然也没问题，不过还是希望翻译窗口能点到网页翻译，可以就用默认设定的引擎就行

**Comment by lmk123** [comment]
按钮和窗口的大小是仁者见仁智者见智，之所以会变小是因为有用户反馈太大了 #65 

我本人对用户界面与用户体验也没有很多经验，所以正向有经验的设计师求助 #93 

未来你会看到一个更好用的划词翻译的 :)

**Comment by gggccc44** [comment]
反馈太大了的估计都是年轻人或者用笔记本的年轻人。咱4张多了发现眼睛越来越不行了啊，现在才知道。。。以前年轻的时候觉得大人说看不清还奇怪呢。。。不麻烦的话，可以做个设置调整不？

**Comment by gggccc44** [comment]
或者，能不自动升级么？我就用5.6.1好了，更新到6.0.5，全文翻译又没割了。。。我觉得吧，安全森马的有时候是借口，割了外部引用也不见得多安全，比如最近ios那个乌龙，虽然要说责任不怪苹果，不过嘛。。。
