### ISSUE TITLE
期望能够定制面板上面的开关。

### ISSUE THREAD

**Issue by zhhaojie** [lmk123/crx-selection-translate#990]
## 功能简介
期望能够定制面板上面的开关，比如：截图翻译，收藏，网页翻译等。
## 为什么你觉得需要（改进）这个功能？
每个人的需求不一样，有的人外语水平一般，功能要求得多一些。而有的人，只是偶尔生僻词不太会。目前这个UI面板对于我来说，过于繁杂了。
我非常乐意通过购买会员，从而使我拥有可定制功能开关的权益。 谢谢作者，辛苦了。

另外，真佩服作者的研究能力，购买翻译积分的功能都能想到。

**Comment by zhhaojie** [comment]
发现可以自定义面板样式来实现。但仍然建议作者考虑实现。为了表示感谢，必须会员支持一下。

**Comment by lmk123** [comment]
好的，我会在未来的版本中加一个“自定义面板”的选项，可以自由控制按钮的显示与隐藏。

> 为了表示感谢，必须会员支持一下。

谢谢支持！

> 另外，真佩服作者的研究能力，购买翻译积分的功能都能想到。

过奖了 😂

**Comment by GH01** [comment]
楼主别关啊，
让主人放入“低优先级”就是了。

**Comment by lmk123** [comment]
在下个版本就可以自定义面板上按钮的显示与隐藏了
