### ISSUE TITLE
希望能加一个词性的显示和音标

### ISSUE THREAD

**Issue by polin-x** [lmk123/crx-selection-translate#991]
## 功能简介

希望能加一个词性的显示，例：adv, adj, n, v...；

在朗读的小喇叭后面 ➕个音标，例： [ˈθæŋk juː]

## 为什么你觉得需要（改进）这个功能？
能更好的学英语

**Comment by lmk123** [comment]
必应词典、有道翻译和搜狗翻译都是有音标的

![image](https://user-images.githubusercontent.com/5035625/115111727-3e1dc480-9fb4-11eb-8889-4263c49502f6.png)

**Comment by polin-x** [comment]
哈哈哈哈，谢谢大佬，刚好没用这三个哈哈哈哈，我加一个试试

**Comment by polin-x** [comment]
那大佬看看 方便➕上词性的显示吗

**Comment by lmk123** [comment]
呃，我截图里发的这仨翻译服务不是都有词性的显示吗
