### ISSUE TITLE
按下其他快捷键划词翻译会自动弹出

### ISSUE THREAD

**Issue by ratt3n** [lmk123/crx-selection-translate#998]
## 基本信息

划词翻译版本：7.6.1
浏览器版本：Chrome 90.0.4430.72
操作系统：macOS 10.15.7 (19H524)

## 重现问题的步骤

1.选中一行文本
2.按下蝴蝶键+Tab或蝴蝶键+空格
3.划词翻译即使设置为关闭也会自动弹出

### 预期行为
不弹出
### 实际行为
执行了快捷键功能的同时弹出划词翻译并把选中文本翻译了一遍

**Comment by lmk123** [comment]
你说的“蝴蝶键”应该是指 ⌥ 吧。你应该是在【设置】-【辅助键】里单独选择了 “Alt / ⌥” 作为 辅助键，如果你不希望出现这种情况，你可以取消辅助键、或者再加一个辅助键。

辅助键即使是在关闭网页划词之后也是会执行的。
